# Ejercicio 2 – Perfilamiento y preparación de T_DIGITURNOS

## Prueba Analista BI

### Objetivo
Preparar una base analítica de turnos que permita analizar tiempos de espera,
picos de demanda, cuellos de botella y utilización de usuarios receptores.

### Fuentes utilizadas
- T_DIGITURNOS.csv
- BD_AFILIADOS.csv
- AFILIADOS_A_CARGO.xlsx

### Regla de clasificación de usuarios
La identificación del cliente se cruza siguiendo este orden:

1. BD_AFILIADOS → **Afiliado**
2. Registros no encontrados → AFILIADOS_A_CARGO → **Grupo familiar**
3. Registros restantes → **No afiliado**

### Variables analíticas a construir
- tipo_vinculo
- categoría
- segmento poblacional
- pirámide1
- pirámide2
- calidad de segmentación
- día de la semana
- hora de solicitud
- tiempo de espera
- tiempo de atención
- tiempo total del servicio

### Principio de trazabilidad
Durante el proceso se documentarán:
- cantidad de registros de entrada;
- registros eliminados y motivo;
- nulos;
- duplicados;
- conversiones de tipos;
- resultados de cada cruce;
- registros sin correspondencia;
- reglas utilizadas para construir indicadores.

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

# ============================================================
# 1. CONFIGURACIÓN DE RUTAS
# ============================================================
# El notebook se encuentra en /notebooks.
# Se toma como raíz del proyecto la carpeta inmediatamente
# superior para que las rutas sean relativas y reproducibles.
# ============================================================

BASE_DIR = Path.cwd().parent

DATA_RAW = BASE_DIR / "data" / "raw"
DATA_PROCESSED = BASE_DIR / "data" / "processed"

ruta_digiturnos = DATA_RAW / "T_DIGITURNOS.csv"
ruta_afiliados = DATA_RAW / "BD_AFILIADOS.csv"
ruta_grupo_familiar = DATA_RAW / "AFILIADOS_A_CARGO.xlsx"

rutas = {
    "T_DIGITURNOS": ruta_digiturnos,
    "BD_AFILIADOS": ruta_afiliados,
    "GRUPO_FAMILIAR": ruta_grupo_familiar
}

print("RAÍZ DEL PROYECTO:")
print(BASE_DIR)

print("\nVALIDACIÓN DE ARCHIVOS:")
for nombre, ruta in rutas.items():
    estado = "OK" if ruta.exists() else "NO ENCONTRADO"
    print(f"{nombre:<20} | {estado:<15} | {ruta}")

RAÍZ DEL PROYECTO:
c:\Users\acoba\Documents\GitHub\Prueba_Analista_BI

VALIDACIÓN DE ARCHIVOS:
T_DIGITURNOS         | OK              | c:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\raw\T_DIGITURNOS.csv
BD_AFILIADOS         | OK              | c:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\raw\BD_AFILIADOS.csv
GRUPO_FAMILIAR       | OK              | c:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\raw\AFILIADOS_A_CARGO.xlsx

### 1.2 Registro de trazabilidad

Se mantiene un registro de las principales transformaciones realizadas sobre las
fuentes de información. Para cada etapa se documenta la tabla intervenida, el
número de registros resultantes, el número de variables y la decisión metodológica
aplicada.

Este registro permite verificar la evolución de los datos desde su estado original
hasta la construcción de la base analítica.

In [2]:
# ============================================================
# 1.2 REGISTRO DE TRAZABILIDAD
# ============================================================

trazabilidad = []

print("Registro de trazabilidad inicializado.")

Registro de trazabilidad inicializado.

## 2.1 Diagnóstico del formato de T_DIGITURNOS

Antes de cargar la fuente se valida su estructura física para identificar
el delimitador y la codificación utilizados en el archivo.

Esta validación se realiza antes de cualquier transformación para evitar
la pérdida silenciosa de registros durante la lectura.

In [3]:
# ============================================================
# 2.1 DIAGNÓSTICO DEL FORMATO DE T_DIGITURNOS
# ============================================================

import csv

# Leer una muestra del archivo sin realizar transformaciones
with open(ruta_digiturnos, "r", encoding="utf-8-sig", errors="replace") as archivo:
    muestra = archivo.read(10000)

print("PRIMEROS 1.000 CARACTERES DEL ARCHIVO")
print("-" * 60)
print(muestra[:1000])

print("\n" + "=" * 60)
print("DETECCIÓN AUTOMÁTICA DEL DELIMITADOR")
print("=" * 60)

try:
    dialecto = csv.Sniffer().sniff(
        muestra,
        delimiters=[",", ";", "\t", "|"]
    )
    
    separador_detectado = dialecto.delimiter
    
    print(f"Separador detectado: {repr(separador_detectado)}")

except csv.Error:
    separador_detectado = None
    print("No fue posible detectar automáticamente el separador.")

PRIMEROS 1.000 CARACTERES DEL ARCHIVO
------------------------------------------------------------
Sede;UES;Clasifiacion;Usuario_receptor;Tipo_servicio;SUBSERVICIO_HOMOLOGADO;Fecha_Servico;Hora_solicitud_Servicio;Hora_llamado__Servicio;Hora_finalizado_Servicio;Identificacion_Cliente;Tipo_Oficina
Calle 26;Subsidio;Radicacion afiliaciones;39767666;Servicio;Rad afiliacion trabajadores hasta 10 formularios;20/03/2024;10:49:41;10:54:47;10:56:03;29012215;Bogota
Calle 26;Subsidio;Radicacion afiliaciones;52622358;Servicio;Rad afiliacion trabajadores hasta 10 formularios;7/09/2024;10:08:56;10:09:18;10:12:34;20000240;Bogota
Calle 26;Subsidio;Radicacion afiliaciones;52622358;Servicio;Rad afiliacion trabajadores hasta 10 formularios;7/09/2024;10:12:34;10:12:34;10:16:37;20000240;Bogota
Calle 26;Subsidio;Tarjeta multiservicios;1024494171;Servicio;Entrega tams primera vez;2/09/2024;9:22:11;9:22:11;9:28:19;20000187;Bogota
Calle 26;Subsidio;Tarjeta multiservicios;1024494171;Servicio;Entrega tams primera vez;2/09/2024;9:21:12;9:21:12;9:22:11;20000187;Bogota
Calle 26;Subsidio;Tarjeta multiservicios;10

============================================================
DETECCIÓN AUTOMÁTICA DEL DELIMITADOR
============================================================
Separador detectado: ';'

In [4]:
# ============================================================
# 2.2 INSPECCIÓN DE LAS PRIMERAS LÍNEAS
# ============================================================

with open(ruta_digiturnos, "r", encoding="utf-8-sig", errors="replace") as archivo:
    for numero, linea in enumerate(archivo):
        print(f"Línea {numero + 1}: {linea[:500]}")
        
        if numero >= 4:
            break

Línea 1: Sede;UES;Clasifiacion;Usuario_receptor;Tipo_servicio;SUBSERVICIO_HOMOLOGADO;Fecha_Servico;Hora_solicitud_Servicio;Hora_llamado__Servicio;Hora_finalizado_Servicio;Identificacion_Cliente;Tipo_Oficina

Línea 2: Calle 26;Subsidio;Radicacion afiliaciones;39767666;Servicio;Rad afiliacion trabajadores hasta 10 formularios;20/03/2024;10:49:41;10:54:47;10:56:03;29012215;Bogota

Línea 3: Calle 26;Subsidio;Radicacion afiliaciones;52622358;Servicio;Rad afiliacion trabajadores hasta 10 formularios;7/09/2024;10:08:56;10:09:18;10:12:34;20000240;Bogota

Línea 4: Calle 26;Subsidio;Radicacion afiliaciones;52622358;Servicio;Rad afiliacion trabajadores hasta 10 formularios;7/09/2024;10:12:34;10:12:34;10:16:37;20000240;Bogota

Línea 5: Calle 26;Subsidio;Tarjeta multiservicios;1024494171;Servicio;Entrega tams primera vez;2/09/2024;9:22:11;9:22:11;9:28:19;20000187;Bogota

In [5]:
# ============================================================
# 2.3 INSPECCIÓN DEL REGISTRO REPORTADO POR EL PARSER
# ============================================================

lineas_revision = range(1974, 1980)

with open(ruta_digiturnos, "r", encoding="utf-8-sig", errors="replace") as archivo:
    for numero, linea in enumerate(archivo, start=1):
        if numero in lineas_revision:
            print(f"Línea {numero}:")
            print(repr(linea[:1000]))
            print("-" * 60)

Línea 1974:
'Calle 26;Subsidio;Subsidio de vivienda;52622358;Servicio;Informacion general subsidio de vivienda;27/02/2024;16:54:57;16:56:12;17:05:40;11404157;Bogota\n'
------------------------------------------------------------
Línea 1975:
'Calle 26;Subsidio;Pagos;1103714304;Servicio;Cambio de clave por olvido;19/02/2024;14:53:20;14:53:20;14:54:03;11403675;Bogota\n'
------------------------------------------------------------
Línea 1976:
'Calle 26;Subsidio;Pagos;1103714304;Servicio;Cambio de clave por olvido;19/02/2024;14:50:11;14:50:32;14:53:20;11403675;Bogota\n'
------------------------------------------------------------
Línea 1977:
'Calle 26;Educacion;Educacion;1033797428;Comercial;Informacion, inscripcion cet tyt y tl;27/06/2024;16:18:44;16:25:05;16:31:08;11372219;Bogota\n'
------------------------------------------------------------
Línea 1978:
'Calle 26;Subsidio;Radicacion afiliaciones;1024480700;Servicio;Rad afiliacion trabajadores hasta 10 formularios;27/06/2024;16:56:23;16:56:51;17:01:17;11372219;Bogota\n'
------------------------------------------------------------
Línea 1979:
"Calle 26;Subsidio;Administracion afiliados;52273627;Servicio;Pqr's cuota monetaria;23/07/2024;8:44:42;8:46:13;8:58:57;11372206;Bogota\n"
------------------------------------------------------------

### Hallazgo de ingesta

El archivo `T_DIGITURNOS.csv` utiliza punto y coma (`;`) como delimitador.

La carga inicial con el separador predeterminado de `pandas.read_csv()` produjo un
`ParserError` en la línea 1977. La inspección del archivo permitió establecer que
el problema no correspondía a una fila corrupta, sino a una coma incluida dentro
del texto de un subservicio:

`Informacion, inscripcion cet tyt y tl`

Al utilizar `;` como delimitador, esta coma se conserva correctamente como parte
del contenido del campo.

**Decisión:** cargar la fuente con `sep=";"` y conservar todos los registros,
sin utilizar `on_bad_lines="skip"`.

## 2. Carga de fuentes

Se cargan las tres fuentes originales sin modificar los archivos de entrada.

Los archivos ubicados en `data/raw` se consideran fuentes inmutables.
Todas las transformaciones posteriores se realizan en memoria y los resultados
procesados se almacenarán en `data/processed`.

Esto permite conservar los datos originales y reproducir completamente el proceso.

In [6]:
# ============================================================
# 2.4 CARGA CONTROLADA DE FUENTES
# ============================================================
# T_DIGITURNOS utiliza punto y coma (;) como delimitador.
# No se descartan registros durante la lectura.
# ============================================================

archivos_faltantes = [
    nombre
    for nombre, ruta in rutas.items()
    if not ruta.exists()
]

if archivos_faltantes:
    raise FileNotFoundError(
        "No se encontraron los siguientes archivos: "
        + ", ".join(archivos_faltantes)
    )

digiturnos = pd.read_csv(
    ruta_digiturnos,
    sep=";",
    encoding="utf-8-sig",
    low_memory=False
)

afiliados = pd.read_csv(
    ruta_afiliados,
    low_memory=False
)

grupo_familiar = pd.read_excel(
    ruta_grupo_familiar
)

print("CARGA COMPLETADA")
print("=" * 60)
print(
    f"T_DIGITURNOS:   "
    f"{digiturnos.shape[0]:,} filas x "
    f"{digiturnos.shape[1]} columnas"
)
print(
    f"BD_AFILIADOS:   "
    f"{afiliados.shape[0]:,} filas x "
    f"{afiliados.shape[1]} columnas"
)
print(
    f"GRUPO_FAMILIAR: "
    f"{grupo_familiar.shape[0]:,} filas x "
    f"{grupo_familiar.shape[1]} columnas"
)

CARGA COMPLETADA
============================================================
T_DIGITURNOS:   1,016,267 filas x 12 columnas
BD_AFILIADOS:   448,951 filas x 1 columnas
GRUPO_FAMILIAR: 39,733 filas x 2 columnas

In [7]:
# ============================================================
# REGISTRO DE TRAZABILIDAD - CARGA ORIGINAL
# ============================================================

trazabilidad.append({
    "etapa": "Carga de fuente",
    "tabla": "T_DIGITURNOS",
    "registros": len(digiturnos),
    "columnas": digiturnos.shape[1],
    "observacion": (
        "Fuente cargada con separador ';'. "
        "No se descartaron registros durante la ingesta."
    )
})

trazabilidad.append({
    "etapa": "Carga de fuente",
    "tabla": "BD_AFILIADOS",
    "registros": len(afiliados),
    "columnas": afiliados.shape[1],
    "observacion": "Fuente cargada sin transformaciones."
})

trazabilidad.append({
    "etapa": "Carga de fuente",
    "tabla": "GRUPO_FAMILIAR",
    "registros": len(grupo_familiar),
    "columnas": grupo_familiar.shape[1],
    "observacion": "Fuente cargada sin transformaciones."
})

display(pd.DataFrame(trazabilidad))

,etapa,tabla,registros,columnas,observacion
0,Carga de fuente,T_DIGITURNOS,1016267,12,Fuente cargada con separador ';'. No se descar...
1,Carga de fuente,BD_AFILIADOS,448951,1,Fuente cargada sin transformaciones.
2,Carga de fuente,GRUPO_FAMILIAR,39733,2,Fuente cargada sin transformaciones.

In [8]:
# ============================================================
# 2.5 VALIDACIÓN ESTRUCTURAL POST-CARGA
# ============================================================

print("COLUMNAS T_DIGITURNOS")
print("=" * 60)

for i, columna in enumerate(digiturnos.columns, start=1):
    print(f"{i:02d}. {columna}")

print("\nNúmero de columnas:", digiturnos.shape[1])

display(digiturnos.head())

COLUMNAS T_DIGITURNOS
============================================================
01. Sede
02. UES
03. Clasifiacion
04. Usuario_receptor
05. Tipo_servicio
06. SUBSERVICIO_HOMOLOGADO
07. Fecha_Servico
08. Hora_solicitud_Servicio
09. Hora_llamado__Servicio
10. Hora_finalizado_Servicio
11. Identificacion_Cliente
12. Tipo_Oficina

Número de columnas: 12

,Sede,UES,Clasifiacion,Usuario_receptor,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,Fecha_Servico,Hora_solicitud_Servicio,Hora_llamado__Servicio,Hora_finalizado_Servicio,Identificacion_Cliente,Tipo_Oficina
0,Calle 26,Subsidio,Radicacion afiliaciones,39767666,Servicio,Rad afiliacion trabajadores hasta 10 formularios,20/03/2024,10:49:41,10:54:47,10:56:03,29012215.0,Bogota
1,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:08:56,10:09:18,10:12:34,20000240.0,Bogota
2,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:12:34,10:12:34,10:16:37,20000240.0,Bogota
3,Calle 26,Subsidio,Tarjeta multiservicios,1024494171,Servicio,Entrega tams primera vez,2/09/2024,9:22:11,9:22:11,9:28:19,20000187.0,Bogota
4,Calle 26,Subsidio,Tarjeta multiservicios,1024494171,Servicio,Entrega tams primera vez,2/09/2024,9:21:12,9:21:12,9:22:11,20000187.0,Bogota

In [9]:
# ============================================================
# 2.5 VALIDACIÓN ESTRUCTURAL POST-CARGA
# ============================================================

print("COLUMNAS T_DIGITURNOS")
print("=" * 60)

for i, columna in enumerate(digiturnos.columns, start=1):
    print(f"{i:02d}. {columna}")

print("\nNúmero de columnas:", digiturnos.shape[1])

display(digiturnos.head())

COLUMNAS T_DIGITURNOS
============================================================
01. Sede
02. UES
03. Clasifiacion
04. Usuario_receptor
05. Tipo_servicio
06. SUBSERVICIO_HOMOLOGADO
07. Fecha_Servico
08. Hora_solicitud_Servicio
09. Hora_llamado__Servicio
10. Hora_finalizado_Servicio
11. Identificacion_Cliente
12. Tipo_Oficina

Número de columnas: 12

,Sede,UES,Clasifiacion,Usuario_receptor,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,Fecha_Servico,Hora_solicitud_Servicio,Hora_llamado__Servicio,Hora_finalizado_Servicio,Identificacion_Cliente,Tipo_Oficina
0,Calle 26,Subsidio,Radicacion afiliaciones,39767666,Servicio,Rad afiliacion trabajadores hasta 10 formularios,20/03/2024,10:49:41,10:54:47,10:56:03,29012215.0,Bogota
1,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:08:56,10:09:18,10:12:34,20000240.0,Bogota
2,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:12:34,10:12:34,10:16:37,20000240.0,Bogota
3,Calle 26,Subsidio,Tarjeta multiservicios,1024494171,Servicio,Entrega tams primera vez,2/09/2024,9:22:11,9:22:11,9:28:19,20000187.0,Bogota
4,Calle 26,Subsidio,Tarjeta multiservicios,1024494171,Servicio,Entrega tams primera vez,2/09/2024,9:21:12,9:21:12,9:22:11,20000187.0,Bogota

In [10]:
# ============================================================
# 3. PERFILAMIENTO INICIAL
# 3.1 Registros completamente vacíos
# ============================================================

filas_iniciales = len(digiturnos)
filas_vacias = digiturnos.isna().all(axis=1).sum()

print(f"Filas cargadas:              {filas_iniciales:,}")
print(f"Filas completamente vacías:  {filas_vacias:,}")
print(
    f"Porcentaje de filas vacías:  "
    f"{filas_vacias / filas_iniciales:.2%}"
)

Filas cargadas:              1,016,267
Filas completamente vacías:  133,187
Porcentaje de filas vacías:  13.11%

In [11]:
# ============================================================
# 3.2 ELIMINACIÓN CONTROLADA DE FILAS VACÍAS
# ============================================================

digiturnos = digiturnos.dropna(how="all").copy()

filas_utiles = len(digiturnos)

print(f"Filas antes:       {filas_iniciales:,}")
print(f"Filas eliminadas:  {filas_vacias:,}")
print(f"Filas útiles:      {filas_utiles:,}")

Filas antes:       1,016,267
Filas eliminadas:  133,187
Filas útiles:      883,080

In [12]:
# ============================================================
# 3.2.1 CONTROL DE LA LIMPIEZA DE FILAS VACÍAS
# ============================================================

print("CONTROL POST-LIMPIEZA")
print("=" * 60)

print(f"Registros originales:          {filas_iniciales:>12,}")
print(f"Filas completamente vacías:    {filas_vacias:>12,}")
print(f"Registros analíticos:          {len(digiturnos):>12,}")
print("-" * 60)
print(
    "Validación aritmética:        ",
    filas_iniciales == filas_vacias + len(digiturnos)
)

filas_vacias_post = digiturnos.isna().all(axis=1).sum()
print(f"Filas vacías después limpieza: {filas_vacias_post:>12,}")

CONTROL POST-LIMPIEZA
============================================================
Registros originales:             1,016,267
Filas completamente vacías:         133,187
Registros analíticos:               883,080
------------------------------------------------------------
Validación aritmética:         True
Filas vacías después limpieza:            0

In [13]:
trazabilidad.append({
    "etapa": "Limpieza inicial",
    "tabla": "T_DIGITURNOS",
    "registros": filas_utiles,
    "columnas": digiturnos.shape[1],
    "observacion": (
        f"Se eliminaron {filas_vacias:,} filas "
        "completamente vacías."
    )
})

display(pd.DataFrame(trazabilidad))

,etapa,tabla,registros,columnas,observacion
0,Carga de fuente,T_DIGITURNOS,1016267,12,Fuente cargada con separador ';'. No se descar...
1,Carga de fuente,BD_AFILIADOS,448951,1,Fuente cargada sin transformaciones.
2,Carga de fuente,GRUPO_FAMILIAR,39733,2,Fuente cargada sin transformaciones.
3,Limpieza inicial,T_DIGITURNOS,883080,12,"Se eliminaron 133,187 filas completamente vacías."

In [14]:
# ============================================================
# 3.3 PERFIL DE CALIDAD POR VARIABLE
# ============================================================

perfil_calidad = pd.DataFrame({
    "tipo_dato": digiturnos.dtypes.astype(str),
    "registros": len(digiturnos),
    "nulos": digiturnos.isna().sum(),
    "pct_nulos": (digiturnos.isna().mean() * 100).round(2),
    "distintos": digiturnos.nunique(dropna=True)
})

perfil_calidad = perfil_calidad.sort_values(
    "pct_nulos",
    ascending=False
)

display(perfil_calidad)

                         tipo_dato  registros  nulos  pct_nulos  distintos
Sede                           str     883080      0        0.0         13
UES                            str     883080      0        0.0          6
Clasifiacion                   str     883080      0        0.0         12
Usuario_receptor               str     883080      0        0.0        122
Tipo_servicio                  str     883080      0        0.0          2
SUBSERVICIO_HOMOLOGADO         str     883080      0        0.0        140
Fecha_Servico                  str     883080      0        0.0        212
Hora_solicitud_Servicio        str     883080      0        0.0      44170
Hora_llamado__Servicio         str     883080      0        0.0      44352
Hora_finalizado_Servicio       str     883080      0        0.0      44401
Identificacion_Cliente     float64     883080      0        0.0      60335
Tipo_Oficina                   str     883080      0        0.0          2

In [15]:
# ============================================================
# 3.4 DUPLICADOS EXACTOS
# ============================================================

duplicados_exactos = digiturnos.duplicated().sum()
pct_duplicados = duplicados_exactos / len(digiturnos) * 100

print("CONTROL DE DUPLICADOS")
print("=" * 60)
print(f"Registros analizados:     {len(digiturnos):,}")
print(f"Duplicados exactos:       {duplicados_exactos:,}")
print(f"Porcentaje duplicados:    {pct_duplicados:.2f}%")

CONTROL DE DUPLICADOS
============================================================
Registros analizados:     883,080
Duplicados exactos:       0
Porcentaje duplicados:    0.00%

### 3.5 Diagnóstico de variables críticas

Antes de construir los indicadores de tiempos de atención y realizar el cruce con
la población afiliada, se valida la calidad de las variables que intervienen
directamente en el análisis.

Se revisan especialmente la identificación del cliente, la fecha del servicio,
las horas de solicitud, llamado y finalización, y el usuario receptor. El objetivo
es identificar valores no válidos o inconsistencias antes de realizar
transformaciones que puedan alterar los registros originales.

In [16]:
# ============================================================
# 3.5 DIAGNÓSTICO DE VARIABLES CRÍTICAS
# ============================================================

columnas_criticas = [
    "Identificacion_Cliente",
    "Fecha_Servico",
    "Hora_solicitud_Servicio",
    "Hora_llamado__Servicio",
    "Hora_finalizado_Servicio",
    "Usuario_receptor"
]

print("DIAGNÓSTICO DE VARIABLES CRÍTICAS")
print("=" * 70)

for columna in columnas_criticas:
    print(f"\n{columna}")
    print("-" * 70)
    print(f"Tipo de dato:       {digiturnos[columna].dtype}")
    print(f"Registros:          {len(digiturnos):,}")
    print(f"Nulos:              {digiturnos[columna].isna().sum():,}")
    print(f"Valores distintos:  {digiturnos[columna].nunique(dropna=True):,}")

DIAGNÓSTICO DE VARIABLES CRÍTICAS
======================================================================

Identificacion_Cliente
----------------------------------------------------------------------
Tipo de dato:       float64
Registros:          883,080
Nulos:              0
Valores distintos:  60,335

Fecha_Servico
----------------------------------------------------------------------
Tipo de dato:       str
Registros:          883,080
Nulos:              0
Valores distintos:  212

Hora_solicitud_Servicio
----------------------------------------------------------------------
Tipo de dato:       str
Registros:          883,080
Nulos:              0
Valores distintos:  44,170

Hora_llamado__Servicio
----------------------------------------------------------------------
Tipo de dato:       str
Registros:          883,080
Nulos:              0
Valores distintos:  44,352

Hora_finalizado_Servicio
----------------------------------------------------------------------
Tipo de dato:       str
Registros:          883,080
Nulos:              0
Valores distintos:  44,401

Usuario_receptor
----------------------------------------------------------------------
Tipo de dato:       str
Registros:          883,080
Nulos:              0
Valores distintos:  122

In [17]:
# ============================================================
# 3.6 DIAGNÓSTICO DEL IDENTIFICADOR DEL CLIENTE
# ============================================================

id_cliente = pd.to_numeric(
    digiturnos["Identificacion_Cliente"],
    errors="coerce"
)

ids_no_numericos = id_cliente.isna().sum()

ids_con_decimales = (
    id_cliente.notna()
    & (id_cliente % 1 != 0)
).sum()

print("CONTROL DEL IDENTIFICADOR DEL CLIENTE")
print("=" * 70)
print(f"Registros analizados:        {len(digiturnos):,}")
print(f"Valores no numéricos:        {ids_no_numericos:,}")
print(f"Valores con parte decimal:   {ids_con_decimales:,}")
print(f"Identificaciones distintas:  {id_cliente.nunique():,}")

CONTROL DEL IDENTIFICADOR DEL CLIENTE
======================================================================
Registros analizados:        883,080
Valores no numéricos:        0
Valores con parte decimal:   0
Identificaciones distintas:  60,335

In [18]:
# ============================================================
# 3.7 VALIDACIÓN DE FECHAS Y HORAS
# ============================================================

fecha_test = pd.to_datetime(
    digiturnos["Fecha_Servico"],
    format="%d/%m/%Y",
    errors="coerce"
)

hora_solicitud_test = pd.to_timedelta(
    digiturnos["Hora_solicitud_Servicio"],
    errors="coerce"
)

hora_llamado_test = pd.to_timedelta(
    digiturnos["Hora_llamado__Servicio"],
    errors="coerce"
)

hora_finalizado_test = pd.to_timedelta(
    digiturnos["Hora_finalizado_Servicio"],
    errors="coerce"
)

validacion_temporal = pd.DataFrame({
    "variable": [
        "Fecha_Servico",
        "Hora_solicitud_Servicio",
        "Hora_llamado__Servicio",
        "Hora_finalizado_Servicio"
    ],
    "registros": [len(digiturnos)] * 4,
    "no_convertibles": [
        fecha_test.isna().sum(),
        hora_solicitud_test.isna().sum(),
        hora_llamado_test.isna().sum(),
        hora_finalizado_test.isna().sum()
    ]
})

validacion_temporal["pct_no_convertibles"] = (
    validacion_temporal["no_convertibles"]
    / validacion_temporal["registros"]
    * 100
).round(4)

display(validacion_temporal)

                   variable  registros  no_convertibles  pct_no_convertibles
0             Fecha_Servico     883080                0                  0.0
1   Hora_solicitud_Servicio     883080                0                  0.0
2    Hora_llamado__Servicio     883080                0                  0.0
3  Hora_finalizado_Servicio     883080                0                  0.0

### 3.8 Estandarización de variables críticas

Las validaciones previas evidenciaron que la identificación del cliente no contiene
valores no numéricos ni componentes decimales reales. Asimismo, la fecha del
servicio y las tres variables horarias presentan una conversión válida para la
totalidad de los registros analíticos.

A partir de estos resultados se estandariza el identificador como texto, con el
fin de utilizarlo posteriormente como llave de integración, y se construyen
marcas de tiempo completas para la solicitud, el llamado y la finalización del
servicio.

Las variables originales se conservan para garantizar la trazabilidad del
proceso.

In [19]:
# ============================================================
# 3.8 ESTANDARIZACIÓN DE VARIABLES CRÍTICAS
# ============================================================

# ------------------------------------------------------------
# 1. Identificación del cliente
# ------------------------------------------------------------

digiturnos["id_cliente"] = (
    pd.to_numeric(
        digiturnos["Identificacion_Cliente"],
        errors="coerce"
    )
    .astype("Int64")
    .astype("string")
)


# ------------------------------------------------------------
# 2. Fecha del servicio
# ------------------------------------------------------------

digiturnos["fecha_servicio"] = pd.to_datetime(
    digiturnos["Fecha_Servico"],
    format="%d/%m/%Y",
    errors="coerce"
)


# ------------------------------------------------------------
# 3. Construcción de timestamps
# ------------------------------------------------------------

digiturnos["ts_solicitud"] = (
    digiturnos["fecha_servicio"]
    + pd.to_timedelta(
        digiturnos["Hora_solicitud_Servicio"],
        errors="coerce"
    )
)

digiturnos["ts_llamado"] = (
    digiturnos["fecha_servicio"]
    + pd.to_timedelta(
        digiturnos["Hora_llamado__Servicio"],
        errors="coerce"
    )
)

digiturnos["ts_finalizacion"] = (
    digiturnos["fecha_servicio"]
    + pd.to_timedelta(
        digiturnos["Hora_finalizado_Servicio"],
        errors="coerce"
    )
)


# ------------------------------------------------------------
# 4. Control de transformación
# ------------------------------------------------------------

print("ESTANDARIZACIÓN DE VARIABLES CRÍTICAS")
print("=" * 70)

print(f"Registros procesados:           {len(digiturnos):,}")
print(f"ID cliente nulos:               {digiturnos['id_cliente'].isna().sum():,}")
print(f"Fecha servicio nula:            {digiturnos['fecha_servicio'].isna().sum():,}")
print(f"Timestamp solicitud nulo:       {digiturnos['ts_solicitud'].isna().sum():,}")
print(f"Timestamp llamado nulo:         {digiturnos['ts_llamado'].isna().sum():,}")
print(f"Timestamp finalización nulo:    {digiturnos['ts_finalizacion'].isna().sum():,}")

ESTANDARIZACIÓN DE VARIABLES CRÍTICAS
======================================================================
Registros procesados:           883,080
ID cliente nulos:               0
Fecha servicio nula:            0
Timestamp solicitud nulo:       0
Timestamp llamado nulo:         0
Timestamp finalización nulo:    0

### 3.9 Construcción y validación de tiempos operativos

A partir de las marcas de tiempo estandarizadas se calculan dos componentes del
proceso de atención:

- **Tiempo de espera:** minutos transcurridos entre la solicitud del turno y el llamado.
- **Tiempo de atención:** minutos transcurridos entre el llamado y la finalización del servicio.

Antes de utilizar estos indicadores se verifica su coherencia temporal. Los
valores negativos se identifican como casos potencialmente inconsistentes y no
se eliminan automáticamente, con el propósito de conservar evidencia para el
control de calidad.

In [20]:
# ============================================================
# 3.9 CONSTRUCCIÓN Y CONTROL DE TIEMPOS OPERATIVOS
# ============================================================

digiturnos["tiempo_espera_min"] = (
    (
        digiturnos["ts_llamado"]
        - digiturnos["ts_solicitud"]
    )
    .dt.total_seconds()
    / 60
)

digiturnos["tiempo_atencion_min"] = (
    (
        digiturnos["ts_finalizacion"]
        - digiturnos["ts_llamado"]
    )
    .dt.total_seconds()
    / 60
)

digiturnos["tiempo_total_min"] = (
    (
        digiturnos["ts_finalizacion"]
        - digiturnos["ts_solicitud"]
    )
    .dt.total_seconds()
    / 60
)


# ------------------------------------------------------------
# Controles de coherencia temporal
# ------------------------------------------------------------

esperas_negativas = (digiturnos["tiempo_espera_min"] < 0).sum()
atenciones_negativas = (digiturnos["tiempo_atencion_min"] < 0).sum()
totales_negativos = (digiturnos["tiempo_total_min"] < 0).sum()

esperas_cero = (digiturnos["tiempo_espera_min"] == 0).sum()
atenciones_cero = (digiturnos["tiempo_atencion_min"] == 0).sum()


print("CONTROL DE COHERENCIA TEMPORAL")
print("=" * 70)

print(f"Registros analizados:             {len(digiturnos):,}")
print()
print(f"Tiempos de espera negativos:      {esperas_negativas:,}")
print(f"Tiempos de atención negativos:    {atenciones_negativas:,}")
print(f"Tiempos totales negativos:        {totales_negativos:,}")
print()
print(f"Tiempos de espera = 0:            {esperas_cero:,}")
print(f"Tiempos de atención = 0:          {atenciones_cero:,}")

CONTROL DE COHERENCIA TEMPORAL
======================================================================
Registros analizados:             883,080

Tiempos de espera negativos:      2
Tiempos de atención negativos:    2
Tiempos totales negativos:        4

Tiempos de espera = 0:            347,996
Tiempos de atención = 0:          2

In [21]:
# ============================================================
# 3.10 DISTRIBUCIÓN PRELIMINAR DE TIEMPOS
# ============================================================

variables_tiempo = [
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "tiempo_total_min"
]

resumen_tiempos = (
    digiturnos[variables_tiempo]
    .describe(
        percentiles=[
            0.25,
            0.50,
            0.75,
            0.90,
            0.95,
            0.99
        ]
    )
    .T
)

display(
    resumen_tiempos[
        [
            "count",
            "mean",
            "std",
            "min",
            "25%",
            "50%",
            "75%",
            "90%",
            "95%",
            "99%",
            "max"
        ]
    ].round(2)
)

,count,mean,std,min,25%,50%,75%,90%,95%,99%,max
tiempo_espera_min,883080.0,6.04,10.21,-786.90,0.00,0.78,8.45,18.92,26.98,45.82,200.62
tiempo_atencion_min,883080.0,5.14,4.40,-578.18,2.33,4.15,6.77,10.13,12.90,20.52,171.25
tiempo_total_min,883080.0,11.18,11.43,-786.90,3.67,7.35,14.98,25.77,34.08,53.29,200.70

### 3.11 Tratamiento de inconsistencias temporales

El control de coherencia identificó un número marginal de registros con secuencias
temporales inconsistentes. Estos casos se conservan en la base para mantener la
trazabilidad de la fuente, pero se clasifican mediante una bandera de calidad.

Para el cálculo posterior de indicadores de tiempos se utilizarán únicamente
registros con secuencia temporal válida. Los tiempos iguales a cero se mantienen,
dado que pueden representar atenciones inmediatas y no constituyen por sí mismos
una inconsistencia.

Los valores extremos positivos tampoco se eliminan en esta etapa. Su comportamiento
será analizado posteriormente por sede y tipo de servicio, dado que pueden
representar eventos operativos reales y ser relevantes para la identificación
de cuellos de botella.

In [22]:
# ============================================================
# 3.11 TRATAMIENTO DE INCONSISTENCIAS TEMPORALES
# ============================================================

digiturnos["flag_tiempo_valido"] = (
    (digiturnos["tiempo_espera_min"] >= 0)
    & (digiturnos["tiempo_atencion_min"] >= 0)
    & (digiturnos["tiempo_total_min"] >= 0)
)

digiturnos["estado_calidad_tiempo"] = (
    digiturnos["flag_tiempo_valido"]
    .map({
        True: "Válido",
        False: "Inconsistente"
    })
)

control_calidad_tiempo = (
    digiturnos["estado_calidad_tiempo"]
    .value_counts(dropna=False)
    .rename_axis("estado")
    .reset_index(name="registros")
)

control_calidad_tiempo["porcentaje"] = (
    control_calidad_tiempo["registros"]
    / len(digiturnos)
    * 100
).round(4)

display(control_calidad_tiempo)

          estado  registros  porcentaje
0         Válido     883076     99.9995
1  Inconsistente          4      0.0005

In [23]:
# ============================================================
# 3.12.1 VERIFICACIÓN DE NOMBRES DE COLUMNAS
# ============================================================

print("COLUMNAS ACTUALES DE T_DIGITURNOS")
print("=" * 70)

for i, columna in enumerate(digiturnos.columns, start=1):
    print(f"{i:02d}. {repr(columna)}")

COLUMNAS ACTUALES DE T_DIGITURNOS
======================================================================
01. 'Sede'
02. 'UES'
03. 'Clasifiacion'
04. 'Usuario_receptor'
05. 'Tipo_servicio'
06. 'SUBSERVICIO_HOMOLOGADO'
07. 'Fecha_Servico'
08. 'Hora_solicitud_Servicio'
09. 'Hora_llamado__Servicio'
10. 'Hora_finalizado_Servicio'
11. 'Identificacion_Cliente'
12. 'Tipo_Oficina'
13. 'id_cliente'
14. 'fecha_servicio'
15. 'ts_solicitud'
16. 'ts_llamado'
17. 'ts_finalizacion'
18. 'tiempo_espera_min'
19. 'tiempo_atencion_min'
20. 'tiempo_total_min'
21. 'flag_tiempo_valido'
22. 'estado_calidad_tiempo'

In [24]:
# ============================================================
# 3.12 AUDITORÍA DE INCONSISTENCIAS TEMPORALES
# ============================================================

columnas_deseadas = [
    "Sede",
    "UES",
    "Clasificacion",
    "Usuario_receptor",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "fecha_servicio",
    "ts_solicitud",
    "ts_llamado",
    "ts_finalizacion",
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "tiempo_total_min"
]

# Seleccionar únicamente columnas que realmente existen
columnas_auditoria = [
    c for c in columnas_deseadas
    if c in digiturnos.columns
]

columnas_faltantes = [
    c for c in columnas_deseadas
    if c not in digiturnos.columns
]

# Primero filtrar filas
casos_inconsistentes = (
    digiturnos.loc[
        ~digiturnos["flag_tiempo_valido"]
    ]
    .copy()
)

# Después seleccionar/reordenar columnas de forma segura
casos_inconsistentes = (
    casos_inconsistentes
    .reindex(columns=columnas_auditoria)
    .sort_values(
        "tiempo_total_min",
        ascending=True
    )
)

print("AUDITORÍA DE INCONSISTENCIAS TEMPORALES")
print("=" * 70)

print(f"Registros analizados:       {len(digiturnos):,}")
print(f"Casos inconsistentes:       {len(casos_inconsistentes):,}")

print(
    f"Porcentaje inconsistente:   "
    f"{len(casos_inconsistentes) / len(digiturnos) * 100:.4f}%"
)

print()

if columnas_faltantes:
    print("Columnas no encontradas:")
    print(columnas_faltantes)
else:
    print("Todas las columnas de auditoría fueron encontradas.")

print()

display(casos_inconsistentes)

AUDITORÍA DE INCONSISTENCIAS TEMPORALES
======================================================================
Registros analizados:       883,080
Casos inconsistentes:       4
Porcentaje inconsistente:   0.0005%

Columnas no encontradas:
['Clasificacion']

,Sede,UES,Usuario_receptor,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,fecha_servicio,ts_solicitud,ts_llamado,ts_finalizacion,tiempo_espera_min,tiempo_atencion_min,tiempo_total_min
500217,Soacha,Hoteleria y turismo,Sin Usuario,Comercial,Radicacion reserva,2024-04-20,2024-04-20 13:06:54,2024-04-20 00:00:00,2024-04-20 00:00:00,-786.900000,0.000000,-786.900000
534463,Soacha,Credito,1024546447,Comercial,Radicacion cupo credito,2024-04-06,2024-04-06 12:26:40,2024-04-06 00:00:00,2024-04-06 00:00:00,-746.666667,0.000000,-746.666667
449138,Santa librada,Subsidio,1019125029,Servicio,Validacion afiliacion trabajador y/o beneficia...,2024-06-13,2024-06-13 16:59:03,2024-06-13 17:18:20,2024-06-13 07:40:09,19.283333,-578.183333,-558.900000
306392,Funza,Subsidio,1003822265,Servicio,Informacion subsidios de arrendamiento,2024-06-11,2024-06-11 17:55:50,2024-06-11 18:08:08,2024-06-11 08:58:29,12.300000,-549.650000,-537.350000

In [25]:
# ============================================================
# 3.13 CONSTRUCCIÓN DE POBLACIÓN VÁLIDA PARA TIEMPOS
# ============================================================

digiturnos_tiempos = (
    digiturnos.loc[
        digiturnos["flag_tiempo_valido"]
    ]
    .copy()
)

registros_excluidos = (
    len(digiturnos)
    - len(digiturnos_tiempos)
)

print("POBLACIÓN ANALÍTICA PARA INDICADORES TEMPORALES")
print("=" * 70)

print(f"Registros base:                  {len(digiturnos):>12,}")
print(f"Registros temporalmente válidos: {len(digiturnos_tiempos):>12,}")
print(f"Registros excluidos:             {registros_excluidos:>12,}")

print("-" * 70)

print(
    "Validación de reconciliación: ",
    len(digiturnos)
    == len(digiturnos_tiempos)
    + registros_excluidos
)

POBLACIÓN ANALÍTICA PARA INDICADORES TEMPORALES
======================================================================
Registros base:                       883,080
Registros temporalmente válidos:      883,076
Registros excluidos:                        4
----------------------------------------------------------------------
Validación de reconciliación:  True

In [26]:
trazabilidad.append({
    "etapa": "Validación temporal",
    "tabla": "T_DIGITURNOS",
    "registros": len(digiturnos_tiempos),
    "columnas": digiturnos_tiempos.shape[1],
    "observacion": (
        f"Se identificaron {registros_excluidos:,} registros "
        "con secuencia temporal inconsistente. Se conservan en "
        "la base original y se excluyen únicamente del cálculo "
        "de indicadores temporales."
    )
})

display(pd.DataFrame(trazabilidad))

,etapa,tabla,registros,columnas,observacion
0,Carga de fuente,T_DIGITURNOS,1016267,12,Fuente cargada con separador ';'. No se descar...
1,Carga de fuente,BD_AFILIADOS,448951,1,Fuente cargada sin transformaciones.
2,Carga de fuente,GRUPO_FAMILIAR,39733,2,Fuente cargada sin transformaciones.
3,Limpieza inicial,T_DIGITURNOS,883080,12,"Se eliminaron 133,187 filas completamente vacías."
4,Validación temporal,T_DIGITURNOS,883076,22,Se identificaron 4 registros con secuencia tem...

## 4. Clasificación de clientes según afiliación

La clasificación de los clientes se desarrolla mediante una estrategia jerárquica
de identificación. Primero se busca correspondencia directa con la base de
afiliados; posteriormente, los clientes sin coincidencia se contrastan con la
base de personas a cargo y, finalmente, aquellos que no presentan correspondencia
en ninguna de las dos fuentes se clasifican como no afiliados.

Antes de realizar los cruces se valida la estructura, calidad y unicidad de las
llaves de identificación utilizadas en cada fuente, con el propósito de evitar
duplicaciones o clasificaciones incorrectas durante las uniones.

In [27]:
# ============================================================
# 4.1 DIAGNÓSTICO DE LLAVES PARA CLASIFICACIÓN DE AFILIACIÓN
# ============================================================

print("DIAGNÓSTICO DE FUENTES PARA CLASIFICACIÓN")
print("=" * 70)

print("\nT_DIGITURNOS")
print("-" * 70)
print(f"Registros: {len(digiturnos):,}")
print(f"Columnas:  {digiturnos.shape[1]}")
print(f"ID clientes distintos: {digiturnos['id_cliente'].nunique():,}")

print("\nBD_AFILIADOS")
print("-" * 70)
print(f"Registros: {len(afiliados):,}")
print(f"Columnas:  {afiliados.shape[1]}")
print("Nombres de columnas:")
for i, col in enumerate(afiliados.columns, 1):
    print(f"{i:02d}. {repr(col)}")

print("\nGRUPO_FAMILIAR")
print("-" * 70)
print(f"Registros: {len(grupo_familiar):,}")
print(f"Columnas:  {grupo_familiar.shape[1]}")
print("Nombres de columnas:")
for i, col in enumerate(grupo_familiar.columns, 1):
    print(f"{i:02d}. {repr(col)}")

DIAGNÓSTICO DE FUENTES PARA CLASIFICACIÓN
======================================================================

T_DIGITURNOS
----------------------------------------------------------------------
Registros: 883,080
Columnas:  22
ID clientes distintos: 60,335

BD_AFILIADOS
----------------------------------------------------------------------
Registros: 448,951
Columnas:  1
Nombres de columnas:
01. ';id_persona_Modificado;NumIdPersona_Modificado;Nombre;Categoria;Segmento_poblacional;Piramide1;Piramide2;RazonSocial;Genero'

GRUPO_FAMILIAR
----------------------------------------------------------------------
Registros: 39,733
Columnas:  2
Nombres de columnas:
01. 'NUM_IDENTIFICACION_AFILIADO'
02. 'NUM_IDENTIFICACION_PERSONA_A_CARGO'

In [28]:
# ============================================================
# 4.2 MUESTRA CONTROLADA DE LAS FUENTES
# ============================================================

print("MUESTRA BD_AFILIADOS")
display(afiliados.head(10))

print("\nMUESTRA GRUPO_FAMILIAR")
display(grupo_familiar.head(10))

print("\nMUESTRA IDENTIFICADORES T_DIGITURNOS")
display(
    digiturnos[
        ["Identificacion_Cliente", "id_cliente"]
    ].head(10)
)

MUESTRA BD_AFILIADOS

  ;id_persona_Modificado;NumIdPersona_Modificado;Nombre;Categoria;Segmento_poblacional;Piramide1;Piramide2;RazonSocial;Genero
0  0;CC10818289;10818289;ORLANDO JOSEALGUERO SOSA...
1  1;CC10224342;10224342;CRISTIAN LEONARDOCORTES ...
2  2;CC10814050;10814050;LAURA NIKOLERAMIREZ LOZA...
3  3;CC31064;31064;JOSE EDILBERTOBOHORQUEZ BEJARA...
4  4;CC10957942;10957942;JOSEFINA ANGARITA PINZON...
5  5;CC750837;750837;RAMON ANTONIOGIRALDO OSORIO;...
6  6;CC463793;463793;CLAUDIA MILENAGONZALEZ LEON;...
7  7;CC760418;760418;ERMINSOL SUAREZ QUINTERO;A;B...
8  8;CC170903;170903;GERARDINO HENRYCASTELLANOS D...
9  9;CC10223482;10223482;JOHN ALEXANDERRODRIGUEZ ...

MUESTRA GRUPO_FAMILIAR

   NUM_IDENTIFICACION_AFILIADO NUM_IDENTIFICACION_PERSONA_A_CARGO
0                         1775                           10036404
1                         3824                           96022201
2                         4133                           99022409
3                         3084                           10003904
4                         3859                           10007324
5                         4133                           11411220
6                         4224                           10039076
7                         3624                           93083126
8                         3282                           98111927
9                         4581                           98110308

MUESTRA IDENTIFICADORES T_DIGITURNOS

   Identificacion_Cliente id_cliente
0              29012215.0   29012215
1              20000240.0   20000240
2              20000240.0   20000240
3              20000187.0   20000187
4              20000187.0   20000187
5              20000187.0   20000187
6              20000187.0   20000187
7              20000187.0   20000187
8              20000187.0   20000187
9              20000187.0   20000187

### 4.3 Estandarización de las fuentes de afiliación

La inspección de `BD_AFILIADOS` evidenció que el archivo utiliza punto y coma (`;`)
como delimitador. La carga inicial interpretó la totalidad de los campos como una
única columna, por lo que se realiza una nueva lectura conservando la fuente
original sin modificaciones.

Posteriormente se estandarizan las llaves de identificación de afiliados y personas
a cargo para garantizar compatibilidad con el identificador previamente normalizado
de `T_DIGITURNOS`.

In [29]:
# ============================================================
# 4.3 CORRECCIÓN Y ESTANDARIZACIÓN DE FUENTES DE AFILIACIÓN
# ============================================================

# Relectura correcta de BD_AFILIADOS
afiliados = pd.read_csv(
    "../data/raw/BD_AFILIADOS.csv",
    sep=";",
    low_memory=False
)

print("BD_AFILIADOS REPROCESADA")
print("=" * 70)
print(f"Registros: {len(afiliados):,}")
print(f"Columnas:  {afiliados.shape[1]}")

print("\nColumnas detectadas:")
for i, col in enumerate(afiliados.columns, 1):
    print(f"{i:02d}. {repr(col)}")

BD_AFILIADOS REPROCESADA
======================================================================
Registros: 448,951
Columnas:  10

Columnas detectadas:
01. 'Unnamed: 0'
02. 'id_persona_Modificado'
03. 'NumIdPersona_Modificado'
04. 'Nombre'
05. 'Categoria'
06. 'Segmento_poblacional'
07. 'Piramide1'
08. 'Piramide2'
09. 'RazonSocial'
10. 'Genero'

In [30]:
# ============================================================
# 4.4 ESTANDARIZACIÓN DE LLAVES DE IDENTIFICACIÓN
# ============================================================

# Afiliados
afiliados["id_afiliado"] = pd.to_numeric(
    afiliados["NumIdPersona_Modificado"],
    errors="coerce"
).astype("Int64")

# Grupo familiar
grupo_familiar["id_afiliado_titular"] = pd.to_numeric(
    grupo_familiar["NUM_IDENTIFICACION_AFILIADO"],
    errors="coerce"
).astype("Int64")

grupo_familiar["id_persona_cargo"] = pd.to_numeric(
    grupo_familiar["NUM_IDENTIFICACION_PERSONA_A_CARGO"],
    errors="coerce"
).astype("Int64")

# Control
print("ESTANDARIZACIÓN DE LLAVES")
print("=" * 70)

print(f"Afiliados - registros:                {len(afiliados):,}")
print(f"Afiliados - ID nulos:                 {afiliados['id_afiliado'].isna().sum():,}")
print(f"Afiliados - ID distintos:             {afiliados['id_afiliado'].nunique():,}")

print()
print(f"Grupo familiar - registros:           {len(grupo_familiar):,}")
print(f"ID titular nulos:                     {grupo_familiar['id_afiliado_titular'].isna().sum():,}")
print(f"ID persona a cargo nulos:             {grupo_familiar['id_persona_cargo'].isna().sum():,}")
print(f"Titulares distintos:                  {grupo_familiar['id_afiliado_titular'].nunique():,}")
print(f"Personas a cargo distintas:           {grupo_familiar['id_persona_cargo'].nunique():,}")

print()
print(f"Digiturnos - clientes distintos:      {digiturnos['id_cliente'].nunique():,}")

ESTANDARIZACIÓN DE LLAVES
======================================================================
Afiliados - registros:                448,951
Afiliados - ID nulos:                 10
Afiliados - ID distintos:             303,946

Grupo familiar - registros:           39,733
ID titular nulos:                     0
ID persona a cargo nulos:             1
Titulares distintos:                  29,879
Personas a cargo distintas:           24,554

Digiturnos - clientes distintos:      60,335

In [31]:
# ============================================================
# 4.5 CONTROL DE UNICIDAD DE LLAVES
# ============================================================

duplicados_afiliados = (
    afiliados["id_afiliado"]
    .dropna()
    .duplicated(keep=False)
    .sum()
)

duplicados_personas_cargo = (
    grupo_familiar["id_persona_cargo"]
    .dropna()
    .duplicated(keep=False)
    .sum()
)

print("CONTROL DE UNICIDAD DE LLAVES")
print("=" * 70)

print(f"Filas con ID afiliado duplicado:       {duplicados_afiliados:,}")
print(f"Filas con persona a cargo duplicada:   {duplicados_personas_cargo:,}")

print()
print("Duplicación potencial:")
print(
    "Afiliados:",
    "REVISAR" if duplicados_afiliados > 0 else "Sin duplicados"
)
print(
    "Personas a cargo:",
    "REVISAR" if duplicados_personas_cargo > 0 else "Sin duplicados"
)

CONTROL DE UNICIDAD DE LLAVES
======================================================================
Filas con ID afiliado duplicado:       289,990
Filas con persona a cargo duplicada:   23,034

Duplicación potencial:
Afiliados: REVISAR
Personas a cargo: REVISAR

In [32]:
# ============================================================
# 4.6 CONTROL DE SOLAPAMIENTO ENTRE AFILIADOS Y PERSONAS A CARGO
# ============================================================

ids_afiliados = set(
    afiliados["id_afiliado"]
    .dropna()
    .astype("int64")
)

ids_personas_cargo = set(
    grupo_familiar["id_persona_cargo"]
    .dropna()
    .astype("int64")
)

ids_digiturnos = set(
    digiturnos["id_cliente"]
    .dropna()
    .astype("int64")
)

solapamiento = ids_afiliados.intersection(ids_personas_cargo)

clientes_afiliados = ids_digiturnos.intersection(ids_afiliados)

clientes_grupo_familiar = (
    ids_digiturnos
    .difference(ids_afiliados)
    .intersection(ids_personas_cargo)
)

clientes_no_afiliados = (
    ids_digiturnos
    .difference(ids_afiliados)
    .difference(ids_personas_cargo)
)

print("DIAGNÓSTICO PREVIO DE CLASIFICACIÓN")
print("=" * 70)

print(f"IDs presentes simultáneamente como afiliado y PAC: {len(solapamiento):,}")

print()
print("Clientes únicos de T_DIGITURNOS:")
print(f"Total:                  {len(ids_digiturnos):,}")
print(f"Afiliados directos:     {len(clientes_afiliados):,}")
print(f"Grupo familiar:         {len(clientes_grupo_familiar):,}")
print(f"No afiliados:           {len(clientes_no_afiliados):,}")

print()
print(
    "Reconciliación:",
    len(ids_digiturnos)
    == (
        len(clientes_afiliados)
        + len(clientes_grupo_familiar)
        + len(clientes_no_afiliados)
    )
)

DIAGNÓSTICO PREVIO DE CLASIFICACIÓN
======================================================================
IDs presentes simultáneamente como afiliado y PAC: 10,335

Clientes únicos de T_DIGITURNOS:
Total:                  60,335
Afiliados directos:     47,873
Grupo familiar:         15
No afiliados:           12,447

Reconciliación: True

In [33]:
# ============================================================
# 4.7 CARGA Y VALIDACIÓN DE DIMENSIÓN DE AFILIADOS CONSISTENTES
# ============================================================

ruta_dim_afiliados = DATA_PROCESSED / "dim_afiliados_consistentes.csv"

dim_afiliados = pd.read_csv(
    ruta_dim_afiliados,
    low_memory=False
)

print("DIMENSIÓN DE AFILIADOS CONSISTENTES")
print("=" * 70)
print(f"Registros: {len(dim_afiliados):,}")
print(f"Columnas:  {dim_afiliados.shape[1]}")

print("\nColumnas disponibles:")
for i, col in enumerate(dim_afiliados.columns, 1):
    print(f"{i:02d}. {repr(col)}")

display(dim_afiliados.head())

DIMENSIÓN DE AFILIADOS CONSISTENTES
======================================================================
Registros: 168,866
Columnas:  7

Columnas disponibles:
01. 'id_normalizado'
02. 'Categoria'
03. 'Segmento_poblacional'
04. 'Piramide1'
05. 'Piramide2'
06. 'registros_fuente'
07. 'calidad_perfil'

,id_normalizado,Categoria,Segmento_poblacional,Piramide1,Piramide2,registros_fuente,calidad_perfil
0,10,A,Medio,4 micro,4.5 transaccional,1,Consistente
1,10000000,A,Basico,2 emp medio,2.2 silver,1,Consistente
2,10000004,A,Basico,1 emp grandes,1.1 platinum,2,Consistente
3,10000009,A,Basico,4 micro,4.5 transaccional,2,Consistente
4,10000041,A,Basico,4 micro,4.5 transaccional,2,Consistente

In [34]:
# ============================================================
# 4.8 VALIDACIÓN DE LLAVE EN DIM_AFILIADOS
# ============================================================

print("CONTROL DE LLAVE")
print("=" * 70)

print(
    "Duplicados por identificación:",
    dim_afiliados["id_normalizado"].duplicated().sum()
)

print(
    "Nulos en identificación:",
    dim_afiliados["id_normalizado"].isna().sum()
)

print(
    "Identificaciones distintas:",
    dim_afiliados["id_normalizado"].nunique()
)

CONTROL DE LLAVE
======================================================================
Duplicados por identificación: 0
Nulos en identificación: 0
Identificaciones distintas: 168866

### 4.9 Construcción de la dimensión de grupo familiar

La relación entre afiliados titulares y personas a cargo se transforma en una
dimensión reutilizable con una fila única por persona a cargo.

Dado que una misma persona puede encontrarse asociada a más de un titular, no se
selecciona arbitrariamente un afiliado responsable. La dimensión conserva el número
de titulares asociados y asigna el identificador del titular únicamente cuando la
relación es unívoca.

El resultado se almacena en `data/processed/dim_grupo_familiar.csv` para ser utilizado
de manera consistente por los diferentes ejercicios de la prueba.

In [35]:
# ============================================================
# 4.9 CONSTRUCCIÓN DE DIM_GRUPO_FAMILIAR
# ============================================================

# Copia controlada de la fuente
gf_base = grupo_familiar.copy()

# ------------------------------------------------------------
# 1. Normalización de identificadores
# ------------------------------------------------------------

gf_base["id_persona_cargo"] = pd.to_numeric(
    gf_base["NUM_IDENTIFICACION_PERSONA_A_CARGO"],
    errors="coerce"
).astype("Int64")

gf_base["id_afiliado_titular"] = pd.to_numeric(
    gf_base["NUM_IDENTIFICACION_AFILIADO"],
    errors="coerce"
).astype("Int64")


# ------------------------------------------------------------
# 2. Retirar únicamente registros sin persona a cargo
# ------------------------------------------------------------

registros_fuente_gf = len(gf_base)
nulos_persona_cargo = gf_base["id_persona_cargo"].isna().sum()

gf_base_valida = (
    gf_base[
        gf_base["id_persona_cargo"].notna()
    ]
    [
        ["id_persona_cargo", "id_afiliado_titular"]
    ]
    .drop_duplicates()
    .copy()
)


# ------------------------------------------------------------
# 3. Consolidación a una fila por persona a cargo
# ------------------------------------------------------------

resumen_titulares = (
    gf_base_valida
    .groupby("id_persona_cargo")
    .agg(
        n_titulares=(
            "id_afiliado_titular",
            lambda x: x.dropna().nunique()
        )
    )
    .reset_index()
)


# ------------------------------------------------------------
# 4. Recuperar titular solo cuando es único
# ------------------------------------------------------------

titular_unico = (
    gf_base_valida
    .groupby("id_persona_cargo")["id_afiliado_titular"]
    .agg(
        lambda x:
        x.dropna().iloc[0]
        if x.dropna().nunique() == 1
        else pd.NA
    )
    .reset_index(name="id_afiliado_titular")
)


# ------------------------------------------------------------
# 5. Construcción de la dimensión
# ------------------------------------------------------------

dim_grupo_familiar = resumen_titulares.merge(
    titular_unico,
    on="id_persona_cargo",
    how="left",
    validate="one_to_one"
)

dim_grupo_familiar["estado_relacion"] = np.select(
    [
        dim_grupo_familiar["n_titulares"].eq(1),
        dim_grupo_familiar["n_titulares"].gt(1)
    ],
    [
        "Titular único",
        "Múltiples titulares"
    ],
    default="Sin titular identificable"
)


# ------------------------------------------------------------
# 6. Control
# ------------------------------------------------------------

print("DIMENSIÓN DE GRUPO FAMILIAR")
print("=" * 70)

print(f"Registros fuente:                  {registros_fuente_gf:,}")
print(f"Registros sin persona a cargo:     {nulos_persona_cargo:,}")
print(f"Personas a cargo únicas:           {len(dim_grupo_familiar):,}")
print(
    f"Duplicados en llave final:         "
    f"{dim_grupo_familiar['id_persona_cargo'].duplicated().sum():,}"
)

print()
display(
    dim_grupo_familiar["estado_relacion"]
    .value_counts()
    .rename_axis("estado_relacion")
    .reset_index(name="personas")
)

display(dim_grupo_familiar.head(10))

DIMENSIÓN DE GRUPO FAMILIAR
======================================================================
Registros fuente:                  39,733
Registros sin persona a cargo:     1
Personas a cargo únicas:           24,554
Duplicados en llave final:         0

       estado_relacion  personas
0        Titular único     16698
1  Múltiples titulares      7856

   id_persona_cargo  n_titulares  id_afiliado_titular estado_relacion
0            149139            1               206257   Titular único
1            157554            1               802720   Titular único
2            172634            1               800493   Titular único
3            196315            1               208593   Titular único
4            227861            1               795722   Titular único
5            245147            1               804186   Titular único
6            250679            1               403825   Titular único
7            251614            1               795204   Titular único
8            251763            1               790598   Titular único
9            251998            1               805057   Titular único

In [36]:
# ============================================================
# 4.10 EXPORTACIÓN DE DIM_GRUPO_FAMILIAR
# ============================================================

ruta_dim_grupo_familiar = (
    DATA_PROCESSED
    / "dim_grupo_familiar.csv"
)

dim_grupo_familiar.to_csv(
    ruta_dim_grupo_familiar,
    index=False,
    encoding="utf-8-sig"
)

print("DIMENSIÓN GENERADA")
print("=" * 70)
print(ruta_dim_grupo_familiar)
print()
print(
    f"Registros exportados: "
    f"{len(dim_grupo_familiar):,}"
)

DIMENSIÓN GENERADA
======================================================================
c:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\processed\dim_grupo_familiar.csv

Registros exportados: 24,554

In [37]:
# ============================================================
# 4.11 VALIDACIÓN DE DIMENSIÓN PERSISTIDA
# ============================================================

dim_grupo_familiar = pd.read_csv(
    ruta_dim_grupo_familiar,
    encoding="utf-8-sig",
    low_memory=False
)

dim_grupo_familiar["id_persona_cargo"] = pd.to_numeric(
    dim_grupo_familiar["id_persona_cargo"],
    errors="coerce"
).astype("Int64")

dim_grupo_familiar["id_afiliado_titular"] = pd.to_numeric(
    dim_grupo_familiar["id_afiliado_titular"],
    errors="coerce"
).astype("Int64")

print("VALIDACIÓN DE DIM_GRUPO_FAMILIAR")
print("=" * 70)

print(f"Registros:                {len(dim_grupo_familiar):,}")
print(
    f"IDs únicos:               "
    f"{dim_grupo_familiar['id_persona_cargo'].nunique():,}"
)
print(
    f"Duplicados en llave:      "
    f"{dim_grupo_familiar['id_persona_cargo'].duplicated().sum():,}"
)
print(
    f"Nulos en llave:           "
    f"{dim_grupo_familiar['id_persona_cargo'].isna().sum():,}"
)

VALIDACIÓN DE DIM_GRUPO_FAMILIAR
======================================================================
Registros:                24,554
IDs únicos:               24,554
Duplicados en llave:      0
Nulos en llave:           0

In [38]:
print("CONTROL PRE-MERGE")
print("=" * 70)

print(
    "Duplicados dim_afiliados:",
    dim_afiliados["id_normalizado"].duplicated().sum()
)

print(
    "Duplicados dim_grupo_familiar:",
    dim_grupo_familiar["id_persona_cargo"].duplicated().sum()
)

print(
    "Nulos dim_afiliados:",
    dim_afiliados["id_normalizado"].isna().sum()
)

print(
    "Nulos dim_grupo_familiar:",
    dim_grupo_familiar["id_persona_cargo"].isna().sum()
)

CONTROL PRE-MERGE
======================================================================
Duplicados dim_afiliados: 0
Duplicados dim_grupo_familiar: 0
Nulos dim_afiliados: 0
Nulos dim_grupo_familiar: 0

In [39]:
print("TIPOS DE LLAVE")
print("=" * 70)

print(
    "digiturnos:",
    digiturnos_tiempos["id_cliente"].dtype
)

print(
    "dim_afiliados:",
    dim_afiliados["id_normalizado"].dtype
)

print(
    "dim_grupo_familiar:",
    dim_grupo_familiar["id_persona_cargo"].dtype
)

TIPOS DE LLAVE
======================================================================
digiturnos: string
dim_afiliados: str
dim_grupo_familiar: Int64

In [40]:
# ============================================================
# 4.12 RECARGA CONTROLADA DE DIMENSIONES MAESTRAS
# ============================================================

ruta_dim_afiliados = DATA_PROCESSED / "dim_afiliados_consistentes.csv"
ruta_dim_grupo_familiar = DATA_PROCESSED / "dim_grupo_familiar.csv"

dim_afiliados = pd.read_csv(
    ruta_dim_afiliados,
    encoding="utf-8-sig",
    low_memory=False
)

dim_grupo_familiar = pd.read_csv(
    ruta_dim_grupo_familiar,
    encoding="utf-8-sig",
    low_memory=False
)

# Estandarización de llaves
dim_afiliados["id_normalizado"] = pd.to_numeric(
    dim_afiliados["id_normalizado"],
    errors="coerce"
).astype("Int64")

dim_grupo_familiar["id_persona_cargo"] = pd.to_numeric(
    dim_grupo_familiar["id_persona_cargo"],
    errors="coerce"
).astype("Int64")

dim_grupo_familiar["id_afiliado_titular"] = pd.to_numeric(
    dim_grupo_familiar["id_afiliado_titular"],
    errors="coerce"
).astype("Int64")

print("VALIDACIÓN DE DIMENSIONES MAESTRAS")
print("=" * 70)

print(
    "dim_afiliados - duplicados:",
    dim_afiliados["id_normalizado"].duplicated().sum()
)
print(
    "dim_afiliados - nulos:",
    dim_afiliados["id_normalizado"].isna().sum()
)

print(
    "dim_grupo_familiar - duplicados:",
    dim_grupo_familiar["id_persona_cargo"].duplicated().sum()
)
print(
    "dim_grupo_familiar - nulos:",
    dim_grupo_familiar["id_persona_cargo"].isna().sum()
)

VALIDACIÓN DE DIMENSIONES MAESTRAS
======================================================================
dim_afiliados - duplicados: 9
dim_afiliados - nulos: 10
dim_grupo_familiar - duplicados: 0
dim_grupo_familiar - nulos: 0

In [41]:
# ============================================================
# 4.12. Diagnóstico de identificadores de afiliados
# ============================================================

import pandas as pd

print("=" * 70)
print("DIAGNÓSTICO DE DIMENSIÓN MAESTRA DE AFILIADOS")
print("=" * 70)

# 1. Información general
print("\n1. INFORMACIÓN GENERAL")

print("Registros totales:", len(dim_afiliados))
print("Columnas disponibles:")
print(dim_afiliados.columns.tolist())

# 2. Identificadores nulos
print("\n2. REGISTROS CON IDENTIFICADOR NULO")

afiliados_nulos = dim_afiliados[
    dim_afiliados["id_normalizado"].isna()
].copy()

print("Cantidad:", len(afiliados_nulos))

display(afiliados_nulos)

# 3. Identificadores duplicados
print("\n3. REGISTROS CON IDENTIFICADOR DUPLICADO")

afiliados_duplicados = dim_afiliados[
    dim_afiliados["id_normalizado"].notna()
    & dim_afiliados["id_normalizado"].duplicated(keep=False)
].copy()

afiliados_duplicados = afiliados_duplicados.sort_values(
    "id_normalizado"
)

print(
    "Cantidad de registros involucrados:",
    len(afiliados_duplicados)
)

print(
    "Identificadores distintos involucrados:",
    afiliados_duplicados["id_normalizado"].nunique()
)

display(afiliados_duplicados)

# 4. Tipos de datos
print("\n4. TIPO DE DATO DEL IDENTIFICADOR")

print(dim_afiliados["id_normalizado"].dtype)

print("\n5. VALIDACIÓN FINAL")

print(
    "Duplicados incluyendo nulos:",
    dim_afiliados["id_normalizado"].duplicated().sum()
)

print(
    "Duplicados excluyendo nulos:",
    dim_afiliados.loc[
        dim_afiliados["id_normalizado"].notna(),
        "id_normalizado"
    ].duplicated().sum()
)

print(
    "Nulos:",
    dim_afiliados["id_normalizado"].isna().sum()
)

======================================================================
DIAGNÓSTICO DE DIMENSIÓN MAESTRA DE AFILIADOS
======================================================================

1. INFORMACIÓN GENERAL
Registros totales: 168866
Columnas disponibles:
['id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil']

2. REGISTROS CON IDENTIFICADOR NULO
Cantidad: 10

,id_normalizado,Categoria,Segmento_poblacional,Piramide1,Piramide2,registros_fuente,calidad_perfil
168856,<NA>,C,Alto,1 emp grandes,1.1 platinum,1,Consistente
168857,<NA>,C,Alto,3 empresas pymes,3.2 vip estandar,1,Consistente
168858,<NA>,A,Joven,4 micro,4.3 trans.juridica ent. 11 a 99 trab.,1,Consistente
168859,<NA>,A,Basico,4 micro,4.1 estandar,1,Consistente
168860,<NA>,A,Basico,4 micro,4.5 transaccional,1,Consistente
168861,<NA>,A,Basico,4 micro,4.1 estandar,1,Consistente
168862,<NA>,A,Basico,4 micro,4.5 transaccional,1,Consistente
168863,<NA>,A,Basico,4 micro,4.5 transaccional,1,Consistente
168864,<NA>,A,Basico,4 micro,4.5 transaccional,1,Consistente
168865,<NA>,A,Basico,4 micro,4.5 transaccional,1,Consistente

3. REGISTROS CON IDENTIFICADOR DUPLICADO
Cantidad de registros involucrados: 0
Identificadores distintos involucrados: 0

Empty DataFrame
Columns: [id_normalizado, Categoria, Segmento_poblacional, Piramide1, Piramide2, registros_fuente, calidad_perfil]
Index: []

4. TIPO DE DATO DEL IDENTIFICADOR
Int64

5. VALIDACIÓN FINAL
Duplicados incluyendo nulos: 9
Duplicados excluyendo nulos: 0
Nulos: 10

### 4.13. Preparación de dimensiones maestras para la integración

La validación de la dimensión de afiliados identificó 168.866 registros, de los cuales 10 presentan identificadores nulos. No se encontraron identificadores duplicados entre los registros válidos.

Para garantizar relaciones uno a uno en los cruces posteriores, se construye una vista operativa que excluye únicamente los registros sin identificador, conservando intacta la dimensión original.

La dimensión de grupo familiar no presenta identificadores nulos ni duplicados.

Esta decisión permite preservar la trazabilidad de los datos y evitar multiplicaciones de registros durante la integración con T_DIGITURNOS.

In [42]:
# ============================================================
# 4.13. Preparación de dimensiones maestras para integración
# ============================================================

# 1. Conservar dimensión original sin modificaciones
total_afiliados_original = len(dim_afiliados)

# 2. Crear dimensión operativa con identificadores válidos
dim_afiliados_cruce = (
    dim_afiliados
    .loc[dim_afiliados["id_normalizado"].notna()]
    .copy()
)

# 3. Preparar dimensión de grupo familiar
dim_grupo_familiar_cruce = dim_grupo_familiar.copy()

# 4. Validar integridad de las llaves
assert dim_afiliados_cruce["id_normalizado"].notna().all()

assert not dim_afiliados_cruce[
    "id_normalizado"
].duplicated().any()

assert dim_grupo_familiar_cruce[
    "id_persona_cargo"
].notna().all()

assert not dim_grupo_familiar_cruce[
    "id_persona_cargo"
].duplicated().any()

# 5. Resumen de control
print("=" * 65)
print("PREPARACIÓN DE DIMENSIONES MAESTRAS")
print("=" * 65)

print(f"Afiliados originales: {total_afiliados_original:,}")

print(
    f"Afiliados disponibles para cruce: "
    f"{len(dim_afiliados_cruce):,}"
)

print(
    f"Registros excluidos por ID nulo: "
    f"{total_afiliados_original - len(dim_afiliados_cruce):,}"
)

print(
    f"Personas a cargo disponibles: "
    f"{len(dim_grupo_familiar_cruce):,}"
)

print("\nVALIDACIÓN COMPLETADA")
print("Dimensiones preparadas sin modificar fuentes originales.")

=================================================================
PREPARACIÓN DE DIMENSIONES MAESTRAS
=================================================================
Afiliados originales: 168,866
Afiliados disponibles para cruce: 168,856
Registros excluidos por ID nulo: 10
Personas a cargo disponibles: 24,554

VALIDACIÓN COMPLETADA
Dimensiones preparadas sin modificar fuentes originales.

### 4.14. Verificación de llaves para la integración de Digiturnos

Se realiza una validación previa de las columnas de identificación de la base transaccional T_DIGITURNOS y de las dimensiones maestras de afiliados y grupo familiar.

El propósito es verificar la disponibilidad, consistencia y compatibilidad de las llaves de identificación antes de ejecutar las relaciones entre tablas.

Esta etapa busca prevenir pérdidas de información, duplicaciones de registros y errores en la clasificación de los usuarios.

In [43]:
# ============================================================
# 4.14. Verificación de llaves para integración
# ============================================================

print("=" * 70)
print("VERIFICACIÓN DE ESTRUCTURAS PARA INTEGRACIÓN")
print("=" * 70)

# Identificar DataFrames disponibles
print("\n1. DATAFRAMES DISPONIBLES")

dataframes_disponibles = {
    nombre: objeto
    for nombre, objeto in globals().copy().items()
    if isinstance(objeto, pd.DataFrame)
}

for nombre, df in dataframes_disponibles.items():
    print(f"{nombre}: {len(df):,} registros")


# Dimensión de afiliados
print("\n2. DIMENSIÓN DE AFILIADOS")

print(dim_afiliados_cruce.columns.tolist())

print("\nTipo de llave:")
print(dim_afiliados_cruce["id_normalizado"].dtype)


# Dimensión de grupo familiar
print("\n3. DIMENSIÓN DE GRUPO FAMILIAR")

print(dim_grupo_familiar_cruce.columns.tolist())

print("\nTipo de llave:")
print(dim_grupo_familiar_cruce["id_persona_cargo"].dtype)


# Buscar variables relacionadas con Digiturnos
print("\n4. VARIABLES RELACIONADAS CON DIGITURNOS")

for nombre, df in dataframes_disponibles.items():

    if "digiturno" in nombre.lower():

        print(f"\nVariable: {nombre}")
        print(f"Registros: {len(df):,}")

        print("\nColumnas:")
        print(df.columns.tolist())

        print("\nPrimeros registros:")
        display(df.head(3))

======================================================================
VERIFICACIÓN DE ESTRUCTURAS PARA INTEGRACIÓN
======================================================================

1. DATAFRAMES DISPONIBLES
digiturnos: 883,080 registros
afiliados: 448,951 registros
grupo_familiar: 39,733 registros
perfil_calidad: 12 registros
validacion_temporal: 4 registros
resumen_tiempos: 3 registros
control_calidad_tiempo: 2 registros
casos_inconsistentes: 4 registros
digiturnos_tiempos: 883,076 registros
dim_afiliados: 168,866 registros
gf_base: 39,733 registros
gf_base_valida: 39,732 registros
resumen_titulares: 24,554 registros
titular_unico: 24,554 registros
dim_grupo_familiar: 24,554 registros
afiliados_nulos: 10 registros
afiliados_duplicados: 0 registros
dim_afiliados_cruce: 168,856 registros
dim_grupo_familiar_cruce: 24,554 registros

2. DIMENSIÓN DE AFILIADOS
['id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil']

Tipo de llave:
Int64

3. DIMENSIÓN DE GRUPO FAMILIAR
['id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion']

Tipo de llave:
Int64

4. VARIABLES RELACIONADAS CON DIGITURNOS

Variable: digiturnos
Registros: 883,080

Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo']

Primeros registros:

,Sede,UES,Clasifiacion,Usuario_receptor,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,Fecha_Servico,Hora_solicitud_Servicio,Hora_llamado__Servicio,Hora_finalizado_Servicio,...,id_cliente,fecha_servicio,ts_solicitud,ts_llamado,ts_finalizacion,tiempo_espera_min,tiempo_atencion_min,tiempo_total_min,flag_tiempo_valido,estado_calidad_tiempo
0,Calle 26,Subsidio,Radicacion afiliaciones,39767666,Servicio,Rad afiliacion trabajadores hasta 10 formularios,20/03/2024,10:49:41,10:54:47,10:56:03,...,29012215,2024-03-20,2024-03-20 10:49:41,2024-03-20 10:54:47,2024-03-20 10:56:03,5.100000,1.266667,6.366667,True,Válido
1,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:08:56,10:09:18,10:12:34,...,20000240,2024-09-07,2024-09-07 10:08:56,2024-09-07 10:09:18,2024-09-07 10:12:34,0.366667,3.266667,3.633333,True,Válido
2,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:12:34,10:12:34,10:16:37,...,20000240,2024-09-07,2024-09-07 10:12:34,2024-09-07 10:12:34,2024-09-07 10:16:37,0.000000,4.050000,4.050000,True,Válido

Variable: digiturnos_tiempos
Registros: 883,076

Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo']

Primeros registros:

,Sede,UES,Clasifiacion,Usuario_receptor,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,Fecha_Servico,Hora_solicitud_Servicio,Hora_llamado__Servicio,Hora_finalizado_Servicio,...,id_cliente,fecha_servicio,ts_solicitud,ts_llamado,ts_finalizacion,tiempo_espera_min,tiempo_atencion_min,tiempo_total_min,flag_tiempo_valido,estado_calidad_tiempo
0,Calle 26,Subsidio,Radicacion afiliaciones,39767666,Servicio,Rad afiliacion trabajadores hasta 10 formularios,20/03/2024,10:49:41,10:54:47,10:56:03,...,29012215,2024-03-20,2024-03-20 10:49:41,2024-03-20 10:54:47,2024-03-20 10:56:03,5.100000,1.266667,6.366667,True,Válido
1,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:08:56,10:09:18,10:12:34,...,20000240,2024-09-07,2024-09-07 10:08:56,2024-09-07 10:09:18,2024-09-07 10:12:34,0.366667,3.266667,3.633333,True,Válido
2,Calle 26,Subsidio,Radicacion afiliaciones,52622358,Servicio,Rad afiliacion trabajadores hasta 10 formularios,7/09/2024,10:12:34,10:12:34,10:16:37,...,20000240,2024-09-07,2024-09-07 10:12:34,2024-09-07 10:12:34,2024-09-07 10:16:37,0.000000,4.050000,4.050000,True,Válido

### 4.15. Validación de identificadores para el cruce

Se verifican las llaves de identificación de Digiturnos y de las dimensiones maestras, con el propósito de garantizar que las relaciones entre tablas sean consistentes.

Se evalúan los tipos de datos, los valores nulos y la correspondencia de identificadores antes de clasificar a los usuarios según su condición de afiliación.

In [44]:
# ============================================================
# 4.15. VALIDACIÓN DE IDENTIFICADORES
# ============================================================

print("=" * 65)
print("VALIDACIÓN DE LLAVES DE INTEGRACIÓN")
print("=" * 65)

# 1. Columnas de identificación de Digiturnos
print("\n1. IDENTIFICADORES DE DIGITURNOS")

columnas_id = [
    col for col in digiturnos_tiempos.columns
    if any(
        palabra in col.lower()
        for palabra in ["ident", "documento", "cliente"]
    )
]

print("Columnas identificadas:", columnas_id)

for col in columnas_id:
    print(f"\nColumna: {col}")
    print("Tipo:", digiturnos_tiempos[col].dtype)
    print("Nulos:", digiturnos_tiempos[col].isna().sum())
    print("Valores únicos:", digiturnos_tiempos[col].nunique())
    print("Ejemplos:")
    print(digiturnos_tiempos[col].dropna().head(5).tolist())


# 2. Llave de afiliados
print("\n2. IDENTIFICADORES DE AFILIADOS")

print("Tipo:", dim_afiliados_cruce["id_normalizado"].dtype)
print("Nulos:", dim_afiliados_cruce["id_normalizado"].isna().sum())
print("Duplicados:", dim_afiliados_cruce["id_normalizado"].duplicated().sum())


# 3. Llave de personas a cargo
print("\n3. IDENTIFICADORES DE GRUPO FAMILIAR")

print("Tipo:", dim_grupo_familiar_cruce["id_persona_cargo"].dtype)
print("Nulos:", dim_grupo_familiar_cruce["id_persona_cargo"].isna().sum())
print("Duplicados:", dim_grupo_familiar_cruce["id_persona_cargo"].duplicated().sum())


# 4. Estructura de las dimensiones
print("\n4. COLUMNAS DISPONIBLES EN DIMENSIONES")

print("\nAfiliados:")
print(dim_afiliados_cruce.columns.tolist())

print("\nGrupo familiar:")
print(dim_grupo_familiar_cruce.columns.tolist())

=================================================================
VALIDACIÓN DE LLAVES DE INTEGRACIÓN
=================================================================

1. IDENTIFICADORES DE DIGITURNOS
Columnas identificadas: ['Identificacion_Cliente', 'id_cliente']

Columna: Identificacion_Cliente
Tipo: float64
Nulos: 0
Valores únicos: 60335
Ejemplos:
[29012215.0, 20000240.0, 20000240.0, 20000187.0, 20000187.0]

Columna: id_cliente
Tipo: string
Nulos: 0
Valores únicos: 60335
Ejemplos:
['29012215', '20000240', '20000240', '20000187', '20000187']

2. IDENTIFICADORES DE AFILIADOS
Tipo: Int64
Nulos: 0
Duplicados: 0

3. IDENTIFICADORES DE GRUPO FAMILIAR
Tipo: Int64
Nulos: 0
Duplicados: 0

4. COLUMNAS DISPONIBLES EN DIMENSIONES

Afiliados:
['id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil']

Grupo familiar:
['id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion']

### 4.16. Integración de Digiturnos con la dimensión de afiliados

Se realiza el primer cruce entre los registros de Digiturnos y la dimensión maestra de afiliados, utilizando los identificadores previamente normalizados.

La integración conserva la totalidad de los registros de Digiturnos y permite identificar a los usuarios con afiliación directa, incorporando sus características poblacionales.

Se verifican la correspondencia de identificadores y la conservación del número de registros para prevenir duplicaciones durante el proceso.

In [45]:
# ============================================================
# 4.16. INTEGRACIÓN DE DIGITURNOS CON AFILIADOS
# ============================================================

print("=" * 65)
print("INTEGRACIÓN DE DIGITURNOS CON AFILIADOS")
print("=" * 65)

# 1. Conservar una copia de trabajo
digiturnos_integrados = digiturnos_tiempos.copy()

total_inicial = len(digiturnos_integrados)

# 2. Preparar las llaves como texto
digiturnos_integrados["id_cliente"] = (
    digiturnos_integrados["id_cliente"]
    .astype("string")
    .str.strip()
)

afiliados_integracion = dim_afiliados_cruce.copy()

afiliados_integracion["id_normalizado"] = (
    afiliados_integracion["id_normalizado"]
    .astype("string")
    .str.strip()
)

# 3. Verificar unicidad de la dimensión
assert (
    afiliados_integracion["id_normalizado"]
    .is_unique
), "ERROR: existen identificadores duplicados en afiliados."

# 4. Realizar cruce conservando todos los turnos
digiturnos_integrados = digiturnos_integrados.merge(
    afiliados_integracion,
    how="left",
    left_on="id_cliente",
    right_on="id_normalizado",
    validate="many_to_one",
    indicator="_cruce_afiliados"
)

# 5. Clasificar coincidencias directas
digiturnos_integrados["tipo_vinculacion"] = "Pendiente"

digiturnos_integrados.loc[
    digiturnos_integrados["_cruce_afiliados"] == "both",
    "tipo_vinculacion"
] = "Afiliado"

# 6. Validar conservación de registros
total_final = len(digiturnos_integrados)

assert total_inicial == total_final, (
    "ERROR: el cruce modificó la cantidad de registros."
)

# 7. Resumen de resultados
print("\nREGISTROS")
print("Antes del cruce:", f"{total_inicial:,}")
print("Después del cruce:", f"{total_final:,}")

print("\nCLASIFICACIÓN PRELIMINAR")
print(
    digiturnos_integrados["tipo_vinculacion"]
    .value_counts(dropna=False)
)

print("\nPORCENTAJE DE COINCIDENCIA")
print(
    digiturnos_integrados["_cruce_afiliados"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nVALIDACIÓN COMPLETADA")
print("Se conservaron todos los registros de Digiturnos.")

=================================================================
INTEGRACIÓN DE DIGITURNOS CON AFILIADOS
=================================================================

REGISTROS
Antes del cruce: 883,076
Después del cruce: 883,076

CLASIFICACIÓN PRELIMINAR
tipo_vinculacion
Pendiente    581152
Afiliado     301924
Name: count, dtype: int64

PORCENTAJE DE COINCIDENCIA
_cruce_afiliados
left_only     65.81
both          34.19
right_only     0.00
Name: proportion, dtype: float64

VALIDACIÓN COMPLETADA
Se conservaron todos los registros de Digiturnos.

### 4.17. Integración con la dimensión de grupo familiar

Se realiza un segundo cruce sobre los registros de Digiturnos que no presentan coincidencia directa con la dimensión de afiliados.

La integración permite identificar usuarios registrados como personas a cargo y recuperar la identificación del afiliado titular, conservando la clasificación de afiliación directa obtenida anteriormente.

Se valida la conservación de los registros y se establece una clasificación preliminar en tres categorías: Afiliado, Grupo familiar y No afiliado.

In [46]:
# ============================================================
# 4.17. INTEGRACIÓN CON GRUPO FAMILIAR
# ============================================================

print("=" * 65)
print("INTEGRACIÓN DE DIGITURNOS CON GRUPO FAMILIAR")
print("=" * 65)

# 1. Conservar una copia de la base integrada
digiturnos_clasificados = digiturnos_integrados.copy()

total_inicial = len(digiturnos_clasificados)

# 2. Preparar la dimensión de grupo familiar
grupo_familiar_integracion = dim_grupo_familiar_cruce.copy()

# Normalizar tipos de identificadores
grupo_familiar_integracion["id_persona_cargo"] = (
    grupo_familiar_integracion["id_persona_cargo"]
    .astype("string")
    .str.strip()
)

grupo_familiar_integracion["id_afiliado_titular"] = (
    grupo_familiar_integracion["id_afiliado_titular"]
    .astype("string")
    .str.strip()
)

# 3. Verificar unicidad de la llave
assert (
    grupo_familiar_integracion["id_persona_cargo"]
    .is_unique
), "ERROR: existen personas a cargo duplicadas."

# 4. Cruzar Digiturnos con grupo familiar
digiturnos_clasificados = digiturnos_clasificados.merge(
    grupo_familiar_integracion,
    how="left",
    left_on="id_cliente",
    right_on="id_persona_cargo",
    validate="many_to_one",
    indicator="_cruce_grupo_familiar"
)

# 5. Identificar personas a cargo entre los pendientes
condicion_grupo = (
    (digiturnos_clasificados["tipo_vinculacion"] == "Pendiente")
    &
    (digiturnos_clasificados["_cruce_grupo_familiar"] == "both")
)

digiturnos_clasificados.loc[
    condicion_grupo,
    "tipo_vinculacion"
] = "Grupo familiar"

# 6. Clasificar registros restantes
digiturnos_clasificados.loc[
    digiturnos_clasificados["tipo_vinculacion"] == "Pendiente",
    "tipo_vinculacion"
] = "No afiliado"

# 7. Verificar conservación de registros
total_final = len(digiturnos_clasificados)

assert total_inicial == total_final, (
    "ERROR: la integración modificó la cantidad de registros."
)

# 8. Verificar conservación de afiliados directos
afiliados_originales = (
    digiturnos_integrados["tipo_vinculacion"]
    .eq("Afiliado")
    .sum()
)

afiliados_finales = (
    digiturnos_clasificados["tipo_vinculacion"]
    .eq("Afiliado")
    .sum()
)

assert afiliados_originales == afiliados_finales, (
    "ERROR: se modificó la clasificación de afiliados directos."
)

# 9. Resumen final
resumen_clasificacion = (
    digiturnos_clasificados["tipo_vinculacion"]
    .value_counts()
    .rename_axis("Tipo de vinculación")
    .reset_index(name="Turnos")
)

resumen_clasificacion["Porcentaje"] = (
    resumen_clasificacion["Turnos"]
    / total_final * 100
).round(2)

print("\nREGISTROS")
print("Antes del cruce:", f"{total_inicial:,}")
print("Después del cruce:", f"{total_final:,}")

print("\nCLASIFICACIÓN DE USUARIOS")
print(resumen_clasificacion.to_string(index=False))

print("\nVALIDACIONES")
print("Conservación de registros: OK")
print("Conservación de afiliados directos: OK")
print("Total clasificado:", resumen_clasificacion["Turnos"].sum())

=================================================================
INTEGRACIÓN DE DIGITURNOS CON GRUPO FAMILIAR
=================================================================

REGISTROS
Antes del cruce: 883,076
Después del cruce: 883,076

CLASIFICACIÓN DE USUARIOS
Tipo de vinculación  Turnos  Porcentaje
        No afiliado  573340       64.93
           Afiliado  301924       34.19
     Grupo familiar    7812        0.88

VALIDACIONES
Conservación de registros: OK
Conservación de afiliados directos: OK
Total clasificado: 883076

### 4.18. Enriquecimiento poblacional del grupo familiar

Se vinculan los usuarios clasificados como grupo familiar con la dimensión maestra de afiliados, utilizando la identificación del titular.

El procedimiento permite recuperar las características poblacionales del afiliado titular y asociarlas a los turnos de sus personas a cargo.

Se evalúa la cobertura del enriquecimiento y se verifica que la integración conserve la totalidad de los registros y la clasificación previamente obtenida.

In [47]:
# ============================================================
# 4.18. ENRIQUECIMIENTO POBLACIONAL DEL GRUPO FAMILIAR
# ============================================================

print("=" * 65)
print("ENRIQUECIMIENTO POBLACIONAL DEL GRUPO FAMILIAR")
print("=" * 65)

# 1. Conservar base clasificada
digiturnos_enriquecidos = digiturnos_clasificados.copy()

total_inicial = len(digiturnos_enriquecidos)

# 2. Preparar información de los titulares
columnas_poblacionales = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

titulares = afiliados_integracion[
    ["id_normalizado"] + columnas_poblacionales
].copy()

# Diferenciar las variables del titular
titulares = titulares.rename(
    columns={
        "id_normalizado": "id_titular_cruce",
        **{
            col: f"{col}_titular"
            for col in columnas_poblacionales
        }
    }
)

# 3. Normalizar identificador del titular
titulares["id_titular_cruce"] = (
    titulares["id_titular_cruce"]
    .astype("string")
    .str.strip()
)

# 4. Validar unicidad
assert titulares["id_titular_cruce"].is_unique, (
    "ERROR: existen titulares duplicados."
)

# 5. Integrar información poblacional del titular
digiturnos_enriquecidos = digiturnos_enriquecidos.merge(
    titulares,
    how="left",
    left_on="id_afiliado_titular",
    right_on="id_titular_cruce",
    validate="many_to_one",
    indicator="_cruce_titular"
)

# 6. Validar conservación de registros
assert len(digiturnos_enriquecidos) == total_inicial, (
    "ERROR: se modificó el número de registros."
)

# 7. Identificar turnos de grupo familiar
es_grupo_familiar = (
    digiturnos_enriquecidos["tipo_vinculacion"]
    == "Grupo familiar"
)

total_grupo_familiar = es_grupo_familiar.sum()

# 8. Evaluar coincidencia con el titular
titular_identificado = (
    es_grupo_familiar
    & (
        digiturnos_enriquecidos["_cruce_titular"]
        == "both"
    )
)

total_titular_identificado = titular_identificado.sum()

sin_titular = (
    total_grupo_familiar
    - total_titular_identificado
)

cobertura = (
    total_titular_identificado
    / total_grupo_familiar * 100
    if total_grupo_familiar > 0
    else 0
)

# 9. Crear variables poblacionales consolidadas
for col in columnas_poblacionales:

    digiturnos_enriquecidos[f"{col}_final"] = (
        digiturnos_enriquecidos[col]
    )

    digiturnos_enriquecidos.loc[
        es_grupo_familiar,
        f"{col}_final"
    ] = digiturnos_enriquecidos.loc[
        es_grupo_familiar,
        f"{col}_titular"
    ]

# 10. Verificar que la clasificación no cambió
assert (
    digiturnos_enriquecidos["tipo_vinculacion"]
    .value_counts()
    .sort_index()
    .equals(
        digiturnos_clasificados["tipo_vinculacion"]
        .value_counts()
        .sort_index()
    )
), "ERROR: se modificó la clasificación de vinculación."

# 11. Presentar resultados
print("\nREGISTROS")
print("Antes:", f"{total_inicial:,}")
print("Después:", f"{len(digiturnos_enriquecidos):,}")

print("\nGRUPO FAMILIAR")
print("Turnos:", f"{total_grupo_familiar:,}")
print(
    "Con titular identificado:",
    f"{total_titular_identificado:,}"
)
print("Sin titular identificado:", f"{sin_titular:,}")
print("Cobertura del cruce:", f"{cobertura:.2f}%")

print("\nDISPONIBILIDAD DE VARIABLES POBLACIONALES")

for col in columnas_poblacionales:
    disponibles = (
        digiturnos_enriquecidos.loc[
            es_grupo_familiar,
            f"{col}_final"
        ]
        .notna()
        .sum()
    )

    print(f"{col}: {disponibles:,} de {total_grupo_familiar:,}")

print("\nVALIDACIÓN COMPLETADA")
print("Registros y clasificación conservados.")

=================================================================
ENRIQUECIMIENTO POBLACIONAL DEL GRUPO FAMILIAR
=================================================================

REGISTROS
Antes: 883,076
Después: 883,076

GRUPO FAMILIAR
Turnos: 7,812
Con titular identificado: 674
Sin titular identificado: 7,138
Cobertura del cruce: 8.63%

DISPONIBILIDAD DE VARIABLES POBLACIONALES
Categoria: 674 de 7,812
Segmento_poblacional: 674 de 7,812
Piramide1: 674 de 7,812
Piramide2: 674 de 7,812

VALIDACIÓN COMPLETADA
Registros y clasificación conservados.

### 4.19. Diagnóstico de cobertura del enriquecimiento familiar

Se analiza la correspondencia entre los identificadores de los titulares registrados en la dimensión de grupo familiar y los identificadores de la dimensión maestra de afiliados.

El objetivo es establecer si la baja cobertura del enriquecimiento se relaciona con diferencias de formato, ausencia de titulares en la dimensión o inconsistencias en las relaciones familiares.

Este diagnóstico no modifica los registros originales ni la clasificación de los turnos.

In [48]:
# ============================================================
# 4.19. DIAGNÓSTICO DE COBERTURA DEL CRUCE FAMILIAR
# ============================================================

import pandas as pd

print("=" * 65)
print("DIAGNÓSTICO DE COBERTURA DEL CRUCE FAMILIAR")
print("=" * 65)

# 1. Identificar los turnos de grupo familiar
familiares = digiturnos_enriquecidos.loc[
    digiturnos_enriquecidos["tipo_vinculacion"]
    == "Grupo familiar"
].copy()

# 2. Examinar identificadores del titular
print("\n1. IDENTIFICADORES DEL TITULAR")

print("Turnos familiares:", len(familiares))

print(
    "Titulares nulos:",
    familiares["id_afiliado_titular"].isna().sum()
)

print(
    "Titulares únicos:",
    familiares["id_afiliado_titular"].nunique()
)

print("\nTipo de dato:")
print(familiares["id_afiliado_titular"].dtype)

print("\nEjemplos:")
print(
    familiares["id_afiliado_titular"]
    .dropna()
    .head(10)
    .tolist()
)

# 3. Comparar formatos de identificadores
print("\n2. COMPARACIÓN DE FORMATOS")

print(
    "Tipo de ID en afiliados:",
    dim_afiliados_cruce["id_normalizado"].dtype
)

print(
    "Tipo de ID del titular:",
    familiares["id_afiliado_titular"].dtype
)

# 4. Normalización temporal para diagnóstico
def normalizar_id_diagnostico(serie):

    return (
        serie.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
    )

ids_titulares = normalizar_id_diagnostico(
    familiares["id_afiliado_titular"]
)

ids_afiliados = normalizar_id_diagnostico(
    dim_afiliados_cruce["id_normalizado"]
)

# 5. Comparar coincidencias
coincidencias = ids_titulares.isin(
    ids_afiliados.dropna()
)

print("\n3. COINCIDENCIAS TRAS NORMALIZACIÓN")

print("Turnos familiares:", len(familiares))
print("Con coincidencia:", coincidencias.sum())
print("Sin coincidencia:", (~coincidencias).sum())

print(
    "Cobertura:",
    f"{coincidencias.mean() * 100:.2f}%"
)

# 6. Examinar titulares no encontrados
print("\n4. EJEMPLOS DE TITULARES NO ENCONTRADOS")

print(
    familiares.loc[
        ~coincidencias,
        [
            "id_cliente",
            "id_afiliado_titular",
            "estado_relacion"
        ]
    ].head(15).to_string(index=False)
)

# 7. Verificar si existen titulares múltiples
print("\n5. DISTRIBUCIÓN DE RELACIONES FAMILIARES")

print(
    familiares["estado_relacion"]
    .value_counts(dropna=False)
)

print("\nDIAGNÓSTICO FINALIZADO")
print("No se modificaron las bases originales.")

=================================================================
DIAGNÓSTICO DE COBERTURA DEL CRUCE FAMILIAR
=================================================================

1. IDENTIFICADORES DEL TITULAR
Turnos familiares: 7812
Titulares nulos: 1613
Titulares únicos: 1498

Tipo de dato:
string

Ejemplos:
['12339122', '12339122', '10141933', '10141933', '10141933', '10141933', '10141933', '10697300', '10697300', '10697300']

2. COMPARACIÓN DE FORMATOS
Tipo de ID en afiliados: Int64
Tipo de ID del titular: string

3. COINCIDENCIAS TRAS NORMALIZACIÓN
Turnos familiares: 7812
Con coincidencia: 674
Sin coincidencia: 7138
Cobertura: 8.63%

4. EJEMPLOS DE TITULARES NO ENCONTRADOS
id_cliente id_afiliado_titular     estado_relacion
  12338895            12339122       Titular único
  12338895            12339122       Titular único
  12336893            10141933       Titular único
  12336893            10141933       Titular único
  12336893            10141933       Titular único
  12336893            10141933       Titular único
  12336893            10141933       Titular único
  12335012            10697300       Titular único
  12335012            10697300       Titular único
  12335012            10697300       Titular único
  12334927            10124242       Titular único
  12334927            10124242       Titular único
  12334927            10124242       Titular único
  12334927            10124242       Titular único
  12334882                <NA> Múltiples titulares

5. DISTRIBUCIÓN DE RELACIONES FAMILIARES
estado_relacion
Titular único          6199
Múltiples titulares    1613
Name: count, dtype: int64

DIAGNÓSTICO FINALIZADO
No se modificaron las bases originales.

### 4.20. Auditoría de titulares familiares sin coincidencia

**Objetivo:** identificar si la ausencia de coincidencias se origina
en la fuente original de afiliados, en la construcción de la dimensión
maestra o en diferencias de normalización de identificadores.

La auditoría se realiza sin modificar las fuentes ni las
clasificaciones existentes.

In [49]:
import pandas as pd

print("=" * 70)
print("4.20. AUDITORÍA DE TITULARES SIN COINCIDENCIA")
print("=" * 70)

# Revisar las estructuras disponibles
print("\nCOLUMNAS DE DIGITURNOS:")
print(digiturnos_final.columns.tolist()
      if "digiturnos_final" in globals()
      else "Verificar nombre del dataframe final")

print("\nCOLUMNAS DE DIMENSIÓN AFILIADOS:")
print(dim_afiliados.columns.tolist())

print("\nCOLUMNAS DE GRUPO FAMILIAR:")
print(dim_grupo_familiar.columns.tolist())

print("\nCOLUMNAS DE BASE ORIGINAL DE AFILIADOS:")
print(afiliados.columns.tolist())

======================================================================
4.20. AUDITORÍA DE TITULARES SIN COINCIDENCIA
======================================================================

COLUMNAS DE DIGITURNOS:
Verificar nombre del dataframe final

COLUMNAS DE DIMENSIÓN AFILIADOS:
['id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil']

COLUMNAS DE GRUPO FAMILIAR:
['id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion']

COLUMNAS DE BASE ORIGINAL DE AFILIADOS:
['Unnamed: 0', 'id_persona_Modificado', 'NumIdPersona_Modificado', 'Nombre', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'RazonSocial', 'Genero', 'id_afiliado']

In [50]:
import pandas as pd

print("=" * 70)
print("IDENTIFICACIÓN DE DATAFRAMES DE DIGITURNOS")
print("=" * 70)

for nombre, objeto in globals().copy().items():
    if isinstance(objeto, pd.DataFrame):
        if (
            "tipo_vinculacion" in objeto.columns
            and len(objeto) == 883076
        ):
            print(f"\nDataFrame candidato: {nombre}")
            print(f"Registros: {len(objeto):,}")
            print("Columnas:")
            print(objeto.columns.tolist())

            print("\nClasificación:")
            print(objeto["tipo_vinculacion"].value_counts(dropna=False))

======================================================================
IDENTIFICACIÓN DE DATAFRAMES DE DIGITURNOS
======================================================================

DataFrame candidato: digiturnos_integrados
Registros: 883,076
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion']

Clasificación:
tipo_vinculacion
Pendiente    581152
Afiliado     301924
Name: count, dtype: int64

DataFrame candidato: digiturnos_clasificados
Registros: 883,076
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar']

Clasificación:
tipo_vinculacion
No afiliado       573340
Afiliado          301924
Grupo familiar      7812
Name: count, dtype: int64

DataFrame candidato: digiturnos_enriquecidos
Registros: 883,076
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', 'id_titular_cruce', 'Categoria_titular', 'Segmento_poblacional_titular', 'Piramide1_titular', 'Piramide2_titular', '_cruce_titular', 'Categoria_final', 'Segmento_poblacional_final', 'Piramide1_final', 'Piramide2_final']

Clasificación:
tipo_vinculacion
No afiliado       573340
Afiliado          301924
Grupo familiar      7812
Name: count, dtype: int64

In [51]:
print("=" * 70)
print("COMPARACIÓN DE AFILIADOS: FUENTE ORIGINAL VS DIMENSIÓN")
print("=" * 70)

print("\nBASE ORIGINAL")
print("Registros:", len(afiliados))
print("Tipo de identificador:", afiliados["id_afiliado"].dtype)
print("Nulos:", afiliados["id_afiliado"].isna().sum())
print("Identificadores únicos:", afiliados["id_afiliado"].nunique())

print("\nDIMENSIÓN MAESTRA")
print("Registros:", len(dim_afiliados))
print("Tipo de identificador:", dim_afiliados["id_normalizado"].dtype)
print("Nulos:", dim_afiliados["id_normalizado"].isna().sum())
print(
    "Identificadores únicos:",
    dim_afiliados["id_normalizado"].nunique()
)

print("\nDIMENSIÓN PREPARADA PARA CRUCE")
print("Registros:", len(dim_afiliados_cruce))
print(
    "Identificadores únicos:",
    dim_afiliados_cruce["id_normalizado"].nunique()
)

======================================================================
COMPARACIÓN DE AFILIADOS: FUENTE ORIGINAL VS DIMENSIÓN
======================================================================

BASE ORIGINAL
Registros: 448951
Tipo de identificador: Int64
Nulos: 10
Identificadores únicos: 303946

DIMENSIÓN MAESTRA
Registros: 168866
Tipo de identificador: Int64
Nulos: 10
Identificadores únicos: 168856

DIMENSIÓN PREPARADA PARA CRUCE
Registros: 168856
Identificadores únicos: 168856

In [52]:
import pandas as pd

print("=" * 70)
print("4.20.3. CONCILIACIÓN DE TITULARES FAMILIARES")
print("=" * 70)

# Normalización auxiliar para comparar identificadores
def normalizar_id_analisis(serie):
    return (
        serie.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .replace({"": pd.NA, "nan": pd.NA, "<NA>": pd.NA})
    )

# Conjuntos de identificadores válidos
ids_fuente = set(
    normalizar_id_analisis(afiliados["id_afiliado"]).dropna()
)

ids_dimension = set(
    normalizar_id_analisis(
        dim_afiliados_cruce["id_normalizado"]
    ).dropna()
)

# Comprobar relaciones entre fuente y dimensión
print("\nCOMPARACIÓN GENERAL")
print("IDs únicos en fuente:", len(ids_fuente))
print("IDs únicos en dimensión:", len(ids_dimension))
print("IDs solo en fuente:", len(ids_fuente - ids_dimension))
print("IDs solo en dimensión:", len(ids_dimension - ids_fuente))

# Trabajar exclusivamente con registros familiares
familiares_auditoria = digiturnos_clasificados.loc[
    digiturnos_clasificados["tipo_vinculacion"] == "Grupo familiar"
].copy()

print("\nREGISTROS FAMILIARES:", len(familiares_auditoria))

# Confirmar disponibilidad de la columna del titular
print("\nCOLUMNAS RELACIONADAS CON TITULAR:")
print([
    c for c in familiares_auditoria.columns
    if "titular" in c.lower()
])

print("\nCOLUMNAS RELACIONADAS CON IDENTIFICACIÓN:")
print([
    c for c in familiares_auditoria.columns
    if "id_" in c.lower() or "identificacion" in c.lower()
])

======================================================================
4.20.3. CONCILIACIÓN DE TITULARES FAMILIARES
======================================================================

COMPARACIÓN GENERAL
IDs únicos en fuente: 303946
IDs únicos en dimensión: 168856
IDs solo en fuente: 135090
IDs solo en dimensión: 0

REGISTROS FAMILIARES: 7812

COLUMNAS RELACIONADAS CON TITULAR:
['n_titulares', 'id_afiliado_titular']

COLUMNAS RELACIONADAS CON IDENTIFICACIÓN:
['Identificacion_Cliente', 'id_cliente', 'id_normalizado', 'id_persona_cargo', 'id_afiliado_titular']

In [53]:
print("=" * 70)
print("4.20.4. AUDITORÍA DEFINITIVA DE TITULARES")
print("=" * 70)

# Copia independiente para auditoría
auditoria_titulares = familiares_auditoria.copy()

# Normalizar identificador del titular
auditoria_titulares["id_titular_auditoria"] = (
    normalizar_id_analisis(
        auditoria_titulares["id_afiliado_titular"]
    )
)

# Identificar presencia en cada fuente
auditoria_titulares["en_fuente_original"] = (
    auditoria_titulares["id_titular_auditoria"]
    .isin(ids_fuente)
)

auditoria_titulares["en_dimension"] = (
    auditoria_titulares["id_titular_auditoria"]
    .isin(ids_dimension)
)

# Clasificación de resultados
def clasificar_auditoria(row):

    if pd.isna(row["id_titular_auditoria"]):
        return "01. Sin identificador de titular"

    if row["en_dimension"]:
        return "02. Titular encontrado en dimensión"

    if row["en_fuente_original"]:
        return "03. Titular solo en fuente original"

    return "04. Titular ausente en ambas fuentes"


auditoria_titulares["estado_auditoria"] = (
    auditoria_titulares.apply(
        clasificar_auditoria,
        axis=1
    )
)

# Resumen por estado
resumen_auditoria = (
    auditoria_titulares
    .groupby("estado_auditoria", dropna=False)
    .agg(
        turnos=("estado_auditoria", "size"),
        titulares_unicos=("id_titular_auditoria", "nunique")
    )
    .reset_index()
)

resumen_auditoria["porcentaje"] = (
    resumen_auditoria["turnos"]
    / len(auditoria_titulares)
    * 100
).round(2)

print("\nRESULTADOS DE LA AUDITORÍA")
display(resumen_auditoria)

print("\nVALIDACIÓN DE CONSERVACIÓN")
print("Turnos originales:", len(familiares_auditoria))
print("Turnos auditados:", len(auditoria_titulares))
print("Total conciliado:", resumen_auditoria["turnos"].sum())

assert len(auditoria_titulares) == 7812
assert resumen_auditoria["turnos"].sum() == 7812

print("\nVALIDACIÓN COMPLETADA")
print("Se conservaron todos los turnos familiares.")

======================================================================
4.20.4. AUDITORÍA DEFINITIVA DE TITULARES
======================================================================

RESULTADOS DE LA AUDITORÍA

                       estado_auditoria  turnos  titulares_unicos  porcentaje
0      01. Sin identificador de titular    1613                 0       20.65
1   02. Titular encontrado en dimensión     674               180        8.63
2   03. Titular solo en fuente original    5411              1294       69.27
3  04. Titular ausente en ambas fuentes     114                24        1.46

VALIDACIÓN DE CONSERVACIÓN
Turnos originales: 7812
Turnos auditados: 7812
Total conciliado: 7812

VALIDACIÓN COMPLETADA
Se conservaron todos los turnos familiares.

### 4.20.5. Evaluación de calidad de los perfiles excluidos de la dimensión maestra

**Objetivo:** evaluar la integridad y consistencia de los perfiles de titulares familiares que existen en `BD_AFILIADOS.csv`, pero no están representados en `dim_afiliados`.

**Criterios de evaluación:**
1. Disponibilidad de atributos poblacionales.
2. Cantidad de registros por identificador.
3. Consistencia de los atributos entre registros.
4. Posibilidad de recuperación mediante reglas de consolidación verificables.

**Principio metodológico:** preservar las fuentes originales y no incorporar perfiles a la dimensión maestra hasta verificar su calidad.

In [55]:
# ============================================================
# DIAGNÓSTICO DE ESTRUCTURAS DE LA AUDITORÍA 4.20.4
# ============================================================

print("=" * 65)
print("IDENTIFICACIÓN DE DATAFRAMES DE AUDITORÍA")
print("=" * 65)

for nombre, objeto in list(globals().items()):

    if (
        isinstance(objeto, pd.DataFrame)
        and (
            "famil" in nombre.lower()
            or "audit" in nombre.lower()
            or "titular" in nombre.lower()
        )
    ):

        print(f"\nDATAFRAME: {nombre}")
        print(f"Registros: {len(objeto):,}")
        print("Columnas:")
        print(objeto.columns.tolist())

        columnas_estado = [
            c for c in objeto.columns
            if "estado" in c.lower()
            or "auditoria" in c.lower()
        ]

        if columnas_estado:
            for columna in columnas_estado:
                print(f"\nDistribución de {columna}:")
                print(
                    objeto[columna]
                    .value_counts(dropna=False)
                    .head(10)
                )

=================================================================
IDENTIFICACIÓN DE DATAFRAMES DE AUDITORÍA
=================================================================

DATAFRAME: grupo_familiar
Registros: 39,733
Columnas:
['NUM_IDENTIFICACION_AFILIADO', 'NUM_IDENTIFICACION_PERSONA_A_CARGO', 'id_afiliado_titular', 'id_persona_cargo']

DATAFRAME: resumen_titulares
Registros: 24,554
Columnas:
['id_persona_cargo', 'n_titulares']

DATAFRAME: titular_unico
Registros: 24,554
Columnas:
['id_persona_cargo', 'id_afiliado_titular']

DATAFRAME: dim_grupo_familiar
Registros: 24,554
Columnas:
['id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion']

Distribución de estado_relacion:
estado_relacion
Titular único          16698
Múltiples titulares     7856
Name: count, dtype: int64

DATAFRAME: dim_grupo_familiar_cruce
Registros: 24,554
Columnas:
['id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion']

Distribución de estado_relacion:
estado_relacion
Titular único          16698
Múltiples titulares     7856
Name: count, dtype: int64

DATAFRAME: grupo_familiar_integracion
Registros: 24,554
Columnas:
['id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion']

Distribución de estado_relacion:
estado_relacion
Titular único          16698
Múltiples titulares     7856
Name: count, dtype: int64

DATAFRAME: titulares
Registros: 168,856
Columnas:
['id_titular_cruce', 'Categoria_titular', 'Segmento_poblacional_titular', 'Piramide1_titular', 'Piramide2_titular']

DATAFRAME: familiares
Registros: 7,812
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', 'id_titular_cruce', 'Categoria_titular', 'Segmento_poblacional_titular', 'Piramide1_titular', 'Piramide2_titular', '_cruce_titular', 'Categoria_final', 'Segmento_poblacional_final', 'Piramide1_final', 'Piramide2_final']

Distribución de estado_calidad_tiempo:
estado_calidad_tiempo
Válido    7812
Name: count, dtype: int64

Distribución de estado_relacion:
estado_relacion
Titular único          6199
Múltiples titulares    1613
Name: count, dtype: int64

DATAFRAME: familiares_auditoria
Registros: 7,812
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar']

Distribución de estado_calidad_tiempo:
estado_calidad_tiempo
Válido    7812
Name: count, dtype: int64

Distribución de estado_relacion:
estado_relacion
Titular único          6199
Múltiples titulares    1613
Name: count, dtype: int64

DATAFRAME: auditoria_titulares
Registros: 7,812
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', 'id_titular_auditoria', 'en_fuente_original', 'en_dimension', 'estado_auditoria']

Distribución de estado_calidad_tiempo:
estado_calidad_tiempo
Válido    7812
Name: count, dtype: int64

Distribución de estado_relacion:
estado_relacion
Titular único          6199
Múltiples titulares    1613
Name: count, dtype: int64

Distribución de id_titular_auditoria:
id_titular_auditoria
<NA>        1613
421443        31
10190661      27
530512        27
10705856      25
529557        23
808826        22
519603        21
10744162      20
10244941      20
Name: count, dtype: Int64

Distribución de estado_auditoria:
estado_auditoria
03. Titular solo en fuente original     5411
01. Sin identificador de titular        1613
02. Titular encontrado en dimensión      674
04. Titular ausente en ambas fuentes     114
Name: count, dtype: int64

DATAFRAME: resumen_auditoria
Registros: 4
Columnas:
['estado_auditoria', 'turnos', 'titulares_unicos', 'porcentaje']

Distribución de estado_auditoria:
estado_auditoria
01. Sin identificador de titular        1
02. Titular encontrado en dimensión     1
03. Titular solo en fuente original     1
04. Titular ausente en ambas fuentes    1
Name: count, dtype: int64

In [56]:
# ============================================================
# 4.20.5.1 IDENTIFICAR LA TABLA FINAL DE AUDITORÍA
# ============================================================

print("=" * 70)
print("IDENTIFICACIÓN DE LA CLASIFICACIÓN DE TITULARES")
print("=" * 70)

for nombre, objeto in list(globals().items()):

    if not isinstance(objeto, pd.DataFrame):
        continue

    columnas_auditoria = [
        columna
        for columna in objeto.columns
        if (
            "estado_auditoria" in columna.lower()
            or "estado_relacion" in columna.lower()
        )
    ]

    if columnas_auditoria:

        print(f"\nDATAFRAME: {nombre}")
        print(f"Registros: {len(objeto):,}")

        for columna in columnas_auditoria:
            print(f"\nColumna: {columna}")
            print(
                objeto[columna]
                .value_counts(dropna=False)
                .head(10)
                .to_string()
            )

======================================================================
IDENTIFICACIÓN DE LA CLASIFICACIÓN DE TITULARES
======================================================================

DATAFRAME: dim_grupo_familiar
Registros: 24,554

Columna: estado_relacion
estado_relacion
Titular único          16698
Múltiples titulares     7856

DATAFRAME: dim_grupo_familiar_cruce
Registros: 24,554

Columna: estado_relacion
estado_relacion
Titular único          16698
Múltiples titulares     7856

DATAFRAME: df
Registros: 24,554

Columna: estado_relacion
estado_relacion
Titular único          16698
Múltiples titulares     7856

DATAFRAME: digiturnos_clasificados
Registros: 883,076

Columna: estado_relacion
estado_relacion
NaN                    874717
Titular único            6630
Múltiples titulares      1729

DATAFRAME: grupo_familiar_integracion
Registros: 24,554

Columna: estado_relacion
estado_relacion
Titular único          16698
Múltiples titulares     7856

DATAFRAME: digiturnos_enriquecidos
Registros: 883,076

Columna: estado_relacion
estado_relacion
NaN                    874717
Titular único            6630
Múltiples titulares      1729

DATAFRAME: familiares
Registros: 7,812

Columna: estado_relacion
estado_relacion
Titular único          6199
Múltiples titulares    1613

DATAFRAME: familiares_auditoria
Registros: 7,812

Columna: estado_relacion
estado_relacion
Titular único          6199
Múltiples titulares    1613

DATAFRAME: auditoria_titulares
Registros: 7,812

Columna: estado_relacion
estado_relacion
Titular único          6199
Múltiples titulares    1613

Columna: estado_auditoria
estado_auditoria
03. Titular solo en fuente original     5411
01. Sin identificador de titular        1613
02. Titular encontrado en dimensión      674
04. Titular ausente en ambas fuentes     114

DATAFRAME: resumen_auditoria
Registros: 4

Columna: estado_auditoria
estado_auditoria
01. Sin identificador de titular        1
02. Titular encontrado en dimensión     1
03. Titular solo en fuente original     1
04. Titular ausente en ambas fuentes    1

In [57]:
# ============================================================
# 4.20.5.1 VERIFICACIÓN FINAL DE ESTRUCTURA
# ============================================================

print("=" * 70)
print("ESTRUCTURAS PARA RECUPERACIÓN DE TITULARES")
print("=" * 70)

for nombre in [
    "familiares_auditoria",
    "afiliados",
    "dim_afiliados_cruce"
]:
    objeto = globals().get(nombre)

    if isinstance(objeto, pd.DataFrame):
        print(f"\nDATAFRAME: {nombre}")
        print(f"Registros: {len(objeto):,}")
        print("Columnas:")
        print(objeto.columns.tolist())
    else:
        print(f"\n{nombre}: no disponible")

======================================================================
ESTRUCTURAS PARA RECUPERACIÓN DE TITULARES
======================================================================

DATAFRAME: familiares_auditoria
Registros: 7,812
Columnas:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar']

DATAFRAME: afiliados
Registros: 448,951
Columnas:
['Unnamed: 0', 'id_persona_Modificado', 'NumIdPersona_Modificado', 'Nombre', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'RazonSocial', 'Genero', 'id_afiliado']

DATAFRAME: dim_afiliados_cruce
Registros: 168,856
Columnas:
['id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil']

### 4.20.5. Evaluación de calidad de los perfiles excluidos de la dimensión maestra

**Objetivo:** Evaluar la calidad de los perfiles de afiliados que están presentes en la fuente original, pero ausentes de la dimensión maestra, para determinar su potencial de recuperación y enriquecimiento de los registros de Digiturnos.

**Procedimiento:**
1. Identificar los titulares presentes únicamente en la fuente original.
2. Recuperar sus registros originales.
3. Evaluar la completitud de las variables poblacionales.
4. Identificar duplicidades y posibles inconsistencias entre perfiles.
5. Cuantificar los titulares y turnos potencialmente recuperables.

**Criterio metodológico:** La existencia de un identificador en la fuente original no garantiza que su perfil pueda incorporarse directamente a la dimensión. La recuperación estará condicionada a la calidad y consistencia de la información disponible.

In [59]:
# ============================================================
# 4.20.5.1. RECUPERACIÓN DE TITULARES EXCLUIDOS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("4.20.5.1. RECUPERACIÓN DE TITULARES EXCLUIDOS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Normalización de identificadores
# ------------------------------------------------------------

def normalizar_id(serie):
    resultado = (
        serie.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
    )

    resultado = resultado.mask(
        resultado.isin(["", "nan", "None", "<NA>"])
    )

    return resultado


# ------------------------------------------------------------
# 2. Construcción de conjuntos de identificadores
# ------------------------------------------------------------

ids_fuente = set(
    normalizar_id(afiliados["id_afiliado"]).dropna()
)

ids_dimension = set(
    normalizar_id(
        dim_afiliados_cruce["id_normalizado"]
    ).dropna()
)


# ------------------------------------------------------------
# 3. Identificación de titulares excluidos
# ------------------------------------------------------------

familiares_revision = familiares_auditoria.copy()

familiares_revision["id_titular_auditoria"] = (
    normalizar_id(
        familiares_revision["id_afiliado_titular"]
    )
)

familiares_revision["presente_fuente"] = (
    familiares_revision["id_titular_auditoria"]
    .isin(ids_fuente)
)

familiares_revision["presente_dimension"] = (
    familiares_revision["id_titular_auditoria"]
    .isin(ids_dimension)
)

# Titulares presentes en fuente y ausentes en dimensión
mascara_excluidos = (
    familiares_revision["id_titular_auditoria"].notna()
    & familiares_revision["presente_fuente"]
    & ~familiares_revision["presente_dimension"]
)

turnos_excluidos = familiares_revision.loc[
    mascara_excluidos
].copy()

ids_excluidos = set(
    turnos_excluidos["id_titular_auditoria"]
)

# ------------------------------------------------------------
# 4. Validación de resultados
# ------------------------------------------------------------

print("\nRESULTADOS")

print(
    "Turnos familiares auditados:",
    f"{len(familiares_revision):,}"
)

print(
    "Turnos asociados a titulares excluidos:",
    f"{len(turnos_excluidos):,}"
)

print(
    "Titulares únicos excluidos:",
    f"{len(ids_excluidos):,}"
)

print("\nCONTROL DE CONCILIACIÓN")

if len(turnos_excluidos) == 5411 and len(ids_excluidos) == 1294:
    print("OK: Coincide con la auditoría 4.20.4.")
else:
    print(
        "ATENCIÓN: Los resultados difieren de la auditoría "
        "4.20.4. Revisar normalización y criterios de cruce."
    )

======================================================================
4.20.5.1. RECUPERACIÓN DE TITULARES EXCLUIDOS
======================================================================

RESULTADOS
Turnos familiares auditados: 7,812
Turnos asociados a titulares excluidos: 5,411
Titulares únicos excluidos: 1,294

CONTROL DE CONCILIACIÓN
OK: Coincide con la auditoría 4.20.4.

### 4.20.5.2. Evaluación de completitud y consistencia de perfiles

**Objetivo:** Determinar la calidad de los perfiles poblacionales de los titulares excluidos de la dimensión maestra, mediante la evaluación de completitud, duplicidad y consistencia de las variables Categoría, Segmento poblacional, Pirámide1 y Pirámide2.

**Criterios de evaluación:**
- **Perfil completo y consistente:** dispone de las cuatro variables poblacionales y presenta una única combinación de valores.
- **Perfil incompleto:** presenta al menos una variable poblacional sin información.
- **Perfil contradictorio:** presenta más de una combinación de valores poblacionales para el mismo identificador.

Los resultados permitirán estimar el potencial de recuperación de perfiles sin alterar las fuentes originales.

In [60]:
# ============================================================
# 4.20.5.2. CALIDAD DE PERFILES EXCLUIDOS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("4.20.5.2. EVALUACIÓN DE CALIDAD DE PERFILES EXCLUIDOS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Preparar registros originales
# ------------------------------------------------------------

variables_perfil = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

columnas_requeridas = ["id_afiliado"] + variables_perfil

faltantes = [
    c for c in columnas_requeridas
    if c not in afiliados.columns
]

if faltantes:
    raise ValueError(
        f"Columnas faltantes en afiliados: {faltantes}"
    )

perfiles_fuente = afiliados[columnas_requeridas].copy()

perfiles_fuente["id_titular"] = normalizar_id(
    perfiles_fuente["id_afiliado"]
)

perfiles_excluidos = perfiles_fuente.loc[
    perfiles_fuente["id_titular"].isin(ids_excluidos)
].copy()

# ------------------------------------------------------------
# 2. Normalizar valores poblacionales
# ------------------------------------------------------------

for columna in variables_perfil:

    perfiles_excluidos[columna] = (
        perfiles_excluidos[columna]
        .astype("string")
        .str.strip()
    )

    perfiles_excluidos[columna] = (
        perfiles_excluidos[columna].mask(
            perfiles_excluidos[columna].str.lower().isin(
                ["", "nan", "none", "null", "<na>"]
            )
        )
    )

# ------------------------------------------------------------
# 3. Evaluar completitud por registro
# ------------------------------------------------------------

perfiles_excluidos["variables_informadas"] = (
    perfiles_excluidos[variables_perfil]
    .notna()
    .sum(axis=1)
)

perfiles_excluidos["perfil_completo"] = (
    perfiles_excluidos["variables_informadas"] == 4
)

# ------------------------------------------------------------
# 4. Evaluar consistencia por titular
# ------------------------------------------------------------

# Cada combinación distinta se considera un perfil diferente.
# Se conservan los valores faltantes para detectar diferencias.

combinaciones = (
    perfiles_excluidos[
        ["id_titular"] + variables_perfil
    ]
    .drop_duplicates()
)

n_perfiles = (
    combinaciones
    .groupby("id_titular")
    .size()
    .rename("n_perfiles_distintos")
)

resumen_titulares = (
    perfiles_excluidos
    .groupby("id_titular")
    .agg(
        registros_fuente=("id_titular", "size"),
        registros_completos=("perfil_completo", "sum"),
        max_variables_informadas=(
            "variables_informadas", "max"
        )
    )
    .join(n_perfiles)
    .reset_index()
)

# ------------------------------------------------------------
# 5. Clasificación de calidad
# ------------------------------------------------------------

condiciones = [
    resumen_titulares["n_perfiles_distintos"] > 1,

    (
        (resumen_titulares["n_perfiles_distintos"] == 1)
        & (resumen_titulares["registros_completos"] > 0)
    )
]

opciones = [
    "Perfil contradictorio",
    "Perfil completo y consistente"
]

resumen_titulares["estado_calidad"] = np.select(
    condiciones,
    opciones,
    default="Perfil incompleto"
)

# ------------------------------------------------------------
# 6. Asociar impacto en turnos
# ------------------------------------------------------------

turnos_por_titular = (
    turnos_excluidos
    .groupby("id_titular_auditoria")
    .size()
    .rename("turnos_asociados")
    .reset_index()
    .rename(
        columns={
            "id_titular_auditoria": "id_titular"
        }
    )
)

resumen_titulares = resumen_titulares.merge(
    turnos_por_titular,
    on="id_titular",
    how="left",
    validate="one_to_one"
)

# ------------------------------------------------------------
# 7. Resumen ejecutivo
# ------------------------------------------------------------

resumen_calidad = (
    resumen_titulares
    .groupby("estado_calidad", dropna=False)
    .agg(
        titulares=("id_titular", "nunique"),
        turnos=("turnos_asociados", "sum")
    )
    .reset_index()
)

resumen_calidad["porcentaje_titulares"] = (
    resumen_calidad["titulares"]
    / resumen_calidad["titulares"].sum()
    * 100
).round(2)

resumen_calidad["porcentaje_turnos"] = (
    resumen_calidad["turnos"]
    / resumen_calidad["turnos"].sum()
    * 100
).round(2)

print("\nRESULTADOS DE CALIDAD")
display(resumen_calidad)

print("\nVALIDACIONES")

print(
    "Titulares evaluados:",
    f"{len(resumen_titulares):,}"
)

print(
    "Turnos asociados:",
    f"{resumen_titulares['turnos_asociados'].sum():,.0f}"
)

print(
    "Registros originales recuperados:",
    f"{len(perfiles_excluidos):,}"
)

assert len(resumen_titulares) == len(ids_excluidos), (
    "No se recuperaron todos los titulares excluidos."
)

assert resumen_titulares["turnos_asociados"].sum() == len(
    turnos_excluidos
), "No se conservaron todos los turnos asociados."

print("\nVALIDACIÓN COMPLETADA")
print("Se conservaron los titulares y turnos evaluados.")
print("No se modificaron las fuentes originales.")

======================================================================
4.20.5.2. EVALUACIÓN DE CALIDAD DE PERFILES EXCLUIDOS
======================================================================

RESULTADOS DE CALIDAD

,estado_calidad,titulares,turnos,porcentaje_titulares,porcentaje_turnos
0,Perfil contradictorio,1294,5411,100.0,100.0

VALIDACIONES
Titulares evaluados: 1,294
Turnos asociados: 5,411
Registros originales recuperados: 2,588

VALIDACIÓN COMPLETADA
Se conservaron los titulares y turnos evaluados.
No se modificaron las fuentes originales.

### 4.20.5.3. Diagnóstico de duplicidades y contradicciones reales

**Objetivo:** Determinar si las diferencias identificadas entre los registros de un mismo titular corresponden a duplicidades, información complementaria o contradicciones reales.

**Criterio de consistencia:** Se considera que existe una contradicción real cuando un mismo identificador presenta dos o más valores distintos y no nulos en alguna de las variables poblacionales.

**Alcance:** Esta etapa es exclusivamente diagnóstica. No modifica las fuentes originales ni incorpora registros a la dimensión maestra.

In [61]:
# ============================================================
# 4.20.5.3. DIAGNÓSTICO DE DUPLICIDADES Y CONTRADICCIONES
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("4.20.5.3. DIAGNÓSTICO DE DUPLICIDADES")
print("=" * 70)

variables_perfil = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

# ------------------------------------------------------------
# 1. Registros por titular
# ------------------------------------------------------------

registros_por_titular = (
    perfiles_excluidos
    .groupby("id_titular")
    .size()
)

print("\n1. DISTRIBUCIÓN DE REGISTROS POR TITULAR")

display(
    registros_por_titular
    .value_counts()
    .sort_index()
    .rename_axis("registros_por_titular")
    .reset_index(name="titulares")
)

# ------------------------------------------------------------
# 2. Valores distintos no nulos por variable
# ------------------------------------------------------------

valores_distintos = (
    perfiles_excluidos
    .groupby("id_titular")[variables_perfil]
    .nunique(dropna=True)
)

# Una contradicción requiere más de un valor no nulo
contradicciones = valores_distintos.gt(1)

diagnostico = pd.DataFrame(
    index=valores_distintos.index
)

diagnostico["variables_contradictorias"] = (
    contradicciones.sum(axis=1)
)

diagnostico["tiene_contradiccion_real"] = (
    diagnostico["variables_contradictorias"] > 0
)

# ------------------------------------------------------------
# 3. Identificar perfiles completos y complementarios
# ------------------------------------------------------------

completitud = (
    perfiles_excluidos
    .groupby("id_titular")[variables_perfil]
    .apply(lambda grupo: grupo.notna().any())
)

diagnostico["variables_recuperables"] = (
    completitud.sum(axis=1)
)

diagnostico["perfil_recuperable_completo"] = (
    diagnostico["variables_recuperables"] == 4
)

# ------------------------------------------------------------
# 4. Clasificación refinada
# ------------------------------------------------------------

condiciones = [
    diagnostico["tiene_contradiccion_real"],

    (
        ~diagnostico["tiene_contradiccion_real"]
        & diagnostico["perfil_recuperable_completo"]
    )
]

opciones = [
    "Contradicción real",
    "Perfil consolidable completo"
]

diagnostico["estado_refinado"] = np.select(
    condiciones,
    opciones,
    default="Perfil consolidable incompleto"
)

# ------------------------------------------------------------
# 5. Resumen por titular
# ------------------------------------------------------------

resumen_refinado = (
    diagnostico["estado_refinado"]
    .value_counts()
    .rename_axis("estado_refinado")
    .reset_index(name="titulares")
)

resumen_refinado["porcentaje"] = (
    resumen_refinado["titulares"]
    / len(diagnostico)
    * 100
).round(2)

print("\n2. CLASIFICACIÓN REFINADA")

display(resumen_refinado)

# ------------------------------------------------------------
# 6. Contradicciones por variable
# ------------------------------------------------------------

resumen_contradicciones = (
    contradicciones.sum()
    .rename("titulares_con_contradiccion")
    .reset_index()
    .rename(columns={"index": "variable"})
)

print("\n3. CONTRADICCIONES POR VARIABLE")

display(resumen_contradicciones)

# ------------------------------------------------------------
# 7. Impacto en turnos
# ------------------------------------------------------------

impacto = (
    diagnostico.reset_index()
    .merge(
        turnos_por_titular,
        on="id_titular",
        how="left",
        validate="one_to_one"
    )
)

resumen_impacto = (
    impacto.groupby("estado_refinado")
    .agg(
        titulares=("id_titular", "nunique"),
        turnos=("turnos_asociados", "sum")
    )
    .reset_index()
)

resumen_impacto["porcentaje_turnos"] = (
    resumen_impacto["turnos"]
    / resumen_impacto["turnos"].sum()
    * 100
).round(2)

print("\n4. IMPACTO SOBRE DIGITURNOS")

display(resumen_impacto)

# ------------------------------------------------------------
# 8. Validaciones
# ------------------------------------------------------------

assert len(diagnostico) == 1294, (
    "El número de titulares no coincide."
)

assert resumen_impacto["turnos"].sum() == 5411, (
    "No se conservaron los turnos."
)

print("\nVALIDACIÓN COMPLETADA")
print("Titulares evaluados:", len(diagnostico))
print("Turnos conciliados:", resumen_impacto["turnos"].sum())
print("Fuentes originales conservadas.")

======================================================================
4.20.5.3. DIAGNÓSTICO DE DUPLICIDADES
======================================================================

1. DISTRIBUCIÓN DE REGISTROS POR TITULAR

   registros_por_titular  titulares
0                      2       1294

2. CLASIFICACIÓN REFINADA

      estado_refinado  titulares  porcentaje
0  Contradicción real       1294       100.0

3. CONTRADICCIONES POR VARIABLE

               variable  titulares_con_contradiccion
0             Categoria                          552
1  Segmento_poblacional                          714
2             Piramide1                         1011
3             Piramide2                         1212

4. IMPACTO SOBRE DIGITURNOS

      estado_refinado  titulares  turnos  porcentaje_turnos
0  Contradicción real       1294    5411              100.0

VALIDACIÓN COMPLETADA
Titulares evaluados: 1294
Turnos conciliados: 5411
Fuentes originales conservadas.

### 4.20.5.4. Caracterización de las contradicciones poblacionales

**Objetivo:** Examinar los valores diferentes asociados a un mismo titular, identificar patrones de contradicción y determinar si existen condiciones para recuperar información poblacional de manera confiable.

**Procedimiento:**
1. Identificar las combinaciones de variables que presentan contradicciones.
2. Examinar ejemplos de los registros originales.
3. Determinar si existen variables consistentes que puedan recuperarse parcialmente.
4. Identificar posibles reglas de resolución que requieran validación de negocio.

**Criterio metodológico:** No se seleccionará arbitrariamente uno de los registros contradictorios. La recuperación deberá sustentarse en reglas verificables y documentadas.

In [62]:
# ============================================================
# 4.20.5.4. CARACTERIZACIÓN DE CONTRADICCIONES
# ============================================================

import pandas as pd

print("=" * 70)
print("4.20.5.4. CARACTERIZACIÓN DE CONTRADICCIONES")
print("=" * 70)

variables_perfil = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

# ------------------------------------------------------------
# 1. Patrón de contradicción por titular
# ------------------------------------------------------------

patrones = contradicciones.copy()

patrones["patron_contradiccion"] = patrones.apply(
    lambda fila: " | ".join(
        columna
        for columna in variables_perfil
        if fila[columna]
    ),
    axis=1
)

resumen_patrones = (
    patrones["patron_contradiccion"]
    .value_counts()
    .reset_index()
)

resumen_patrones.columns = [
    "patron_contradiccion",
    "titulares"
]

resumen_patrones["porcentaje"] = (
    resumen_patrones["titulares"]
    / len(patrones)
    * 100
).round(2)

print("\n1. PATRONES DE CONTRADICCIÓN")

display(resumen_patrones)

# ------------------------------------------------------------
# 2. Variables consistentes por titular
# ------------------------------------------------------------

variables_consistentes = (
    valores_distintos == 1
)

resumen_consistencia = pd.DataFrame({
    "variable": variables_perfil,
    "titulares_sin_contradiccion": [
        int((valores_distintos[c] <= 1).sum())
        for c in variables_perfil
    ],
    "titulares_con_valor_unico_informado": [
        int(variables_consistentes[c].sum())
        for c in variables_perfil
    ],
    "titulares_con_contradiccion": [
        int(contradicciones[c].sum())
        for c in variables_perfil
    ]
})

print("\n2. POSIBILIDAD DE RECUPERACIÓN POR VARIABLE")

display(resumen_consistencia)

# ------------------------------------------------------------
# 3. Ejemplos de contradicciones
# ------------------------------------------------------------

ids_ejemplo = (
    diagnostico.loc[
        diagnostico["tiene_contradiccion_real"]
    ]
    .sort_values(
        "variables_contradictorias",
        ascending=False
    )
    .head(10)
    .index
)

ejemplos = (
    perfiles_excluidos.loc[
        perfiles_excluidos["id_titular"].isin(ids_ejemplo),
        ["id_titular"] + variables_perfil
    ]
    .sort_values("id_titular")
)

print("\n3. EJEMPLOS DE PERFILES CONTRADICTORIOS")

display(ejemplos)

# ------------------------------------------------------------
# 4. Validaciones
# ------------------------------------------------------------

assert resumen_patrones["titulares"].sum() == 1294

print("\nVALIDACIÓN COMPLETADA")
print("Titulares caracterizados:", len(patrones))
print("Fuentes originales conservadas.")

======================================================================
4.20.5.4. CARACTERIZACIÓN DE CONTRADICCIONES
======================================================================

1. PATRONES DE CONTRADICCIÓN

                                 patron_contradiccion  titulares  porcentaje
0                               Piramide1 | Piramide2        311       24.03
1   Categoria | Segmento_poblacional | Piramide1 |...        284       21.95
2        Segmento_poblacional | Piramide1 | Piramide2        266       20.56
3                   Categoria | Piramide1 | Piramide2        150       11.59
4                                           Piramide2         75        5.80
5                    Segmento_poblacional | Piramide2         51        3.94
6        Categoria | Segmento_poblacional | Piramide2         46        3.55
7                                Segmento_poblacional         39        3.01
8                               Categoria | Piramide2         29        2.24
9                    Categoria | Segmento_poblacional         28        2.16
10                                          Categoria         15        1.16

2. POSIBILIDAD DE RECUPERACIÓN POR VARIABLE

,variable,titulares_sin_contradiccion,titulares_con_valor_unico_informado,titulares_con_contradiccion
0,Categoria,742,742,552
1,Segmento_poblacional,580,580,714
2,Piramide1,283,283,1011
3,Piramide2,82,82,1212

3. EJEMPLOS DE PERFILES CONTRADICTORIOS

,id_titular,Categoria,Segmento_poblacional,Piramide1,Piramide2
100255,10102037,B,Joven,2 emp medio,2.1 gold
187935,10102037,A,Basico,1 emp grandes,1.1 platinum
90684,10123234,A,Joven,1 emp grandes,1.1 platinum
154612,10123234,B,Medio,4 micro,4.1 estandar
79687,808225,C,Joven,2 emp medio,2.2 silver
133939,808225,A,Basico,4 micro,4.5 transaccional
122624,808302,B,Medio,3 empresas pymes,3.1 vip
143484,808302,A,Basico,4 micro,4.1 estandar
22100,808569,A,Basico,3 empresas pymes,3.2 vip estandar
267265,808569,C,Medio,2 emp medio,2.2 silver
18276,808581,B,Medio,2 emp medio,2.2 silver
137100,808581,A,Basico,1 emp grandes,1.1 platinum
73320,808785,A,Joven,4 micro,4.5 transaccional
294296,808785,B,Medio,2 emp medio,2.1 gold
66868,809009,A,Basico,4 micro,4.5 transaccional
133355,809009,C,Joven,3 empresas pymes,3.1 vip
5844,809026,A,Basico,3 empresas pymes,3.1 vip
115189,809026,B,Joven,2 emp medio,2.1 gold
250645,934182,A,Basico,4 micro,4.2 trans. mas de 100 trab.
363858,934182,C,Medio,3 empresas pymes,3.1 vip

VALIDACIÓN COMPLETADA
Titulares caracterizados: 1294
Fuentes originales conservadas.

### 4.20.5.5. Recuperación controlada de atributos poblacionales

**Objetivo:** Recuperar información poblacional verificable de los titulares excluidos de la dimensión maestra, mediante reglas de consistencia aplicadas individualmente a cada variable.

**Reglas de recuperación:**

1. Si un titular tiene un único valor no nulo en una variable y no existen registros nulos para esa variable, se recupera dicho valor.
2. Si existen dos o más valores distintos, la variable se conserva sin asignación.
3. Si existen valores nulos mezclados con valores informados, la variable queda pendiente de validación.
4. No se seleccionan registros por orden de aparición ni se infieren valores a partir de otras variables.
5. La recuperación se almacena en una dimensión auxiliar, preservando las fuentes y dimensiones originales.

**Resultado esperado:** Una dimensión de titulares excluidos con atributos recuperados, indicadores de calidad y trazabilidad de las decisiones.

In [63]:
# ============================================================
# 4.20.5.5. RECUPERACIÓN CONTROLADA DE ATRIBUTOS
# ============================================================

import pandas as pd

print("=" * 70)
print("4.20.5.5. RECUPERACIÓN CONTROLADA")
print("=" * 70)

variables_perfil = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

# ------------------------------------------------------------
# 1. Preparación de copia de trabajo
# ------------------------------------------------------------

perfiles_trabajo = perfiles_excluidos[
    ["id_titular"] + variables_perfil
].copy()

for variable in variables_perfil:

    perfiles_trabajo[variable] = (
        perfiles_trabajo[variable]
        .astype("string")
        .str.strip()
        .replace({
            "": pd.NA,
            "nan": pd.NA,
            "None": pd.NA,
            "NULL": pd.NA
        })
    )

# ------------------------------------------------------------
# 2. Construcción de dimensión auxiliar
# ------------------------------------------------------------

dimension_recuperada = (
    perfiles_trabajo[["id_titular"]]
    .drop_duplicates()
    .set_index("id_titular")
)

for variable in variables_perfil:

    agrupado = perfiles_trabajo.groupby(
        "id_titular"
    )[variable]

    valores_unicos = agrupado.nunique(dropna=True)

    registros_nulos = agrupado.apply(
        lambda x: x.isna().sum()
    )

    primer_valor = agrupado.first()

    # Recuperar únicamente valores sin contradicciones
    # y sin registros nulos.
    recuperable = (
        (valores_unicos == 1)
        & (registros_nulos == 0)
    )

    dimension_recuperada[variable] = (
        primer_valor.where(recuperable)
    )

    dimension_recuperada[
        f"estado_{variable}"
    ] = "Contradictorio"

    dimension_recuperada.loc[
        recuperable,
        f"estado_{variable}"
    ] = "Recuperado"

    dimension_recuperada.loc[
        (valores_unicos == 0),
        f"estado_{variable}"
    ] = "Sin información"

    dimension_recuperada.loc[
        (valores_unicos == 1)
        & (registros_nulos > 0),
        f"estado_{variable}"
    ] = "Información incompleta"

dimension_recuperada = (
    dimension_recuperada
    .reset_index()
)

# ------------------------------------------------------------
# 3. Resumen de recuperación
# ------------------------------------------------------------

resumen_recuperacion = []

for variable in variables_perfil:

    conteos = (
        dimension_recuperada[
            f"estado_{variable}"
        ]
        .value_counts()
    )

    resumen_recuperacion.append({
        "variable": variable,
        "recuperados": conteos.get("Recuperado", 0),
        "contradictorios": conteos.get(
            "Contradictorio", 0
        ),
        "incompletos": conteos.get(
            "Información incompleta", 0
        ),
        "sin_informacion": conteos.get(
            "Sin información", 0
        )
    })

resumen_recuperacion = pd.DataFrame(
    resumen_recuperacion
)

resumen_recuperacion[
    "porcentaje_recuperacion"
] = (
    resumen_recuperacion["recuperados"]
    / len(dimension_recuperada)
    * 100
).round(2)

print("\n1. RESUMEN DE RECUPERACIÓN")

display(resumen_recuperacion)

# ------------------------------------------------------------
# 4. Cobertura conjunta
# ------------------------------------------------------------

dimension_recuperada[
    "atributos_recuperados"
] = (
    dimension_recuperada[variables_perfil]
    .notna()
    .sum(axis=1)
)

resumen_atributos = (
    dimension_recuperada[
        "atributos_recuperados"
    ]
    .value_counts()
    .sort_index()
    .rename_axis("atributos_recuperados")
    .reset_index(name="titulares")
)

print("\n2. ATRIBUTOS RECUPERADOS POR TITULAR")

display(resumen_atributos)

# ------------------------------------------------------------
# 5. Validaciones
# ------------------------------------------------------------

assert len(dimension_recuperada) == 1294

assert (
    dimension_recuperada["id_titular"]
    .is_unique
)

assert (
    resumen_recuperacion[
        [
            "recuperados",
            "contradictorios",
            "incompletos",
            "sin_informacion"
        ]
    ].sum(axis=1) == 1294
).all()

print("\nVALIDACIÓN COMPLETADA")
print("Titulares evaluados:", len(dimension_recuperada))
print("Dimensión maestra original conservada.")
print("Fuentes originales conservadas.")

======================================================================
4.20.5.5. RECUPERACIÓN CONTROLADA
======================================================================

1. RESUMEN DE RECUPERACIÓN

,variable,recuperados,contradictorios,incompletos,sin_informacion,porcentaje_recuperacion
0,Categoria,742,552,0,0,57.34
1,Segmento_poblacional,580,714,0,0,44.82
2,Piramide1,283,1011,0,0,21.87
3,Piramide2,82,1212,0,0,6.34

2. ATRIBUTOS RECUPERADOS POR TITULAR

   atributos_recuperados  titulares
0                      0        284
1                      1        462
2                      2        419
3                      3        129

VALIDACIÓN COMPLETADA
Titulares evaluados: 1294
Dimensión maestra original conservada.
Fuentes originales conservadas.

### 4.20.5.6. Evaluación del impacto de la recuperación sobre Digiturnos

**Objetivo:** Cuantificar el número y porcentaje de turnos asociados a titulares excluidos que pueden enriquecerse con atributos poblacionales recuperados mediante reglas de consistencia.

**Metodología:**

1. Vincular los 5.411 turnos auditados con la dimensión auxiliar de titulares recuperados.
2. Identificar la disponibilidad de cada atributo poblacional.
3. Calcular la cantidad de atributos recuperados por turno.
4. Evaluar la cobertura de caracterización individual y conjunta.
5. Verificar la conservación de registros y la ausencia de duplicaciones.

**Criterio de calidad:** La recuperación de atributos no implica modificar la condición de afiliación del usuario ni reemplazar la dimensión maestra.

In [65]:
# ============================================================
# 4.20.5.6. IMPACTO DE RECUPERACIÓN SOBRE DIGITURNOS
# ============================================================

import pandas as pd

print("=" * 70)
print("4.20.5.6. IMPACTO SOBRE DIGITURNOS")
print("=" * 70)

variables = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

# ------------------------------------------------------------
# 1. Seleccionar turnos asociados a titulares excluidos
# ------------------------------------------------------------

def normalizar_id(serie):
    return (
        serie.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .replace({
            "": pd.NA,
            "nan": pd.NA,
            "None": pd.NA
        })
    )

# Copia de trabajo, sin modificar la auditoría original
familiares_trabajo = familiares_auditoria.copy()

# Normalizar identificadores de titulares
familiares_trabajo["id_titular_cruce"] = normalizar_id(
    familiares_trabajo["id_afiliado_titular"]
)

# Identificadores excluidos identificados en 4.20.5.1
ids_excluidos_normalizados = set(
    normalizar_id(
        pd.Series(list(ids_excluidos))
    ).dropna()
)

# Recuperar exclusivamente los turnos correspondientes
turnos_excluidos = familiares_trabajo.loc[
    familiares_trabajo["id_titular_cruce"].isin(
        ids_excluidos_normalizados
    )
].copy()

print("\n1. TURNOS OBJETO DE ANÁLISIS")
print("Turnos identificados:", len(turnos_excluidos))

print(
    "Titulares únicos:",
    turnos_excluidos["id_titular_cruce"].nunique()
)

# Validaciones contra la auditoría anterior
assert len(turnos_excluidos) == 5411, (
    "El número de turnos no coincide con la auditoría 4.20.5.4."
)

assert (
    turnos_excluidos["id_titular_cruce"].nunique() == 1294
), "El número de titulares no coincide con la auditoría."

print("\nVALIDACIÓN COMPLETADA")
print("Se recuperaron los 5.411 turnos esperados.")
print("Se identificaron los 1.294 titulares excluidos.")

# ------------------------------------------------------------
# 2. Preparar dimensión auxiliar
# ------------------------------------------------------------

dim_recuperacion = dimension_recuperada[
    ["id_titular"] + variables
].copy()

assert dim_recuperacion["id_titular"].is_unique

# Normalización homogénea de llaves
def normalizar_id(serie):
    return (
        serie.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    )

turnos_excluidos["id_titular_cruce"] = normalizar_id(
    turnos_excluidos["id_afiliado_titular"]
)

dim_recuperacion["id_titular_cruce"] = normalizar_id(
    dim_recuperacion["id_titular"]
)

dim_recuperacion = dim_recuperacion.drop(
    columns=["id_titular"]
)

assert dim_recuperacion["id_titular_cruce"].is_unique

# ------------------------------------------------------------
# 3. Integración controlada
# ------------------------------------------------------------

turnos_enriquecidos = turnos_excluidos.merge(
    dim_recuperacion,
    on="id_titular_cruce",
    how="left",
    validate="many_to_one",
    indicator="_cruce_recuperacion",
    suffixes=("", "_recuperado")
)

assert len(turnos_enriquecidos) == len(turnos_excluidos)

# ------------------------------------------------------------
# 4. Identificación de atributos recuperados
# ------------------------------------------------------------

columnas_recuperadas = []

for variable in variables:

    columna = (
        f"{variable}_recuperado"
        if f"{variable}_recuperado" in turnos_enriquecidos.columns
        else variable
    )

    columnas_recuperadas.append(columna)

    turnos_enriquecidos[
        f"flag_recuperado_{variable}"
    ] = turnos_enriquecidos[columna].notna()

turnos_enriquecidos["n_atributos_recuperados"] = (
    turnos_enriquecidos[
        [f"flag_recuperado_{v}" for v in variables]
    ]
    .sum(axis=1)
)

# ------------------------------------------------------------
# 5. Resumen por atributo
# ------------------------------------------------------------

resumen_impacto = pd.DataFrame([
    {
        "variable": variable,
        "turnos_recuperados": int(
            turnos_enriquecidos[
                f"flag_recuperado_{variable}"
            ].sum()
        )
    }
    for variable in variables
])

resumen_impacto["porcentaje_turnos"] = (
    resumen_impacto["turnos_recuperados"]
    / len(turnos_enriquecidos)
    * 100
).round(2)

print("\n2. COBERTURA POR ATRIBUTO")

display(resumen_impacto)

# ------------------------------------------------------------
# 6. Distribución conjunta
# ------------------------------------------------------------

resumen_conjunto = (
    turnos_enriquecidos["n_atributos_recuperados"]
    .value_counts()
    .sort_index()
    .rename_axis("atributos_recuperados")
    .reset_index(name="turnos")
)

resumen_conjunto["porcentaje"] = (
    resumen_conjunto["turnos"]
    / len(turnos_enriquecidos)
    * 100
).round(2)

print("\n3. ATRIBUTOS RECUPERADOS POR TURNO")

display(resumen_conjunto)

# ------------------------------------------------------------
# 7. Indicadores generales
# ------------------------------------------------------------

turnos_con_recuperacion = int(
    (turnos_enriquecidos["n_atributos_recuperados"] > 0)
    .sum()
)

turnos_sin_recuperacion = (
    len(turnos_enriquecidos) - turnos_con_recuperacion
)

print("\n4. INDICADORES GENERALES")

print("Total de turnos:", len(turnos_enriquecidos))
print("Con al menos un atributo:", turnos_con_recuperacion)
print("Sin atributos:", turnos_sin_recuperacion)

print(
    "Cobertura parcial:",
    round(
        turnos_con_recuperacion
        / len(turnos_enriquecidos) * 100,
        2
    ),
    "%"
)

# ------------------------------------------------------------
# 8. Validaciones
# ------------------------------------------------------------

assert len(turnos_enriquecidos) == 5411

assert (
    resumen_conjunto["turnos"].sum() == 5411
)

assert (
    turnos_enriquecidos["_cruce_recuperacion"]
    .eq("both")
    .all()
), "Existen titulares sin coincidencia en la dimensión auxiliar."

print("\nVALIDACIÓN COMPLETADA")
print("Se conservaron los 5.411 turnos.")
print("No se modificaron las dimensiones originales.")
print("La clasificación de afiliación permanece intacta.")

======================================================================
4.20.5.6. IMPACTO SOBRE DIGITURNOS
======================================================================

1. TURNOS OBJETO DE ANÁLISIS
Turnos identificados: 5411
Titulares únicos: 1294

VALIDACIÓN COMPLETADA
Se recuperaron los 5.411 turnos esperados.
Se identificaron los 1.294 titulares excluidos.

2. COBERTURA POR ATRIBUTO

               variable  turnos_recuperados  porcentaje_turnos
0             Categoria                3017              55.76
1  Segmento_poblacional                2376              43.91
2             Piramide1                1163              21.49
3             Piramide2                 378               6.99

3. ATRIBUTOS RECUPERADOS POR TURNO

   atributos_recuperados  turnos  porcentaje
0                      0    1163       21.49
1                      1    2023       37.39
2                      2    1764       32.60
3                      3     461        8.52

4. INDICADORES GENERALES
Total de turnos: 5411
Con al menos un atributo: 4248
Sin atributos: 1163
Cobertura parcial: 78.51 %

VALIDACIÓN COMPLETADA
Se conservaron los 5.411 turnos.
No se modificaron las dimensiones originales.
La clasificación de afiliación permanece intacta.


### 4.20.6. Consolidación de la clasificación y enriquecimiento poblacional de Digiturnos

**Objetivo:** Construir una base analítica consolidada de Digiturnos, integrando la clasificación de afiliación y los atributos poblacionales disponibles, incluidos aquellos recuperados mediante reglas de consistencia.

**Criterios de integración:**

1. Conservar los 883.076 turnos y sus variables operativas.
2. Mantener la clasificación original: Afiliado, Grupo familiar y No afiliado.
3. Preservar los atributos de afiliados directos.
4. Incorporar información poblacional de titulares familiares identificados.
5. Recuperar atributos consistentes de titulares excluidos, sin incorporar valores contradictorios.
6. Conservar los atributos sin información como valores nulos.
7. Registrar la procedencia y calidad de cada atributo.
8. Verificar integridad, unicidad del cruce y conservación de registros.

**Principio metodológico:** La recuperación de atributos poblacionales no modifica la condición de afiliación del usuario.

In [66]:

# ============================================================
# 4.20.6. CONSOLIDACIÓN Y ENRIQUECIMIENTO DE DIGITURNOS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("4.20.6. CONSOLIDACIÓN FINAL DE DIGITURNOS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Función de normalización de identificadores
# ------------------------------------------------------------

def normalizar_id_final(serie):
    return (
        serie.astype("string")
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .replace({
            "": pd.NA,
            "nan": pd.NA,
            "None": pd.NA,
            "<NA>": pd.NA
        })
    )

variables_poblacionales = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

# ------------------------------------------------------------
# 2. Base de trabajo
# ------------------------------------------------------------

digiturnos_final = digiturnos_clasificados.copy()

registros_originales = len(digiturnos_final)

assert registros_originales == 883076

print("\n1. BASE ORIGINAL")
print("Turnos:", registros_originales)

print("\nClasificación original:")
print(
    digiturnos_final["tipo_vinculacion"]
    .value_counts(dropna=False)
)

# Identificador técnico para verificar integridad
digiturnos_final["_id_fila_control"] = np.arange(
    registros_originales
)

# ------------------------------------------------------------
# 3. Preparar recuperación poblacional
# ------------------------------------------------------------

recuperacion_auxiliar = dimension_recuperada[
    ["id_titular"] + variables_poblacionales
].copy()

recuperacion_auxiliar["id_titular_cruce"] = (
    normalizar_id_final(
        recuperacion_auxiliar["id_titular"]
    )
)

recuperacion_auxiliar = recuperacion_auxiliar.drop(
    columns=["id_titular"]
)

assert (
    recuperacion_auxiliar["id_titular_cruce"]
    .is_unique
)

# Renombrar atributos para evitar sobrescritura
recuperacion_auxiliar = recuperacion_auxiliar.rename(
    columns={
        v: f"{v}_recuperacion"
        for v in variables_poblacionales
    }
)

# ------------------------------------------------------------
# 4. Preparar identificador de titular familiar
# ------------------------------------------------------------

assert "id_afiliado_titular" in digiturnos_final.columns

digiturnos_final["id_titular_cruce"] = (
    normalizar_id_final(
        digiturnos_final["id_afiliado_titular"]
    )
)

# ------------------------------------------------------------
# 5. Integración controlada
# ------------------------------------------------------------

digiturnos_final = digiturnos_final.merge(
    recuperacion_auxiliar,
    on="id_titular_cruce",
    how="left",
    validate="many_to_one",
    indicator="_cruce_recuperacion_final"
)

assert len(digiturnos_final) == registros_originales

# ------------------------------------------------------------
# 6. Consolidación de atributos poblacionales
# ------------------------------------------------------------

for variable in variables_poblacionales:

    columna_recuperada = f"{variable}_recuperacion"
    columna_origen = f"{variable}_origen"

    # Conservar información existente
    digiturnos_final[columna_origen] = (
        digiturnos_final[variable]
    )

    # Solo enriquecer registros de grupo familiar
    mascara_recuperacion = (
        digiturnos_final["tipo_vinculacion"].eq(
            "Grupo familiar"
        )
        & digiturnos_final[variable].isna()
        & digiturnos_final[
            columna_recuperada
        ].notna()
    )

    # Variable de procedencia
    digiturnos_final[
        f"fuente_{variable}"
    ] = "No disponible"

    digiturnos_final.loc[
        digiturnos_final[variable].notna(),
        f"fuente_{variable}"
    ] = "Dimension original"

    digiturnos_final.loc[
        mascara_recuperacion,
        f"fuente_{variable}"
    ] = "Recuperacion controlada"

    # Completar solo valores ausentes
    digiturnos_final.loc[
        mascara_recuperacion,
        variable
    ] = digiturnos_final.loc[
        mascara_recuperacion,
        columna_recuperada
    ]

# ------------------------------------------------------------
# 7. Indicadores de calidad y cobertura
# ------------------------------------------------------------

digiturnos_final[
    "n_atributos_poblacionales"
] = (
    digiturnos_final[
        variables_poblacionales
    ]
    .notna()
    .sum(axis=1)
)

digiturnos_final[
    "perfil_poblacional_completo"
] = (
    digiturnos_final[
        "n_atributos_poblacionales"
    ] == 4
)

digiturnos_final[
    "perfil_poblacional_parcial"
] = (
    digiturnos_final[
        "n_atributos_poblacionales"
    ].between(1, 3)
)

digiturnos_final[
    "perfil_poblacional_sin_datos"
] = (
    digiturnos_final[
        "n_atributos_poblacionales"
    ] == 0
)

fuentes_recuperacion = [
    f"fuente_{v}"
    for v in variables_poblacionales
]

digiturnos_final[
    "flag_recuperacion_controlada"
] = (
    digiturnos_final[
        fuentes_recuperacion
    ]
    .eq("Recuperacion controlada")
    .any(axis=1)
)

# ------------------------------------------------------------
# 8. Resumen general
# ------------------------------------------------------------

resumen_consolidacion = (
    digiturnos_final
    .groupby("tipo_vinculacion", dropna=False)
    .agg(
        turnos=("_id_fila_control", "size"),
        perfiles_completos=(
            "perfil_poblacional_completo", "sum"
        ),
        perfiles_parciales=(
            "perfil_poblacional_parcial", "sum"
        ),
        perfiles_sin_datos=(
            "perfil_poblacional_sin_datos", "sum"
        ),
        turnos_enriquecidos=(
            "flag_recuperacion_controlada", "sum"
        )
    )
    .reset_index()
)

resumen_consolidacion[
    "porcentaje_con_informacion"
] = (
    (
        resumen_consolidacion["perfiles_completos"]
        + resumen_consolidacion["perfiles_parciales"]
    )
    / resumen_consolidacion["turnos"]
    * 100
).round(2)

print("\n2. RESULTADOS DE CONSOLIDACIÓN")

display(resumen_consolidacion)

# ------------------------------------------------------------
# 9. Cobertura por variable
# ------------------------------------------------------------

resumen_cobertura = []

for variable in variables_poblacionales:

    resumen_cobertura.append({
        "variable": variable,
        "turnos_con_informacion": int(
            digiturnos_final[variable].notna().sum()
        ),
        "turnos_recuperados": int(
            digiturnos_final[
                f"fuente_{variable}"
            ].eq("Recuperacion controlada").sum()
        )
    })

resumen_cobertura = pd.DataFrame(
    resumen_cobertura
)

resumen_cobertura[
    "porcentaje_cobertura"
] = (
    resumen_cobertura["turnos_con_informacion"]
    / registros_originales
    * 100
).round(2)

print("\n3. COBERTURA POBLACIONAL FINAL")

display(resumen_cobertura)

# ------------------------------------------------------------
# 10. Validaciones de integridad
# ------------------------------------------------------------

assert len(digiturnos_final) == 883076

assert (
    digiturnos_final["_id_fila_control"]
    .is_unique
)

assert (
    digiturnos_final["tipo_vinculacion"]
    .value_counts()
    .to_dict()
    ==
    digiturnos_clasificados[
        "tipo_vinculacion"
    ]
    .value_counts()
    .to_dict()
)

assert (
    resumen_consolidacion["turnos"].sum()
    == registros_originales
)

print("\n4. VALIDACIONES")

print("Conservación de registros: OK")
print("Unicidad de filas: OK")
print("Clasificación de afiliación: OK")
print("Dimensiones originales: conservadas")

print("\nCONSOLIDACIÓN COMPLETADA")

======================================================================
4.20.6. CONSOLIDACIÓN FINAL DE DIGITURNOS
======================================================================

1. BASE ORIGINAL
Turnos: 883076

Clasificación original:
tipo_vinculacion
No afiliado       573340
Afiliado          301924
Grupo familiar      7812
Name: count, dtype: int64

2. RESULTADOS DE CONSOLIDACIÓN

,tipo_vinculacion,turnos,perfiles_completos,perfiles_parciales,perfiles_sin_datos,turnos_enriquecidos,porcentaje_con_informacion
0,Afiliado,301924,301924,0,0,0,100.00
1,Grupo familiar,7812,0,4248,3564,4248,54.38
2,No afiliado,573340,0,0,573340,0,0.00

3. COBERTURA POBLACIONAL FINAL

,variable,turnos_con_informacion,turnos_recuperados,porcentaje_cobertura
0,Categoria,304941,3017,34.53
1,Segmento_poblacional,304300,2376,34.46
2,Piramide1,303087,1163,34.32
3,Piramide2,302302,378,34.23

4. VALIDACIONES
Conservación de registros: OK
Unicidad de filas: OK
Clasificación de afiliación: OK
Dimensiones originales: conservadas

CONSOLIDACIÓN COMPLETADA

In [67]:

# ============================================================
# 4.20.6.1. VALIDACIÓN DE VARIABLES OPERATIVAS
# ============================================================

print("=" * 70)
print("4.20.6.1. VALIDACIÓN DE INTEGRIDAD OPERATIVA")
print("=" * 70)

variables_operativas = [
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "flag_tiempo_valido",
    "estado_calidad_tiempo"
]

# Alinear mediante el identificador técnico original
base_original = digiturnos_clasificados.reset_index(
    drop=True
)

base_final = (
    digiturnos_final
    .sort_values("_id_fila_control")
    .reset_index(drop=True)
)

for variable in variables_operativas:

    if (
        variable in base_original.columns
        and variable in base_final.columns
    ):

        iguales = (
            base_original[variable]
            .equals(base_final[variable])
        )

        print(f"{variable}: {'OK' if iguales else 'REVISAR'}")

        assert iguales, (
            f"Se detectaron diferencias en {variable}"
        )

    else:
        print(f"{variable}: columna no disponible")

print("\nVALIDACIÓN OPERATIVA COMPLETADA")

======================================================================
4.20.6.1. VALIDACIÓN DE INTEGRIDAD OPERATIVA
======================================================================
tiempo_espera_min: OK
tiempo_atencion_min: OK
flag_tiempo_valido: OK
estado_calidad_tiempo: OK

VALIDACIÓN OPERATIVA COMPLETADA

## 4.20.7. Auditoría final de calidad e integridad de Digiturnos

### Propósito

Evaluar la integridad, completitud, consistencia y trazabilidad de la base
consolidada de Digiturnos, verificando que las transformaciones realizadas
durante la preparación de datos no alteraron los registros originales,
la clasificación de afiliación ni las variables operativas.

La auditoría distingue entre:

- Errores estructurales que comprometen la integridad de los datos.
- Alertas de calidad que requieren documentación o tratamiento posterior.
- Limitaciones de información que condicionan la interpretación de indicadores.

Los resultados permitirán establecer el nivel de preparación de la base
para el análisis exploratorio y su posterior integración en PostgreSQL.

In [68]:
# ================================================================
# 4.20.7.1. DIAGNÓSTICO INICIAL DE LA BASE CONSOLIDADA
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("4.20.7. AUDITORÍA FINAL DE DIGITURNOS")
print("=" * 70)

# ------------------------------------------------
# 1. IDENTIFICACIÓN DE LA BASE CONSOLIDADA
# ------------------------------------------------

candidatos = [
    "digiturnos_final",
    "digiturnos_consolidados",
    "digiturnos_consolidado",
    "digiturnos_enriquecidos",
    "digiturnos_clasificados",
    "digiturnos_integrados"
]

columnas_requeridas = {
    "tipo_vinculacion",
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "flag_tiempo_valido"
}

bases_validas = []

for nombre in candidatos:

    objeto = globals().get(nombre)

    if isinstance(objeto, pd.DataFrame):

        if columnas_requeridas.issubset(objeto.columns):

            bases_validas.append(
                (nombre, objeto)
            )

if not bases_validas:

    raise ValueError(
        "No se encontró automáticamente una base consolidada "
        "con las columnas requeridas. "
        "Verificar el nombre utilizado en la sección 4.20.6."
    )

# Se prioriza la primera base válida según el orden definido.
nombre_base, base_origen = bases_validas[0]

# Copia exclusiva para auditoría.
digiturnos_auditoria = base_origen.copy()

print("\nBASE IDENTIFICADA")
print("Nombre:", nombre_base)
print("Registros:", f"{len(digiturnos_auditoria):,}")
print("Columnas:", len(digiturnos_auditoria.columns))

# ------------------------------------------------
# 2. VALIDACIÓN DEL NÚMERO DE TURNOS
# ------------------------------------------------

turnos_esperados = 883_076
turnos_observados = len(digiturnos_auditoria)

integridad_registros = (
    turnos_observados == turnos_esperados
)

print("\nINTEGRIDAD DE REGISTROS")

print("Esperados:", f"{turnos_esperados:,}")
print("Observados:", f"{turnos_observados:,}")

print(
    "Resultado:",
    "OK" if integridad_registros else "ALERTA"
)

# ------------------------------------------------
# 3. VALIDACIÓN DE CLASIFICACIÓN
# ------------------------------------------------

clasificacion_esperada = {
    "Afiliado": 301924,
    "Grupo familiar": 7812,
    "No afiliado": 573340
}

clasificacion_observada = (
    digiturnos_auditoria["tipo_vinculacion"]
    .value_counts(dropna=False)
)

print("\nCLASIFICACIÓN DE AFILIACIÓN")

print(clasificacion_observada.to_string())

clasificacion_correcta = (
    clasificacion_observada.to_dict()
    == clasificacion_esperada
)

print(
    "\nResultado:",
    "OK" if clasificacion_correcta else "ALERTA"
)

# ------------------------------------------------
# 4. IDENTIFICACIÓN DE COLUMNAS DISPONIBLES
# ------------------------------------------------

print("\nCOLUMNAS DISPONIBLES")

for columna in digiturnos_auditoria.columns:
    print("-", columna)

# ------------------------------------------------
# 5. VALIDACIONES DE CONTROL
# ------------------------------------------------

assert integridad_registros, (
    "La cantidad de turnos no coincide con la base original."
)

assert clasificacion_correcta, (
    "La clasificación de afiliación presenta diferencias."
)

print("\n" + "=" * 70)
print("DIAGNÓSTICO INICIAL COMPLETADO")
print("Registros y clasificación conservados.")
print("Base original sin modificaciones.")
print("=" * 70)

======================================================================
4.20.7. AUDITORÍA FINAL DE DIGITURNOS
======================================================================

BASE IDENTIFICADA
Nombre: digiturnos_final
Registros: 883,076
Columnas: 56

INTEGRIDAD DE REGISTROS
Esperados: 883,076
Observados: 883,076
Resultado: OK

CLASIFICACIÓN DE AFILIACIÓN
tipo_vinculacion
No afiliado       573340
Afiliado          301924
Grupo familiar      7812

Resultado: OK

COLUMNAS DISPONIBLES
- Sede
- UES
- Clasifiacion
- Usuario_receptor
- Tipo_servicio
- SUBSERVICIO_HOMOLOGADO
- Fecha_Servico
- Hora_solicitud_Servicio
- Hora_llamado__Servicio
- Hora_finalizado_Servicio
- Identificacion_Cliente
- Tipo_Oficina
- id_cliente
- fecha_servicio
- ts_solicitud
- ts_llamado
- ts_finalizacion
- tiempo_espera_min
- tiempo_atencion_min
- tiempo_total_min
- flag_tiempo_valido
- estado_calidad_tiempo
- id_normalizado
- Categoria
- Segmento_poblacional
- Piramide1
- Piramide2
- registros_fuente
- calidad_perfil
- _cruce_afiliados
- tipo_vinculacion
- id_persona_cargo
- n_titulares
- id_afiliado_titular
- estado_relacion
- _cruce_grupo_familiar
- _id_fila_control
- id_titular_cruce
- Categoria_recuperacion
- Segmento_poblacional_recuperacion
- Piramide1_recuperacion
- Piramide2_recuperacion
- _cruce_recuperacion_final
- Categoria_origen
- fuente_Categoria
- Segmento_poblacional_origen
- fuente_Segmento_poblacional
- Piramide1_origen
- fuente_Piramide1
- Piramide2_origen
- fuente_Piramide2
- n_atributos_poblacionales
- perfil_poblacional_completo
- perfil_poblacional_parcial
- perfil_poblacional_sin_datos
- flag_recuperacion_controlada

======================================================================
DIAGNÓSTICO INICIAL COMPLETADO
Registros y clasificación conservados.
Base original sin modificaciones.
======================================================================

In [69]:
# ================================================================
# 4.20.7.2. AUDITORÍA DE COMPLETITUD
# ================================================================

print("=" * 70)
print("AUDITORÍA DE COMPLETITUD")
print("=" * 70)

variables_auditar = [
    "Sede",
    "UES",
    "Clasificacion",
    "Usuario_receptor",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "fecha_servicio",
    "ts_solicitud",
    "ts_llamado",
    "ts_finalizacion",
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "tipo_vinculacion",
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

resultados = []

for variable in variables_auditar:

    if variable not in digiturnos_auditoria.columns:

        resultados.append({
            "variable": variable,
            "estado": "Columna no disponible",
            "registros": len(digiturnos_auditoria),
            "completos": np.nan,
            "faltantes": np.nan,
            "porcentaje_completitud": np.nan
        })

        continue

    serie = digiturnos_auditoria[variable]

    # Se consideran faltantes tanto los nulos como
    # las cadenas vacías o compuestas por espacios.
    faltantes = (
        serie.isna()
        | serie.astype("string").str.strip().eq("").fillna(False)
    )

    n_faltantes = int(faltantes.sum())
    n_completos = len(serie) - n_faltantes

    porcentaje = round(
        100 * n_completos / len(serie),
        2
    )

    resultados.append({
        "variable": variable,
        "estado": "Disponible",
        "registros": len(serie),
        "completos": n_completos,
        "faltantes": n_faltantes,
        "porcentaje_completitud": porcentaje
    })

resumen_completitud = pd.DataFrame(resultados)

display(resumen_completitud)

print("\nVALIDACIÓN COMPLETADA")
print("No se modificaron registros ni valores originales.")

======================================================================
AUDITORÍA DE COMPLETITUD
======================================================================

,variable,estado,registros,completos,faltantes,porcentaje_completitud
0,Sede,Disponible,883076,883076.0,0.0,100.00
1,UES,Disponible,883076,883076.0,0.0,100.00
2,Clasificacion,Columna no disponible,883076,NaN,NaN,NaN
3,Usuario_receptor,Disponible,883076,883076.0,0.0,100.00
4,Tipo_servicio,Disponible,883076,883076.0,0.0,100.00
5,SUBSERVICIO_HOMOLOGADO,Disponible,883076,883076.0,0.0,100.00
6,fecha_servicio,Disponible,883076,883076.0,0.0,100.00
7,ts_solicitud,Disponible,883076,883076.0,0.0,100.00
8,ts_llamado,Disponible,883076,883076.0,0.0,100.00
9,ts_finalizacion,Disponible,883076,883076.0,0.0,100.00
10,tiempo_espera_min,Disponible,883076,883076.0,0.0,100.00
11,tiempo_atencion_min,Disponible,883076,883076.0,0.0,100.00
12,tipo_vinculacion,Disponible,883076,883076.0,0.0,100.00
13,Categoria,Disponible,883076,304941.0,578135.0,34.53
14,Segmento_poblacional,Disponible,883076,304300.0,578776.0,34.46
15,Piramide1,Disponible,883076,303087.0,579989.0,34.32
16,Piramide2,Disponible,883076,302302.0,580774.0,34.23

VALIDACIÓN COMPLETADA
No se modificaron registros ni valores originales.

### 4.20.7.3. Completitud poblacional por tipo de vinculación

Evaluar la disponibilidad de los atributos poblacionales
según el tipo de vinculación del cliente.

Se diferencia entre:
- Afiliados: información obtenida de la dimensión maestra.
- Grupo familiar: información recuperada del afiliado titular.
- No afiliados: población sin correspondencia en las fuentes de afiliación.

La ausencia de atributos no se interpreta automáticamente como
un error de calidad. Se evalúa de acuerdo con las reglas de negocio
y la disponibilidad de las fuentes originales.

In [70]:
# ================================================================
# 4.20.7.3. COMPLETITUD POBLACIONAL POR TIPO DE VINCULACIÓN
# ================================================================

import pandas as pd

print("=" * 70)
print("4.20.7.3. COMPLETITUD POBLACIONAL POR VINCULACIÓN")
print("=" * 70)

variables_poblacionales = [
    "Categoria",
    "Segmento_poblacional",
    "Piramide1",
    "Piramide2"
]

base = digiturnos_auditoria

# ------------------------------------------------
# 1. VALIDACIÓN DE COLUMNAS
# ------------------------------------------------

requeridas = [
    "tipo_vinculacion",
    *variables_poblacionales
]

faltantes = [
    c for c in requeridas
    if c not in base.columns
]

if faltantes:
    raise ValueError(
        f"Columnas no disponibles: {faltantes}"
    )

# ------------------------------------------------
# 2. FUNCIÓN DE COMPLETITUD
# ------------------------------------------------

def valor_informado(serie):

    texto = serie.astype("string").str.strip()

    return (
        serie.notna()
        & texto.ne("")
        & ~texto.str.lower().isin(
            ["nan", "none", "null", "<na>"]
        )
    ).fillna(False)


# ------------------------------------------------
# 3. COMPLETITUD POR VINCULACIÓN
# ------------------------------------------------

resultados = []

for vinculacion, grupo in base.groupby(
    "tipo_vinculacion",
    dropna=False
):

    total = len(grupo)

    for variable in variables_poblacionales:

        informados = int(
            valor_informado(grupo[variable]).sum()
        )

        resultados.append({
            "tipo_vinculacion": vinculacion,
            "variable": variable,
            "turnos": total,
            "con_informacion": informados,
            "sin_informacion": total - informados,
            "porcentaje_completitud": round(
                100 * informados / total, 2
            ) if total else 0
        })

completitud_vinculacion = pd.DataFrame(resultados)

print("\n1. COMPLETITUD POR VARIABLE Y VINCULACIÓN")

display(
    completitud_vinculacion.sort_values(
        ["tipo_vinculacion", "variable"]
    ).reset_index(drop=True)
)

# ------------------------------------------------
# 4. COBERTURA DE ATRIBUTOS POR TURNO
# ------------------------------------------------

matriz_informacion = pd.DataFrame({
    variable: valor_informado(base[variable])
    for variable in variables_poblacionales
}, index=base.index)

cantidad_atributos = matriz_informacion.sum(axis=1)

resumen_atributos = (
    pd.DataFrame({
        "tipo_vinculacion": base["tipo_vinculacion"],
        "atributos_informados": cantidad_atributos
    })
    .groupby(
        ["tipo_vinculacion", "atributos_informados"],
        dropna=False
    )
    .size()
    .reset_index(name="turnos")
)

totales = (
    base["tipo_vinculacion"]
    .value_counts(dropna=False)
)

resumen_atributos["porcentaje"] = (
    resumen_atributos.apply(
        lambda fila: round(
            100 * fila["turnos"]
            / totales.loc[fila["tipo_vinculacion"]],
            2
        ),
        axis=1
    )
)

print("\n2. NÚMERO DE ATRIBUTOS INFORMADOS POR TURNO")

display(resumen_atributos)

# ------------------------------------------------
# 5. CONTROL DE CONSERVACIÓN
# ------------------------------------------------

assert (
    resumen_atributos["turnos"].sum()
    == len(base)
), "La auditoría no conserva todos los turnos."

assert (
    completitud_vinculacion.groupby("variable")[
        "turnos"
    ].sum() == len(base)
).all(), "Existen diferencias en los totales por variable."

print("\nVALIDACIÓN COMPLETADA")
print("Turnos auditados:", f"{len(base):,}")
print("Registros originales conservados.")
print("No se modificaron atributos poblacionales.")

======================================================================
4.20.7.3. COMPLETITUD POBLACIONAL POR VINCULACIÓN
======================================================================

1. COMPLETITUD POR VARIABLE Y VINCULACIÓN

,tipo_vinculacion,variable,turnos,con_informacion,sin_informacion,porcentaje_completitud
0,Afiliado,Categoria,301924,301924,0,100.00
1,Afiliado,Piramide1,301924,301924,0,100.00
2,Afiliado,Piramide2,301924,301924,0,100.00
3,Afiliado,Segmento_poblacional,301924,301924,0,100.00
4,Grupo familiar,Categoria,7812,3017,4795,38.62
5,Grupo familiar,Piramide1,7812,1163,6649,14.89
6,Grupo familiar,Piramide2,7812,378,7434,4.84
7,Grupo familiar,Segmento_poblacional,7812,2376,5436,30.41
8,No afiliado,Categoria,573340,0,573340,0.00
9,No afiliado,Piramide1,573340,0,573340,0.00
10,No afiliado,Piramide2,573340,0,573340,0.00
11,No afiliado,Segmento_poblacional,573340,0,573340,0.00

2. NÚMERO DE ATRIBUTOS INFORMADOS POR TURNO

  tipo_vinculacion  atributos_informados  turnos  porcentaje
0         Afiliado                     4  301924      100.00
1   Grupo familiar                     0    3564       45.62
2   Grupo familiar                     1    2023       25.90
3   Grupo familiar                     2    1764       22.58
4   Grupo familiar                     3     461        5.90
5      No afiliado                     0  573340      100.00

VALIDACIÓN COMPLETADA
Turnos auditados: 883,076
Registros originales conservados.
No se modificaron atributos poblacionales.

### 4.20.7.4. Auditoría de duplicados y unicidad de registros

Evaluar la existencia de duplicados exactos y posibles
repeticiones operativas en la base consolidada de Digiturnos.

La auditoría distingue entre duplicidad de registros y
reiteración legítima de servicios.

No se eliminan registros ni se modifican las fuentes originales.

In [71]:
# ================================================================
# 4.20.7.4. AUDITORÍA DE DUPLICADOS Y UNICIDAD
# ================================================================

import pandas as pd

print("=" * 70)
print("4.20.7.4. AUDITORÍA DE DUPLICADOS Y UNICIDAD")
print("=" * 70)

base = digiturnos_auditoria

print("\n1. INTEGRIDAD GENERAL")
print("Registros:", f"{len(base):,}")
print("Columnas:", len(base.columns))

# ------------------------------------------------
# 1. DUPLICADOS EXACTOS EN COLUMNAS ORIGINALES
# ------------------------------------------------

columnas_originales = [
    "Sede",
    "UES",
    "Usuario_receptor",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "Fecha_Servico",
    "Hora_solicitud_Servicio",
    "Hora_llamado__Servicio",
    "Hora_finalizado_Servicio",
    "Identificacion_Cliente",
    "Tipo_Oficina"
]

disponibles = [
    c for c in columnas_originales
    if c in base.columns
]

faltantes = [
    c for c in columnas_originales
    if c not in base.columns
]

print("\n2. DISPONIBILIDAD DE COLUMNAS ORIGINALES")
print("Disponibles:", disponibles)
print("No disponibles:", faltantes)

if faltantes:
    print(
        "ADVERTENCIA: La comparación utiliza únicamente "
        "las columnas originales disponibles."
    )

if not disponibles:
    raise ValueError(
        "No se encontraron columnas originales para comparar."
    )

duplicados_exactos = base.duplicated(
    subset=disponibles,
    keep=False
)

registros_duplicados = int(duplicados_exactos.sum())

grupos_duplicados = (
    base.loc[duplicados_exactos, disponibles]
    .groupby(disponibles, dropna=False)
    .size()
    .reset_index(name="repeticiones")
)

print("\n3. DUPLICADOS EN COLUMNAS ORIGINALES")
print("Registros involucrados:", registros_duplicados)
print("Grupos repetidos:", len(grupos_duplicados))

if not grupos_duplicados.empty:
    display(
        grupos_duplicados.sort_values(
            "repeticiones",
            ascending=False
        ).head(10)
    )

# ------------------------------------------------
# 2. POSIBLES REPETICIONES OPERATIVAS
# ------------------------------------------------

clave_operativa = [
    "Sede",
    "id_cliente",
    "ts_solicitud"
]

faltantes_clave = [
    c for c in clave_operativa
    if c not in base.columns
]

if faltantes_clave:
    raise ValueError(
        f"Faltan columnas para clave operativa: "
        f"{faltantes_clave}"
    )

# No considerar como coincidencias válidas las
# claves incompletas.

claves_validas = base[clave_operativa].notna().all(axis=1)

repeticiones_operativas = pd.Series(
    False,
    index=base.index
)

repeticiones_operativas.loc[claves_validas] = (
    base.loc[claves_validas]
    .duplicated(
        subset=clave_operativa,
        keep=False
    )
)

print("\n4. POSIBLES REPETICIONES OPERATIVAS")
print(
    "Registros involucrados:",
    int(repeticiones_operativas.sum())
)

# ------------------------------------------------
# 3. DISTRIBUCIÓN POR VINCULACIÓN
# ------------------------------------------------

resumen_duplicados = (
    base.assign(
        duplicado_original=duplicados_exactos,
        repeticion_operativa=repeticiones_operativas
    )
    .groupby("tipo_vinculacion", dropna=False)
    .agg(
        turnos=("tipo_vinculacion", "size"),
        duplicados_originales=(
            "duplicado_original", "sum"
        ),
        repeticiones_operativas=(
            "repeticion_operativa", "sum"
        )
    )
    .reset_index()
)

resumen_duplicados["porcentaje_duplicados"] = (
    100
    * resumen_duplicados["duplicados_originales"]
    / resumen_duplicados["turnos"]
).round(2)

print("\n5. DUPLICADOS POR VINCULACIÓN")
display(resumen_duplicados)

# ------------------------------------------------
# 4. VALIDACIÓN DE CONSERVACIÓN
# ------------------------------------------------

assert len(base) == 883076, (
    "La base no conserva los 883.076 turnos."
)

assert resumen_duplicados["turnos"].sum() == len(base)

print("\nVALIDACIÓN COMPLETADA")
print("Registros conservados:", f"{len(base):,}")
print("No se eliminaron duplicados.")
print("No se modificaron las fuentes originales.")

======================================================================
4.20.7.4. AUDITORÍA DE DUPLICADOS Y UNICIDAD
======================================================================

1. INTEGRIDAD GENERAL
Registros: 883,076
Columnas: 56

2. DISPONIBILIDAD DE COLUMNAS ORIGINALES
Disponibles: ['Sede', 'UES', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina']
No disponibles: []

3. DUPLICADOS EN COLUMNAS ORIGINALES
Registros involucrados: 0
Grupos repetidos: 0

4. POSIBLES REPETICIONES OPERATIVAS
Registros involucrados: 54

5. DUPLICADOS POR VINCULACIÓN

,tipo_vinculacion,turnos,duplicados_originales,repeticiones_operativas,porcentaje_duplicados
0,Afiliado,301924,0,30,0.0
1,Grupo familiar,7812,0,0,0.0
2,No afiliado,573340,0,24,0.0

VALIDACIÓN COMPLETADA
Registros conservados: 883,076
No se eliminaron duplicados.
No se modificaron las fuentes originales.

### 4.20.7.5. Caracterización de coincidencias operativas

Analizar los registros que comparten sede, cliente y momento
de solicitud para distinguir entre solicitudes simultáneas,
servicios diferentes y posibles duplicaciones.

La coincidencia de una clave operativa no constituye,
por sí sola, evidencia de duplicidad.

Se conservan todos los registros originales.

In [72]:
# ================================================================
# 4.20.7.5. CARACTERIZACIÓN DE COINCIDENCIAS OPERATIVAS
# ================================================================

import pandas as pd

print("=" * 70)
print("4.20.7.5. COINCIDENCIAS OPERATIVAS")
print("=" * 70)

base = digiturnos_auditoria

clave = [
    "Sede",
    "id_cliente",
    "ts_solicitud"
]

columnas_analisis = [
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "Usuario_receptor",
    "ts_llamado",
    "ts_finalizacion",
    "tipo_vinculacion"
]

requeridas = clave + columnas_analisis

faltantes = [
    c for c in requeridas
    if c not in base.columns
]

if faltantes:
    raise ValueError(
        f"Columnas faltantes: {faltantes}"
    )

# ------------------------------------------------
# 1. IDENTIFICACIÓN DE COINCIDENCIAS
# ------------------------------------------------

claves_validas = base[clave].notna().all(axis=1)

coincidencias = base.loc[claves_validas].copy()

coincidencias = coincidencias.loc[
    coincidencias.duplicated(
        subset=clave,
        keep=False
    )
].copy()

print("\n1. REGISTROS COINCIDENTES")
print("Registros:", len(coincidencias))

# ------------------------------------------------
# 2. CARACTERIZACIÓN POR GRUPO
# ------------------------------------------------

resumen = (
    coincidencias
    .groupby(clave, dropna=False)
    .agg(
        registros=("tipo_vinculacion", "size"),
        servicios_distintos=(
            "Tipo_servicio", "nunique"
        ),
        subservicios_distintos=(
            "SUBSERVICIO_HOMOLOGADO", "nunique"
        ),
        receptores_distintos=(
            "Usuario_receptor", "nunique"
        ),
        llamados_distintos=(
            "ts_llamado", "nunique"
        ),
        finalizaciones_distintas=(
            "ts_finalizacion", "nunique"
        )
    )
    .reset_index()
)

resumen["diagnostico_preliminar"] = "Revisar coincidencia"

diferente_servicio = (
    (resumen["servicios_distintos"] > 1)
    | (resumen["subservicios_distintos"] > 1)
)

diferente_atencion = (
    (resumen["receptores_distintos"] > 1)
    | (resumen["llamados_distintos"] > 1)
    | (resumen["finalizaciones_distintas"] > 1)
)

resumen.loc[
    diferente_servicio,
    "diagnostico_preliminar"
] = "Servicios diferentes"

resumen.loc[
    ~diferente_servicio & diferente_atencion,
    "diagnostico_preliminar"
] = "Mismo servicio con atención diferente"

print("\n2. RESUMEN DE COINCIDENCIAS")

display(
    resumen[
        [
            "registros",
            "servicios_distintos",
            "subservicios_distintos",
            "receptores_distintos",
            "llamados_distintos",
            "finalizaciones_distintas",
            "diagnostico_preliminar"
        ]
    ].groupby(
        "diagnostico_preliminar",
        dropna=False
    ).agg(
        grupos=("registros", "size"),
        turnos=("registros", "sum")
    ).reset_index()
)

# ------------------------------------------------
# 3. EJEMPLOS PARA REVISIÓN
# ------------------------------------------------

print("\n3. DETALLE DE COINCIDENCIAS")

display(
    coincidencias[
        clave + columnas_analisis
    ].sort_values(clave).head(30)
)

# ------------------------------------------------
# 4. VALIDACIONES
# ------------------------------------------------

assert len(coincidencias) == 54, (
    "El resultado difiere de los 54 registros "
    "identificados en 4.20.7.4."
)

assert resumen["registros"].sum() == len(coincidencias)

assert len(base) == 883076

print("\nVALIDACIÓN COMPLETADA")
print("Registros coincidentes:", len(coincidencias))
print("Grupos de coincidencia:", len(resumen))
print("No se eliminaron registros.")
print("Fuentes originales conservadas.")

======================================================================
4.20.7.5. COINCIDENCIAS OPERATIVAS
======================================================================

1. REGISTROS COINCIDENTES
Registros: 54

2. RESUMEN DE COINCIDENCIAS

                  diagnostico_preliminar  grupos  turnos
0  Mismo servicio con atención diferente       4       8
1                   Servicios diferentes      23      46

3. DETALLE DE COINCIDENCIAS

,Sede,id_cliente,ts_solicitud,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,Usuario_receptor,ts_llamado,ts_finalizacion,tipo_vinculacion
7031,Calle 26,11044212,2024-01-16 11:53:43,Comercial,Informacion credito consumo,52259961,2024-01-16 11:53:43,2024-01-16 11:57:21,No afiliado
7033,Calle 26,11044212,2024-01-16 11:53:43,Comercial,Radicacion solicitudes consumo,52273627,2024-01-16 11:53:43,2024-01-16 11:57:49,No afiliado
238715,Centro mayor,10136,2024-03-04 15:19:52,Servicio,Certificado afiliacion trabajador y/o benefici...,1233695721,2024-03-04 16:49:56,2024-03-04 16:54:28,No afiliado
238838,Centro mayor,10136,2024-03-04 15:19:52,Servicio,Pqr's cuota monetaria,52887154,2024-03-04 15:19:52,2024-03-04 15:20:14,No afiliado
237995,Centro mayor,10136,2024-03-30 12:37:36,Servicio,Entrega tams primera vez,1233695721,2024-03-30 12:37:36,2024-03-30 12:40:50,No afiliado
238349,Centro mayor,10136,2024-03-30 12:37:36,Servicio,Cambio de clave por primera vez,1015995249,2024-03-30 12:37:36,2024-03-30 12:37:55,No afiliado
231011,Centro mayor,10238,2024-01-27 14:29:03,Comercial,Radicacion solicitudes consumo,1233695721,2024-01-27 15:31:22,2024-01-27 15:36:35,Afiliado
231353,Centro mayor,10238,2024-01-27 14:29:03,Comercial,Radicacion solicitudes consumo,1233695721,2024-01-27 14:29:03,2024-01-27 14:31:36,Afiliado
227926,Centro mayor,10244,2024-01-03 10:41:18,Comercial,Informacion y venta de boleteria piscitour,1033791402,2024-01-03 10:41:18,2024-01-03 10:44:53,Afiliado
228069,Centro mayor,10244,2024-01-03 10:41:18,Servicio,Pago reexpedicion tarjeta multiservicios,1033791402,2024-01-03 10:47:56,2024-01-03 10:51:31,Afiliado
290282,Funza,10735,2024-04-05 09:42:35,Servicio,Cambio de clave por primera vez,1073162619,2024-04-05 09:42:35,2024-04-05 09:43:18,No afiliado
292472,Funza,10735,2024-04-05 09:42:35,Servicio,Radicacion certificados escolares,1016030417,2024-04-05 09:44:36,2024-04-05 09:45:46,No afiliado
342894,Fusagasuga,10697,2024-02-16 16:22:48,Comercial,Radicacion solicitudes consumo,82393782,2024-02-16 16:22:48,2024-02-16 16:29:18,Afiliado
351760,Fusagasuga,10697,2024-02-16 16:22:48,Servicio,Radicacion certificados escolares,1069734976,2024-02-16 16:30:37,2024-02-16 16:32:43,Afiliado
344089,Fusagasuga,10697,2024-03-04 11:46:02,Comercial,Informacion credito hipotecario,1069728036,2024-03-04 11:46:02,2024-03-04 11:51:23,Afiliado
349897,Fusagasuga,10697,2024-03-04 11:46:02,Servicio,Validacion afiliacion trabajador y/o beneficia...,82393782,2024-03-04 11:46:26,2024-03-04 11:53:45,Afiliado
343202,Fusagasuga,10697,2024-03-04 15:53:18,Servicio,Entrega tams primera vez,1109844356,2024-03-04 15:53:18,2024-03-04 15:55:44,Afiliado
351926,Fusagasuga,10697,2024-03-04 15:53:18,Servicio,Informacion e inconsistencias bono lonchera,1069734976,2024-03-04 16:09:41,2024-03-04 16:10:53,Afiliado
349957,Fusagasuga,10697,2024-03-20 16:32:31,Servicio,Radicacion certificados escolares,1069734976,2024-03-20 16:32:56,2024-03-20 16:34:58,Afiliado
352503,Fusagasuga,10697,2024-03-20 16:32:31,Comercial,Radicacion solicitudes consumo,1069728036,2024-03-20 16:32:31,2024-03-20 16:35:15,Afiliado
345675,Fusagasuga,10697,2024-04-16 14:30:50,Comercial,Informacion cupo credito,82393782,2024-04-16 14:30:50,2024-04-16 14:32:11,Afiliado
352606,Fusagasuga,10697,2024-04-16 14:30:50,Servicio,Rad afiliacion trabajadores hasta 10 formularios,1069734976,2024-04-16 14:33:29,2024-04-16 14:40:23,Afiliado
352307,Fusagasuga,10697,2024-06-07 16:44:24,Servicio,Entrega tams primera vez,1069734976,2024-06-07 16:56:10,2024-06-07 16:59:25,Afiliado
353611,Fusagasuga,10697,2024-06-07 16:44:24,Comercial,Informacion cupo credito,1109844356,2024-06-07 16:45:45,2024-06-07 16:56:28,Afiliado
343844,Fusagasuga,10697,2024-08-13 11:44:52,Servicio,Entrega tams primera vez,82393782,2024-08-13 11:44:52,2024-08-13 11:56:09,Afiliado
353803,Fusagasuga,10697,2024-08-13 11:44:52,Comercial,Radicacion cupo credito,1069728036,2024-08-13 11:44:52,2024-08-13 11:57:51,Afiliado
391537,Girardot,10706,2024-04-29 16:23:02,Comercial,Informacion credito hipotecario,1070625194,2024-04-29 16:28:51,2024-04-29 16:29:03,No afiliado
394731,Girardot,10706,2024-04-29 16:23:02,Servicio,Rad postulacion mejoramiento y cons. sitio propio,1070584928,2024-04-29 16:23:02,2024-04-29 16:25:00,No afiliado
461024,Santa librada,10229,2024-03-26 08:13:27,Servicio,Radicacion certificados escolares,1022959440,2024-03-26 08:18:06,2024-03-26 08:19:42,No afiliado
461192,Santa librada,10229,2024-03-26 08:13:27,Comercial,Radicacion solicitudes consumo,53031630,2024-03-26 08:13:27,2024-03-26 08:22:03,No afiliado

VALIDACIÓN COMPLETADA
Registros coincidentes: 54
Grupos de coincidencia: 27
No se eliminaron registros.
Fuentes originales conservadas.

### 4.20.7.6. Auditoría de consistencia temporal

Evaluar la coherencia cronológica de los eventos registrados
en Digiturnos y la confiabilidad de las duraciones calculadas.

Se verifican:
- Completitud de las marcas temporales.
- Secuencia solicitud → llamado → finalización.
- Tiempos de espera y atención negativos.
- Duraciones extremas que requieren revisión.
- Consistencia entre duraciones almacenadas y recalculadas.

Los registros se conservan sin modificaciones. Los umbrales
de duración extrema se utilizan como alertas exploratorias,
no como criterios automáticos de exclusión.

In [73]:
# ================================================================
# 4.20.7.6. AUDITORÍA DE CONSISTENCIA TEMPORAL
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("4.20.7.6. AUDITORÍA DE CONSISTENCIA TEMPORAL")
print("=" * 70)

base = digiturnos_auditoria

columnas = [
    "ts_solicitud",
    "ts_llamado",
    "ts_finalizacion",
    "tiempo_espera_min",
    "tiempo_atencion_min"
]

faltantes = [c for c in columnas if c not in base.columns]

if faltantes:
    raise ValueError(f"Columnas faltantes: {faltantes}")

# Copia exclusiva para auditoría
auditoria_temporal = base[columnas].copy()

# ------------------------------------------------
# 1. NORMALIZACIÓN TEMPORAL PARA AUDITORÍA
# ------------------------------------------------

for columna in [
    "ts_solicitud",
    "ts_llamado",
    "ts_finalizacion"
]:
    auditoria_temporal[columna] = pd.to_datetime(
        auditoria_temporal[columna],
        errors="coerce"
    )

for columna in [
    "tiempo_espera_min",
    "tiempo_atencion_min"
]:
    auditoria_temporal[columna] = pd.to_numeric(
        auditoria_temporal[columna],
        errors="coerce"
    )

total = len(auditoria_temporal)

# ------------------------------------------------
# 2. COMPLETITUD
# ------------------------------------------------

resumen_completitud = pd.DataFrame([
    {
        "variable": c,
        "registros": total,
        "faltantes": int(
            auditoria_temporal[c].isna().sum()
        ),
        "porcentaje_completitud": round(
            100 * auditoria_temporal[c].notna().mean(),
            2
        )
    }
    for c in columnas
])

print("\n1. COMPLETITUD TEMPORAL")
display(resumen_completitud)

# ------------------------------------------------
# 3. SECUENCIA CRONOLÓGICA
# ------------------------------------------------

solicitud = auditoria_temporal["ts_solicitud"]
llamado = auditoria_temporal["ts_llamado"]
finalizacion = auditoria_temporal["ts_finalizacion"]

secuencia_completa = (
    solicitud.notna()
    & llamado.notna()
    & finalizacion.notna()
)

llamado_antes_solicitud = (
    secuencia_completa
    & (llamado < solicitud)
)

finalizacion_antes_llamado = (
    secuencia_completa
    & (finalizacion < llamado)
)

secuencia_invalida = (
    llamado_antes_solicitud
    | finalizacion_antes_llamado
)

resumen_secuencia = pd.DataFrame([
    {
        "control": "Secuencia completa",
        "turnos": int(secuencia_completa.sum())
    },
    {
        "control": "Llamado anterior a solicitud",
        "turnos": int(llamado_antes_solicitud.sum())
    },
    {
        "control": "Finalización anterior a llamado",
        "turnos": int(finalizacion_antes_llamado.sum())
    },
    {
        "control": "Turnos con secuencia inválida",
        "turnos": int(secuencia_invalida.sum())
    },
    {
        "control": "Turnos sin secuencia completa",
        "turnos": int((~secuencia_completa).sum())
    }
])

print("\n2. CONSISTENCIA CRONOLÓGICA")
display(resumen_secuencia)

# ------------------------------------------------
# 4. RECÁLCULO DE DURACIONES
# ------------------------------------------------

espera_calculada = (
    (llamado - solicitud).dt.total_seconds() / 60
)

atencion_calculada = (
    (finalizacion - llamado).dt.total_seconds() / 60
)

auditoria_temporal["espera_calculada"] = espera_calculada
auditoria_temporal["atencion_calculada"] = atencion_calculada

# Umbrales exploratorios, no reglas de exclusión
UMBRAL_ESPERA = 180
UMBRAL_ATENCION = 240

resumen_duraciones = pd.DataFrame([
    {
        "indicador": "Espera negativa",
        "turnos": int((espera_calculada < 0).sum())
    },
    {
        "indicador": "Atención negativa",
        "turnos": int((atencion_calculada < 0).sum())
    },
    {
        "indicador": "Espera mayor a 180 minutos",
        "turnos": int(
            (espera_calculada > UMBRAL_ESPERA).sum()
        )
    },
    {
        "indicador": "Atención mayor a 240 minutos",
        "turnos": int(
            (atencion_calculada > UMBRAL_ATENCION).sum()
        )
    },
    {
        "indicador": "Espera igual a cero",
        "turnos": int((espera_calculada == 0).sum())
    },
    {
        "indicador": "Atención igual a cero",
        "turnos": int((atencion_calculada == 0).sum())
    }
])

print("\n3. ALERTAS DE DURACIÓN")
display(resumen_duraciones)

# ------------------------------------------------
# 5. CONSISTENCIA DE DURACIONES ALMACENADAS
# ------------------------------------------------

TOLERANCIA_MIN = 0.02

comparaciones = []

for almacenada, calculada, nombre in [
    (
        "tiempo_espera_min",
        "espera_calculada",
        "Espera"
    ),
    (
        "tiempo_atencion_min",
        "atencion_calculada",
        "Atención"
    )
]:
    diferencia = (
        auditoria_temporal[almacenada]
        - auditoria_temporal[calculada]
    ).abs()

    comparables = diferencia.notna()

    discrepancias = (
        comparables
        & (diferencia > TOLERANCIA_MIN)
    )

    comparaciones.append({
        "indicador": nombre,
        "registros_comparables": int(
            comparables.sum()
        ),
        "discrepancias": int(
            discrepancias.sum()
        ),
        "diferencia_maxima_min": (
            round(float(diferencia.max()), 4)
            if comparables.any()
            else np.nan
        )
    })

print("\n4. CONSISTENCIA DE CÁLCULOS")
display(pd.DataFrame(comparaciones))

# ------------------------------------------------
# 6. ESTADÍSTICOS DESCRIPTIVOS
# ------------------------------------------------

print("\n5. DISTRIBUCIÓN DE DURACIONES")

display(
    auditoria_temporal[
        ["espera_calculada", "atencion_calculada"]
    ].describe(
        percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
    ).round(2)
)

# ------------------------------------------------
# 7. CONSERVACIÓN
# ------------------------------------------------

assert len(auditoria_temporal) == len(base)
assert len(base) == 883076

print("\nVALIDACIÓN COMPLETADA")
print("Turnos auditados:", f"{total:,}")
print("No se modificaron los registros originales.")
print("No se aplicaron exclusiones automáticas.")

======================================================================
4.20.7.6. AUDITORÍA DE CONSISTENCIA TEMPORAL
======================================================================

1. COMPLETITUD TEMPORAL

              variable  registros  faltantes  porcentaje_completitud
0         ts_solicitud     883076          0                   100.0
1           ts_llamado     883076          0                   100.0
2      ts_finalizacion     883076          0                   100.0
3    tiempo_espera_min     883076          0                   100.0
4  tiempo_atencion_min     883076          0                   100.0

2. CONSISTENCIA CRONOLÓGICA

                           control  turnos
0               Secuencia completa  883076
1     Llamado anterior a solicitud       0
2  Finalización anterior a llamado       0
3    Turnos con secuencia inválida       0
4    Turnos sin secuencia completa       0

3. ALERTAS DE DURACIÓN

                      indicador  turnos
0               Espera negativa       0
1             Atención negativa       0
2    Espera mayor a 180 minutos       2
3  Atención mayor a 240 minutos       0
4           Espera igual a cero  347996
5         Atención igual a cero       0

4. CONSISTENCIA DE CÁLCULOS

  indicador  registros_comparables  discrepancias  diferencia_maxima_min
0    Espera                 883076              0                    0.0
1  Atención                 883076              0                    0.0

5. DISTRIBUCIÓN DE DURACIONES

       espera_calculada  atencion_calculada
count         883076.00           883076.00
mean               6.04                5.15
std               10.14                4.31
min                0.00                0.02
50%                0.78                4.15
75%                8.45                6.77
90%               18.92               10.13
95%               26.98               12.90
99%               45.82               20.52
max              200.62              171.25

VALIDACIÓN COMPLETADA
Turnos auditados: 883,076
No se modificaron los registros originales.
No se aplicaron exclusiones automáticas.


### 4.20.7.7. Caracterización de turnos con tiempo de espera igual a cero

**Propósito:** caracterizar los turnos cuyo tiempo transcurrido entre la solicitud y el llamado es igual a cero, identificando su concentración por sede, servicio, subservicio, usuario receptor y tipo de vinculación.

**Antecedente:** la auditoría temporal identificó 347.996 turnos con espera igual a cero, equivalentes al 39,41 % de los 883.076 registros.

**Procedimiento:**
1. Cuantificar los turnos con espera cero y espera positiva.
2. Examinar su distribución por variables operativas.
3. Comparar los tiempos de atención entre ambos grupos.
4. Evaluar la coincidencia exacta entre las marcas temporales de solicitud y llamado.
5. Identificar concentraciones que requieran validación funcional.

**Regla de negocio:** un tiempo de espera igual a cero no constituye automáticamente un error. Los registros se conservan y se identifican mediante una variable analítica derivada, sin modificar la base original.

**Resultado esperado:** diagnóstico reproducible que permita decidir cómo interpretar las esperas cero en los indicadores de desempeño.

In [74]:

# ============================================================
# 4.20.7.7. CARACTERIZACIÓN DE TURNOS CON ESPERA IGUAL A CERO
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 70)
print("4.20.7.7. CARACTERIZACIÓN DE ESPERAS IGUALES A CERO")
print("=" * 70)

# ------------------------------------------------------------
# 1. BASE DE TRABAJO Y VALIDACIONES
# ------------------------------------------------------------

assert "digiturnos_final" in globals(), (
    "No está disponible digiturnos_final."
)

base = digiturnos_final.copy()

columnas_requeridas = [
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "ts_solicitud",
    "ts_llamado",
    "Sede",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "Usuario_receptor",
    "tipo_vinculacion"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in base.columns
]

assert not faltantes, (
    f"Columnas requeridas no disponibles: {faltantes}"
)

n_original = len(base)

assert n_original == 883076, (
    f"Cantidad inesperada de turnos: {n_original}"
)

base["espera_auditada"] = pd.to_numeric(
    base["tiempo_espera_min"],
    errors="coerce"
)

base["atencion_auditada"] = pd.to_numeric(
    base["tiempo_atencion_min"],
    errors="coerce"
)

# Clasificación analítica sin modificar la base maestra.
base["grupo_espera"] = np.select(
    [
        base["espera_auditada"].eq(0),
        base["espera_auditada"].gt(0),
        base["espera_auditada"].lt(0)
    ],
    [
        "Espera cero",
        "Espera positiva",
        "Espera negativa"
    ],
    default="Sin información"
)

# ------------------------------------------------------------
# 2. DISTRIBUCIÓN GENERAL
# ------------------------------------------------------------

resumen_general = (
    base.groupby("grupo_espera", dropna=False)
    .size()
    .reset_index(name="turnos")
)

resumen_general["porcentaje"] = (
    resumen_general["turnos"] / n_original * 100
).round(2)

print("\n1. DISTRIBUCIÓN GENERAL")
display(resumen_general)

n_cero = int(
    base["grupo_espera"].eq("Espera cero").sum()
)

n_positiva = int(
    base["grupo_espera"].eq("Espera positiva").sum()
)

assert resumen_general["turnos"].sum() == n_original

assert n_cero == 347996, (
    f"Esperas cero diferentes a auditoría previa: {n_cero}"
)

print(f"Turnos totales: {n_original:,}")
print(f"Espera cero: {n_cero:,}")
print(f"Espera positiva: {n_positiva:,}")

# ------------------------------------------------------------
# 3. FUNCIÓN DE CARACTERIZACIÓN OPERATIVA
# ------------------------------------------------------------

def caracterizar_espera_cero(df, variable, top_n=15):

    tabla = (
        df.groupby(variable, dropna=False)
        .agg(
            turnos=("grupo_espera", "size"),
            espera_cero=(
                "grupo_espera",
                lambda s: s.eq("Espera cero").sum()
            ),
            espera_positiva=(
                "grupo_espera",
                lambda s: s.eq("Espera positiva").sum()
            )
        )
        .reset_index()
    )

    tabla["porcentaje_espera_cero"] = (
        tabla["espera_cero"]
        / tabla["turnos"] * 100
    ).round(2)

    tabla["participacion_en_esperas_cero"] = (
        tabla["espera_cero"]
        / n_cero * 100
    ).round(2)

    tabla = tabla.sort_values(
        ["espera_cero", "turnos"],
        ascending=False
    )

    return tabla.head(top_n)


variables_analisis = [
    "Sede",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "Usuario_receptor",
    "tipo_vinculacion"
]

resultados_concentracion = {}

for variable in variables_analisis:

    print("\n" + "-" * 70)
    print(f"2. CONCENTRACIÓN POR {variable.upper()}")
    print("-" * 70)

    tabla = caracterizar_espera_cero(
        base,
        variable,
        top_n=15
    )

    resultados_concentracion[variable] = tabla

    display(tabla)

# ------------------------------------------------------------
# 4. COMPARACIÓN DE TIEMPOS DE ATENCIÓN
# ------------------------------------------------------------

comparacion_atencion = (
    base.groupby("grupo_espera", dropna=False)
    .agg(
        turnos=("atencion_auditada", "size"),
        atencion_promedio_min=(
            "atencion_auditada", "mean"
        ),
        atencion_mediana_min=(
            "atencion_auditada", "median"
        ),
        atencion_p90_min=(
            "atencion_auditada",
            lambda s: s.quantile(0.90)
        ),
        atencion_p95_min=(
            "atencion_auditada",
            lambda s: s.quantile(0.95)
        )
    )
    .reset_index()
)

columnas_numericas = comparacion_atencion.select_dtypes(
    include="number"
).columns.difference(["turnos"])

comparacion_atencion[columnas_numericas] = (
    comparacion_atencion[columnas_numericas].round(2)
)

print("\n3. COMPARACIÓN DE TIEMPOS DE ATENCIÓN")
display(comparacion_atencion)

# ------------------------------------------------------------
# 5. VERIFICACIÓN DE MARCAS TEMPORALES
# ------------------------------------------------------------

solicitud = pd.to_datetime(
    base["ts_solicitud"],
    errors="coerce"
)

llamado = pd.to_datetime(
    base["ts_llamado"],
    errors="coerce"
)

base["coincidencia_exacta"] = (
    solicitud.notna()
    & llamado.notna()
    & solicitud.eq(llamado)
)

base["diferencia_segundos"] = (
    llamado - solicitud
).dt.total_seconds()

cero = base.loc[
    base["grupo_espera"].eq("Espera cero")
]

resumen_temporal = pd.DataFrame({
    "indicador": [
        "Turnos con espera cero",
        "Solicitud y llamado exactamente iguales",
        "Espera cero sin coincidencia exacta",
        "Espera cero con marcas temporales faltantes"
    ],
    "turnos": [
        len(cero),
        int(cero["coincidencia_exacta"].sum()),
        int(
            (
                ~cero["coincidencia_exacta"]
                & solicitud.loc[cero.index].notna()
                & llamado.loc[cero.index].notna()
            ).sum()
        ),
        int(
            (
                solicitud.loc[cero.index].isna()
                | llamado.loc[cero.index].isna()
            ).sum()
        )
    ]
})

print("\n4. VERIFICACIÓN DE MARCAS TEMPORALES")
display(resumen_temporal)

# ------------------------------------------------------------
# 6. ESPERAS CERO POR HORA DE SOLICITUD
# ------------------------------------------------------------

base["hora_solicitud_auditada"] = solicitud.dt.hour

concentracion_horaria = caracterizar_espera_cero(
    base,
    "hora_solicitud_auditada",
    top_n=24
).sort_values("hora_solicitud_auditada")

print("\n5. DISTRIBUCIÓN POR HORA DE SOLICITUD")
display(concentracion_horaria)

# ------------------------------------------------------------
# 7. CONTROLES DE INTEGRIDAD
# ------------------------------------------------------------

assert len(base) == len(digiturnos_final), (
    "Se alteró la cantidad de registros."
)

assert (
    base["grupo_espera"].value_counts().sum()
    == n_original
)

print("\n" + "=" * 70)
print("VALIDACIÓN COMPLETADA")
print(f"Registros auditados: {n_original:,}")
print(f"Esperas iguales a cero: {n_cero:,}")
print("No se eliminaron registros.")
print("No se modificó digiturnos_final.")
print("Clasificación analítica generada en copia.")
print("=" * 70)

======================================================================
4.20.7.7. CARACTERIZACIÓN DE ESPERAS IGUALES A CERO
======================================================================

1. DISTRIBUCIÓN GENERAL

      grupo_espera  turnos  porcentaje
0      Espera cero  347996       39.41
1  Espera positiva  535080       60.59

Turnos totales: 883,076
Espera cero: 347,996
Espera positiva: 535,080

----------------------------------------------------------------------
2. CONCENTRACIÓN POR SEDE
----------------------------------------------------------------------

,Sede,turnos,espera_cero,espera_positiva,porcentaje_espera_cero,participacion_en_esperas_cero
0,Calle 26,157060,69347,87713,44.15,19.93
10,Tintal plaza,112312,63937,48375,56.93,18.37
2,Centro mayor,79106,36334,42772,45.93,10.44
8,Soacha,93104,28938,64166,31.08,8.32
9,Suba,81721,25707,56014,31.46,7.39
12,Usaquen,55305,24184,31121,43.73,6.95
11,Unicentro de occidente,56338,22080,34258,39.19,6.34
3,Funza,53763,17794,35969,33.10,5.11
5,Girardot,47419,15319,32100,32.31,4.40
1,Calle 63,47613,14193,33420,29.81,4.08
7,Santa librada,40790,13868,26922,34.00,3.99
4,Fusagasuga,45219,11885,33334,26.28,3.42
6,La mesa,13326,4410,8916,33.09,1.27

----------------------------------------------------------------------
2. CONCENTRACIÓN POR TIPO_SERVICIO
----------------------------------------------------------------------

,Tipo_servicio,turnos,espera_cero,espera_positiva,porcentaje_espera_cero,participacion_en_esperas_cero
1,Servicio,636911,186744,450167,29.32,53.66
0,Comercial,246165,161252,84913,65.51,46.34

----------------------------------------------------------------------
2. CONCENTRACIÓN POR SUBSERVICIO_HOMOLOGADO
----------------------------------------------------------------------

,SUBSERVICIO_HOMOLOGADO,turnos,espera_cero,espera_positiva,porcentaje_espera_cero,participacion_en_esperas_cero
25,Entrega tams primera vez,86012,36730,49282,42.70,10.55
111,Radicacion cupo credito,32996,31159,1837,94.43,8.95
121,Radicacion solicitudes consumo,29191,27269,1922,93.42,7.84
39,Informacion cupo credito,28787,18752,10035,65.14,5.39
138,Validacion afiliacion trabajador y/o beneficia...,42037,17903,24134,42.59,5.14
37,Informacion credito consumo,30459,10926,19533,35.87,3.14
44,Informacion general subsidio de vivienda,30561,10204,20357,33.39,2.93
52,Informacion subsidios de arrendamiento,16994,9871,7123,58.09,2.84
118,Radicacion reserva,11391,9199,2192,80.76,2.64
94,Pqr's cuota monetaria,20581,8944,11637,43.46,2.57
55,Informacion y venta de boleteria piscitour,20249,8828,11421,43.60,2.54
117,Radicacion reactivaciones cupo,8571,8049,522,93.91,2.31
92,Pqr's administracion de afiliados,19834,7999,11835,40.33,2.30
45,Informacion hoteleria y turismo,17482,7417,10065,42.43,2.13
101,Rad afiliacion trabajadores hasta 10 formularios,94137,6424,87713,6.82,1.85

----------------------------------------------------------------------
2. CONCENTRACIÓN POR USUARIO_RECEPTOR
----------------------------------------------------------------------

,Usuario_receptor,turnos,espera_cero,espera_positiva,porcentaje_espera_cero,participacion_en_esperas_cero
4,1010208374,20396,15532,4864,76.15,4.46
68,1077865422,18720,12404,6316,66.26,3.56
102,52988267,16445,11884,4561,72.27,3.41
38,1024506461,15674,11186,4488,71.37,3.21
57,1033797428,14310,8857,5453,61.89,2.55
47,1030591341,12193,8510,3683,69.79,2.45
99,52952196,13498,7823,5675,57.96,2.25
3,1010170232,12549,7800,4749,62.16,2.24
41,1024546447,16591,7519,9072,45.32,2.16
90,52506017,10498,7041,3457,67.07,2.02
118,91518611,13925,6927,6998,49.75,1.99
53,1033714051,10727,6908,3819,64.40,1.99
49,1031144097,10926,6888,4038,63.04,1.98
79,39721542,9559,6239,3320,65.27,1.79
66,1073162619,12194,6193,6001,50.79,1.78

----------------------------------------------------------------------
2. CONCENTRACIÓN POR TIPO_VINCULACION
----------------------------------------------------------------------

,tipo_vinculacion,turnos,espera_cero,espera_positiva,porcentaje_espera_cero,participacion_en_esperas_cero
2,No afiliado,573340,226418,346922,39.49,65.06
0,Afiliado,301924,118156,183768,39.13,33.95
1,Grupo familiar,7812,3422,4390,43.80,0.98

3. COMPARACIÓN DE TIEMPOS DE ATENCIÓN

,grupo_espera,turnos,atencion_promedio_min,atencion_mediana_min,atencion_p90_min,atencion_p95_min
0,Espera cero,347996,4.51,3.70,9.12,11.45
1,Espera positiva,535080,5.56,4.45,10.80,13.78

4. VERIFICACIÓN DE MARCAS TEMPORALES

                                     indicador  turnos
0                       Turnos con espera cero  347996
1      Solicitud y llamado exactamente iguales  347996
2          Espera cero sin coincidencia exacta       0
3  Espera cero con marcas temporales faltantes       0

5. DISTRIBUCIÓN POR HORA DE SOLICITUD

,hora_solicitud_auditada,turnos,espera_cero,espera_positiva,porcentaje_espera_cero,participacion_en_esperas_cero
0,6,2,0,2,0.00,0.00
1,7,11153,3637,7516,32.61,1.05
2,8,42362,12854,29508,30.34,3.69
3,9,78527,27439,51088,34.94,7.88
4,10,101736,39090,62646,38.42,11.23
5,11,106321,42485,63836,39.96,12.21
6,12,92914,36752,56162,39.55,10.56
7,13,83732,34172,49560,40.81,9.82
8,14,86287,32705,53582,37.90,9.40
9,15,101588,40294,61294,39.66,11.58
10,16,93411,39024,54387,41.78,11.21
11,17,56995,25135,31860,44.10,7.22
12,18,25842,12562,13280,48.61,3.61
13,19,2204,1845,359,83.71,0.53
14,20,2,2,0,100.00,0.00

======================================================================
VALIDACIÓN COMPLETADA
Registros auditados: 883,076
Esperas iguales a cero: 347,996
No se eliminaron registros.
No se modificó digiturnos_final.
Clasificación analítica generada en copia.
======================================================================

### 4.20.7.8. Auditoría cruzada de esperas cero por sede, tipo de servicio y subservicio

**Propósito:** determinar si la concentración de turnos con espera cero está asociada a la composición de servicios de cada sede o a diferencias que persisten al comparar servicios equivalentes.

**Criterios metodológicos:**
- No modificar la base original ni la clasificación de afiliación.
- Mantener los turnos con espera cero.
- Calcular porcentajes utilizando como denominador los turnos de cada grupo.
- Evitar comparaciones entre grupos con volúmenes insuficientes.
- Tratar las alertas como señales de revisión, no como errores confirmados.

In [75]:
import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 70)
print("4.20.7.8. AUDITORÍA CRUZADA DE ESPERAS CERO")
print("=" * 70)

# ------------------------------------------------------------
# 1. Base de trabajo independiente
# ------------------------------------------------------------

assert "digiturnos_final" in globals(), (
    "No se encuentra digiturnos_final. "
    "Ejecuta las secciones anteriores."
)

base_478 = digiturnos_final.copy(deep=True)

N_ORIGINAL = len(digiturnos_final)

columnas_requeridas = [
    "Sede",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "tiempo_espera_min"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in base_478.columns
]

assert not faltantes, (
    f"Columnas faltantes: {faltantes}"
)

# ------------------------------------------------------------
# 2. Clasificación analítica
# ------------------------------------------------------------

espera = pd.to_numeric(
    base_478["tiempo_espera_min"],
    errors="coerce"
)

assert espera.notna().all(), (
    "Existen tiempos de espera no numéricos o faltantes."
)

assert espera.ge(0).all(), (
    "Existen tiempos de espera negativos."
)

base_478["espera_cero_auditada"] = espera.eq(0)

# Normalizar únicamente las etiquetas de la copia analítica
for columna in [
    "Sede",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO"
]:
    base_478[columna] = (
        base_478[columna]
        .astype("string")
        .str.strip()
        .fillna("Sin información")
    )

# ------------------------------------------------------------
# 3. Función de resumen
# ------------------------------------------------------------

def resumen_esperas(df, dimensiones):

    resultado = (
        df.groupby(dimensiones, dropna=False)
        .agg(
            turnos=("espera_cero_auditada", "size"),
            espera_cero=("espera_cero_auditada", "sum")
        )
        .reset_index()
    )

    resultado["espera_positiva"] = (
        resultado["turnos"] - resultado["espera_cero"]
    )

    resultado["porcentaje_espera_cero"] = (
        100 * resultado["espera_cero"]
        / resultado["turnos"]
    ).round(2)

    return resultado

# ------------------------------------------------------------
# 4. Sede x tipo de servicio
# ------------------------------------------------------------

cruce_sede_tipo = resumen_esperas(
    base_478,
    ["Sede", "Tipo_servicio"]
)

cruce_sede_tipo = cruce_sede_tipo.sort_values(
    ["Sede", "Tipo_servicio"]
).reset_index(drop=True)

print("\n1. CRUCE SEDE X TIPO DE SERVICIO")
display(cruce_sede_tipo)

print("\nVALIDACIÓN")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Turnos en cruce:",
    f"{cruce_sede_tipo['turnos'].sum():,}"
)

assert cruce_sede_tipo["turnos"].sum() == N_ORIGINAL

print("Integridad: OK")

======================================================================
4.20.7.8. AUDITORÍA CRUZADA DE ESPERAS CERO
======================================================================

1. CRUCE SEDE X TIPO DE SERVICIO

,Sede,Tipo_servicio,turnos,espera_cero,espera_positiva,porcentaje_espera_cero
0,Calle 26,Comercial,45301,31641,13660,69.85
1,Calle 26,Servicio,111759,37706,74053,33.74
2,Calle 63,Comercial,14547,8617,5930,59.24
3,Calle 63,Servicio,33066,5576,27490,16.86
4,Centro mayor,Comercial,20651,14303,6348,69.26
5,Centro mayor,Servicio,58455,22031,36424,37.69
6,Funza,Comercial,13951,7988,5963,57.26
7,Funza,Servicio,39812,9806,30006,24.63
8,Fusagasuga,Comercial,12903,7317,5586,56.71
9,Fusagasuga,Servicio,32316,4568,27748,14.14
10,Girardot,Comercial,10604,6720,3884,63.37
11,Girardot,Servicio,36815,8599,28216,23.36
12,La mesa,Comercial,3638,2428,1210,66.74
13,La mesa,Servicio,9688,1982,7706,20.46
14,Santa librada,Comercial,15198,10064,5134,66.22
15,Santa librada,Servicio,25592,3804,21788,14.86
16,Soacha,Comercial,16896,9570,7326,56.64
17,Soacha,Servicio,76208,19368,56840,25.41
18,Suba,Comercial,18401,10205,8196,55.46
19,Suba,Servicio,63320,15502,47818,24.48
20,Tintal plaza,Comercial,37355,29725,7630,79.57
21,Tintal plaza,Servicio,74957,34212,40745,45.64
22,Unicentro de occidente,Comercial,17537,10322,7215,58.86
23,Unicentro de occidente,Servicio,38801,11758,27043,30.30
24,Usaquen,Comercial,19183,12352,6831,64.39
25,Usaquen,Servicio,36122,11832,24290,32.76

VALIDACIÓN
Turnos originales: 883,076
Turnos en cruce: 883,076
Integridad: OK

In [76]:
print("=" * 70)
print("4.20.7.8.2. COMPARACIÓN DE SUBSERVICIOS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Cruce por sede y subservicio
# ------------------------------------------------------------

cruce_sede_subservicio = resumen_esperas(
    base_478,
    [
        "Sede",
        "Tipo_servicio",
        "SUBSERVICIO_HOMOLOGADO"
    ]
)

# ------------------------------------------------------------
# 2. Umbral mínimo de comparación
# ------------------------------------------------------------

MIN_TURNOS = 100

comparables = cruce_sede_subservicio.loc[
    cruce_sede_subservicio["turnos"] >= MIN_TURNOS
].copy()

print("\nCombinaciones totales:",
      len(cruce_sede_subservicio))

print("Combinaciones comparables:",
      len(comparables))

print("\nCOMBINACIONES CON MAYOR ESPERA CERO")

display(
    comparables.sort_values(
        "porcentaje_espera_cero",
        ascending=False
    ).head(20)
)

# ------------------------------------------------------------
# 3. Variabilidad entre sedes para un mismo subservicio
# ------------------------------------------------------------

variabilidad = (
    comparables.groupby(
        ["Tipo_servicio", "SUBSERVICIO_HOMOLOGADO"]
    )
    .agg(
        sedes_comparables=("Sede", "nunique"),
        porcentaje_min=("porcentaje_espera_cero", "min"),
        porcentaje_max=("porcentaje_espera_cero", "max"),
        turnos=("turnos", "sum")
    )
    .reset_index()
)

variabilidad["brecha_pp"] = (
    variabilidad["porcentaje_max"]
    - variabilidad["porcentaje_min"]
).round(2)

variabilidad = variabilidad.loc[
    variabilidad["sedes_comparables"] >= 2
].sort_values(
    "brecha_pp",
    ascending=False
)

print("\nSUBSERVICIOS CON MAYORES DIFERENCIAS ENTRE SEDES")

display(variabilidad.head(20))

assert cruce_sede_subservicio["turnos"].sum() == N_ORIGINAL

print("\nIntegridad: OK")

======================================================================
4.20.7.8.2. COMPARACIÓN DE SUBSERVICIOS
======================================================================

Combinaciones totales: 1725
Combinaciones comparables: 710

COMBINACIONES CON MAYOR ESPERA CERO

,Sede,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,turnos,espera_cero,espera_positiva,porcentaje_espera_cero
1212,Suba,Comercial,Radicacion aumento de cupos,124,124,0,100.00
285,Centro mayor,Comercial,"Informacion, inscripcion productos bac",273,273,0,100.00
539,Funza,Servicio,Solicitud devolucion puntos agiles,257,257,0,100.00
442,Funza,Comercial,Radicacion solicitudes credito hipotecario,278,278,0,100.00
441,Funza,Comercial,Radicacion solicitudes consumo,1363,1360,3,99.78
438,Funza,Comercial,Radicacion cupo credito,1308,1303,5,99.62
953,Santa librada,Comercial,Radicacion solicitudes credito hipotecario,223,222,1,99.55
327,Centro mayor,Servicio,Devolucion productos de educacion,790,786,4,99.49
1217,Suba,Comercial,Radicacion solicitudes credito hipotecario,381,379,2,99.48
274,Centro mayor,Comercial,Informacion e inscripcion de escuelas culturales,172,171,1,99.42
301,Centro mayor,Comercial,Radicacion reactivaciones cupo,320,318,2,99.38
1351,Tintal plaza,Comercial,Radicacion solicitudes credito hipotecario,1458,1446,12,99.18
690,Girardot,Comercial,Radicacion solicitudes credito hipotecario,244,242,2,99.18
1350,Tintal plaza,Comercial,Radicacion solicitudes consumo,5616,5569,47,99.16
568,Fusagasuga,Comercial,Radicacion cupo credito,1442,1429,13,99.10
348,Centro mayor,Servicio,Informacion resultados solicitudes hipotecario,102,101,1,99.02
1216,Suba,Comercial,Radicacion solicitudes consumo,1503,1488,15,99.00
1214,Suba,Comercial,Radicacion reactivaciones cupo,665,658,7,98.95
949,Santa librada,Comercial,Radicacion cupo credito,1229,1216,13,98.94
1213,Suba,Comercial,Radicacion cupo credito,1889,1869,20,98.94

SUBSERVICIOS CON MAYORES DIFERENCIAS ENTRE SEDES

,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,sedes_comparables,porcentaje_min,porcentaje_max,turnos,brecha_pp
47,Servicio,Entrega cheque cuota monetaria,6,2.67,98.48,3911,95.81
56,Servicio,Informacion beneficios subsidio al desempleo,9,2.11,97.70,6611,95.59
88,Servicio,Radicacion novedades,10,2.31,96.84,3980,94.53
102,Servicio,Solicitud proceso contingente envio tarjeta,10,3.54,96.64,4224,93.10
0,Comercial,Cotizacion y venta proyectos de vivienda,9,6.96,95.84,2938,88.88
97,Servicio,Requisitos cambio administrador,3,6.19,94.06,1575,87.87
41,Servicio,Desbloqueo por mora,5,2.04,87.91,1004,85.87
94,Servicio,Reclamacion cambio estado tarjeta no gestionado,6,0.91,86.33,1648,85.42
11,Comercial,Informacion y venta de boleteria piscitour,12,3.18,87.80,20246,84.62
35,Servicio,Cambio de clave por primera vez,10,2.31,86.82,4907,84.51
95,Servicio,Reclamacion por la no entrega de la tarjeta,2,2.20,86.43,448,84.23
57,Servicio,Informacion e inconsistencias bono lonchera,7,5.44,88.44,4388,83.00
104,Servicio,Validacion afiliacion trabajador y/o beneficia...,13,0.24,82.32,42037,82.08
93,Servicio,Radicacion solicitud cambio administrador,4,12.32,93.50,1487,81.18
13,Comercial,Informacion y venta escuelas deportivas,10,10.35,90.42,9392,80.07
73,Servicio,Pqr's credito,10,14.37,94.04,10255,79.67
61,Servicio,Informacion resultados solicitudes de consumo,3,17.24,96.49,673,79.25
10,Comercial,Informacion y venta de boleteria individual,6,3.32,82.30,3040,78.98
7,Comercial,Informacion hoteleria y turismo,13,11.87,90.71,17482,78.84
99,Servicio,Solicitud devolucion de aportes,6,0.00,78.26,1317,78.26

Integridad: OK

In [77]:
print("=" * 70)
print("4.20.7.8.3. EFECTO DE COMPOSICIÓN")
print("=" * 70)

# ------------------------------------------------------------
# 1. Tasas globales por servicio y subservicio
# ------------------------------------------------------------

dimensiones_servicio = [
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO"
]

tasas_globales = resumen_esperas(
    base_478,
    dimensiones_servicio
)

tasas_globales["tasa_global"] = (
    tasas_globales["espera_cero"]
    / tasas_globales["turnos"]
)

# ------------------------------------------------------------
# 2. Composición de cada sede
# ------------------------------------------------------------

composicion = cruce_sede_subservicio.merge(
    tasas_globales[
        dimensiones_servicio + ["tasa_global"]
    ],
    on=dimensiones_servicio,
    how="left",
    validate="many_to_one"
)

assert composicion["tasa_global"].notna().all()

# Turnos con espera cero esperados si cada sede tuviera
# la tasa global de sus respectivos servicios

composicion["esperas_cero_esperadas"] = (
    composicion["turnos"]
    * composicion["tasa_global"]
)

# ------------------------------------------------------------
# 3. Resumen ajustado por sede
# ------------------------------------------------------------

ajuste_sedes = (
    composicion.groupby("Sede")
    .agg(
        turnos=("turnos", "sum"),
        esperas_cero_observadas=("espera_cero", "sum"),
        esperas_cero_esperadas=(
            "esperas_cero_esperadas", "sum"
        )
    )
    .reset_index()
)

ajuste_sedes["tasa_observada_pct"] = (
    100 * ajuste_sedes["esperas_cero_observadas"]
    / ajuste_sedes["turnos"]
)

ajuste_sedes["tasa_esperada_pct"] = (
    100 * ajuste_sedes["esperas_cero_esperadas"]
    / ajuste_sedes["turnos"]
)

ajuste_sedes["diferencia_ajustada_pp"] = (
    ajuste_sedes["tasa_observada_pct"]
    - ajuste_sedes["tasa_esperada_pct"]
)

columnas_redondeo = [
    "tasa_observada_pct",
    "tasa_esperada_pct",
    "diferencia_ajustada_pp"
]

ajuste_sedes[columnas_redondeo] = (
    ajuste_sedes[columnas_redondeo].round(2)
)

ajuste_sedes = ajuste_sedes.sort_values(
    "diferencia_ajustada_pp",
    ascending=False
)

print("\nCOMPARACIÓN OBSERVADA VS ESPERADA")

display(ajuste_sedes)

print("\nVALIDACIÓN")
assert ajuste_sedes["turnos"].sum() == N_ORIGINAL
print("Integridad: OK")

======================================================================
4.20.7.8.3. EFECTO DE COMPOSICIÓN
======================================================================

COMPARACIÓN OBSERVADA VS ESPERADA

,Sede,turnos,esperas_cero_observadas,esperas_cero_esperadas,tasa_observada_pct,tasa_esperada_pct,diferencia_ajustada_pp
10,Tintal plaza,112312,63937,50577.494214,56.93,45.03,11.89
2,Centro mayor,79106,36334,31776.061697,45.93,40.17,5.76
0,Calle 26,157060,69347,62251.611570,44.15,39.64,4.52
12,Usaquen,55305,24184,21875.235380,43.73,39.55,4.17
9,Suba,81721,25707,28256.608613,31.46,34.58,-3.12
3,Funza,53763,17794,19993.904647,33.10,37.19,-4.09
5,Girardot,47419,15319,17274.470391,32.31,36.43,-4.12
11,Unicentro de occidente,56338,22080,24465.463254,39.19,43.43,-4.23
8,Soacha,93104,28938,33384.577517,31.08,35.86,-4.78
7,Santa librada,40790,13868,16563.108771,34.00,40.61,-6.61
6,La mesa,13326,4410,5652.886382,33.09,42.42,-9.33
1,Calle 63,47613,14193,18666.803870,29.81,39.21,-9.40
4,Fusagasuga,45219,11885,17257.773694,26.28,38.16,-11.88

VALIDACIÓN
Integridad: OK

In [78]:
print("=" * 70)
print("4.20.7.8.4. MATRIZ DE ALERTAS OPERATIVAS")
print("=" * 70)

# Umbrales exploratorios, no estándares institucionales
UMBRAL_DIFERENCIA_PP = 10
UMBRAL_BRECHA_SUBSERVICIO_PP = 20

matriz_alertas = ajuste_sedes.copy()

matriz_alertas["alerta_composicion"] = np.select(
    [
        matriz_alertas["diferencia_ajustada_pp"]
        >= UMBRAL_DIFERENCIA_PP,

        matriz_alertas["diferencia_ajustada_pp"]
        <= -UMBRAL_DIFERENCIA_PP
    ],
    [
        "Espera cero superior a referencia",
        "Espera cero inferior a referencia"
    ],
    default="Sin desviación relevante"
)

matriz_alertas["prioridad_revision"] = np.where(
    matriz_alertas["diferencia_ajustada_pp"].abs()
    >= UMBRAL_DIFERENCIA_PP,
    "Revisar",
    "Seguimiento"
)

print("\nMATRIZ DE ALERTAS POR SEDE")

display(
    matriz_alertas[
        [
            "Sede",
            "turnos",
            "tasa_observada_pct",
            "tasa_esperada_pct",
            "diferencia_ajustada_pp",
            "alerta_composicion",
            "prioridad_revision"
        ]
    ]
)

# ------------------------------------------------------------
# Subservicios con variación elevada entre sedes
# ------------------------------------------------------------

alertas_subservicio = variabilidad.loc[
    variabilidad["brecha_pp"]
    >= UMBRAL_BRECHA_SUBSERVICIO_PP
].copy()

print("\nSUBSERVICIOS CON BRECHAS DE 20 PP O MÁS")

display(alertas_subservicio)

print("\nNOTA METODOLÓGICA")
print(
    "Las alertas identifican diferencias descriptivas "
    "que requieren revisión. No constituyen evidencia "
    "de errores, incumplimientos ni baja eficiencia."
)

======================================================================
4.20.7.8.4. MATRIZ DE ALERTAS OPERATIVAS
======================================================================

MATRIZ DE ALERTAS POR SEDE

,Sede,turnos,tasa_observada_pct,tasa_esperada_pct,diferencia_ajustada_pp,alerta_composicion,prioridad_revision
10,Tintal plaza,112312,56.93,45.03,11.89,Espera cero superior a referencia,Revisar
2,Centro mayor,79106,45.93,40.17,5.76,Sin desviación relevante,Seguimiento
0,Calle 26,157060,44.15,39.64,4.52,Sin desviación relevante,Seguimiento
12,Usaquen,55305,43.73,39.55,4.17,Sin desviación relevante,Seguimiento
9,Suba,81721,31.46,34.58,-3.12,Sin desviación relevante,Seguimiento
3,Funza,53763,33.10,37.19,-4.09,Sin desviación relevante,Seguimiento
5,Girardot,47419,32.31,36.43,-4.12,Sin desviación relevante,Seguimiento
11,Unicentro de occidente,56338,39.19,43.43,-4.23,Sin desviación relevante,Seguimiento
8,Soacha,93104,31.08,35.86,-4.78,Sin desviación relevante,Seguimiento
7,Santa librada,40790,34.00,40.61,-6.61,Sin desviación relevante,Seguimiento
6,La mesa,13326,33.09,42.42,-9.33,Sin desviación relevante,Seguimiento
1,Calle 63,47613,29.81,39.21,-9.40,Sin desviación relevante,Seguimiento
4,Fusagasuga,45219,26.28,38.16,-11.88,Espera cero inferior a referencia,Revisar

SUBSERVICIOS CON BRECHAS DE 20 PP O MÁS

,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,sedes_comparables,porcentaje_min,porcentaje_max,turnos,brecha_pp
47,Servicio,Entrega cheque cuota monetaria,6,2.67,98.48,3911,95.81
56,Servicio,Informacion beneficios subsidio al desempleo,9,2.11,97.70,6611,95.59
88,Servicio,Radicacion novedades,10,2.31,96.84,3980,94.53
102,Servicio,Solicitud proceso contingente envio tarjeta,10,3.54,96.64,4224,93.10
0,Comercial,Cotizacion y venta proyectos de vivienda,9,6.96,95.84,2938,88.88
...,...,...,...,...,...,...,...
32,Servicio,Bloqueo por aportes,12,2.36,27.27,7264,24.91
34,Servicio,Cambio de clave por olvido,12,1.28,25.64,31571,24.36
26,Comercial,Radicacion solicitudes credito hipotecario,12,75.77,100.00,6576,24.23
85,Servicio,Radicacion ajustes o renuncias sub. vivienda,2,66.67,90.11,329,23.44
22,Comercial,Radicacion cupo credito,13,78.39,99.62,32996,21.23

NOTA METODOLÓGICA
Las alertas identifican diferencias descriptivas que requieren revisión. No constituyen evidencia de errores, incumplimientos ni baja eficiencia.

In [79]:
print("=" * 70)
print("4.20.7.8.5. VALIDACIÓN FINAL")
print("=" * 70)

# ------------------------------------------------------------
# 1. Integridad de registros
# ------------------------------------------------------------

assert len(base_478) == N_ORIGINAL

# ------------------------------------------------------------
# 2. Conservación de la clasificación
# ------------------------------------------------------------

assert (
    base_478["tipo_vinculacion"]
    .equals(digiturnos_final["tipo_vinculacion"])
), "Se detectaron diferencias en tipo_vinculacion."

# ------------------------------------------------------------
# 3. Reconciliación de esperas
# ------------------------------------------------------------

n_cero = int(base_478["espera_cero_auditada"].sum())
n_positiva = N_ORIGINAL - n_cero

assert n_cero + n_positiva == N_ORIGINAL

assert cruce_sede_tipo["espera_cero"].sum() == n_cero

assert (
    cruce_sede_subservicio["espera_cero"].sum()
    == n_cero
)

assert (
    ajuste_sedes["esperas_cero_observadas"].sum()
    == n_cero
)

# ------------------------------------------------------------
# 4. Resumen de auditoría
# ------------------------------------------------------------

print(f"Turnos originales: {N_ORIGINAL:,}")
print(f"Turnos con espera cero: {n_cero:,}")
print(f"Turnos con espera positiva: {n_positiva:,}")

print(
    "Sedes analizadas:",
    base_478["Sede"].nunique()
)

print(
    "Subservicios analizados:",
    base_478["SUBSERVICIO_HOMOLOGADO"].nunique()
)

print(
    "Sedes con alerta:",
    int(
        matriz_alertas["prioridad_revision"]
        .eq("Revisar").sum()
    )
)

print(
    "Subservicios con alerta:",
    len(alertas_subservicio)
)

print("\nVALIDACIÓN COMPLETADA")
print("Registros originales conservados.")
print("Clasificación de afiliación conservada.")
print("No se eliminaron esperas cero.")
print("No se modificó digiturnos_final.")
print("Análisis realizado sobre copia independiente.")

======================================================================
4.20.7.8.5. VALIDACIÓN FINAL
======================================================================
Turnos originales: 883,076
Turnos con espera cero: 347,996
Turnos con espera positiva: 535,080
Sedes analizadas: 13
Subservicios analizados: 140
Sedes con alerta: 2
Subservicios con alerta: 79

VALIDACIÓN COMPLETADA
Registros originales conservados.
Clasificación de afiliación conservada.
No se eliminaron esperas cero.
No se modificó digiturnos_final.
Análisis realizado sobre copia independiente.

### 4.20.7.8.6. Conclusiones de la auditoría cruzada

La auditoría de 883.076 turnos identificó que el 39,41 % registra un tiempo de espera igual a cero. Este comportamiento presenta diferencias relevantes según la sede, el tipo de servicio y el subservicio atendido.

Los servicios comerciales registran sistemáticamente mayores proporciones de espera cero que los servicios operativos. Sin embargo, el análisis ajustado por composición evidencia que las diferencias entre sedes no se explican exclusivamente por la mezcla de servicios. Tintal plaza presenta una proporción de esperas cero 11,89 puntos porcentuales superior a la referencia ajustada, mientras que Fusagasugá registra una diferencia de −11,88 puntos porcentuales.

Adicionalmente, se identificaron 79 subservicios con brechas de al menos 20 puntos porcentuales entre sedes comparables, lo que sugiere la necesidad de contrastar los procedimientos de registro y las condiciones operativas antes de interpretar estas diferencias como resultados de eficiencia.

**Decisión metodológica:** conservar la totalidad de los registros, incluidos los turnos con espera cero, y considerar este fenómeno como una dimensión específica del análisis operativo. Los indicadores posteriores deberán distinguir entre el tiempo promedio de espera de todos los turnos y el correspondiente a aquellos con espera positiva.

La auditoría concluye sin modificaciones de la fuente original ni exclusiones automáticas de registros.

# 5. ANÁLISIS EXPLORATORIO E INDICADORES DE GESTIÓN

## 5.1. Análisis de la demanda de atención

### 5.1.3. Preparación y validación de la base analítica

Se construye una copia independiente de digiturnos_final para analizar
la distribución de turnos por sede, tipo de servicio, subservicio y periodo.

No se modifican registros originales ni se aplican exclusiones automáticas.

In [80]:

# ============================================================
# 5.1.3. PREPARACIÓN Y VALIDACIÓN DE LA BASE ANALÍTICA
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 70)
print("5.1.3. PREPARACIÓN DE LA DEMANDA DE DIGITURNOS")
print("=" * 70)

# ------------------------------------------------------------
# 1. VALIDAR LA FUENTE CONSOLIDADA
# ------------------------------------------------------------

assert "digiturnos_final" in globals(), (
    "No existe digiturnos_final. "
    "Ejecuta primero las secciones de consolidación."
)

N_ORIGINAL = 883_076

assert isinstance(digiturnos_final, pd.DataFrame)
assert len(digiturnos_final) == N_ORIGINAL, (
    "La cantidad de registros no coincide con la auditoría."
)

# ------------------------------------------------------------
# 2. CREAR COPIA INDEPENDIENTE
# ------------------------------------------------------------

demanda_51 = digiturnos_final.copy(deep=True)

# ------------------------------------------------------------
# 3. VALIDAR VARIABLES REQUERIDAS
# ------------------------------------------------------------

columnas_requeridas = [
    "Sede",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "fecha_servicio"
]

faltantes = [
    col for col in columnas_requeridas
    if col not in demanda_51.columns
]

assert not faltantes, (
    f"Columnas no disponibles: {faltantes}"
)

# ------------------------------------------------------------
# 4. CONSTRUIR VARIABLES TEMPORALES ANALÍTICAS
# ------------------------------------------------------------

demanda_51["fecha_analisis"] = pd.to_datetime(
    demanda_51["fecha_servicio"],
    errors="coerce"
)

demanda_51["periodo_mes"] = (
    demanda_51["fecha_analisis"]
    .dt.to_period("M")
    .astype("string")
)

demanda_51["anio"] = (
    demanda_51["fecha_analisis"]
    .dt.year
    .astype("Int64")
)

demanda_51["mes_numero"] = (
    demanda_51["fecha_analisis"]
    .dt.month
    .astype("Int64")
)

# ------------------------------------------------------------
# 5. AUDITORÍA DE INTEGRIDAD
# ------------------------------------------------------------

assert len(demanda_51) == len(digiturnos_final)

assert demanda_51.index.equals(
    digiturnos_final.index
)

columnas_originales = digiturnos_final.columns.tolist()

pd.testing.assert_frame_equal(
    demanda_51[columnas_originales],
    digiturnos_final,
    check_dtype=True
)

# ------------------------------------------------------------
# 6. RESUMEN DE LA BASE ANALÍTICA
# ------------------------------------------------------------

resumen_51 = pd.DataFrame({
    "indicador": [
        "Turnos originales",
        "Turnos analíticos",
        "Sedes",
        "Tipos de servicio",
        "Subservicios",
        "Fechas no interpretables",
        "Primera fecha",
        "Última fecha"
    ],
    "resultado": [
        len(digiturnos_final),
        len(demanda_51),
        demanda_51["Sede"].nunique(dropna=True),
        demanda_51["Tipo_servicio"].nunique(dropna=True),
        demanda_51["SUBSERVICIO_HOMOLOGADO"].nunique(
            dropna=True
        ),
        demanda_51["fecha_analisis"].isna().sum(),
        demanda_51["fecha_analisis"].min(),
        demanda_51["fecha_analisis"].max()
    ]
})

display(resumen_51)

print("\nVALIDACIÓN")
print(f"Registros conservados: {len(demanda_51):,}")
print("Fuente original sin modificaciones: OK")
print("Base analítica independiente: OK")

======================================================================
5.1.3. PREPARACIÓN DE LA DEMANDA DE DIGITURNOS
======================================================================

                  indicador            resultado
0         Turnos originales               883076
1         Turnos analíticos               883076
2                     Sedes                   13
3         Tipos de servicio                    2
4              Subservicios                  140
5  Fechas no interpretables                    0
6             Primera fecha  2024-01-02 00:00:00
7              Última fecha  2024-09-17 00:00:00

VALIDACIÓN
Registros conservados: 883,076
Fuente original sin modificaciones: OK
Base analítica independiente: OK

### 5.1.4. Distribución de la demanda por sede

Se calcula el volumen de turnos y su participación porcentual
respecto del total institucional.

Se incorpora la participación acumulada para identificar
la concentración de la demanda.

In [81]:

# ============================================================
# 5.1.4. DISTRIBUCIÓN DE LA DEMANDA POR SEDE
# ============================================================

print("=" * 70)
print("5.1.4. DISTRIBUCIÓN DE LA DEMANDA POR SEDE")
print("=" * 70)

# ------------------------------------------------------------
# 1. AGRUPAR TURNOS POR SEDE
# ------------------------------------------------------------

demanda_sede_51 = (
    demanda_51
    .groupby("Sede", dropna=False)
    .size()
    .reset_index(name="turnos")
)

# ------------------------------------------------------------
# 2. CALCULAR PARTICIPACIÓN
# ------------------------------------------------------------

total_turnos_51 = len(demanda_51)

demanda_sede_51["participacion_pct"] = (
    demanda_sede_51["turnos"]
    / total_turnos_51
    * 100
)

# ------------------------------------------------------------
# 3. ORDENAR Y CALCULAR CONCENTRACIÓN
# ------------------------------------------------------------

demanda_sede_51 = (
    demanda_sede_51
    .sort_values(
        "turnos",
        ascending=False
    )
    .reset_index(drop=True)
)

demanda_sede_51["participacion_acumulada_pct"] = (
    demanda_sede_51["participacion_pct"]
    .cumsum()
)

# ------------------------------------------------------------
# 4. VALIDACIONES
# ------------------------------------------------------------

assert demanda_sede_51["turnos"].sum() == total_turnos_51

assert np.isclose(
    demanda_sede_51["participacion_pct"].sum(),
    100,
    atol=1e-8
)

# ------------------------------------------------------------
# 5. RESULTADOS
# ------------------------------------------------------------

display(
    demanda_sede_51.round(2)
)

top_3 = demanda_sede_51.head(3)

print("\nRESUMEN")
print(f"Turnos: {total_turnos_51:,}")
print(f"Sedes: {len(demanda_sede_51)}")

print(
    "Participación de las tres sedes "
    f"con mayor demanda: "
    f"{top_3['participacion_pct'].sum():.2f}%"
)

print("\nIntegridad: OK")

======================================================================
5.1.4. DISTRIBUCIÓN DE LA DEMANDA POR SEDE
======================================================================

,Sede,turnos,participacion_pct,participacion_acumulada_pct
0,Calle 26,157060,17.79,17.79
1,Tintal plaza,112312,12.72,30.50
2,Soacha,93104,10.54,41.05
3,Suba,81721,9.25,50.30
4,Centro mayor,79106,8.96,59.26
5,Unicentro de occidente,56338,6.38,65.64
6,Usaquen,55305,6.26,71.90
7,Funza,53763,6.09,77.99
8,Calle 63,47613,5.39,83.38
9,Girardot,47419,5.37,88.75
10,Fusagasuga,45219,5.12,93.87
11,Santa librada,40790,4.62,98.49
12,La mesa,13326,1.51,100.00

RESUMEN
Turnos: 883,076
Sedes: 13
Participación de las tres sedes con mayor demanda: 41.05%

Integridad: OK

### 5.1.5. Distribución de la demanda por tipo de servicio y subservicio

Se analiza la composición de los turnos según el tipo de servicio
y el subservicio homologado.

Se calculan indicadores de participación institucional, concentración
acumulada y participación de cada subservicio dentro de su tipo
de servicio.

Se conservan todos los registros y no se modifica la base original.

In [82]:

# ============================================================
# 5.1.5. DEMANDA POR TIPO DE SERVICIO Y SUBSERVICIO
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 70)
print("5.1.5. DEMANDA POR TIPO DE SERVICIO Y SUBSERVICIO")
print("=" * 70)

# ------------------------------------------------------------
# 1. VALIDAR FUENTE
# ------------------------------------------------------------

assert "demanda_51" in globals(), (
    "Primero ejecuta la sección 5.1.3."
)

N_BASE = len(demanda_51)

assert N_BASE == 883_076

columnas = [
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO"
]

assert all(col in demanda_51.columns for col in columnas)

# ------------------------------------------------------------
# 2. DEMANDA POR TIPO DE SERVICIO
# ------------------------------------------------------------

demanda_tipo_51 = (
    demanda_51
    .groupby("Tipo_servicio", dropna=False)
    .size()
    .reset_index(name="turnos")
    .sort_values("turnos", ascending=False)
    .reset_index(drop=True)
)

demanda_tipo_51["participacion_pct"] = (
    demanda_tipo_51["turnos"] / N_BASE * 100
)

print("\n1. DISTRIBUCIÓN POR TIPO DE SERVICIO")

display(demanda_tipo_51.round(2))

# ------------------------------------------------------------
# 3. DEMANDA POR SUBSERVICIO
# ------------------------------------------------------------

demanda_subservicio_51 = (
    demanda_51
    .groupby(
        ["Tipo_servicio", "SUBSERVICIO_HOMOLOGADO"],
        dropna=False
    )
    .size()
    .reset_index(name="turnos")
    .sort_values("turnos", ascending=False)
    .reset_index(drop=True)
)

# Participación sobre el total institucional
demanda_subservicio_51["participacion_total_pct"] = (
    demanda_subservicio_51["turnos"] / N_BASE * 100
)

# Participación acumulada institucional
demanda_subservicio_51["participacion_acumulada_pct"] = (
    demanda_subservicio_51["participacion_total_pct"]
    .cumsum()
)

# ------------------------------------------------------------
# 4. PARTICIPACIÓN DENTRO DEL TIPO DE SERVICIO
# ------------------------------------------------------------

totales_tipo = (
    demanda_tipo_51
    .set_index("Tipo_servicio")["turnos"]
)

demanda_subservicio_51["total_tipo"] = (
    demanda_subservicio_51["Tipo_servicio"]
    .map(totales_tipo)
)

demanda_subservicio_51["participacion_tipo_pct"] = (
    demanda_subservicio_51["turnos"]
    / demanda_subservicio_51["total_tipo"]
    * 100
)

print("\n2. LOS 20 SUBSERVICIOS CON MAYOR DEMANDA")

display(
    demanda_subservicio_51[
        [
            "Tipo_servicio",
            "SUBSERVICIO_HOMOLOGADO",
            "turnos",
            "participacion_total_pct",
            "participacion_tipo_pct",
            "participacion_acumulada_pct"
        ]
    ]
    .head(20)
    .round(2)
)

# ------------------------------------------------------------
# 5. INDICADORES DE CONCENTRACIÓN
# ------------------------------------------------------------

top_5 = demanda_subservicio_51.head(5)
top_10 = demanda_subservicio_51.head(10)
top_20 = demanda_subservicio_51.head(20)

resumen_concentracion_51 = pd.DataFrame({
    "grupo": [
        "Top 5 subservicios",
        "Top 10 subservicios",
        "Top 20 subservicios"
    ],
    "turnos": [
        top_5["turnos"].sum(),
        top_10["turnos"].sum(),
        top_20["turnos"].sum()
    ]
})

resumen_concentracion_51["participacion_pct"] = (
    resumen_concentracion_51["turnos"]
    / N_BASE
    * 100
)

print("\n3. CONCENTRACIÓN DE LA DEMANDA")

display(resumen_concentracion_51.round(2))

# ------------------------------------------------------------
# 6. VALIDACIONES DE INTEGRIDAD
# ------------------------------------------------------------

assert demanda_tipo_51["turnos"].sum() == N_BASE

assert demanda_subservicio_51["turnos"].sum() == N_BASE

assert np.isclose(
    demanda_tipo_51["participacion_pct"].sum(),
    100,
    atol=1e-8
)

assert np.isclose(
    demanda_subservicio_51["participacion_total_pct"].sum(),
    100,
    atol=1e-8
)

assert len(demanda_51) == len(digiturnos_final)

print("\n4. VALIDACIÓN FINAL")
print(f"Turnos originales: {len(digiturnos_final):,}")
print(f"Turnos analizados: {N_BASE:,}")
print(
    "Combinaciones tipo-subservicio: "
    f"{len(demanda_subservicio_51):,}"
)
print(
    "Subservicios únicos: "
    f"{demanda_51['SUBSERVICIO_HOMOLOGADO'].nunique()}"
)

print("Integridad de registros: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.5. DEMANDA POR TIPO DE SERVICIO Y SUBSERVICIO
======================================================================

1. DISTRIBUCIÓN POR TIPO DE SERVICIO

  Tipo_servicio  turnos  participacion_pct
0      Servicio  636911              72.12
1     Comercial  246165              27.88

2. LOS 20 SUBSERVICIOS CON MAYOR DEMANDA

,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,turnos,participacion_total_pct,participacion_tipo_pct,participacion_acumulada_pct
0,Servicio,Rad afiliacion trabajadores hasta 10 formularios,94137,10.66,14.78,10.66
1,Servicio,Entrega tams primera vez,86012,9.74,13.50,20.40
2,Servicio,Validacion afiliacion trabajador y/o beneficia...,42037,4.76,6.60,25.16
3,Comercial,Radicacion cupo credito,32996,3.74,13.40,28.90
4,Servicio,Cambio de clave por olvido,31644,3.58,4.97,32.48
5,Servicio,Informacion general subsidio de vivienda,30561,3.46,4.80,35.94
6,Comercial,Informacion credito consumo,30459,3.45,12.37,39.39
7,Servicio,Radicacion postulacion de subsidio vivienda nueva,29991,3.40,4.71,42.79
8,Comercial,Radicacion solicitudes consumo,29191,3.31,11.86,46.09
9,Comercial,Informacion cupo credito,28787,3.26,11.69,49.35
10,Servicio,Radicacion certificados escolares,23710,2.68,3.72,52.04
11,Servicio,Entrega tams reexpedicion,21805,2.47,3.42,54.51
12,Servicio,Pqr's cuota monetaria,20581,2.33,3.23,56.84
13,Comercial,Informacion y venta de boleteria piscitour,20249,2.29,8.23,59.13
14,Servicio,Pqr's administracion de afiliados,19834,2.25,3.11,61.38
15,Servicio,Certificado afiliacion trabajador y/o benefici...,18591,2.11,2.92,63.48
16,Comercial,Informacion hoteleria y turismo,17482,1.98,7.10,65.46
17,Servicio,Informacion subsidios de arrendamiento,16994,1.92,2.67,67.39
18,Servicio,Aclaracion procesos de cobranza,16616,1.88,2.61,69.27
19,Servicio,Pago cupo credito,11657,1.32,1.83,70.59

3. CONCENTRACIÓN DE LA DEMANDA

                 grupo  turnos  participacion_pct
0   Top 5 subservicios  286826              32.48
1  Top 10 subservicios  435815              49.35
2  Top 20 subservicios  623334              70.59

4. VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos analizados: 883,076
Combinaciones tipo-subservicio: 141
Subservicios únicos: 140
Integridad de registros: OK
Base original conservada: OK
======================================================================

### 5.1.6. Evolución mensual de la demanda

Se analiza la evolución de los turnos por mes y tipo de servicio,
identificando variaciones mensuales, concentración temporal y
cobertura de fechas.

Las comparaciones se presentan con una advertencia metodológica:
enero y septiembre tienen cobertura parcial respecto al calendario.

Se conservan todos los registros y la base analítica original.

In [83]:

# ============================================================
# 5.1.6. EVOLUCIÓN MENSUAL DE LA DEMANDA
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 70)
print("5.1.6. EVOLUCIÓN MENSUAL DE LA DEMANDA")
print("=" * 70)

# ------------------------------------------------------------
# 1. BASE INDEPENDIENTE Y CONTROLES
# ------------------------------------------------------------

assert "demanda_51" in globals(), (
    "Ejecuta primero la sección 5.1.3."
)

N_BASE = len(demanda_51)
assert N_BASE == 883_076

# Se trabaja sobre una copia independiente.
demanda_temporal_51 = demanda_51.copy(deep=True)

# Verificar el nombre de la columna temporal.
# La sección 5.1.3 utiliza la fecha original del servicio.
COLUMNA_FECHA = "Fecha_Servico"

assert COLUMNA_FECHA in demanda_temporal_51.columns, (
    f"No existe la columna {COLUMNA_FECHA}. "
    "Verifica su nombre en demanda_51.columns."
)

demanda_temporal_51["fecha_analisis"] = pd.to_datetime(
    demanda_temporal_51[COLUMNA_FECHA],
    errors="coerce",
    dayfirst=True
).dt.normalize()

assert demanda_temporal_51["fecha_analisis"].notna().all(), (
    "Se encontraron fechas no interpretables."
)

# ------------------------------------------------------------
# 2. VARIABLES TEMPORALES
# ------------------------------------------------------------

demanda_temporal_51["periodo_mes"] = (
    demanda_temporal_51["fecha_analisis"]
    .dt.to_period("M")
)

demanda_temporal_51["anio"] = (
    demanda_temporal_51["fecha_analisis"].dt.year
)

demanda_temporal_51["mes"] = (
    demanda_temporal_51["fecha_analisis"].dt.month
)

# ------------------------------------------------------------
# 3. DEMANDA MENSUAL INSTITUCIONAL
# ------------------------------------------------------------

demanda_mensual_51 = (
    demanda_temporal_51
    .groupby("periodo_mes")
    .agg(
        turnos=("fecha_analisis", "size"),
        primera_fecha=("fecha_analisis", "min"),
        ultima_fecha=("fecha_analisis", "max"),
        dias_con_registros=("fecha_analisis", "nunique")
    )
    .reset_index()
    .sort_values("periodo_mes")
    .reset_index(drop=True)
)

demanda_mensual_51["dias_calendario_mes"] = (
    demanda_mensual_51["periodo_mes"]
    .dt.days_in_month
)

demanda_mensual_51["cobertura_fechas_pct"] = (
    demanda_mensual_51["dias_con_registros"]
    / demanda_mensual_51["dias_calendario_mes"]
    * 100
)

demanda_mensual_51["participacion_pct"] = (
    demanda_mensual_51["turnos"] / N_BASE * 100
)

demanda_mensual_51["variacion_mensual_pct"] = (
    demanda_mensual_51["turnos"]
    .pct_change()
    .mul(100)
    .replace([np.inf, -np.inf], np.nan)
)

# Promedio por día con registros:
# indicador descriptivo, no equivalente a día hábil.
demanda_mensual_51["promedio_dia_con_registros"] = (
    demanda_mensual_51["turnos"]
    / demanda_mensual_51["dias_con_registros"]
)

print("\n1. EVOLUCIÓN MENSUAL INSTITUCIONAL")

display(demanda_mensual_51.round(2))

# ------------------------------------------------------------
# 4. DEMANDA MENSUAL POR TIPO DE SERVICIO
# ------------------------------------------------------------

demanda_mensual_tipo_51 = (
    demanda_temporal_51
    .groupby(
        ["periodo_mes", "Tipo_servicio"],
        dropna=False
    )
    .size()
    .reset_index(name="turnos")
    .sort_values(["periodo_mes", "Tipo_servicio"])
    .reset_index(drop=True)
)

totales_mes = (
    demanda_mensual_51
    .set_index("periodo_mes")["turnos"]
)

demanda_mensual_tipo_51["total_mes"] = (
    demanda_mensual_tipo_51["periodo_mes"]
    .map(totales_mes)
)

demanda_mensual_tipo_51["participacion_mes_pct"] = (
    demanda_mensual_tipo_51["turnos"]
    / demanda_mensual_tipo_51["total_mes"]
    * 100
)

print("\n2. DEMANDA MENSUAL POR TIPO DE SERVICIO")

display(demanda_mensual_tipo_51.round(2))

# ------------------------------------------------------------
# 5. COBERTURA DEL PERIODO
# ------------------------------------------------------------

fecha_min = demanda_temporal_51["fecha_analisis"].min()
fecha_max = demanda_temporal_51["fecha_analisis"].max()

primer_periodo = fecha_min.to_period("M")
ultimo_periodo = fecha_max.to_period("M")

print("\n3. COBERTURA TEMPORAL")
print(f"Primera fecha: {fecha_min.date()}")
print(f"Última fecha: {fecha_max.date()}")
print(f"Meses observados: {len(demanda_mensual_51)}")

print(
    "Primer mes inicia el día 1:",
    fecha_min.day == 1
)

print(
    "Último mes termina el último día:",
    fecha_max.day == fecha_max.days_in_month
)

# ------------------------------------------------------------
# 6. VALIDACIONES DE INTEGRIDAD
# ------------------------------------------------------------

assert demanda_mensual_51["turnos"].sum() == N_BASE

assert demanda_mensual_tipo_51["turnos"].sum() == N_BASE

assert np.isclose(
    demanda_mensual_51["participacion_pct"].sum(),
    100,
    atol=1e-8
)

control_mes = (
    demanda_mensual_tipo_51
    .groupby("periodo_mes")["turnos"]
    .sum()
)

assert control_mes.equals(
    demanda_mensual_51.set_index("periodo_mes")["turnos"]
)

assert len(demanda_temporal_51) == len(demanda_51)

print("\n4. VALIDACIÓN FINAL")
print(f"Turnos originales: {N_BASE:,}")
print(f"Turnos mensuales conciliados: {demanda_mensual_51['turnos'].sum():,}")
print("Integridad mensual: OK")
print("Integridad por tipo de servicio: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.6. EVOLUCIÓN MENSUAL DE LA DEMANDA
======================================================================

1. EVOLUCIÓN MENSUAL INSTITUCIONAL

C:\Users\acoba\AppData\Local\Temp\ipykernel_3292\1065490516.py:112: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  display(demanda_mensual_51.round(2))

,periodo_mes,turnos,primera_fecha,ultima_fecha,dias_con_registros,dias_calendario_mes,cobertura_fechas_pct,participacion_pct,variacion_mensual_pct,promedio_dia_con_registros
0,2024-01,131444,2024-01-02,2024-01-31,25,31,80.65,14.88,NaN,5257.76
1,2024-02,116571,2024-02-01,2024-02-29,25,29,86.21,13.20,-11.32,4662.84
2,2024-03,108791,2024-03-01,2024-03-30,23,31,74.19,12.32,-6.67,4730.04
3,2024-04,118149,2024-04-01,2024-04-30,26,30,86.67,13.38,8.60,4544.19
4,2024-05,103252,2024-05-02,2024-05-31,25,31,80.65,11.69,-12.61,4130.08
5,2024-06,90095,2024-06-01,2024-06-30,24,30,80.00,10.20,-12.74,3753.96
6,2024-07,92069,2024-07-02,2024-07-31,25,31,80.65,10.43,2.19,3682.76
7,2024-08,82994,2024-08-01,2024-08-31,25,31,80.65,9.40,-9.86,3319.76
8,2024-09,39711,2024-09-02,2024-09-17,14,30,46.67,4.50,-52.15,2836.50

2. DEMANDA MENSUAL POR TIPO DE SERVICIO

C:\Users\acoba\AppData\Local\Temp\ipykernel_3292\1065490516.py:148: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  display(demanda_mensual_tipo_51.round(2))

   periodo_mes Tipo_servicio  turnos  total_mes  participacion_mes_pct
0      2024-01     Comercial   38985     131444                  29.66
1      2024-01      Servicio   92459     131444                  70.34
2      2024-02     Comercial   31019     116571                  26.61
3      2024-02      Servicio   85552     116571                  73.39
4      2024-03     Comercial   27346     108791                  25.14
5      2024-03      Servicio   81445     108791                  74.86
6      2024-04     Comercial   31711     118149                  26.84
7      2024-04      Servicio   86438     118149                  73.16
8      2024-05     Comercial   28440     103252                  27.54
9      2024-05      Servicio   74812     103252                  72.46
10     2024-06     Comercial   27788      90095                  30.84
11     2024-06      Servicio   62307      90095                  69.16
12     2024-07     Comercial   26901      92069                  29.22
13     2024-07      Servicio   65168      92069                  70.78
14     2024-08     Comercial   23277      82994                  28.05
15     2024-08      Servicio   59717      82994                  71.95
16     2024-09     Comercial   10698      39711                  26.94
17     2024-09      Servicio   29013      39711                  73.06

3. COBERTURA TEMPORAL
Primera fecha: 2024-01-02
Última fecha: 2024-09-17
Meses observados: 9
Primer mes inicia el día 1: False
Último mes termina el último día: False

4. VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos mensuales conciliados: 883,076
Integridad mensual: OK
Integridad por tipo de servicio: OK
Base original conservada: OK
======================================================================

In [84]:

# ============================================================
# 5.1.7.1. PREPARACIÓN Y VALIDACIÓN TEMPORAL
# ============================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 70)
print("5.1.7.1. PREPARACIÓN TEMPORAL DE LA DEMANDA")
print("=" * 70)

# ------------------------------------------------------------
# 1. Copia independiente de la base analítica
# ------------------------------------------------------------

demanda_horaria_51 = demanda_temporal_51.copy(deep=True)

N_ORIGINAL = 883_076

assert len(demanda_horaria_51) == N_ORIGINAL, (
    "ERROR: no coincide el número de registros originales."
)

# ------------------------------------------------------------
# 2. Verificación de columnas requeridas
# ------------------------------------------------------------

columnas_requeridas = [
    "fecha_analisis",
    "Sede",
    "Tipo_servicio"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in demanda_horaria_51.columns
]

assert not faltantes, (
    f"Columnas requeridas no disponibles: {faltantes}"
)

# La hora debe provenir de la marca temporal de solicitud,
# no de la hora de llamado ni de finalización.

candidatas_solicitud = [
    "ts_solicitud",
    "Hora_solicitud_Servicio"
]

columna_solicitud = next(
    (
        c for c in candidatas_solicitud
        if c in demanda_horaria_51.columns
    ),
    None
)

assert columna_solicitud is not None, (
    "No se encontró la marca temporal de solicitud. "
    "Verificar las columnas de demanda_temporal_51."
)

# ------------------------------------------------------------
# 3. Preparación de fechas
# ------------------------------------------------------------

demanda_horaria_51["fecha_analisis"] = pd.to_datetime(
    demanda_horaria_51["fecha_analisis"],
    errors="coerce"
)

assert demanda_horaria_51["fecha_analisis"].notna().all(), (
    "Existen fechas de análisis no interpretables."
)

# Preferir la marca completa previamente auditada.
# Si solo existe una columna de hora, extraer HH:MM:SS.
if columna_solicitud == "ts_solicitud":

    solicitud_dt = pd.to_datetime(
        demanda_horaria_51[columna_solicitud],
        errors="coerce"
    )

    demanda_horaria_51["hora_solicitud_analisis"] = (
        solicitud_dt.dt.hour
    )

    demanda_horaria_51["fecha_solicitud_analisis"] = (
        solicitud_dt.dt.normalize()
    )

else:

    hora_texto = (
        demanda_horaria_51[columna_solicitud]
        .astype("string")
        .str.strip()
    )

    # Admite tanto HH:MM:SS como fecha y hora completas.
    hora_extraida = hora_texto.str.extract(
        r"(\d{1,2}):(\d{2})(?::(\d{2}))?"
    )

    demanda_horaria_51["hora_solicitud_analisis"] = (
        pd.to_numeric(
            hora_extraida[0],
            errors="coerce"
        )
    )

    demanda_horaria_51["fecha_solicitud_analisis"] = (
        demanda_horaria_51["fecha_analisis"].dt.normalize()
    )

# ------------------------------------------------------------
# 4. Derivación del día de la semana
# ------------------------------------------------------------

dias_es = {
    0: "Lunes",
    1: "Martes",
    2: "Miércoles",
    3: "Jueves",
    4: "Viernes",
    5: "Sábado",
    6: "Domingo"
}

demanda_horaria_51["dia_semana_num"] = (
    demanda_horaria_51["fecha_solicitud_analisis"]
    .dt.dayofweek
)

demanda_horaria_51["dia_semana"] = (
    demanda_horaria_51["dia_semana_num"]
    .map(dias_es)
)

demanda_horaria_51["hora_solicitud_analisis"] = (
    pd.to_numeric(
        demanda_horaria_51["hora_solicitud_analisis"],
        errors="coerce"
    ).astype("Int64")
)

demanda_horaria_51["franja_horaria"] = (
    demanda_horaria_51["hora_solicitud_analisis"]
    .map(
        lambda h: (
            f"{int(h):02d}:00-{int(h):02d}:59"
            if pd.notna(h)
            else pd.NA
        )
    )
)

# ------------------------------------------------------------
# 5. Auditoría de integridad temporal
# ------------------------------------------------------------

auditoria_temporal_517 = pd.DataFrame([
    {
        "indicador": "Turnos originales",
        "resultado": N_ORIGINAL
    },
    {
        "indicador": "Turnos analíticos",
        "resultado": len(demanda_horaria_51)
    },
    {
        "indicador": "Fechas faltantes",
        "resultado": int(
            demanda_horaria_51[
                "fecha_solicitud_analisis"
            ].isna().sum()
        )
    },
    {
        "indicador": "Horas faltantes",
        "resultado": int(
            demanda_horaria_51[
                "hora_solicitud_analisis"
            ].isna().sum()
        )
    },
    {
        "indicador": "Horas fuera de rango",
        "resultado": int(
            (
                demanda_horaria_51[
                    "hora_solicitud_analisis"
                ].notna()
                &
                ~demanda_horaria_51[
                    "hora_solicitud_analisis"
                ].between(0, 23)
            ).sum()
        )
    },
    {
        "indicador": "Días no identificados",
        "resultado": int(
            demanda_horaria_51[
                "dia_semana"
            ].isna().sum()
        )
    }
])

display(auditoria_temporal_517)

# ------------------------------------------------------------
# 6. Validaciones
# ------------------------------------------------------------

assert len(demanda_horaria_51) == N_ORIGINAL

assert (
    demanda_horaria_51[
        "hora_solicitud_analisis"
    ].notna().all()
), "Existen horas faltantes."

assert (
    demanda_horaria_51[
        "hora_solicitud_analisis"
    ].between(0, 23).all()
), "Existen horas fuera del rango 0-23."

assert (
    demanda_horaria_51["dia_semana_num"]
    .between(0, 6).all()
), "Existen días de la semana no válidos."

# Control cruzado con la fecha de análisis original
diferencias_fecha = (
    demanda_horaria_51[
        "fecha_solicitud_analisis"
    ].dt.normalize()
    !=
    demanda_horaria_51[
        "fecha_analisis"
    ].dt.normalize()
).sum()

print("\nCONTROL DE FECHAS")
print(
    "Diferencias entre fecha de solicitud "
    f"y fecha de análisis: {diferencias_fecha:,}"
)

assert diferencias_fecha == 0, (
    "Existen discrepancias entre la fecha analítica "
    "y la fecha de solicitud."
)

print("\nVALIDACIÓN COMPLETADA")
print(f"Registros conservados: {len(demanda_horaria_51):,}")
print("Días de semana preparados: OK")
print("Horas de solicitud preparadas: OK")
print("Base analítica independiente: OK")
print("=" * 70)

======================================================================
5.1.7.1. PREPARACIÓN TEMPORAL DE LA DEMANDA
======================================================================

               indicador  resultado
0      Turnos originales     883076
1      Turnos analíticos     883076
2       Fechas faltantes          0
3        Horas faltantes          0
4   Horas fuera de rango          0
5  Días no identificados          0

CONTROL DE FECHAS
Diferencias entre fecha de solicitud y fecha de análisis: 0

VALIDACIÓN COMPLETADA
Registros conservados: 883,076
Días de semana preparados: OK
Horas de solicitud preparadas: OK
Base analítica independiente: OK
======================================================================

In [85]:

# ============================================================
# 5.1.7.2. DEMANDA POR DÍA DE LA SEMANA
# ============================================================

print("=" * 70)
print("5.1.7.2. DEMANDA POR DÍA DE LA SEMANA")
print("=" * 70)

# ------------------------------------------------------------
# 1. Agregación de turnos
# ------------------------------------------------------------

demanda_dia_517 = (
    demanda_horaria_51
    .groupby(
        ["dia_semana_num", "dia_semana"],
        dropna=False
    )
    .agg(
        turnos=("fecha_solicitud_analisis", "size"),
        dias_observados=(
            "fecha_solicitud_analisis",
            "nunique"
        )
    )
    .reset_index()
    .sort_values("dia_semana_num")
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 2. Indicadores de distribución
# ------------------------------------------------------------

demanda_dia_517["participacion_pct"] = (
    demanda_dia_517["turnos"]
    / N_ORIGINAL * 100
)

demanda_dia_517["promedio_por_dia_observado"] = (
    demanda_dia_517["turnos"]
    / demanda_dia_517["dias_observados"]
)

# ------------------------------------------------------------
# 3. Presentación
# ------------------------------------------------------------

display(
    demanda_dia_517.round({
        "participacion_pct": 2,
        "promedio_por_dia_observado": 2
    })
)

# ------------------------------------------------------------
# 4. Controles de integridad
# ------------------------------------------------------------

assert demanda_dia_517["turnos"].sum() == N_ORIGINAL

assert np.isclose(
    demanda_dia_517["participacion_pct"].sum(),
    100,
    atol=1e-8
)

assert (
    demanda_dia_517["dias_observados"] > 0
).all()

print("\nRESUMEN")

mayor_volumen = demanda_dia_517.loc[
    demanda_dia_517["turnos"].idxmax()
]

mayor_intensidad = demanda_dia_517.loc[
    demanda_dia_517[
        "promedio_por_dia_observado"
    ].idxmax()
]

print(
    "Día con mayor volumen acumulado: "
    f"{mayor_volumen['dia_semana']}"
)

print(
    "Día con mayor promedio por día observado: "
    f"{mayor_intensidad['dia_semana']}"
)

print(f"Turnos conciliados: {N_ORIGINAL:,}")
print("Integridad: OK")
print("=" * 70)

======================================================================
5.1.7.2. DEMANDA POR DÍA DE LA SEMANA
======================================================================

,dia_semana_num,dia_semana,turnos,dias_observados,participacion_pct,promedio_por_dia_observado
0,0,Lunes,134787,30,15.26,4492.90
1,1,Martes,170299,38,19.28,4481.55
2,2,Miércoles,153055,35,17.33,4373.00
3,3,Jueves,149413,36,16.92,4150.36
4,4,Viernes,156265,36,17.70,4340.69
5,5,Sábado,119046,36,13.48,3306.83
6,6,Domingo,211,1,0.02,211.00

RESUMEN
Día con mayor volumen acumulado: Martes
Día con mayor promedio por día observado: Lunes
Turnos conciliados: 883,076
Integridad: OK
======================================================================

In [86]:

# ============================================================
# 5.1.7.3. DISTRIBUCIÓN POR HORA DE SOLICITUD
# ============================================================

print("=" * 70)
print("5.1.7.3. DISTRIBUCIÓN HORARIA DE LA DEMANDA")
print("=" * 70)

# 1. Agregación por hora

demanda_hora_517 = (
    demanda_horaria_51
    .groupby("hora_solicitud_analisis", dropna=False)
    .agg(
        turnos=("fecha_solicitud_analisis", "size"),
        dias_observados=(
            "fecha_solicitud_analisis", "nunique"
        )
    )
    .reset_index()
    .sort_values("hora_solicitud_analisis")
    .reset_index(drop=True)
)

# 2. Indicadores

demanda_hora_517["participacion_pct"] = (
    demanda_hora_517["turnos"] / N_ORIGINAL * 100
)

demanda_hora_517["promedio_por_dia_observado"] = (
    demanda_hora_517["turnos"]
    / demanda_hora_517["dias_observados"]
)

demanda_hora_517["participacion_acumulada_pct"] = (
    demanda_hora_517["participacion_pct"].cumsum()
)

demanda_hora_517["franja_horaria"] = (
    demanda_hora_517["hora_solicitud_analisis"]
    .map(lambda h: f"{int(h):02d}:00-{int(h):02d}:59")
)

# 3. Presentación

display(
    demanda_hora_517[
        [
            "hora_solicitud_analisis",
            "franja_horaria",
            "turnos",
            "dias_observados",
            "participacion_pct",
            "promedio_por_dia_observado",
            "participacion_acumulada_pct"
        ]
    ].round(2)
)

# 4. Horas de mayor demanda

top_horas_517 = (
    demanda_hora_517
    .sort_values("turnos", ascending=False)
    .head(5)
)

print("\nCINCO FRANJAS CON MAYOR VOLUMEN")
display(
    top_horas_517[
        [
            "franja_horaria",
            "turnos",
            "participacion_pct",
            "promedio_por_dia_observado"
        ]
    ].round(2)
)

# 5. Conciliación

assert demanda_hora_517["turnos"].sum() == N_ORIGINAL

assert np.isclose(
    demanda_hora_517["participacion_pct"].sum(),
    100,
    atol=1e-8
)

assert demanda_hora_517[
    "hora_solicitud_analisis"
].between(0, 23).all()

assert demanda_hora_517["dias_observados"].gt(0).all()

# 6. Resumen ejecutivo

hora_pico = demanda_hora_517.loc[
    demanda_hora_517["turnos"].idxmax()
]

concentracion_top5 = (
    top_horas_517["turnos"].sum()
    / N_ORIGINAL * 100
)

print("\nRESUMEN")
print(f"Turnos conciliados: {N_ORIGINAL:,}")
print(
    "Hora de mayor volumen: "
    f"{hora_pico['franja_horaria']}"
)
print(
    "Turnos en hora pico: "
    f"{hora_pico['turnos']:,}"
)
print(
    "Participación de las cinco horas principales: "
    f"{concentracion_top5:.2f}%"
)
print("Integridad horaria: OK")
print("=" * 70)

======================================================================
5.1.7.3. DISTRIBUCIÓN HORARIA DE LA DEMANDA
======================================================================

,hora_solicitud_analisis,franja_horaria,turnos,dias_observados,participacion_pct,promedio_por_dia_observado,participacion_acumulada_pct
0,6,06:00-06:59,2,2,0.00,1.00,0.00
1,7,07:00-07:59,11153,176,1.26,63.37,1.26
2,8,08:00-08:59,42362,211,4.80,200.77,6.06
3,9,09:00-09:59,78527,211,8.89,372.17,14.95
4,10,10:00-10:59,101736,211,11.52,482.16,26.47
5,11,11:00-11:59,106321,211,12.04,503.89,38.51
6,12,12:00-12:59,92914,211,10.52,440.35,49.03
7,13,13:00-13:59,83732,211,9.48,396.83,58.52
8,14,14:00-14:59,86287,211,9.77,408.94,68.29
9,15,15:00-15:59,101588,211,11.50,481.46,79.79
10,16,16:00-16:59,93411,210,10.58,444.81,90.37
11,17,17:00-17:59,56995,177,6.45,322.01,96.82
12,18,18:00-18:59,25842,174,2.93,148.52,99.75
13,19,19:00-19:59,2204,166,0.25,13.28,100.00
14,20,20:00-20:59,2,1,0.00,2.00,100.00

CINCO FRANJAS CON MAYOR VOLUMEN

   franja_horaria  turnos  participacion_pct  promedio_por_dia_observado
5     11:00-11:59  106321              12.04                      503.89
4     10:00-10:59  101736              11.52                      482.16
9     15:00-15:59  101588              11.50                      481.46
10    16:00-16:59   93411              10.58                      444.81
6     12:00-12:59   92914              10.52                      440.35

RESUMEN
Turnos conciliados: 883,076
Hora de mayor volumen: 11:00-11:59
Turnos en hora pico: 106,321
Participación de las cinco horas principales: 56.16%
Integridad horaria: OK
======================================================================

In [87]:

# ============================================================
# 5.1.7.4. MATRIZ DIA DE SEMANA X HORA DE SOLICITUD
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.4. MATRIZ TEMPORAL DE LA DEMANDA")
print("=" * 70)

# ------------------------------------------------------------
# 1. PREPARACION INDEPENDIENTE
# ------------------------------------------------------------

matriz_base_517 = demanda_horaria_51.copy()

columnas_requeridas = [
    "fecha_solicitud_analisis",
    "dia_semana_num",
    "dia_semana",
    "hora_solicitud_analisis"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in matriz_base_517.columns
]

assert not faltantes, f"Columnas faltantes: {faltantes}"

assert len(matriz_base_517) == N_ORIGINAL

assert matriz_base_517[columnas_requeridas].notna().all().all()

assert matriz_base_517["dia_semana_num"].between(0, 6).all()

assert matriz_base_517[
    "hora_solicitud_analisis"
].between(0, 23).all()

# ------------------------------------------------------------
# 2. AGREGACION POR DIA Y HORA
# ------------------------------------------------------------

demanda_dia_hora_517 = (
    matriz_base_517
    .groupby(
        [
            "dia_semana_num",
            "dia_semana",
            "hora_solicitud_analisis"
        ],
        as_index=False,
        dropna=False
    )
    .agg(
        turnos=("fecha_solicitud_analisis", "size"),
        fechas_observadas=(
            "fecha_solicitud_analisis", "nunique"
        )
    )
)

demanda_dia_hora_517["participacion_pct"] = (
    demanda_dia_hora_517["turnos"]
    / N_ORIGINAL * 100
)

demanda_dia_hora_517["promedio_por_fecha_observada"] = (
    demanda_dia_hora_517["turnos"]
    / demanda_dia_hora_517["fechas_observadas"]
)

demanda_dia_hora_517["franja_horaria"] = (
    demanda_dia_hora_517["hora_solicitud_analisis"]
    .map(lambda h: f"{int(h):02d}:00-{int(h):02d}:59")
)

demanda_dia_hora_517 = (
    demanda_dia_hora_517
    .sort_values(
        ["dia_semana_num", "hora_solicitud_analisis"]
    )
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 3. MATRIZ DE TURNOS ACUMULADOS
# ------------------------------------------------------------

matriz_turnos_517 = (
    demanda_dia_hora_517
    .pivot(
        index="dia_semana",
        columns="hora_solicitud_analisis",
        values="turnos"
    )
    .fillna(0)
    .astype(int)
)

orden_dias_517 = [
    "Lunes", "Martes", "Miércoles",
    "Jueves", "Viernes", "Sábado", "Domingo"
]

matriz_turnos_517 = matriz_turnos_517.reindex(
    orden_dias_517,
    fill_value=0
)

print("\n1. MATRIZ DE TURNOS ACUMULADOS")
display(matriz_turnos_517)

# ------------------------------------------------------------
# 4. MATRIZ DE INTENSIDAD PROMEDIO
# ------------------------------------------------------------

# Denominador: todas las fechas con registros del dia
# correspondiente, incluidas aquellas sin turnos
# en una hora especifica.

fechas_por_dia_517 = (
    matriz_base_517
    .groupby("dia_semana_num")[
        "fecha_solicitud_analisis"
    ]
    .nunique()
)

demanda_dia_hora_517["fechas_del_dia_observadas"] = (
    demanda_dia_hora_517["dia_semana_num"]
    .map(fechas_por_dia_517)
)

demanda_dia_hora_517["promedio_por_dia_observado"] = (
    demanda_dia_hora_517["turnos"]
    / demanda_dia_hora_517["fechas_del_dia_observadas"]
)

matriz_promedio_517 = (
    demanda_dia_hora_517
    .pivot(
        index="dia_semana",
        columns="hora_solicitud_analisis",
        values="promedio_por_dia_observado"
    )
    .reindex(
        index=orden_dias_517,
        columns=matriz_turnos_517.columns
    )
    .fillna(0)
)

print("\n2. MATRIZ DE PROMEDIO POR DIA OBSERVADO")
display(matriz_promedio_517.round(2))

# ------------------------------------------------------------
# 5. PRINCIPALES COMBINACIONES DIA-HORA
# ------------------------------------------------------------

top_combinaciones_517 = (
    demanda_dia_hora_517
    .sort_values(
        "turnos",
        ascending=False
    )
    .head(15)
)

print("\n3. QUINCE COMBINACIONES CON MAYOR DEMANDA")
display(
    top_combinaciones_517[
        [
            "dia_semana",
            "franja_horaria",
            "turnos",
            "fechas_del_dia_observadas",
            "participacion_pct",
            "promedio_por_dia_observado"
        ]
    ].round(2)
)

# ------------------------------------------------------------
# 6. CONTROLES DE INTEGRIDAD
# ------------------------------------------------------------

assert demanda_dia_hora_517["turnos"].sum() == N_ORIGINAL

assert matriz_turnos_517.to_numpy().sum() == N_ORIGINAL

assert np.isclose(
    demanda_dia_hora_517["participacion_pct"].sum(),
    100,
    atol=1e-8
)

# Conciliacion contra agregados previamente calculados

control_dia_517 = (
    demanda_dia_hora_517
    .groupby("dia_semana_num")["turnos"]
    .sum()
    .sort_index()
)

control_hora_517 = (
    demanda_dia_hora_517
    .groupby("hora_solicitud_analisis")["turnos"]
    .sum()
    .sort_index()
)

assert control_dia_517.sum() == N_ORIGINAL
assert control_hora_517.sum() == N_ORIGINAL

assert control_hora_517.equals(
    demanda_hora_517
    .set_index("hora_solicitud_analisis")["turnos"]
    .sort_index()
    .rename_axis("hora_solicitud_analisis")
)

# ------------------------------------------------------------
# 7. RESUMEN
# ------------------------------------------------------------

pico_517 = top_combinaciones_517.iloc[0]

print("\nRESUMEN OPERATIVO")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Combinaciones dia-hora observadas: "
    f"{len(demanda_dia_hora_517):,}"
)
print(
    "Mayor volumen: "
    f"{pico_517['dia_semana']} - "
    f"{pico_517['franja_horaria']}"
)
print(f"Turnos en combinacion pico: {pico_517['turnos']:,}")
print("Conciliacion por dia: OK")
print("Conciliacion por hora: OK")
print("Integridad general: OK")
print("=" * 70)

======================================================================
5.1.7.4. MATRIZ TEMPORAL DE LA DEMANDA
======================================================================

1. MATRIZ DE TURNOS ACUMULADOS

hora_solicitud_analisis,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
dia_semana,,,,,,,,,,,,,,,
Lunes,0,1697,5641,11865,14113,14723,12614,11745,13901,16670,16370,10219,4786,443,0
Martes,1,2634,7671,15116,17827,18798,16132,15149,17047,20282,20289,12809,5958,584,2
Miércoles,1,2126,6926,14020,16238,16561,14382,13574,15496,18870,18301,10931,5206,423,0
Jueves,0,2162,6639,13527,15526,16188,14073,13495,15383,18668,17764,10814,4771,403,0
Viernes,0,2530,7168,14105,15700,16492,14451,13730,15367,19371,19662,12217,5121,351,0
Sábado,0,4,8317,9892,22296,23512,21222,16011,9063,7699,1025,5,0,0,0
Domingo,0,0,0,2,36,47,40,28,30,28,0,0,0,0,0

2. MATRIZ DE PROMEDIO POR DIA OBSERVADO

hora_solicitud_analisis,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
dia_semana,,,,,,,,,,,,,,,
Lunes,0.00,56.57,188.03,395.50,470.43,490.77,420.47,391.50,463.37,555.67,545.67,340.63,159.53,14.77,0.00
Martes,0.03,69.32,201.87,397.79,469.13,494.68,424.53,398.66,448.61,533.74,533.92,337.08,156.79,15.37,0.05
Miércoles,0.03,60.74,197.89,400.57,463.94,473.17,410.91,387.83,442.74,539.14,522.89,312.31,148.74,12.09,0.00
Jueves,0.00,60.06,184.42,375.75,431.28,449.67,390.92,374.86,427.31,518.56,493.44,300.39,132.53,11.19,0.00
Viernes,0.00,70.28,199.11,391.81,436.11,458.11,401.42,381.39,426.86,538.08,546.17,339.36,142.25,9.75,0.00
Sábado,0.00,0.11,231.03,274.78,619.33,653.11,589.50,444.75,251.75,213.86,28.47,0.14,0.00,0.00,0.00
Domingo,0.00,0.00,0.00,2.00,36.00,47.00,40.00,28.00,30.00,28.00,0.00,0.00,0.00,0.00,0.00

3. QUINCE COMBINACIONES CON MAYOR DEMANDA

,dia_semana,franja_horaria,turnos,fechas_del_dia_observadas,participacion_pct,promedio_por_dia_observado
72,Sábado,11:00-11:59,23512,36,2.66,653.11
71,Sábado,10:00-10:59,22296,36,2.52,619.33
73,Sábado,12:00-12:59,21222,36,2.40,589.50
23,Martes,16:00-16:59,20289,38,2.30,533.92
22,Martes,15:00-15:59,20282,38,2.30,533.74
64,Viernes,16:00-16:59,19662,36,2.23,546.17
63,Viernes,15:00-15:59,19371,36,2.19,538.08
37,Miércoles,15:00-15:59,18870,35,2.14,539.14
18,Martes,11:00-11:59,18798,38,2.13,494.68
50,Jueves,15:00-15:59,18668,36,2.11,518.56
38,Miércoles,16:00-16:59,18301,35,2.07,522.89
17,Martes,10:00-10:59,17827,38,2.02,469.13
51,Jueves,16:00-16:59,17764,36,2.01,493.44
21,Martes,14:00-14:59,17047,38,1.93,448.61
8,Lunes,15:00-15:59,16670,30,1.89,555.67

RESUMEN OPERATIVO
Turnos originales: 883,076
Combinaciones dia-hora observadas: 86
Mayor volumen: Sábado - 11:00-11:59
Turnos en combinacion pico: 23,512
Conciliacion por dia: OK
Conciliacion por hora: OK
Integridad general: OK
======================================================================

In [88]:

# ============================================================
# 5.1.7.5. DEMANDA POR SEDE, DIA Y HORA
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.5. DEMANDA POR SEDE, DIA Y HORA")
print("=" * 70)

# ------------------------------------------------------------
# 1. BASE ANALITICA INDEPENDIENTE
# ------------------------------------------------------------

base_sede_hora_517 = demanda_horaria_51.copy()

columnas_5175 = [
    "Sede",
    "fecha_solicitud_analisis",
    "dia_semana_num",
    "dia_semana",
    "hora_solicitud_analisis"
]

faltantes_5175 = [
    c for c in columnas_5175
    if c not in base_sede_hora_517.columns
]

assert not faltantes_5175, (
    f"Columnas faltantes: {faltantes_5175}"
)

assert len(base_sede_hora_517) == N_ORIGINAL

assert base_sede_hora_517[
    columnas_5175
].notna().all().all()

# ------------------------------------------------------------
# 2. AGREGACION POR SEDE, DIA Y HORA
# ------------------------------------------------------------

demanda_sede_dia_hora_517 = (
    base_sede_hora_517
    .groupby(
        [
            "Sede",
            "dia_semana_num",
            "dia_semana",
            "hora_solicitud_analisis"
        ],
        as_index=False
    )
    .agg(
        turnos=("fecha_solicitud_analisis", "size"),
        fechas_con_turnos_en_franja=(
            "fecha_solicitud_analisis", "nunique"
        )
    )
)

# ------------------------------------------------------------
# 3. DENOMINADORES COMPARABLES
# ------------------------------------------------------------

# Fechas observadas en cada sede y dia de semana.
# Incluye fechas sin solicitudes en una hora especifica.

fechas_sede_dia_517 = (
    base_sede_hora_517
    .groupby(
        ["Sede", "dia_semana_num"],
        as_index=False
    )
    .agg(
        fechas_observadas_sede_dia=(
            "fecha_solicitud_analisis", "nunique"
        )
    )
)

demanda_sede_dia_hora_517 = (
    demanda_sede_dia_hora_517
    .merge(
        fechas_sede_dia_517,
        on=["Sede", "dia_semana_num"],
        how="left",
        validate="many_to_one"
    )
)

demanda_sede_dia_hora_517[
    "promedio_por_fecha_observada"
] = (
    demanda_sede_dia_hora_517["turnos"]
    / demanda_sede_dia_hora_517[
        "fechas_observadas_sede_dia"
    ]
)

# Participacion en el total institucional

demanda_sede_dia_hora_517[
    "participacion_institucional_pct"
] = (
    demanda_sede_dia_hora_517["turnos"]
    / N_ORIGINAL * 100
)

# Participacion dentro de cada sede

totales_sede_517 = (
    base_sede_hora_517
    .groupby("Sede")
    .size()
    .rename("total_turnos_sede")
    .reset_index()
)

demanda_sede_dia_hora_517 = (
    demanda_sede_dia_hora_517
    .merge(
        totales_sede_517,
        on="Sede",
        how="left",
        validate="many_to_one"
    )
)

demanda_sede_dia_hora_517[
    "participacion_sede_pct"
] = (
    demanda_sede_dia_hora_517["turnos"]
    / demanda_sede_dia_hora_517["total_turnos_sede"]
    * 100
)

demanda_sede_dia_hora_517["franja_horaria"] = (
    demanda_sede_dia_hora_517[
        "hora_solicitud_analisis"
    ].map(
        lambda h: f"{int(h):02d}:00-{int(h):02d}:59"
    )
)

# ------------------------------------------------------------
# 4. TOP 20 DE MAYOR VOLUMEN
# ------------------------------------------------------------

top_sede_dia_hora_517 = (
    demanda_sede_dia_hora_517
    .sort_values(
        "turnos",
        ascending=False
    )
    .head(20)
)

print("\n1. MAYORES VOLUMENES POR SEDE, DIA Y HORA")

display(
    top_sede_dia_hora_517[
        [
            "Sede",
            "dia_semana",
            "franja_horaria",
            "turnos",
            "fechas_observadas_sede_dia",
            "promedio_por_fecha_observada",
            "participacion_sede_pct"
        ]
    ].round(2)
)

# ------------------------------------------------------------
# 5. HORA DE MAYOR DEMANDA POR SEDE
# ------------------------------------------------------------

# Identifica el pico acumulado de cada sede.
# No equivale a la maxima carga en una fecha concreta.

picos_por_sede_517 = (
    demanda_sede_dia_hora_517
    .sort_values(
        [
            "Sede",
            "turnos",
            "dia_semana_num",
            "hora_solicitud_analisis"
        ],
        ascending=[True, False, True, True]
    )
    .drop_duplicates(subset=["Sede"])
    .sort_values("turnos", ascending=False)
    .reset_index(drop=True)
)

print("\n2. COMBINACION DE MAYOR VOLUMEN POR SEDE")

display(
    picos_por_sede_517[
        [
            "Sede",
            "dia_semana",
            "franja_horaria",
            "turnos",
            "promedio_por_fecha_observada",
            "participacion_sede_pct"
        ]
    ].round(2)
)

# ------------------------------------------------------------
# 6. CONTROLES DE INTEGRIDAD
# ------------------------------------------------------------

assert (
    demanda_sede_dia_hora_517["turnos"].sum()
    == N_ORIGINAL
)

assert (
    demanda_sede_dia_hora_517[
        "fechas_observadas_sede_dia"
    ].gt(0).all()
)

assert (
    demanda_sede_dia_hora_517[
        "fechas_con_turnos_en_franja"
    ]
    <= demanda_sede_dia_hora_517[
        "fechas_observadas_sede_dia"
    ]
).all()

assert np.isclose(
    demanda_sede_dia_hora_517[
        "participacion_institucional_pct"
    ].sum(),
    100,
    atol=1e-8
)

# Conciliacion contra los totales por sede

control_sedes_517 = (
    demanda_sede_dia_hora_517
    .groupby("Sede")["turnos"]
    .sum()
    .sort_index()
)

original_sedes_517 = (
    base_sede_hora_517
    .groupby("Sede")
    .size()
    .sort_index()
)

pd.testing.assert_series_equal(
    control_sedes_517,
    original_sedes_517,
    check_names=False
)

# Conciliacion contra la matriz dia-hora

control_dia_hora_517 = (
    demanda_sede_dia_hora_517
    .groupby(
        ["dia_semana_num", "hora_solicitud_analisis"]
    )["turnos"]
    .sum()
    .sort_index()
)

referencia_dia_hora_517 = (
    demanda_dia_hora_517
    .groupby(
        ["dia_semana_num", "hora_solicitud_analisis"]
    )["turnos"]
    .sum()
    .sort_index()
)

pd.testing.assert_series_equal(
    control_dia_hora_517,
    referencia_dia_hora_517,
    check_names=False
)

# ------------------------------------------------------------
# 7. RESUMEN FINAL
# ------------------------------------------------------------

print("\nVALIDACION FINAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Turnos agregados: "
    f"{demanda_sede_dia_hora_517['turnos'].sum():,}"
)
print(
    "Sedes analizadas: "
    f"{demanda_sede_dia_hora_517['Sede'].nunique()}"
)
print(
    "Combinaciones sede-dia-hora: "
    f"{len(demanda_sede_dia_hora_517):,}"
)
print("Conciliacion por sede: OK")
print("Conciliacion por dia y hora: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.7.5. DEMANDA POR SEDE, DIA Y HORA
======================================================================

1. MAYORES VOLUMENES POR SEDE, DIA Y HORA

,Sede,dia_semana,franja_horaria,turnos,fechas_observadas_sede_dia,promedio_por_fecha_observada,participacion_sede_pct
61,Calle 26,Sábado,11:00-11:59,4341,36,120.58,2.76
62,Calle 26,Sábado,12:00-12:59,4136,36,114.89,2.63
60,Calle 26,Sábado,10:00-10:59,3637,36,101.03,2.32
20,Calle 26,Martes,15:00-15:59,3599,38,94.71,2.29
16,Calle 26,Martes,11:00-11:59,3457,38,90.97,2.20
63,Calle 26,Sábado,13:00-13:59,3431,36,95.31,2.18
55,Calle 26,Viernes,15:00-15:59,3414,36,94.83,2.17
21,Calle 26,Martes,16:00-16:59,3369,38,88.66,2.15
56,Calle 26,Viernes,16:00-16:59,3367,36,93.53,2.14
19,Calle 26,Martes,14:00-14:59,3261,38,85.82,2.08
43,Calle 26,Jueves,15:00-15:59,3202,36,88.94,2.04
15,Calle 26,Martes,10:00-10:59,3186,38,83.84,2.03
32,Calle 26,Miércoles,15:00-15:59,3173,35,90.66,2.02
27,Calle 26,Miércoles,10:00-10:59,3138,35,89.66,2.00
17,Calle 26,Martes,12:00-12:59,3132,38,82.42,1.99
51,Calle 26,Viernes,11:00-11:59,3099,36,86.08,1.97
39,Calle 26,Jueves,11:00-11:59,3096,36,86.00,1.97
50,Calle 26,Viernes,10:00-10:59,3091,36,85.86,1.97
28,Calle 26,Miércoles,11:00-11:59,3084,35,88.11,1.96
18,Calle 26,Martes,13:00-13:59,3073,38,80.87,1.96

2. COMBINACION DE MAYOR VOLUMEN POR SEDE

,Sede,dia_semana,franja_horaria,turnos,promedio_por_fecha_observada,participacion_sede_pct
0,Calle 26,Sábado,11:00-11:59,4341,120.58,2.76
1,Tintal plaza,Sábado,10:00-10:59,3045,87.00,2.71
2,Soacha,Sábado,10:00-10:59,2603,72.31,2.80
3,Suba,Sábado,11:00-11:59,2230,69.69,2.73
4,Centro mayor,Sábado,14:00-14:59,2162,90.08,2.73
5,Unicentro de occidente,Sábado,10:00-10:59,1825,50.69,3.24
6,Usaquen,Sábado,11:00-11:59,1579,43.86,2.86
7,Funza,Viernes,16:00-16:59,1424,39.56,2.65
8,Fusagasuga,Viernes,16:00-16:59,1380,39.43,3.05
9,Calle 63,Sábado,11:00-11:59,1359,37.75,2.85
10,Girardot,Martes,16:00-16:59,1236,32.53,2.61
11,Santa librada,Sábado,11:00-11:59,1156,32.11,2.83
12,La mesa,Martes,11:00-11:59,333,9.00,2.50

VALIDACION FINAL
Turnos originales: 883,076
Turnos agregados: 883,076
Sedes analizadas: 13
Combinaciones sede-dia-hora: 828
Conciliacion por sede: OK
Conciliacion por dia y hora: OK
Base original conservada: OK
======================================================================

In [90]:
# Identificar los DataFrames disponibles en el notebook

import pandas as pd

bases_disponibles = []

for nombre, objeto in globals().copy().items():
    if isinstance(objeto, pd.DataFrame):
        bases_disponibles.append({
            "variable": nombre,
            "registros": len(objeto),
            "columnas": len(objeto.columns)
        })

df_bases = pd.DataFrame(bases_disponibles)

display(
    df_bases.sort_values(
        ["registros", "variable"],
        ascending=[False, True]
    )
)

                variable  registros  columnas
0             digiturnos     883080        22
77    auditoria_temporal     883076         7
70                  base     883076        62
87              base_478     883076        57
66            base_final     883076        56
..                   ...        ...       ...
81       resumen_general          2         3
39       resumen_calidad          1         5
44      resumen_refinado          1         3
16  afiliados_duplicados          0         7
74     grupos_duplicados          0        12

[125 rows x 3 columns]

In [91]:
# Mostrar los DataFrames que tienen 883.076 registros

for nombre, objeto in globals().copy().items():
    if isinstance(objeto, pd.DataFrame) and len(objeto) == 883076:
        print("\n" + "=" * 60)
        print("VARIABLE:", nombre)
        print("REGISTROS:", len(objeto))
        print("COLUMNAS:")
        print(objeto.columns.tolist())

============================================================
VARIABLE: digiturnos_tiempos
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo']

============================================================
VARIABLE: digiturnos_integrados
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion']

============================================================
VARIABLE: digiturnos_clasificados
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar']

============================================================
VARIABLE: digiturnos_enriquecidos
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', 'id_titular_cruce', 'Categoria_titular', 'Segmento_poblacional_titular', 'Piramide1_titular', 'Piramide2_titular', '_cruce_titular', 'Categoria_final', 'Segmento_poblacional_final', 'Piramide1_final', 'Piramide2_final']

============================================================
VARIABLE: digiturnos_final
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada']

============================================================
VARIABLE: base_original
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar']

============================================================
VARIABLE: base_final
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada']

============================================================
VARIABLE: base_origen
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada']

============================================================
VARIABLE: digiturnos_auditoria
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada']

============================================================
VARIABLE: base
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'espera_auditada', 'atencion_auditada', 'grupo_espera', 'coincidencia_exacta', 'diferencia_segundos', 'hora_solicitud_auditada']

============================================================
VARIABLE: matriz_informacion
REGISTROS: 883076
COLUMNAS:
['Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2']

============================================================
VARIABLE: auditoria_temporal
REGISTROS: 883076
COLUMNAS:
['ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'espera_calculada', 'atencion_calculada']

============================================================
VARIABLE: base_478
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'espera_cero_auditada']

============================================================
VARIABLE: demanda_51
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'fecha_analisis', 'periodo_mes', 'anio', 'mes_numero']

============================================================
VARIABLE: demanda_temporal_51
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'fecha_analisis', 'periodo_mes', 'anio', 'mes_numero', 'mes']

============================================================
VARIABLE: demanda_horaria_51
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'fecha_analisis', 'periodo_mes', 'anio', 'mes_numero', 'mes', 'hora_solicitud_analisis', 'fecha_solicitud_analisis', 'dia_semana_num', 'dia_semana', 'franja_horaria']

============================================================
VARIABLE: matriz_base_517
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'fecha_analisis', 'periodo_mes', 'anio', 'mes_numero', 'mes', 'hora_solicitud_analisis', 'fecha_solicitud_analisis', 'dia_semana_num', 'dia_semana', 'franja_horaria']

============================================================
VARIABLE: base_sede_hora_517
REGISTROS: 883076
COLUMNAS:
['Sede', 'UES', 'Clasifiacion', 'Usuario_receptor', 'Tipo_servicio', 'SUBSERVICIO_HOMOLOGADO', 'Fecha_Servico', 'Hora_solicitud_Servicio', 'Hora_llamado__Servicio', 'Hora_finalizado_Servicio', 'Identificacion_Cliente', 'Tipo_Oficina', 'id_cliente', 'fecha_servicio', 'ts_solicitud', 'ts_llamado', 'ts_finalizacion', 'tiempo_espera_min', 'tiempo_atencion_min', 'tiempo_total_min', 'flag_tiempo_valido', 'estado_calidad_tiempo', 'id_normalizado', 'Categoria', 'Segmento_poblacional', 'Piramide1', 'Piramide2', 'registros_fuente', 'calidad_perfil', '_cruce_afiliados', 'tipo_vinculacion', 'id_persona_cargo', 'n_titulares', 'id_afiliado_titular', 'estado_relacion', '_cruce_grupo_familiar', '_id_fila_control', 'id_titular_cruce', 'Categoria_recuperacion', 'Segmento_poblacional_recuperacion', 'Piramide1_recuperacion', 'Piramide2_recuperacion', '_cruce_recuperacion_final', 'Categoria_origen', 'fuente_Categoria', 'Segmento_poblacional_origen', 'fuente_Segmento_poblacional', 'Piramide1_origen', 'fuente_Piramide1', 'Piramide2_origen', 'fuente_Piramide2', 'n_atributos_poblacionales', 'perfil_poblacional_completo', 'perfil_poblacional_parcial', 'perfil_poblacional_sin_datos', 'flag_recuperacion_controlada', 'fecha_analisis', 'periodo_mes', 'anio', 'mes_numero', 'mes', 'hora_solicitud_analisis', 'fecha_solicitud_analisis', 'dia_semana_num', 'dia_semana', 'franja_horaria']

In [92]:
# ============================================================
# 5.1.7.6.1. PREPARACIÓN Y VALIDACIÓN
# ============================================================

import pandas as pd

print("=" * 70)
print("5.1.7.6.1. PREPARACIÓN Y VALIDACIÓN")
print("=" * 70)

# Base analítica independiente
demanda_5176 = base_sede_hora_517.copy(deep=True)

N_ORIGINAL = len(base_sede_hora_517)

# Control de integridad
assert len(demanda_5176) == N_ORIGINAL, (
    "ERROR: se modificó el número de registros"
)

assert N_ORIGINAL == 883076, (
    "ERROR: el total no coincide con la base validada"
)

# Verificación de variables
columnas_requeridas = [
    "Sede",
    "Tipo_servicio",
    "dia_semana",
    "dia_semana_num",
    "hora_solicitud_analisis"
]

columnas_faltantes = [
    col for col in columnas_requeridas
    if col not in demanda_5176.columns
]

print("\nVARIABLES REQUERIDAS")
print("Columnas faltantes:", columnas_faltantes)

if columnas_faltantes:
    raise ValueError(
        f"Faltan variables necesarias: {columnas_faltantes}"
    )

print("\nVALIDACIÓN")
print(f"Registros conservados: {len(demanda_5176):,}")
print("Integridad de registros: OK")
print("Variables requeridas: OK")
print("Base analítica independiente: OK")

======================================================================
5.1.7.6.1. PREPARACIÓN Y VALIDACIÓN
======================================================================

VARIABLES REQUERIDAS
Columnas faltantes: []

VALIDACIÓN
Registros conservados: 883,076
Integridad de registros: OK
Variables requeridas: OK
Base analítica independiente: OK

In [93]:
# ============================================================
# INVENTARIO DE VARIABLES PARA INTEGRACIÓN OPERATIVA
# ============================================================

palabras_clave = [
    "espera",
    "duracion",
    "tiempo",
    "minuto",
    "solicitud",
    "llamado",
    "finalizado",
    "fecha",
    "hora"
]

columnas_tiempos = [
    col for col in demanda_5176.columns
    if any(
        palabra in col.lower()
        for palabra in palabras_clave
    )
]

print("=" * 70)
print("VARIABLES DISPONIBLES PARA ANÁLISIS OPERATIVO")
print("=" * 70)

for columna in columnas_tiempos:
    print(
        f"{columna} | "
        f"Tipo: {demanda_5176[columna].dtype} | "
        f"Nulos: {demanda_5176[columna].isna().sum():,}"
    )

======================================================================
VARIABLES DISPONIBLES PARA ANÁLISIS OPERATIVO
======================================================================
Fecha_Servico | Tipo: str | Nulos: 0
Hora_solicitud_Servicio | Tipo: str | Nulos: 0
Hora_llamado__Servicio | Tipo: str | Nulos: 0
Hora_finalizado_Servicio | Tipo: str | Nulos: 0
fecha_servicio | Tipo: datetime64[us] | Nulos: 0
ts_solicitud | Tipo: datetime64[us] | Nulos: 0
ts_llamado | Tipo: datetime64[us] | Nulos: 0
tiempo_espera_min | Tipo: float64 | Nulos: 0
tiempo_atencion_min | Tipo: float64 | Nulos: 0
tiempo_total_min | Tipo: float64 | Nulos: 0
flag_tiempo_valido | Tipo: bool | Nulos: 0
estado_calidad_tiempo | Tipo: str | Nulos: 0
fecha_analisis | Tipo: datetime64[us] | Nulos: 0
hora_solicitud_analisis | Tipo: Int64 | Nulos: 0
fecha_solicitud_analisis | Tipo: datetime64[us] | Nulos: 0
franja_horaria | Tipo: str | Nulos: 0

In [94]:
# ============================================================
# 5.1.7.6.2. INTEGRACIÓN DE DEMANDA Y TIEMPOS DE ESPERA
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.2. INTEGRACIÓN OPERATIVA")
print("=" * 70)

# ------------------------------------------------------------
# 1. Base independiente
# ------------------------------------------------------------

operacion_5176 = demanda_5176.copy(deep=True)

N_ORIGINAL = len(demanda_5176)

# ------------------------------------------------------------
# 2. Verificación de variables
# ------------------------------------------------------------

variables = [
    "Sede",
    "Tipo_servicio",
    "dia_semana",
    "dia_semana_num",
    "hora_solicitud_analisis",
    "franja_horaria",
    "fecha_analisis",
    "tiempo_espera_min",
    "tiempo_atencion_min",
    "tiempo_total_min",
    "flag_tiempo_valido",
    "estado_calidad_tiempo"
]

faltantes = [
    c for c in variables
    if c not in operacion_5176.columns
]

if faltantes:
    raise ValueError(
        f"Variables faltantes: {faltantes}"
    )

# ------------------------------------------------------------
# 3. Validación de tiempos
# ------------------------------------------------------------

# No modificamos los tiempos originales.
# Creamos columnas independientes para el análisis.

operacion_5176["espera_valida_min"] = (
    operacion_5176["tiempo_espera_min"]
    .where(operacion_5176["flag_tiempo_valido"].eq(True))
)

operacion_5176["atencion_valida_min"] = (
    operacion_5176["tiempo_atencion_min"]
    .where(operacion_5176["flag_tiempo_valido"].eq(True))
)

operacion_5176["total_valido_min"] = (
    operacion_5176["tiempo_total_min"]
    .where(operacion_5176["flag_tiempo_valido"].eq(True))
)

# ------------------------------------------------------------
# 4. Indicadores de calidad
# ------------------------------------------------------------

n_validos = int(
    operacion_5176["flag_tiempo_valido"].sum()
)

n_invalidos = N_ORIGINAL - n_validos

pct_validos = (
    n_validos / N_ORIGINAL * 100
)

# ------------------------------------------------------------
# 5. Conciliación
# ------------------------------------------------------------

assert len(operacion_5176) == N_ORIGINAL

assert n_validos + n_invalidos == N_ORIGINAL

assert (
    operacion_5176.loc[
        ~operacion_5176["flag_tiempo_valido"],
        "espera_valida_min"
    ].isna().all()
)

# ------------------------------------------------------------
# 6. Resultados
# ------------------------------------------------------------

resumen_integracion = pd.DataFrame({
    "indicador": [
        "Turnos originales",
        "Turnos conservados",
        "Turnos con tiempos válidos",
        "Turnos con tiempos inválidos",
        "Porcentaje de tiempos válidos"
    ],
    "resultado": [
        N_ORIGINAL,
        len(operacion_5176),
        n_validos,
        n_invalidos,
        round(pct_validos, 2)
    ]
})

display(resumen_integracion)

print("\nESTADOS DE CALIDAD TEMPORAL")

display(
    operacion_5176[
        "estado_calidad_tiempo"
    ].value_counts(dropna=False)
)

print("\nVALIDACIÓN")
print(f"Registros conservados: {N_ORIGINAL:,}")
print("Conciliación de registros: OK")
print("Base original sin modificaciones: OK")
print("Base operativa independiente: OK")
print("=" * 70)

======================================================================
5.1.7.6.2. INTEGRACIÓN OPERATIVA
======================================================================

                       indicador  resultado
0              Turnos originales   883076.0
1             Turnos conservados   883076.0
2     Turnos con tiempos válidos   883076.0
3   Turnos con tiempos inválidos        0.0
4  Porcentaje de tiempos válidos      100.0

ESTADOS DE CALIDAD TEMPORAL

estado_calidad_tiempo
Válido    883076
Name: count, dtype: int64

VALIDACIÓN
Registros conservados: 883,076
Conciliación de registros: OK
Base original sin modificaciones: OK
Base operativa independiente: OK
======================================================================

In [95]:
# ============================================================
# 5.1.7.6.3. INDICADORES OPERATIVOS POR SEDE, DÍA Y HORA
# ============================================================

print("=" * 70)
print("5.1.7.6.3. DEMANDA Y TIEMPOS DE ESPERA")
print("=" * 70)

# ------------------------------------------------------------
# 1. Dimensiones de análisis
# ------------------------------------------------------------

dimensiones = [
    "Sede",
    "dia_semana_num",
    "dia_semana",
    "hora_solicitud_analisis",
    "franja_horaria"
]

# ------------------------------------------------------------
# 2. Agregación de indicadores
# ------------------------------------------------------------

indicadores_5176 = (
    operacion_5176
    .groupby(dimensiones, dropna=False)
    .agg(
        turnos=("Sede", "size"),

        turnos_validos=(
            "flag_tiempo_valido", "sum"
        ),

        fechas_observadas=(
            "fecha_analisis", "nunique"
        ),

        espera_promedio_min=(
            "espera_valida_min", "mean"
        ),

        espera_mediana_min=(
            "espera_valida_min", "median"
        ),

        espera_p90_min=(
            "espera_valida_min",
            lambda x: x.quantile(0.90)
        ),

        atencion_promedio_min=(
            "atencion_valida_min", "mean"
        ),

        tiempo_total_promedio_min=(
            "total_valido_min", "mean"
        )
    )
    .reset_index()
)

# ------------------------------------------------------------
# 3. Indicadores derivados
# ------------------------------------------------------------

indicadores_5176["turnos_invalidos"] = (
    indicadores_5176["turnos"]
    - indicadores_5176["turnos_validos"]
)

indicadores_5176["pct_tiempos_validos"] = (
    indicadores_5176["turnos_validos"]
    / indicadores_5176["turnos"]
    * 100
)

indicadores_5176["promedio_turnos_dia"] = (
    indicadores_5176["turnos"]
    / indicadores_5176["fechas_observadas"]
)

# Participación dentro de la sede
total_sede = (
    indicadores_5176
    .groupby("Sede")["turnos"]
    .transform("sum")
)

indicadores_5176["participacion_sede_pct"] = (
    indicadores_5176["turnos"]
    / total_sede
    * 100
)

# ------------------------------------------------------------
# 4. Ordenamiento
# ------------------------------------------------------------

indicadores_5176 = (
    indicadores_5176
    .sort_values(
        ["Sede", "dia_semana_num",
         "hora_solicitud_analisis"]
    )
    .reset_index(drop=True)
)

# ------------------------------------------------------------
# 5. Controles de integridad
# ------------------------------------------------------------

assert (
    indicadores_5176["turnos"].sum()
    == N_ORIGINAL
), "ERROR: los turnos no concilian"

assert (
    indicadores_5176["turnos_validos"].sum()
    == n_validos
), "ERROR: los tiempos válidos no concilian"

assert (
    indicadores_5176["turnos_invalidos"].sum()
    == n_invalidos
), "ERROR: los tiempos inválidos no concilian"

assert not indicadores_5176.duplicated(
    subset=dimensiones
).any(), "ERROR: dimensiones duplicadas"

# ------------------------------------------------------------
# 6. Presentación de resultados
# ------------------------------------------------------------

print("\n20 COMBINACIONES CON MAYOR DEMANDA")

columnas_mostrar = [
    "Sede",
    "dia_semana",
    "franja_horaria",
    "turnos",
    "promedio_turnos_dia",
    "espera_promedio_min",
    "espera_mediana_min",
    "espera_p90_min",
    "pct_tiempos_validos"
]

display(
    indicadores_5176
    .sort_values("turnos", ascending=False)
    [columnas_mostrar]
    .head(20)
    .round(2)
)

print("\nVALIDACIÓN FINAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    f"Turnos agregados: "
    f"{indicadores_5176['turnos'].sum():,}"
)
print(
    f"Combinaciones operativas: "
    f"{len(indicadores_5176):,}"
)
print("Conciliación de demanda: OK")
print("Conciliación de tiempos válidos: OK")
print("Integridad de dimensiones: OK")
print("=" * 70)

======================================================================
5.1.7.6.3. DEMANDA Y TIEMPOS DE ESPERA
======================================================================

20 COMBINACIONES CON MAYOR DEMANDA

,Sede,dia_semana,franja_horaria,turnos,promedio_turnos_dia,espera_promedio_min,espera_mediana_min,espera_p90_min,pct_tiempos_validos
61,Calle 26,Sábado,11:00-11:59,4341,120.58,7.56,1.13,23.88,100.0
62,Calle 26,Sábado,12:00-12:59,4136,114.89,7.86,0.77,26.33,100.0
60,Calle 26,Sábado,10:00-10:59,3637,101.03,5.39,0.72,17.00,100.0
20,Calle 26,Martes,15:00-15:59,3599,97.27,7.16,0.82,23.23,100.0
16,Calle 26,Martes,11:00-11:59,3457,93.43,6.85,0.88,21.98,100.0
63,Calle 26,Sábado,13:00-13:59,3431,95.31,4.43,0.00,15.38,100.0
55,Calle 26,Viernes,15:00-15:59,3414,94.83,7.19,1.02,21.75,100.0
21,Calle 26,Martes,16:00-16:59,3369,91.05,4.22,0.38,13.99,100.0
56,Calle 26,Viernes,16:00-16:59,3367,93.53,4.26,0.27,13.88,100.0
19,Calle 26,Martes,14:00-14:59,3261,88.14,8.74,1.97,27.13,100.0
43,Calle 26,Jueves,15:00-15:59,3202,88.94,6.02,0.83,18.95,100.0
15,Calle 26,Martes,10:00-10:59,3186,86.11,4.61,0.60,14.76,100.0
32,Calle 26,Miércoles,15:00-15:59,3173,90.66,6.37,0.67,20.78,100.0
27,Calle 26,Miércoles,10:00-10:59,3138,89.66,3.94,0.57,12.62,100.0
17,Calle 26,Martes,12:00-12:59,3132,84.65,7.99,1.27,23.74,100.0
51,Calle 26,Viernes,11:00-11:59,3099,86.08,5.85,0.70,18.67,100.0
39,Calle 26,Jueves,11:00-11:59,3096,86.00,6.53,0.68,20.62,100.0
50,Calle 26,Viernes,10:00-10:59,3091,85.86,4.22,0.58,14.05,100.0
28,Calle 26,Miércoles,11:00-11:59,3084,88.11,6.00,0.65,18.85,100.0
18,Calle 26,Martes,13:00-13:59,3073,83.05,7.29,1.03,22.68,100.0

VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos agregados: 883,076
Combinaciones operativas: 828
Conciliación de demanda: OK
Conciliación de tiempos válidos: OK
Integridad de dimensiones: OK
======================================================================

In [96]:
# ============================================================
# 5.1.7.6.4.1. CARACTERIZACIÓN DE LA ESPERA
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.1. CARACTERIZACIÓN DE LA ESPERA")
print("=" * 70)

# ------------------------------------------------------------
# 1. Base independiente
# ------------------------------------------------------------

esperas_51764 = operacion_5176.copy(deep=True)

N_ORIGINAL = len(operacion_5176)

# ------------------------------------------------------------
# 2. Variables requeridas
# ------------------------------------------------------------

requeridas = [
    "Sede",
    "dia_semana_num",
    "dia_semana",
    "hora_solicitud_analisis",
    "franja_horaria",
    "fecha_analisis",
    "tiempo_espera_min",
    "flag_tiempo_valido"
]

faltantes = [
    c for c in requeridas
    if c not in esperas_51764.columns
]

if faltantes:
    raise ValueError(f"Columnas faltantes: {faltantes}")

# ------------------------------------------------------------
# 3. Clasificación de la espera
# ------------------------------------------------------------

valido = esperas_51764["flag_tiempo_valido"].eq(True)

tiempo = pd.to_numeric(
    esperas_51764["tiempo_espera_min"],
    errors="coerce"
)

# Control adicional sobre la bandera existente
inconsistentes = (
    valido & (
        tiempo.isna()
        | ~np.isfinite(tiempo)
        | (tiempo < 0)
    )
)

if inconsistentes.any():
    raise ValueError(
        f"Existen {inconsistentes.sum():,} tiempos "
        "marcados como válidos que requieren revisión."
    )

esperas_51764["espera_cero"] = (
    valido & tiempo.eq(0)
)

esperas_51764["espera_positiva"] = (
    valido & tiempo.gt(0)
)

esperas_51764["espera_mayor_15"] = (
    valido & tiempo.gt(15)
)

esperas_51764["espera_mayor_30"] = (
    valido & tiempo.gt(30)
)

# ------------------------------------------------------------
# 4. Agrupación operativa
# ------------------------------------------------------------

dimensiones = [
    "Sede",
    "dia_semana_num",
    "dia_semana",
    "hora_solicitud_analisis",
    "franja_horaria"
]

caracterizacion_51764 = (
    esperas_51764
    .groupby(dimensiones, dropna=False)
    .agg(
        turnos=("Sede", "size"),
        tiempos_validos=("flag_tiempo_valido", "sum"),
        esperas_cero=("espera_cero", "sum"),
        esperas_positivas=("espera_positiva", "sum"),
        esperas_mayores_15=("espera_mayor_15", "sum"),
        esperas_mayores_30=("espera_mayor_30", "sum"),
        espera_promedio_min=("espera_valida_min", "mean"),
        espera_mediana_min=("espera_valida_min", "median"),
        espera_p90_min=(
            "espera_valida_min",
            lambda x: x.quantile(0.90)
        ),
        fechas_observadas=("fecha_analisis", "nunique")
    )
    .reset_index()
)

# ------------------------------------------------------------
# 5. Indicadores derivados
# ------------------------------------------------------------

denominador = caracterizacion_51764[
    "tiempos_validos"
].replace(0, np.nan)

caracterizacion_51764["pct_espera_cero"] = (
    caracterizacion_51764["esperas_cero"]
    / denominador * 100
)

caracterizacion_51764["pct_espera_mayor_15"] = (
    caracterizacion_51764["esperas_mayores_15"]
    / denominador * 100
)

caracterizacion_51764["pct_espera_mayor_30"] = (
    caracterizacion_51764["esperas_mayores_30"]
    / denominador * 100
)

caracterizacion_51764["promedio_turnos_dia"] = (
    caracterizacion_51764["turnos"]
    / caracterizacion_51764["fechas_observadas"]
)

# ------------------------------------------------------------
# 6. Validaciones
# ------------------------------------------------------------

assert (
    caracterizacion_51764["turnos"].sum()
    == N_ORIGINAL
)

assert (
    caracterizacion_51764["esperas_cero"].sum()
    == esperas_51764["espera_cero"].sum()
)

assert (
    caracterizacion_51764["esperas_positivas"].sum()
    == esperas_51764["espera_positiva"].sum()
)

assert (
    caracterizacion_51764["esperas_cero"].sum()
    + caracterizacion_51764["esperas_positivas"].sum()
    == caracterizacion_51764["tiempos_validos"].sum()
)

assert not caracterizacion_51764.duplicated(
    subset=dimensiones
).any()

# ------------------------------------------------------------
# 7. Resultados
# ------------------------------------------------------------

print("\nRESUMEN GENERAL")

total_validos = int(
    caracterizacion_51764["tiempos_validos"].sum()
)

total_cero = int(
    caracterizacion_51764["esperas_cero"].sum()
)

total_positivas = int(
    caracterizacion_51764["esperas_positivas"].sum()
)

print(f"Turnos originales: {N_ORIGINAL:,}")
print(f"Tiempos válidos: {total_validos:,}")
print(f"Esperas cero: {total_cero:,}")
print(f"Esperas positivas: {total_positivas:,}")
print(
    f"Porcentaje de esperas cero: "
    f"{total_cero / total_validos * 100:.2f}%"
)

print("\n20 FRANJAS CON MAYOR ESPERA P90")
print("Filtro exploratorio: mínimo 100 turnos válidos")

columnas = [
    "Sede",
    "dia_semana",
    "franja_horaria",
    "turnos",
    "espera_promedio_min",
    "espera_mediana_min",
    "espera_p90_min",
    "pct_espera_cero",
    "pct_espera_mayor_15",
    "pct_espera_mayor_30"
]

display(
    caracterizacion_51764
    .loc[
        caracterizacion_51764["tiempos_validos"] >= 100
    ]
    .sort_values("espera_p90_min", ascending=False)
    [columnas]
    .head(20)
    .round(2)
)

print("\nVALIDACIÓN FINAL")
print("Conciliación de registros: OK")
print("Conciliación de esperas cero: OK")
print("Conciliación de esperas positivas: OK")
print("Integridad de dimensiones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.1. CARACTERIZACIÓN DE LA ESPERA
======================================================================

RESUMEN GENERAL
Turnos originales: 883,076
Tiempos válidos: 883,076
Esperas cero: 347,996
Esperas positivas: 535,080
Porcentaje de esperas cero: 39.41%

20 FRANJAS CON MAYOR ESPERA P90
Filtro exploratorio: mínimo 100 turnos válidos

,Sede,dia_semana,franja_horaria,turnos,espera_promedio_min,espera_mediana_min,espera_p90_min,pct_espera_cero,pct_espera_mayor_15,pct_espera_mayor_30
185,Centro mayor,Sábado,12:00-12:59,1871,12.97,0.77,42.95,46.07,28.17,17.53
186,Centro mayor,Sábado,13:00-13:59,1913,12.70,1.90,42.10,42.29,30.16,17.72
691,Tintal plaza,Sábado,12:00-12:59,2571,12.33,0.00,41.73,52.74,30.26,16.26
760,Unicentro de occidente,Sábado,12:00-12:59,1575,11.59,1.80,40.29,42.79,26.10,15.37
630,Suba,Sábado,11:00-11:59,2230,13.35,4.85,38.32,29.10,33.81,16.59
690,Tintal plaza,Sábado,11:00-11:59,2717,11.24,0.00,37.51,53.96,27.27,15.09
629,Suba,Sábado,10:00-10:59,2025,13.35,6.12,36.91,28.64,33.83,16.64
187,Centro mayor,Sábado,14:00-14:59,2162,10.56,0.72,35.44,45.10,23.59,12.67
759,Unicentro de occidente,Sábado,11:00-11:59,1710,10.53,1.56,35.09,44.27,25.96,13.74
143,Centro mayor,Martes,14:00-14:59,1319,9.02,0.82,32.84,42.30,22.52,11.75
184,Centro mayor,Sábado,11:00-11:59,2142,9.62,0.44,32.43,45.75,21.38,11.53
761,Unicentro de occidente,Sábado,13:00-13:59,1336,9.61,1.13,32.28,44.91,23.73,11.23
495,Santa librada,Sábado,11:00-11:59,1156,11.72,6.98,32.21,32.01,31.83,11.42
631,Suba,Sábado,12:00-12:59,2166,11.07,3.75,31.39,31.44,28.35,10.90
579,Suba,Lunes,15:00-15:59,1427,9.43,2.60,30.21,29.92,24.60,10.09
560,Soacha,Sábado,13:00-13:59,2014,11.03,7.27,29.98,30.49,31.88,9.98
609,Suba,Jueves,12:00-12:59,1282,8.81,2.38,29.71,32.61,21.68,9.59
580,Suba,Lunes,16:00-16:59,1575,8.94,2.18,28.88,31.56,21.84,9.52
127,Centro mayor,Lunes,09:00-09:59,797,9.57,2.70,28.48,30.36,24.09,9.41
576,Suba,Lunes,12:00-12:59,1098,8.90,2.33,28.31,30.97,20.67,8.29

VALIDACIÓN FINAL
Conciliación de registros: OK
Conciliación de esperas cero: OK
Conciliación de esperas positivas: OK
Integridad de dimensiones: OK
======================================================================

In [97]:
# ============================================================
# 5.1.7.6.4.2. COMPARACIÓN DE PRESIÓN OPERATIVA ENTRE SEDES
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.2. COMPARACIÓN DE PRESIÓN OPERATIVA ENTRE SEDES")
print("=" * 70)

# ------------------------------------------------------------
# 1. Base analítica independiente
# ------------------------------------------------------------

presion_517642 = esperas_51764.copy(deep=True)

N_ORIGINAL = len(operacion_5176)

assert len(presion_517642) == N_ORIGINAL

# ------------------------------------------------------------
# 2. Indicadores institucionales por sede
# ------------------------------------------------------------

comparacion_sedes_517642 = (
    presion_517642
    .groupby("Sede", dropna=False)
    .agg(
        turnos=("Sede", "size"),
        fechas_observadas=("fecha_analisis", "nunique"),
        tiempos_validos=("flag_tiempo_valido", "sum"),
        esperas_cero=("espera_cero", "sum"),
        esperas_positivas=("espera_positiva", "sum"),
        esperas_mayores_15=("espera_mayor_15", "sum"),
        esperas_mayores_30=("espera_mayor_30", "sum"),
        espera_promedio_min=("espera_valida_min", "mean"),
        espera_mediana_min=("espera_valida_min", "median"),
        espera_p90_min=(
            "espera_valida_min",
            lambda x: x.quantile(0.90)
        )
    )
    .reset_index()
)

# ------------------------------------------------------------
# 3. Indicadores derivados
# ------------------------------------------------------------

comparacion_sedes_517642["participacion_institucional_pct"] = (
    comparacion_sedes_517642["turnos"]
    / N_ORIGINAL * 100
)

comparacion_sedes_517642["promedio_turnos_dia"] = (
    comparacion_sedes_517642["turnos"]
    / comparacion_sedes_517642["fechas_observadas"]
)

denominador = (
    comparacion_sedes_517642["tiempos_validos"]
    .replace(0, np.nan)
)

comparacion_sedes_517642["pct_espera_cero"] = (
    comparacion_sedes_517642["esperas_cero"]
    / denominador * 100
)

comparacion_sedes_517642["pct_espera_mayor_15"] = (
    comparacion_sedes_517642["esperas_mayores_15"]
    / denominador * 100
)

comparacion_sedes_517642["pct_espera_mayor_30"] = (
    comparacion_sedes_517642["esperas_mayores_30"]
    / denominador * 100
)

# ------------------------------------------------------------
# 4. Ordenamiento por volumen
# ------------------------------------------------------------

comparacion_sedes_517642 = (
    comparacion_sedes_517642
    .sort_values("turnos", ascending=False)
    .reset_index(drop=True)
)

columnas_resultado = [
    "Sede",
    "turnos",
    "participacion_institucional_pct",
    "fechas_observadas",
    "promedio_turnos_dia",
    "espera_promedio_min",
    "espera_mediana_min",
    "espera_p90_min",
    "pct_espera_cero",
    "pct_espera_mayor_15",
    "pct_espera_mayor_30"
]

print("\n1. COMPARACIÓN GENERAL DE SEDES")

display(
    comparacion_sedes_517642[
        columnas_resultado
    ].round(2)
)

# ------------------------------------------------------------
# 5. Ranking por espera P90
# ------------------------------------------------------------

print("\n2. SEDES ORDENADAS POR ESPERA P90")

display(
    comparacion_sedes_517642[
        columnas_resultado
    ]
    .sort_values(
        "espera_p90_min",
        ascending=False
    )
    .round(2)
)

# ------------------------------------------------------------
# 6. Ranking por porcentaje de esperas > 30 minutos
# ------------------------------------------------------------

print("\n3. SEDES CON MAYOR PROPORCIÓN DE ESPERAS > 30 MIN")

display(
    comparacion_sedes_517642[
        columnas_resultado
    ]
    .sort_values(
        "pct_espera_mayor_30",
        ascending=False
    )
    .round(2)
)

# ------------------------------------------------------------
# 7. Validación de conciliación
# ------------------------------------------------------------

assert (
    comparacion_sedes_517642["turnos"].sum()
    == N_ORIGINAL
)

assert (
    comparacion_sedes_517642["tiempos_validos"].sum()
    == presion_517642["flag_tiempo_valido"].sum()
)

assert (
    comparacion_sedes_517642["esperas_cero"].sum()
    == presion_517642["espera_cero"].sum()
)

assert (
    comparacion_sedes_517642["esperas_mayores_30"].sum()
    == presion_517642["espera_mayor_30"].sum()
)

assert not comparacion_sedes_517642[
    "Sede"
].duplicated().any()

print("\nVALIDACIÓN FINAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Turnos conciliados: "
    f"{comparacion_sedes_517642['turnos'].sum():,}"
)
print(
    "Sedes analizadas: "
    f"{comparacion_sedes_517642['Sede'].nunique()}"
)
print("Conciliación de registros: OK")
print("Conciliación de tiempos válidos: OK")
print("Conciliación de esperas cero: OK")
print("Conciliación de esperas superiores a 30 minutos: OK")
print("Integridad de dimensiones: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.2. COMPARACIÓN DE PRESIÓN OPERATIVA ENTRE SEDES
======================================================================

1. COMPARACIÓN GENERAL DE SEDES

,Sede,turnos,participacion_institucional_pct,fechas_observadas,promedio_turnos_dia,espera_promedio_min,espera_mediana_min,espera_p90_min,pct_espera_cero,pct_espera_mayor_15,pct_espera_mayor_30
0,Calle 26,157060,17.79,211,744.36,5.49,0.57,17.67,44.15,12.86,3.47
1,Tintal plaza,112312,12.72,209,537.38,5.67,0.00,20.28,56.93,14.06,5.22
2,Soacha,93104,10.54,211,441.25,7.22,3.07,20.58,31.08,18.45,3.26
3,Suba,81721,9.25,186,439.36,7.74,2.25,23.90,31.46,19.34,6.17
4,Centro mayor,79106,8.96,135,585.97,6.82,0.38,22.95,45.93,16.16,6.56
5,Unicentro de occidente,56338,6.38,210,268.28,6.41,0.97,20.30,39.19,15.19,4.61
6,Usaquen,55305,6.26,211,262.11,5.95,1.02,18.68,43.73,14.54,3.12
7,Funza,53763,6.09,211,254.80,3.93,0.47,12.50,33.10,7.61,1.92
8,Calle 63,47613,5.39,211,225.65,5.22,0.63,16.95,29.81,11.98,3.01
9,Girardot,47419,5.37,211,224.73,5.97,2.90,14.80,32.31,9.27,1.24
10,Fusagasuga,45219,5.12,210,215.33,5.06,1.20,15.38,26.28,10.44,1.92
11,Santa librada,40790,4.62,211,193.32,6.63,2.12,19.67,34.00,16.36,3.29
12,La mesa,13326,1.51,210,63.46,4.44,1.03,13.57,33.09,6.72,0.31

2. SEDES ORDENADAS POR ESPERA P90

,Sede,turnos,participacion_institucional_pct,fechas_observadas,promedio_turnos_dia,espera_promedio_min,espera_mediana_min,espera_p90_min,pct_espera_cero,pct_espera_mayor_15,pct_espera_mayor_30
3,Suba,81721,9.25,186,439.36,7.74,2.25,23.90,31.46,19.34,6.17
4,Centro mayor,79106,8.96,135,585.97,6.82,0.38,22.95,45.93,16.16,6.56
2,Soacha,93104,10.54,211,441.25,7.22,3.07,20.58,31.08,18.45,3.26
5,Unicentro de occidente,56338,6.38,210,268.28,6.41,0.97,20.30,39.19,15.19,4.61
1,Tintal plaza,112312,12.72,209,537.38,5.67,0.00,20.28,56.93,14.06,5.22
11,Santa librada,40790,4.62,211,193.32,6.63,2.12,19.67,34.00,16.36,3.29
6,Usaquen,55305,6.26,211,262.11,5.95,1.02,18.68,43.73,14.54,3.12
0,Calle 26,157060,17.79,211,744.36,5.49,0.57,17.67,44.15,12.86,3.47
8,Calle 63,47613,5.39,211,225.65,5.22,0.63,16.95,29.81,11.98,3.01
10,Fusagasuga,45219,5.12,210,215.33,5.06,1.20,15.38,26.28,10.44,1.92
9,Girardot,47419,5.37,211,224.73,5.97,2.90,14.80,32.31,9.27,1.24
12,La mesa,13326,1.51,210,63.46,4.44,1.03,13.57,33.09,6.72,0.31
7,Funza,53763,6.09,211,254.80,3.93,0.47,12.50,33.10,7.61,1.92

3. SEDES CON MAYOR PROPORCIÓN DE ESPERAS > 30 MIN

,Sede,turnos,participacion_institucional_pct,fechas_observadas,promedio_turnos_dia,espera_promedio_min,espera_mediana_min,espera_p90_min,pct_espera_cero,pct_espera_mayor_15,pct_espera_mayor_30
4,Centro mayor,79106,8.96,135,585.97,6.82,0.38,22.95,45.93,16.16,6.56
3,Suba,81721,9.25,186,439.36,7.74,2.25,23.90,31.46,19.34,6.17
1,Tintal plaza,112312,12.72,209,537.38,5.67,0.00,20.28,56.93,14.06,5.22
5,Unicentro de occidente,56338,6.38,210,268.28,6.41,0.97,20.30,39.19,15.19,4.61
0,Calle 26,157060,17.79,211,744.36,5.49,0.57,17.67,44.15,12.86,3.47
11,Santa librada,40790,4.62,211,193.32,6.63,2.12,19.67,34.00,16.36,3.29
2,Soacha,93104,10.54,211,441.25,7.22,3.07,20.58,31.08,18.45,3.26
6,Usaquen,55305,6.26,211,262.11,5.95,1.02,18.68,43.73,14.54,3.12
8,Calle 63,47613,5.39,211,225.65,5.22,0.63,16.95,29.81,11.98,3.01
10,Fusagasuga,45219,5.12,210,215.33,5.06,1.20,15.38,26.28,10.44,1.92
7,Funza,53763,6.09,211,254.80,3.93,0.47,12.50,33.10,7.61,1.92
9,Girardot,47419,5.37,211,224.73,5.97,2.90,14.80,32.31,9.27,1.24
12,La mesa,13326,1.51,210,63.46,4.44,1.03,13.57,33.09,6.72,0.31

VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos conciliados: 883,076
Sedes analizadas: 13
Conciliación de registros: OK
Conciliación de tiempos válidos: OK
Conciliación de esperas cero: OK
Conciliación de esperas superiores a 30 minutos: OK
Integridad de dimensiones: OK
Base original conservada: OK
======================================================================

In [98]:
# ============================================================
# 5.1.7.6.4.3. MATRIZ DE PRIORIZACIÓN OPERATIVA
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.3. MATRIZ DE PRIORIZACIÓN OPERATIVA")
print("=" * 70)

# 1. Base independiente
priorizacion_base = presion_517642.copy(deep=True)
N_ORIGINAL = len(priorizacion_base)

columnas = [
    "Sede", "dia_semana", "franja_horaria",
    "fecha_analisis", "flag_tiempo_valido",
    "espera_valida_min", "espera_mayor_30"
]

faltantes = [
    c for c in columnas
    if c not in priorizacion_base.columns
]

assert not faltantes, f"Columnas faltantes: {faltantes}"
assert N_ORIGINAL == 883076

# 2. Agregación por sede, día y hora
matriz_priorizacion_517643 = (
    priorizacion_base
    .groupby(
        ["Sede", "dia_semana", "franja_horaria"],
        dropna=False
    )
    .agg(
        turnos=("Sede", "size"),
        fechas_observadas=("fecha_analisis", "nunique"),
        tiempos_validos=("flag_tiempo_valido", "sum"),
        espera_promedio_min=("espera_valida_min", "mean"),
        espera_p90_min=(
            "espera_valida_min",
            lambda x: x.quantile(0.90)
        ),
        esperas_mayores_30=("espera_mayor_30", "sum")
    )
    .reset_index()
)

# 3. Indicadores derivados
matriz_priorizacion_517643["promedio_turnos_dia"] = (
    matriz_priorizacion_517643["turnos"]
    / matriz_priorizacion_517643[
        "fechas_observadas"
    ].replace(0, np.nan)
)

matriz_priorizacion_517643["pct_espera_mayor_30"] = (
    100
    * matriz_priorizacion_517643["esperas_mayores_30"]
    / matriz_priorizacion_517643[
        "tiempos_validos"
    ].replace(0, np.nan)
)

# 4. Elegibilidad estadística exploratoria
MIN_TURNOS_VALIDOS = 100

matriz_priorizacion_517643["elegible"] = (
    matriz_priorizacion_517643["tiempos_validos"]
    >= MIN_TURNOS_VALIDOS
)

elegibles = matriz_priorizacion_517643.loc[
    matriz_priorizacion_517643["elegible"]
].copy()

assert not elegibles.empty, "No existen grupos elegibles"

# Umbrales relativos: percentil 75 entre grupos elegibles
umbral_demanda = elegibles["promedio_turnos_dia"].quantile(0.75)
umbral_p90 = elegibles["espera_p90_min"].quantile(0.75)

matriz_priorizacion_517643["demanda_alta"] = (
    matriz_priorizacion_517643["promedio_turnos_dia"]
    >= umbral_demanda
)

matriz_priorizacion_517643["espera_alta"] = (
    matriz_priorizacion_517643["espera_p90_min"]
    >= umbral_p90
)

# 5. Clasificación
condiciones = [
    ~matriz_priorizacion_517643["elegible"],
    (
        matriz_priorizacion_517643["demanda_alta"]
        & matriz_priorizacion_517643["espera_alta"]
    ),
    matriz_priorizacion_517643["espera_alta"],
    matriz_priorizacion_517643["demanda_alta"]
]

categorias = [
    "Muestra insuficiente",
    "Prioridad alta",
    "Espera elevada",
    "Demanda elevada"
]

matriz_priorizacion_517643["categoria_operativa"] = (
    np.select(
        condiciones,
        categorias,
        default="Seguimiento regular"
    )
)

# 6. Resultados
print("\nUMBRALES EXPLORATORIOS")
print(f"Demanda alta: >= {umbral_demanda:.2f} turnos/día")
print(f"Espera alta: P90 >= {umbral_p90:.2f} minutos")
print(f"Mínimo de turnos válidos: {MIN_TURNOS_VALIDOS}")

print("\nDISTRIBUCIÓN DE CATEGORÍAS")
display(
    matriz_priorizacion_517643[
        "categoria_operativa"
    ].value_counts().rename_axis(
        "categoria"
    ).reset_index(name="combinaciones")
)

print("\n20 COMBINACIONES DE PRIORIDAD ALTA")
display(
    matriz_priorizacion_517643.loc[
        matriz_priorizacion_517643[
            "categoria_operativa"
        ] == "Prioridad alta",
        [
            "Sede", "dia_semana", "franja_horaria",
            "turnos", "fechas_observadas",
            "promedio_turnos_dia",
            "espera_promedio_min",
            "espera_p90_min",
            "pct_espera_mayor_30"
        ]
    ]
    .sort_values(
        ["espera_p90_min", "promedio_turnos_dia"],
        ascending=False
    )
    .head(20)
    .round(2)
)

# 7. Conciliación
assert matriz_priorizacion_517643["turnos"].sum() == N_ORIGINAL

assert (
    matriz_priorizacion_517643["tiempos_validos"].sum()
    == priorizacion_base["flag_tiempo_valido"].sum()
)

assert (
    matriz_priorizacion_517643["esperas_mayores_30"].sum()
    == priorizacion_base["espera_mayor_30"].sum()
)

assert not matriz_priorizacion_517643.duplicated(
    ["Sede", "dia_semana", "franja_horaria"]
).any()

print("\nVALIDACIÓN FINAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Turnos conciliados: "
    f"{matriz_priorizacion_517643['turnos'].sum():,}"
)
print("Conciliación de registros: OK")
print("Conciliación de tiempos válidos: OK")
print("Integridad de dimensiones: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.3. MATRIZ DE PRIORIZACIÓN OPERATIVA
======================================================================

UMBRALES EXPLORATORIOS
Demanda alta: >= 48.11 turnos/día
Espera alta: P90 >= 21.26 minutos
Mínimo de turnos válidos: 100

DISTRIBUCIÓN DE CATEGORÍAS

              categoria  combinaciones
0   Seguimiento regular            451
1       Demanda elevada            110
2        Espera elevada            110
3  Muestra insuficiente             79
4        Prioridad alta             78

20 COMBINACIONES DE PRIORIDAD ALTA

,Sede,dia_semana,franja_horaria,turnos,fechas_observadas,promedio_turnos_dia,espera_promedio_min,espera_p90_min,pct_espera_mayor_30
174,Centro mayor,Sábado,12:00-12:59,1871,24,77.96,12.97,42.95,17.53
175,Centro mayor,Sábado,13:00-13:59,1913,24,79.71,12.70,42.10,17.72
686,Tintal plaza,Sábado,12:00-12:59,2571,35,73.46,12.33,41.73,16.26
619,Suba,Sábado,11:00-11:59,2230,32,69.69,13.35,38.32,16.59
685,Tintal plaza,Sábado,11:00-11:59,2717,35,77.63,11.24,37.51,15.09
618,Suba,Sábado,10:00-10:59,2025,32,63.28,13.35,36.91,16.64
176,Centro mayor,Sábado,14:00-14:59,2162,23,94.00,10.56,35.44,12.67
154,Centro mayor,Martes,14:00-14:59,1319,24,54.96,9.02,32.84,11.75
173,Centro mayor,Sábado,11:00-11:59,2142,24,89.25,9.62,32.43,11.53
620,Suba,Sábado,12:00-12:59,2166,32,67.69,11.07,31.39,10.90
590,Suba,Lunes,15:00-15:59,1427,26,54.88,9.43,30.21,10.09
555,Soacha,Sábado,13:00-13:59,2014,36,55.94,11.03,29.98,9.98
591,Suba,Lunes,16:00-16:59,1575,26,60.58,8.94,28.88,9.52
177,Centro mayor,Sábado,15:00-15:59,2147,23,93.35,7.99,27.96,8.29
687,Tintal plaza,Sábado,13:00-13:59,2478,35,70.80,7.26,27.88,8.76
601,Suba,Martes,15:00-15:59,1820,33,55.15,9.51,27.67,7.58
31,Calle 26,Martes,14:00-14:59,3261,37,88.14,8.74,27.13,8.19
554,Soacha,Sábado,12:00-12:59,2211,36,61.42,10.26,27.10,8.01
139,Centro mayor,Lunes,10:00-10:59,1002,18,55.67,7.21,27.08,8.38
152,Centro mayor,Martes,12:00-12:59,1279,24,53.29,7.78,27.00,8.29

VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos conciliados: 883,076
Conciliación de registros: OK
Conciliación de tiempos válidos: OK
Integridad de dimensiones: OK
Base original conservada: OK
======================================================================

In [99]:
# ============================================================
# 5.1.7.6.4.4. SERVICIOS EN FRANJAS DE PRIORIDAD ALTA
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.4. SERVICIOS EN FRANJAS DE PRIORIDAD ALTA")
print("=" * 70)

# 1. Bases independientes
base_servicios_517644 = presion_517642.copy(deep=True)
matriz_critica_517644 = matriz_priorizacion_517643.copy(deep=True)

N_ORIGINAL = len(base_servicios_517644)

claves = ["Sede", "dia_semana", "franja_horaria"]

columnas_requeridas = claves + [
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "flag_tiempo_valido",
    "espera_valida_min",
    "espera_mayor_30"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in base_servicios_517644.columns
]

assert not faltantes, f"Columnas faltantes: {faltantes}"
assert N_ORIGINAL == 883076

# 2. Identificar combinaciones de prioridad alta
claves_criticas = (
    matriz_critica_517644.loc[
        matriz_critica_517644["categoria_operativa"]
        == "Prioridad alta",
        claves
    ]
    .drop_duplicates()
    .assign(prioridad_alta=True)
)

assert len(claves_criticas) == 78
assert not claves_criticas.duplicated(claves).any()

# 3. Clasificar cada turno sin excluir registros
base_servicios_517644 = base_servicios_517644.merge(
    claves_criticas,
    on=claves,
    how="left",
    validate="many_to_one",
    indicator=True
)

base_servicios_517644["prioridad_alta"] = (
    base_servicios_517644["prioridad_alta"]
    .fillna(False)
    .astype(bool)
)

assert len(base_servicios_517644) == N_ORIGINAL

# 4. Separar turnos de las franjas críticas
turnos_criticos_517644 = base_servicios_517644.loc[
    base_servicios_517644["prioridad_alta"]
].copy()

N_CRITICOS = len(turnos_criticos_517644)

# 5. Agregación por sede, día, hora y servicio
dimensiones = claves + [
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO"
]

servicios_criticos_517644 = (
    turnos_criticos_517644
    .groupby(dimensiones, dropna=False)
    .agg(
        turnos=("Sede", "size"),
        tiempos_validos=("flag_tiempo_valido", "sum"),
        espera_promedio_min=("espera_valida_min", "mean"),
        espera_mediana_min=("espera_valida_min", "median"),
        espera_p90_min=(
            "espera_valida_min",
            lambda x: x.quantile(0.90)
        ),
        esperas_mayores_30=("espera_mayor_30", "sum")
    )
    .reset_index()
)

# 6. Indicadores
servicios_criticos_517644["pct_espera_mayor_30"] = (
    100
    * servicios_criticos_517644["esperas_mayores_30"]
    / servicios_criticos_517644[
        "tiempos_validos"
    ].replace(0, np.nan)
)

servicios_criticos_517644["participacion_criticos_pct"] = (
    100
    * servicios_criticos_517644["turnos"]
    / N_CRITICOS
)

# 7. Resumen por tipo de servicio
resumen_tipo_servicio_517644 = (
    turnos_criticos_517644
    .groupby("Tipo_servicio", dropna=False)
    .agg(
        turnos=("Sede", "size"),
        tiempos_validos=("flag_tiempo_valido", "sum"),
        espera_promedio_min=("espera_valida_min", "mean"),
        espera_p90_min=(
            "espera_valida_min",
            lambda x: x.quantile(0.90)
        ),
        esperas_mayores_30=("espera_mayor_30", "sum")
    )
    .reset_index()
)

resumen_tipo_servicio_517644["participacion_pct"] = (
    100
    * resumen_tipo_servicio_517644["turnos"]
    / N_CRITICOS
)

resumen_tipo_servicio_517644["pct_espera_mayor_30"] = (
    100
    * resumen_tipo_servicio_517644["esperas_mayores_30"]
    / resumen_tipo_servicio_517644[
        "tiempos_validos"
    ].replace(0, np.nan)
)

# 8. Resultados
print("\nRESUMEN GENERAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(f"Combinaciones críticas: {len(claves_criticas):,}")
print(f"Turnos en franjas críticas: {N_CRITICOS:,}")
print(
    f"Participación institucional: "
    f"{100 * N_CRITICOS / N_ORIGINAL:.2f}%"
)

print("\nTIPOS DE SERVICIO EN FRANJAS CRÍTICAS")
display(
    resumen_tipo_servicio_517644
    .sort_values("turnos", ascending=False)
    .round(2)
)

print("\n20 COMBINACIONES SERVICIO-FRANJA CON MAYOR VOLUMEN")
display(
    servicios_criticos_517644
    .sort_values("turnos", ascending=False)
    .head(20)
    .round(2)
)

print("\n20 COMBINACIONES CON MAYOR P90 (MÍNIMO 100 TURNOS)")
display(
    servicios_criticos_517644.loc[
        servicios_criticos_517644["tiempos_validos"] >= 100
    ]
    .sort_values("espera_p90_min", ascending=False)
    .head(20)
    .round(2)
)

# 9. Conciliación
assert (
    servicios_criticos_517644["turnos"].sum()
    == N_CRITICOS
)

assert (
    resumen_tipo_servicio_517644["turnos"].sum()
    == N_CRITICOS
)

assert (
    servicios_criticos_517644["tiempos_validos"].sum()
    == turnos_criticos_517644["flag_tiempo_valido"].sum()
)

assert (
    servicios_criticos_517644["esperas_mayores_30"].sum()
    == turnos_criticos_517644["espera_mayor_30"].sum()
)

assert not servicios_criticos_517644.duplicated(
    dimensiones
).any()

print("\nVALIDACIÓN FINAL")
print("Conservación de base original: OK")
print("Conciliación de turnos críticos: OK")
print("Conciliación de tiempos válidos: OK")
print("Conciliación de esperas superiores a 30 minutos: OK")
print("Integridad de dimensiones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.4. SERVICIOS EN FRANJAS DE PRIORIDAD ALTA
======================================================================

RESUMEN GENERAL
Turnos originales: 883,076
Combinaciones críticas: 78
Turnos en franjas críticas: 161,554
Participación institucional: 18.29%

TIPOS DE SERVICIO EN FRANJAS CRÍTICAS

,Tipo_servicio,turnos,tiempos_validos,espera_promedio_min,espera_p90_min,esperas_mayores_30,participacion_pct,pct_espera_mayor_30
1,Servicio,117537,117537,9.47,28.34,10470,72.75,8.91
0,Comercial,44017,44017,4.09,14.56,1711,27.25,3.89

20 COMBINACIONES SERVICIO-FRANJA CON MAYOR VOLUMEN

,Sede,dia_semana,franja_horaria,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,turnos,tiempos_validos,espera_promedio_min,espera_mediana_min,espera_p90_min,esperas_mayores_30,pct_espera_mayor_30,participacion_criticos_pct
866,Calle 26,Martes,15:00-15:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,497,497,10.24,8.13,24.17,17,3.42,0.31
1457,Calle 26,Viernes,15:00-15:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,481,481,8.89,7.33,19.10,13,2.70,0.30
1056,Calle 26,Sábado,11:00-11:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,464,464,7.37,4.22,18.35,10,2.16,0.29
476,Calle 26,Martes,11:00-11:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,451,451,7.46,4.93,19.40,3,0.67,0.28
1128,Calle 26,Sábado,12:00-12:59,Servicio,Entrega tams primera vez,451,451,11.18,1.10,34.25,66,14.63,0.28
1162,Calle 26,Sábado,12:00-12:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,447,447,7.69,5.20,18.56,10,2.24,0.28
577,Calle 26,Martes,12:00-12:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,445,445,7.45,4.97,18.29,4,0.90,0.28
3870,Soacha,Sábado,11:00-11:59,Servicio,Entrega tams primera vez,441,441,7.67,0.92,23.10,25,5.67,0.27
1363,Calle 26,Viernes,14:00-14:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,437,437,7.18,4.52,17.97,8,1.83,0.27
773,Calle 26,Martes,14:00-14:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,435,435,10.42,7.43,24.32,27,6.21,0.27
4126,Soacha,Sábado,14:00-14:59,Servicio,Entrega tams primera vez,427,427,9.06,3.07,25.13,30,7.03,0.26
677,Calle 26,Martes,13:00-13:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,426,426,7.20,4.70,18.06,1,0.23,0.26
1024,Calle 26,Sábado,11:00-11:59,Servicio,Entrega tams primera vez,421,421,8.75,0.50,30.75,44,10.45,0.26
958,Calle 26,Miércoles,14:00-14:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,402,402,8.08,3.94,20.36,13,3.23,0.25
173,Calle 26,Jueves,14:00-14:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,395,395,7.91,4.63,18.98,16,4.05,0.24
75,Calle 26,Jueves,12:00-12:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,388,388,7.68,5.72,18.36,4,1.03,0.24
3899,Soacha,Sábado,11:00-11:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,375,375,13.11,12.47,24.88,14,3.73,0.23
6906,Tintal plaza,Sábado,13:00-13:59,Servicio,Entrega tams primera vez,375,375,7.70,0.00,32.77,45,12.00,0.23
1427,Calle 26,Viernes,15:00-15:59,Servicio,Entrega tams primera vez,373,373,7.48,0.00,27.05,34,9.12,0.23
6609,Tintal plaza,Sábado,10:00-10:59,Servicio,Entrega tams primera vez,368,368,8.30,0.00,34.71,40,10.87,0.23

20 COMBINACIONES CON MAYOR P90 (MÍNIMO 100 TURNOS)

,Sede,dia_semana,franja_horaria,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,turnos,tiempos_validos,espera_promedio_min,espera_mediana_min,espera_p90_min,esperas_mayores_30,pct_espera_mayor_30,participacion_criticos_pct
6808,Tintal plaza,Sábado,12:00-12:59,Servicio,Entrega tams primera vez,363,363,12.42,0.00,53.45,70,19.28,0.22
4634,Suba,Lunes,16:00-16:59,Servicio,Entrega tams primera vez,167,167,15.91,2.30,52.31,41,24.55,0.10
2924,Centro mayor,Sábado,12:00-12:59,Servicio,Entrega tams primera vez,212,212,18.24,8.72,51.14,56,26.42,0.13
5279,Suba,Sábado,10:00-10:59,Comercial,Informacion credito consumo,115,115,19.87,12.85,50.01,36,31.30,0.07
6711,Tintal plaza,Sábado,11:00-11:59,Servicio,Entrega tams primera vez,320,320,12.03,0.00,45.57,52,16.25,0.20
4883,Suba,Martes,16:00-16:59,Servicio,Certificado afiliacion trabajador y/o benefici...,114,114,12.11,3.42,44.90,18,15.79,0.07
3023,Centro mayor,Sábado,13:00-13:59,Servicio,Entrega tams primera vez,266,266,18.15,13.48,44.89,81,30.45,0.16
5460,Suba,Sábado,12:00-12:59,Comercial,Informacion credito consumo,107,107,17.67,10.48,44.68,27,25.23,0.07
3125,Centro mayor,Sábado,14:00-14:59,Servicio,Entrega tams primera vez,346,346,13.36,0.68,44.25,67,19.36,0.21
6750,Tintal plaza,Sábado,11:00-11:59,Servicio,Radicacion postulacion de subsidio vivienda nueva,105,105,15.57,7.40,43.63,24,22.86,0.06
4556,Suba,Lunes,15:00-15:59,Servicio,Entrega tams primera vez,181,181,16.14,12.38,43.57,40,22.10,0.11
5401,Suba,Sábado,11:00-11:59,Servicio,Certificado afiliacion trabajador y/o benefici...,101,101,14.70,6.85,43.53,19,18.81,0.06
5408,Suba,Sábado,11:00-11:59,Servicio,Entrega tams primera vez,211,211,17.50,13.93,43.00,58,27.49,0.13
6765,Tintal plaza,Sábado,12:00-12:59,Comercial,Informacion credito consumo,101,101,12.90,0.35,42.77,20,19.80,0.06
1428,Calle 26,Viernes,15:00-15:59,Servicio,Entrega tams reexpedicion,118,118,11.80,1.96,42.10,19,16.10,0.07
5437,Suba,Sábado,11:00-11:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,321,321,15.14,8.00,40.73,54,16.82,0.20
985,Calle 26,Sábado,11:00-11:59,Comercial,Informacion credito consumo,169,169,13.46,2.92,40.65,32,18.93,0.10
1088,Calle 26,Sábado,12:00-12:59,Comercial,Informacion credito consumo,167,167,10.62,0.00,39.59,28,16.77,0.10
6837,Tintal plaza,Sábado,12:00-12:59,Servicio,Rad afiliacion trabajadores hasta 10 formularios,229,229,18.77,16.05,39.57,37,16.16,0.14
1035,Calle 26,Sábado,11:00-11:59,Servicio,Informacion general subsidio de vivienda,260,260,12.19,6.49,39.05,41,15.77,0.16

VALIDACIÓN FINAL
Conservación de base original: OK
Conciliación de turnos críticos: OK
Conciliación de tiempos válidos: OK
Conciliación de esperas superiores a 30 minutos: OK
Integridad de dimensiones: OK
======================================================================

In [100]:

# ============================================================
# 5.1.7.6.4.5.1. PREPARACIÓN Y VALIDACIÓN OPERATIVA
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.5.1. PREPARACIÓN Y VALIDACIÓN OPERATIVA")
print("=" * 70)

# ------------------------------------------------------------
# 1. CREAR BASE INDEPENDIENTE
# ------------------------------------------------------------

# Se parte de la base individual clasificada en la sección
# anterior, conservando los 883.076 turnos.

base_capacidad_517645 = base_servicios_517644.copy(deep=True)

N_ORIGINAL = len(base_capacidad_517645)

assert N_ORIGINAL == 883076, (
    f"Se esperaban 883076 registros y se encontraron "
    f"{N_ORIGINAL}"
)

# ------------------------------------------------------------
# 2. VALIDAR COLUMNAS REQUERIDAS
# ------------------------------------------------------------

columnas_requeridas = [
    "Sede",
    "dia_semana",
    "franja_horaria",
    "Tipo_servicio",
    "SUBSERVICIO_HOMOLOGADO",
    "Usuario_receptor",
    "prioridad_alta",
    "flag_tiempo_valido",
    "tiempo_espera_min",
    "tiempo_atencion_min"
]

# La columna de espera validada ya se utilizó en la sección
# anterior. Se conserva como variable principal de análisis.

if "espera_valida_min" in base_capacidad_517645.columns:
    columna_espera = "espera_valida_min"
else:
    columna_espera = "tiempo_espera_min"

columnas_requeridas = [
    c for c in columnas_requeridas
    if c != "tiempo_espera_min"
]

columnas_requeridas.append(columna_espera)

faltantes = [
    c for c in columnas_requeridas
    if c not in base_capacidad_517645.columns
]

print("\nVALIDACIÓN DE VARIABLES")
print(f"Columnas faltantes: {faltantes}")

assert not faltantes, (
    f"No es posible continuar. Faltan columnas: {faltantes}"
)

# ------------------------------------------------------------
# 3. PREPARAR VARIABLES DE ATENCIÓN
# ------------------------------------------------------------

base_capacidad_517645["atencion_min_analisis"] = (
    pd.to_numeric(
        base_capacidad_517645["tiempo_atencion_min"],
        errors="coerce"
    )
)

base_capacidad_517645["espera_min_analisis"] = (
    pd.to_numeric(
        base_capacidad_517645[columna_espera],
        errors="coerce"
    )
)

# Se define validez temporal sin modificar las variables
# originales ni eliminar observaciones.

base_capacidad_517645["atencion_valida"] = (
    base_capacidad_517645["flag_tiempo_valido"].eq(True)
    & base_capacidad_517645["atencion_min_analisis"].notna()
    & np.isfinite(
        base_capacidad_517645["atencion_min_analisis"]
    )
    & base_capacidad_517645["atencion_min_analisis"].ge(0)
)

base_capacidad_517645["espera_valida"] = (
    base_capacidad_517645["flag_tiempo_valido"].eq(True)
    & base_capacidad_517645["espera_min_analisis"].notna()
    & np.isfinite(
        base_capacidad_517645["espera_min_analisis"]
    )
    & base_capacidad_517645["espera_min_analisis"].ge(0)
)

# Solo se utilizan los tiempos válidos en las agregaciones.
# Los registros permanecen en la base.

base_capacidad_517645["atencion_valida_min"] = (
    base_capacidad_517645["atencion_min_analisis"]
    .where(base_capacidad_517645["atencion_valida"])
)

base_capacidad_517645["espera_valida_operativa_min"] = (
    base_capacidad_517645["espera_min_analisis"]
    .where(base_capacidad_517645["espera_valida"])
)

# ------------------------------------------------------------
# 4. VALIDAR IDENTIFICACIÓN DE RECEPTORES
# ------------------------------------------------------------

receptor_texto = (
    base_capacidad_517645["Usuario_receptor"]
    .astype("string")
    .str.strip()
)

valores_sin_receptor = [
    "",
    "nan",
    "none",
    "null",
    "sin asignar",
    "no asignado"
]

base_capacidad_517645["receptor_identificado"] = (
    receptor_texto.notna()
    & ~receptor_texto.str.lower().isin(
        valores_sin_receptor
    ).fillna(False)
)

# No se reemplazan los identificadores originales.

# ------------------------------------------------------------
# 5. CONCILIACIÓN GENERAL
# ------------------------------------------------------------

N_CRITICOS_ESPERADO = 161554

n_criticos = int(
    base_capacidad_517645["prioridad_alta"].sum()
)

resumen_validacion_517645 = pd.DataFrame({
    "indicador": [
        "Turnos originales",
        "Turnos conservados",
        "Turnos en franjas críticas",
        "Turnos fuera de franjas críticas",
        "Tiempos de espera válidos",
        "Tiempos de atención válidos",
        "Receptores identificados",
        "Turnos sin receptor identificado"
    ],
    "resultado": [
        N_ORIGINAL,
        len(base_capacidad_517645),
        n_criticos,
        N_ORIGINAL - n_criticos,
        int(base_capacidad_517645["espera_valida"].sum()),
        int(base_capacidad_517645["atencion_valida"].sum()),
        int(
            base_capacidad_517645.loc[
                base_capacidad_517645["receptor_identificado"],
                "Usuario_receptor"
            ].nunique()
        ),
        int(
            (~base_capacidad_517645[
                "receptor_identificado"
            ]).sum()
        )
    ]
})

display(resumen_validacion_517645)

# ------------------------------------------------------------
# 6. DISTRIBUCIÓN DE TIEMPOS DE ATENCIÓN
# ------------------------------------------------------------

print("\nDISTRIBUCIÓN DE TIEMPOS DE ATENCIÓN")

tiempos_atencion = (
    base_capacidad_517645["atencion_valida_min"]
    .dropna()
)

resumen_atencion_517645 = pd.DataFrame({
    "indicador": [
        "Promedio de atención (min)",
        "Mediana de atención (min)",
        "Percentil 75 (min)",
        "Percentil 90 (min)",
        "Percentil 95 (min)",
        "Máximo observado (min)",
        "Atenciones de duración cero"
    ],
    "resultado": [
        tiempos_atencion.mean(),
        tiempos_atencion.median(),
        tiempos_atencion.quantile(0.75),
        tiempos_atencion.quantile(0.90),
        tiempos_atencion.quantile(0.95),
        tiempos_atencion.max(),
        int(tiempos_atencion.eq(0).sum())
    ]
})

display(resumen_atencion_517645.round(2))

# ------------------------------------------------------------
# 7. CONCILIACIÓN FINAL
# ------------------------------------------------------------

assert len(base_capacidad_517645) == N_ORIGINAL

assert n_criticos == N_CRITICOS_ESPERADO, (
    f"Turnos críticos esperados: {N_CRITICOS_ESPERADO}; "
    f"encontrados: {n_criticos}"
)

assert (
    base_capacidad_517645["prioridad_alta"].sum()
    + (~base_capacidad_517645["prioridad_alta"]).sum()
    == N_ORIGINAL
)

assert (
    base_capacidad_517645["atencion_valida"].sum()
    <= N_ORIGINAL
)

assert (
    base_capacidad_517645["espera_valida"].sum()
    <= N_ORIGINAL
)

print("\nVALIDACIÓN FINAL")
print(f"Registros originales: {N_ORIGINAL:,}")
print(f"Registros conservados: {len(base_capacidad_517645):,}")
print(f"Turnos críticos conciliados: {n_criticos:,}")
print("Integridad de registros: OK")
print("Clasificación de prioridad: OK")
print("Base original sin modificaciones: OK")
print("Base operativa independiente: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.1. PREPARACIÓN Y VALIDACIÓN OPERATIVA
======================================================================

VALIDACIÓN DE VARIABLES
Columnas faltantes: []

                          indicador  resultado
0                 Turnos originales     883076
1                Turnos conservados     883076
2        Turnos en franjas críticas     161554
3  Turnos fuera de franjas críticas     721522
4         Tiempos de espera válidos     883076
5       Tiempos de atención válidos     883076
6          Receptores identificados        121
7  Turnos sin receptor identificado          0

DISTRIBUCIÓN DE TIEMPOS DE ATENCIÓN

                     indicador  resultado
0   Promedio de atención (min)       5.15
1    Mediana de atención (min)       4.15
2           Percentil 75 (min)       6.77
3           Percentil 90 (min)      10.13
4           Percentil 95 (min)      12.90
5       Máximo observado (min)     171.25
6  Atenciones de duración cero       0.00

VALIDACIÓN FINAL
Registros originales: 883,076
Registros conservados: 883,076
Turnos críticos conciliados: 161,554
Integridad de registros: OK
Clasificación de prioridad: OK
Base original sin modificaciones: OK
Base operativa independiente: OK
======================================================================

In [101]:

# ============================================================
# 5.1.7.6.4.5.2. DEMANDA Y DURACIÓN DEL SERVICIO
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.5.2. DEMANDA Y DURACIÓN DEL SERVICIO")
print("=" * 70)

# ------------------------------------------------------------
# 1. BASE INDEPENDIENTE
# ------------------------------------------------------------

servicios_5176452 = base_capacidad_517645.copy(deep=True)

N_ORIGINAL = len(servicios_5176452)
N_CRITICOS = int(servicios_5176452["prioridad_alta"].sum())

assert N_ORIGINAL == 883076
assert N_CRITICOS == 161554

# ------------------------------------------------------------
# 2. FUNCIÓN DE INDICADORES
# ------------------------------------------------------------

def indicadores_servicio_5176452(grupo):

    atenciones = grupo["atencion_valida_min"].dropna()
    esperas = grupo["espera_valida_operativa_min"].dropna()

    return pd.Series({
        "turnos": len(grupo),
        "atenciones_validas": len(atenciones),
        "minutos_atencion": atenciones.sum(),
        "atencion_promedio_min": atenciones.mean(),
        "atencion_mediana_min": atenciones.median(),
        "atencion_p90_min": atenciones.quantile(0.90),
        "espera_promedio_min": esperas.mean(),
        "espera_p90_min": esperas.quantile(0.90),
        "esperas_mayores_30": int((esperas > 30).sum())
    })

# ------------------------------------------------------------
# 3. RESUMEN POR TIPO DE SERVICIO
# ------------------------------------------------------------

resumen_tipo_5176452 = (
    servicios_5176452
    .groupby("Tipo_servicio", dropna=False)
    .apply(
        indicadores_servicio_5176452,
        include_groups=False
    )
    .reset_index()
)

resumen_tipo_5176452["participacion_turnos_pct"] = (
    resumen_tipo_5176452["turnos"]
    / N_ORIGINAL * 100
)

total_minutos = (
    servicios_5176452["atencion_valida_min"].sum()
)

resumen_tipo_5176452["participacion_minutos_pct"] = (
    resumen_tipo_5176452["minutos_atencion"]
    / total_minutos * 100
)

resumen_tipo_5176452["pct_espera_mayor_30"] = (
    resumen_tipo_5176452["esperas_mayores_30"]
    / resumen_tipo_5176452["turnos"] * 100
)

print("\n1. RESUMEN POR TIPO DE SERVICIO")

display(
    resumen_tipo_5176452
    .sort_values("turnos", ascending=False)
    .round(2)
)

# ------------------------------------------------------------
# 4. RESUMEN POR SUBSERVICIO
# ------------------------------------------------------------

resumen_subservicio_5176452 = (
    servicios_5176452
    .groupby(
        ["Tipo_servicio", "SUBSERVICIO_HOMOLOGADO"],
        dropna=False
    )
    .apply(
        indicadores_servicio_5176452,
        include_groups=False
    )
    .reset_index()
)

resumen_subservicio_5176452["participacion_turnos_pct"] = (
    resumen_subservicio_5176452["turnos"]
    / N_ORIGINAL * 100
)

resumen_subservicio_5176452["participacion_minutos_pct"] = (
    resumen_subservicio_5176452["minutos_atencion"]
    / total_minutos * 100
)

print("\n2. 20 SUBSERVICIOS CON MAYOR DEMANDA")

display(
    resumen_subservicio_5176452
    .sort_values("turnos", ascending=False)
    .head(20)
    .round(2)
)

print("\n3. 20 SUBSERVICIOS CON MAYOR CARGA EN MINUTOS")

display(
    resumen_subservicio_5176452
    .sort_values("minutos_atencion", ascending=False)
    .head(20)
    .round(2)
)

# ------------------------------------------------------------
# 5. COMPARACIÓN ENTRE FRANJAS CRÍTICAS Y NO CRÍTICAS
# ------------------------------------------------------------

resumen_prioridad_5176452 = (
    servicios_5176452
    .groupby(
        ["prioridad_alta", "Tipo_servicio"],
        dropna=False
    )
    .apply(
        indicadores_servicio_5176452,
        include_groups=False
    )
    .reset_index()
)

resumen_prioridad_5176452["tipo_franja"] = np.where(
    resumen_prioridad_5176452["prioridad_alta"],
    "Prioridad alta",
    "Resto de franjas"
)

print("\n4. DEMANDA Y TIEMPOS SEGÚN PRIORIDAD")

display(
    resumen_prioridad_5176452[
        [
            "tipo_franja",
            "Tipo_servicio",
            "turnos",
            "minutos_atencion",
            "atencion_promedio_min",
            "atencion_p90_min",
            "espera_promedio_min",
            "espera_p90_min",
            "esperas_mayores_30"
        ]
    ].round(2)
)

# ------------------------------------------------------------
# 6. CONCILIACIONES
# ------------------------------------------------------------

assert int(resumen_tipo_5176452["turnos"].sum()) == N_ORIGINAL

assert int(
    resumen_subservicio_5176452["turnos"].sum()
) == N_ORIGINAL

assert int(
    resumen_prioridad_5176452["turnos"].sum()
) == N_ORIGINAL

assert np.isclose(
    resumen_tipo_5176452["minutos_atencion"].sum(),
    total_minutos
)

assert np.isclose(
    resumen_subservicio_5176452["minutos_atencion"].sum(),
    total_minutos
)

assert int(
    resumen_prioridad_5176452.loc[
        resumen_prioridad_5176452["prioridad_alta"],
        "turnos"
    ].sum()
) == N_CRITICOS

assert len(servicios_5176452) == N_ORIGINAL

print("\nVALIDACIÓN FINAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Turnos conciliados por tipo: "
    f"{int(resumen_tipo_5176452['turnos'].sum()):,}"
)
print(
    "Turnos conciliados por subservicio: "
    f"{int(resumen_subservicio_5176452['turnos'].sum()):,}"
)
print(f"Turnos críticos: {N_CRITICOS:,}")
print(f"Minutos de atención: {total_minutos:,.2f}")
print("Conciliación de registros: OK")
print("Conciliación de minutos: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.2. DEMANDA Y DURACIÓN DEL SERVICIO
======================================================================

1. RESUMEN POR TIPO DE SERVICIO

,Tipo_servicio,turnos,atenciones_validas,minutos_atencion,atencion_promedio_min,atencion_mediana_min,atencion_p90_min,espera_promedio_min,espera_p90_min,esperas_mayores_30,participacion_turnos_pct,participacion_minutos_pct,pct_espera_mayor_30
1,Servicio,636911.0,636911.0,3205849.88,5.03,3.97,10.00,7.12,20.80,28923.0,72.12,70.55,4.54
0,Comercial,246165.0,246165.0,1338184.92,5.44,4.63,10.47,3.25,11.57,5282.0,27.88,29.45,2.15

2. 20 SUBSERVICIOS CON MAYOR DEMANDA

,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,turnos,atenciones_validas,minutos_atencion,atencion_promedio_min,atencion_mediana_min,atencion_p90_min,espera_promedio_min,espera_p90_min,esperas_mayores_30,participacion_turnos_pct,participacion_minutos_pct
111,Servicio,Rad afiliacion trabajadores hasta 10 formularios,94137.0,94137.0,403931.03,4.29,3.43,8.25,7.60,19.08,2529.0,10.66,8.89
64,Servicio,Entrega tams primera vez,86012.0,86012.0,423289.60,4.92,4.25,9.35,7.30,23.13,4927.0,9.74,9.32
140,Servicio,Validacion afiliacion trabajador y/o beneficia...,42037.0,42037.0,202128.18,4.81,3.95,9.50,5.63,17.70,1504.0,4.76,4.45
33,Comercial,Radicacion cupo credito,32996.0,32996.0,179660.45,5.44,4.72,10.17,0.61,0.00,136.0,3.74,3.95
48,Servicio,Cambio de clave por olvido,31644.0,31644.0,101925.32,3.22,2.70,5.70,4.84,13.33,281.0,3.58,2.24
77,Servicio,Informacion general subsidio de vivienda,30561.0,30561.0,195935.55,6.41,5.55,12.02,8.06,24.13,1906.0,3.46,4.31
4,Comercial,Informacion credito consumo,30459.0,30459.0,182814.33,6.00,5.10,11.67,7.53,23.55,1918.0,3.45,4.02
122,Servicio,Radicacion postulacion de subsidio vivienda nueva,29991.0,29991.0,315002.02,10.50,8.80,21.02,7.85,21.20,1244.0,3.40,6.93
36,Comercial,Radicacion solicitudes consumo,29191.0,29191.0,166659.65,5.71,4.92,10.93,0.80,0.00,195.0,3.31,3.67
6,Comercial,Informacion cupo credito,28787.0,28787.0,169054.60,5.87,5.18,10.79,3.49,12.55,710.0,3.26,3.72
118,Servicio,Radicacion certificados escolares,23710.0,23710.0,72284.10,3.05,2.30,5.95,8.61,20.47,734.0,2.68,1.59
65,Servicio,Entrega tams reexpedicion,21805.0,21805.0,114540.40,5.25,4.60,9.62,9.03,26.01,1581.0,2.47,2.52
104,Servicio,Pqr's cuota monetaria,20581.0,20581.0,111595.52,5.42,4.72,10.20,7.99,25.58,1521.0,2.33,2.46
12,Comercial,Informacion y venta de boleteria piscitour,20249.0,20249.0,93693.18,4.63,3.95,8.88,3.63,12.00,227.0,2.29,2.06
102,Servicio,Pqr's administracion de afiliados,19834.0,19834.0,109777.02,5.53,4.87,10.25,7.23,22.88,1158.0,2.25,2.42
53,Servicio,Certificado afiliacion trabajador y/o benefici...,18591.0,18591.0,90543.98,4.87,4.05,9.70,8.55,24.95,1288.0,2.11,1.99
8,Comercial,Informacion hoteleria y turismo,17482.0,17482.0,109961.65,6.29,5.40,11.93,5.34,17.28,586.0,1.98,2.42
83,Servicio,Informacion subsidios de arrendamiento,16994.0,16994.0,86136.25,5.07,4.22,10.02,5.24,18.48,740.0,1.92,1.90
41,Servicio,Aclaracion procesos de cobranza,16616.0,16616.0,99232.72,5.97,5.17,11.20,10.17,27.90,1430.0,1.88,2.18
92,Servicio,Pago cupo credito,11657.0,11657.0,45856.10,3.93,3.43,6.82,4.72,12.88,132.0,1.32,1.01

3. 20 SUBSERVICIOS CON MAYOR CARGA EN MINUTOS

,Tipo_servicio,SUBSERVICIO_HOMOLOGADO,turnos,atenciones_validas,minutos_atencion,atencion_promedio_min,atencion_mediana_min,atencion_p90_min,espera_promedio_min,espera_p90_min,esperas_mayores_30,participacion_turnos_pct,participacion_minutos_pct
64,Servicio,Entrega tams primera vez,86012.0,86012.0,423289.60,4.92,4.25,9.35,7.30,23.13,4927.0,9.74,9.32
111,Servicio,Rad afiliacion trabajadores hasta 10 formularios,94137.0,94137.0,403931.03,4.29,3.43,8.25,7.60,19.08,2529.0,10.66,8.89
122,Servicio,Radicacion postulacion de subsidio vivienda nueva,29991.0,29991.0,315002.02,10.50,8.80,21.02,7.85,21.20,1244.0,3.40,6.93
140,Servicio,Validacion afiliacion trabajador y/o beneficia...,42037.0,42037.0,202128.18,4.81,3.95,9.50,5.63,17.70,1504.0,4.76,4.45
77,Servicio,Informacion general subsidio de vivienda,30561.0,30561.0,195935.55,6.41,5.55,12.02,8.06,24.13,1906.0,3.46,4.31
4,Comercial,Informacion credito consumo,30459.0,30459.0,182814.33,6.00,5.10,11.67,7.53,23.55,1918.0,3.45,4.02
33,Comercial,Radicacion cupo credito,32996.0,32996.0,179660.45,5.44,4.72,10.17,0.61,0.00,136.0,3.74,3.95
6,Comercial,Informacion cupo credito,28787.0,28787.0,169054.60,5.87,5.18,10.79,3.49,12.55,710.0,3.26,3.72
36,Comercial,Radicacion solicitudes consumo,29191.0,29191.0,166659.65,5.71,4.92,10.93,0.80,0.00,195.0,3.31,3.67
65,Servicio,Entrega tams reexpedicion,21805.0,21805.0,114540.40,5.25,4.60,9.62,9.03,26.01,1581.0,2.47,2.52
104,Servicio,Pqr's cuota monetaria,20581.0,20581.0,111595.52,5.42,4.72,10.20,7.99,25.58,1521.0,2.33,2.46
8,Comercial,Informacion hoteleria y turismo,17482.0,17482.0,109961.65,6.29,5.40,11.93,5.34,17.28,586.0,1.98,2.42
102,Servicio,Pqr's administracion de afiliados,19834.0,19834.0,109777.02,5.53,4.87,10.25,7.23,22.88,1158.0,2.25,2.42
48,Servicio,Cambio de clave por olvido,31644.0,31644.0,101925.32,3.22,2.70,5.70,4.84,13.33,281.0,3.58,2.24
41,Servicio,Aclaracion procesos de cobranza,16616.0,16616.0,99232.72,5.97,5.17,11.20,10.17,27.90,1430.0,1.88,2.18
12,Comercial,Informacion y venta de boleteria piscitour,20249.0,20249.0,93693.18,4.63,3.95,8.88,3.63,12.00,227.0,2.29,2.06
53,Servicio,Certificado afiliacion trabajador y/o benefici...,18591.0,18591.0,90543.98,4.87,4.05,9.70,8.55,24.95,1288.0,2.11,1.99
83,Servicio,Informacion subsidios de arrendamiento,16994.0,16994.0,86136.25,5.07,4.22,10.02,5.24,18.48,740.0,1.92,1.90
118,Servicio,Radicacion certificados escolares,23710.0,23710.0,72284.10,3.05,2.30,5.95,8.61,20.47,734.0,2.68,1.59
35,Comercial,Radicacion reserva,11391.0,11391.0,69934.07,6.14,5.25,12.02,2.06,5.82,175.0,1.29,1.54

4. DEMANDA Y TIEMPOS SEGÚN PRIORIDAD

,tipo_franja,Tipo_servicio,turnos,minutos_atencion,atencion_promedio_min,atencion_p90_min,espera_promedio_min,espera_p90_min,esperas_mayores_30
0,Resto de franjas,Comercial,202148.0,1098780.13,5.44,10.43,3.06,11.08,3571.0
1,Resto de franjas,Servicio,519374.0,2599684.75,5.01,9.93,6.59,19.18,18453.0
2,Prioridad alta,Comercial,44017.0,239404.78,5.44,10.62,4.09,14.56,1711.0
3,Prioridad alta,Servicio,117537.0,606165.13,5.16,10.33,9.47,28.34,10470.0

VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos conciliados por tipo: 883,076
Turnos conciliados por subservicio: 883,076
Turnos críticos: 161,554
Minutos de atención: 4,544,034.80
Conciliación de registros: OK
Conciliación de minutos: OK
Base original conservada: OK
======================================================================

In [102]:

# ============================================================
# 5.1.7.6.4.5.3. DISTRIBUCIÓN DE CARGA POR RECEPTOR
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.5.3. DISTRIBUCIÓN DE CARGA POR RECEPTOR")
print("=" * 70)

# 1. BASE INDEPENDIENTE

base_receptores_5176453 = base_capacidad_517645.copy(deep=True)

N_ORIGINAL = len(base_receptores_5176453)
N_CRITICOS = int(base_receptores_5176453["prioridad_alta"].sum())

assert N_ORIGINAL == 883076
assert N_CRITICOS == 161554

# Verificar variables antes de agrupar
columnas_requeridas = [
    "Sede",
    "Usuario_receptor",
    "Tipo_servicio",
    "prioridad_alta",
    "atencion_valida_min",
    "espera_valida_operativa_min"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in base_receptores_5176453.columns
]

assert not faltantes, f"Columnas faltantes: {faltantes}"

# 2. INDICADORES POR RECEPTOR Y SEDE

carga_receptor_sede_5176453 = (
    base_receptores_5176453
    .groupby(["Sede", "Usuario_receptor"], dropna=False)
    .agg(
        turnos=("Usuario_receptor", "size"),
        minutos_atencion=("atencion_valida_min", "sum"),
        atencion_promedio_min=("atencion_valida_min", "mean"),
        atencion_p90_min=(
            "atencion_valida_min",
            lambda x: x.quantile(0.90)
        ),
        espera_promedio_min=("espera_valida_operativa_min", "mean"),
        espera_p90_min=(
            "espera_valida_operativa_min",
            lambda x: x.quantile(0.90)
        ),
        turnos_criticos=("prioridad_alta", "sum")
    )
    .reset_index()
)

# Participación en la carga de cada sede
totales_sede = (
    carga_receptor_sede_5176453
    .groupby("Sede")[["turnos", "minutos_atencion"]]
    .transform("sum")
)

carga_receptor_sede_5176453["participacion_turnos_sede_pct"] = (
    carga_receptor_sede_5176453["turnos"]
    / totales_sede["turnos"] * 100
)

carga_receptor_sede_5176453["participacion_minutos_sede_pct"] = (
    carga_receptor_sede_5176453["minutos_atencion"]
    / totales_sede["minutos_atencion"] * 100
)

carga_receptor_sede_5176453["pct_turnos_criticos"] = (
    carga_receptor_sede_5176453["turnos_criticos"]
    / carga_receptor_sede_5176453["turnos"] * 100
)

print("\n1. 20 COMBINACIONES RECEPTOR-SEDE CON MÁS TURNOS")

display(
    carga_receptor_sede_5176453
    .sort_values("turnos", ascending=False)
    .head(20)
    .round(2)
)

print("\n2. 20 COMBINACIONES RECEPTOR-SEDE CON MÁS MINUTOS")

display(
    carga_receptor_sede_5176453
    .sort_values("minutos_atencion", ascending=False)
    .head(20)
    .round(2)
)

# 3. CONCENTRACIÓN DE CARGA POR SEDE

concentracion_sede_5176453 = (
    carga_receptor_sede_5176453
    .groupby("Sede", dropna=False)
    .agg(
        receptores_observados=("Usuario_receptor", "nunique"),
        turnos=("turnos", "sum"),
        minutos_atencion=("minutos_atencion", "sum"),
        mediana_turnos_receptor=("turnos", "median"),
        max_turnos_receptor=("turnos", "max")
    )
    .reset_index()
)

concentracion_sede_5176453["turnos_por_receptor_observado"] = (
    concentracion_sede_5176453["turnos"]
    / concentracion_sede_5176453["receptores_observados"]
)

concentracion_sede_5176453["minutos_por_receptor_observado"] = (
    concentracion_sede_5176453["minutos_atencion"]
    / concentracion_sede_5176453["receptores_observados"]
)

print("\n3. DISTRIBUCIÓN DE CARGA ENTRE SEDES")

display(
    concentracion_sede_5176453
    .sort_values("turnos", ascending=False)
    .round(2)
)

# 4. CARGA EN FRANJAS CRÍTICAS

carga_critica_receptor_5176453 = (
    base_receptores_5176453
    .loc[base_receptores_5176453["prioridad_alta"]]
    .groupby(["Sede", "Usuario_receptor"], dropna=False)
    .agg(
        turnos_criticos=("Usuario_receptor", "size"),
        minutos_criticos=("atencion_valida_min", "sum"),
        atencion_promedio_min=("atencion_valida_min", "mean"),
        espera_promedio_min=("espera_valida_operativa_min", "mean"),
        espera_p90_min=(
            "espera_valida_operativa_min",
            lambda x: x.quantile(0.90)
        )
    )
    .reset_index()
)

print("\n4. 20 RECEPTORES-SEDE CON MAYOR CARGA CRÍTICA")

display(
    carga_critica_receptor_5176453
    .sort_values("minutos_criticos", ascending=False)
    .head(20)
    .round(2)
)

# 5. RECEPTOR EN MÁS DE UNA SEDE

sedes_por_receptor_5176453 = (
    base_receptores_5176453
    .groupby("Usuario_receptor", dropna=False)["Sede"]
    .nunique()
    .reset_index(name="sedes_distintas")
)

multisede_5176453 = (
    sedes_por_receptor_5176453
    .query("sedes_distintas > 1")
    .sort_values("sedes_distintas", ascending=False)
)

print("\n5. RECEPTORES REGISTRADOS EN VARIAS SEDES")
print("Receptores multisede:", len(multisede_5176453))

display(multisede_5176453.head(20))

# 6. VALIDACIÓN

assert int(carga_receptor_sede_5176453["turnos"].sum()) == N_ORIGINAL
assert int(concentracion_sede_5176453["turnos"].sum()) == N_ORIGINAL

assert int(
    carga_critica_receptor_5176453["turnos_criticos"].sum()
) == N_CRITICOS

assert np.isclose(
    carga_receptor_sede_5176453["minutos_atencion"].sum(),
    base_receptores_5176453["atencion_valida_min"].sum()
)

assert len(base_receptores_5176453) == N_ORIGINAL

print("\nVALIDACIÓN FINAL")
print(f"Turnos originales: {N_ORIGINAL:,}")
print(
    "Turnos conciliados por receptor-sede: "
    f"{int(carga_receptor_sede_5176453['turnos'].sum()):,}"
)
print(f"Turnos críticos conciliados: {N_CRITICOS:,}")
print(
    "Receptores únicos: "
    f"{base_receptores_5176453['Usuario_receptor'].nunique():,}"
)
print(
    "Combinaciones receptor-sede: "
    f"{len(carga_receptor_sede_5176453):,}"
)
print("Conciliación de registros: OK")
print("Conciliación de minutos: OK")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.3. DISTRIBUCIÓN DE CARGA POR RECEPTOR
======================================================================

1. 20 COMBINACIONES RECEPTOR-SEDE CON MÁS TURNOS

,Sede,Usuario_receptor,turnos,minutos_atencion,atencion_promedio_min,atencion_p90_min,espera_promedio_min,espera_p90_min,turnos_criticos,participacion_turnos_sede_pct,participacion_minutos_sede_pct,pct_turnos_criticos
176,Tintal plaza,1010208374,20331,60462.50,2.97,6.58,3.76,14.50,5580,18.10,13.65,27.45
189,Tintal plaza,1077865422,18720,62021.48,3.31,5.47,5.07,19.35,5146,16.67,14.00,27.49
139,Soacha,1024546447,16591,64024.10,3.86,7.97,6.22,19.70,2179,17.82,13.65,13.13
199,Tintal plaza,52988267,16445,59055.83,3.59,7.30,3.99,14.82,4485,14.64,13.33,27.27
18,Calle 26,1033797428,14310,69675.88,4.87,7.82,4.17,14.57,4285,9.11,7.55,29.94
105,Girardot,1082124871,14295,72190.45,5.05,10.30,6.89,14.50,0,30.15,28.98,0.00
67,Centro mayor,1024506461,14233,48779.12,3.43,5.87,5.30,21.14,6051,17.99,11.76,42.51
93,Fusagasuga,1069728036,13759,55007.50,4.00,7.70,4.41,14.94,0,30.43,25.36,0.00
198,Tintal plaza,52952196,13498,41258.55,3.06,5.92,4.03,13.62,3961,12.02,9.31,29.35
137,Soacha,1024513266,12894,69337.33,5.38,10.65,7.24,21.57,1492,13.85,14.79,11.57
174,Suba,91518611,12851,62208.98,4.84,9.38,7.31,25.58,4899,15.73,13.65,38.12
13,Calle 26,1030591341,12137,75937.65,6.26,12.21,3.67,13.37,3504,7.73,8.23,28.87
106,Girardot,39569485,12064,75547.37,6.26,12.63,5.58,15.72,0,25.44,30.33,0.00
90,Funza,1073162619,11906,49261.07,4.14,9.55,4.04,14.30,0,22.15,23.01,0.00
19,Calle 26,1103714304,11577,30260.37,2.61,4.46,3.38,11.53,3783,7.37,3.28,32.68
210,Unicentro de occidente,1015428656,11508,70168.58,6.10,10.23,5.98,20.77,332,20.43,23.08,2.88
143,Soacha,1033724471,11422,67862.73,5.94,9.95,6.22,20.31,1482,12.27,14.47,12.97
89,Funza,1072962277,11282,46427.65,4.12,8.30,4.13,13.62,0,20.98,21.68,0.00
213,Unicentro de occidente,1016038265,11151,65569.77,5.88,10.72,7.07,23.17,357,19.79,21.56,3.20
99,Fusagasuga,82393782,11040,70740.02,6.41,11.20,4.79,15.87,0,24.41,32.61,0.00

2. 20 COMBINACIONES RECEPTOR-SEDE CON MÁS MINUTOS

,Sede,Usuario_receptor,turnos,minutos_atencion,atencion_promedio_min,atencion_p90_min,espera_promedio_min,espera_p90_min,turnos_criticos,participacion_turnos_sede_pct,participacion_minutos_sede_pct,pct_turnos_criticos
13,Calle 26,1030591341,12137,75937.65,6.26,12.21,3.67,13.37,3504,7.73,8.23,28.87
106,Girardot,39569485,12064,75547.37,6.26,12.63,5.58,15.72,0,25.44,30.33,0.00
36,Calle 26,80156054,10120,73919.45,7.30,13.90,6.06,20.54,2940,6.44,8.01,29.05
105,Girardot,1082124871,14295,72190.45,5.05,10.30,6.89,14.50,0,30.15,28.98,0.00
99,Fusagasuga,82393782,11040,70740.02,6.41,11.20,4.79,15.87,0,24.41,32.61,0.00
210,Unicentro de occidente,1015428656,11508,70168.58,6.10,10.23,5.98,20.77,332,20.43,23.08,2.88
10,Calle 26,1024494171,10595,70143.72,6.62,11.97,5.05,17.58,2999,6.75,7.60,28.31
18,Calle 26,1033797428,14310,69675.88,4.87,7.82,4.17,14.57,4285,9.11,7.55,29.94
22,Calle 26,52259961,10569,69482.60,6.57,12.02,4.94,16.97,3101,6.73,7.53,29.34
137,Soacha,1024513266,12894,69337.33,5.38,10.65,7.24,21.57,1492,13.85,14.79,11.57
23,Calle 26,52273627,10136,68466.93,6.75,12.53,5.09,18.46,3003,6.45,7.42,29.63
143,Soacha,1033724471,11422,67862.73,5.94,9.95,6.22,20.31,1482,12.27,14.47,12.97
35,Calle 26,53167689,8966,65904.38,7.35,11.78,6.83,23.02,2764,5.71,7.14,30.83
213,Unicentro de occidente,1016038265,11151,65569.77,5.88,10.72,7.07,23.17,357,19.79,21.56,3.20
26,Calle 26,52506017,10451,65019.68,6.22,11.33,3.93,14.48,2981,6.65,7.05,28.52
139,Soacha,1024546447,16591,64024.10,3.86,7.97,6.22,19.70,2179,17.82,13.65,13.13
121,Santa librada,39800277,8262,63241.97,7.65,14.92,5.68,19.58,0,20.25,24.02,0.00
174,Suba,91518611,12851,62208.98,4.84,9.38,7.31,25.58,4899,15.73,13.65,38.12
189,Tintal plaza,1077865422,18720,62021.48,3.31,5.47,5.07,19.35,5146,16.67,14.00,27.49
157,Suba,1015395361,9038,61147.03,6.77,14.07,7.20,25.42,3513,11.06,13.41,38.87

3. DISTRIBUCIÓN DE CARGA ENTRE SEDES

,Sede,receptores_observados,turnos,minutos_atencion,mediana_turnos_receptor,max_turnos_receptor,turnos_por_receptor_observado,minutos_por_receptor_observado
0,Calle 26,38,157060,922595.45,1877.0,14310,4133.16,24278.83
10,Tintal plaza,31,112312,442944.48,598.0,20331,3622.97,14288.53
8,Soacha,26,93104,468967.33,996.0,16591,3580.92,18037.21
9,Suba,21,81721,455827.10,1031.0,12851,3891.48,21706.05
2,Centro mayor,24,79106,414700.93,1334.5,14233,3296.08,17279.21
11,Unicentro de occidente,29,56338,304067.07,183.0,11508,1942.69,10485.07
12,Usaquen,20,55305,272403.43,706.0,10926,2765.25,13620.17
3,Funza,8,53763,214112.05,9350.0,11906,6720.38,26764.01
1,Calle 63,23,47613,258483.20,339.0,10265,2070.13,11238.40
5,Girardot,7,47419,249079.30,9394.0,14295,6774.14,35582.76
4,Fusagasuga,7,45219,216913.72,8740.0,13759,6459.86,30987.67
7,Santa librada,18,40790,263285.53,667.5,8759,2266.11,14626.97
6,La mesa,3,13326,60655.20,5568.0,7287,4442.00,20218.40

4. 20 RECEPTORES-SEDE CON MAYOR CARGA CRÍTICA

,Sede,Usuario_receptor,turnos_criticos,minutos_criticos,atencion_promedio_min,espera_promedio_min,espera_p90_min
104,Suba,91518611,4899,24296.00,4.96,8.30,29.80
87,Suba,1015395361,3513,23673.92,6.74,8.35,28.75
13,Calle 26,1030591341,3504,22212.38,6.34,5.20,20.73
36,Calle 26,80156054,2940,22108.67,7.52,8.81,29.87
51,Centro mayor,1233695721,2296,21618.07,9.42,11.57,37.48
18,Calle 26,1033797428,4285,21152.62,4.94,5.64,21.59
22,Calle 26,52259961,3101,21135.62,6.82,7.23,26.42
95,Suba,1032453195,3684,20778.57,5.64,11.35,32.77
102,Suba,52986936,3339,20670.50,6.19,9.21,23.68
101,Suba,52932041,2874,20635.02,7.18,10.91,32.36
44,Centro mayor,1024506461,6051,20505.02,3.39,6.66,28.68
35,Calle 26,53167689,2764,20475.57,7.41,9.22,31.55
23,Calle 26,52273627,3003,20423.40,6.80,6.62,24.78
10,Calle 26,1024494171,2999,20269.67,6.76,7.09,26.35
98,Suba,51948524,3282,20056.67,6.11,7.65,27.38
56,Centro mayor,52887154,2892,19134.65,6.62,8.46,30.96
26,Calle 26,52506017,2981,18928.03,6.35,5.96,23.28
38,Centro mayor,1010170232,3492,18292.52,5.24,8.93,33.88
27,Calle 26,52622358,2998,17939.07,5.98,8.17,23.16
119,Tintal plaza,1077865422,5146,17037.53,3.31,6.80,26.40

5. RECEPTORES REGISTRADOS EN VARIAS SEDES
Receptores multisede: 62

    Usuario_receptor  sedes_distintas
80          39767666                8
13        1016065011                7
53        1033714051                7
40        1024544431                7
106         53031632                7
3         1010170232                6
51        1032453195                6
1         1007345774                6
5         1014220989                6
20        1019125029                5
94          52757929                5
9         1015995249                4
44        1024571914                4
28        1022935552                4
104         53003630                4
109         53152781                4
118         91518611                4
96          52848017                4
18        1018445026                4
21        1020767191                4

VALIDACIÓN FINAL
Turnos originales: 883,076
Turnos conciliados por receptor-sede: 883,076
Turnos críticos conciliados: 161,554
Receptores únicos: 121
Combinaciones receptor-sede: 255
Conciliación de registros: OK
Conciliación de minutos: OK
Base original conservada: OK
======================================================================

In [2]:

# ================================================================
# 5.1.7.6.4.5.5.1. CONSISTENCIA TEMPORAL Y SOLAPAMIENTOS
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import unicodedata

# ------------------------------------------------
# 1. Localización y lectura de la base original
# ------------------------------------------------

ruta_base = Path.cwd()

if ruta_base.name.lower() == "notebooks":
    ruta_base = ruta_base.parent

archivo = ruta_base / "data" / "raw" / "T_DIGITURNOS.csv"

if not archivo.exists():
    raise FileNotFoundError(
        f"No se encontró el archivo: {archivo}"
    )

def leer_csv_robusto(ruta):
    for codificacion in ("utf-8-sig", "utf-8", "cp1252", "latin-1"):
        try:
            return pd.read_csv(
                ruta,
                encoding=codificacion,
                sep=None,
                engine="python",
                dtype="string",
                low_memory=False
            )
        except (UnicodeError, ValueError):
            continue
    raise ValueError("No fue posible leer el archivo CSV.")

# sep=None y low_memory=False no son compatibles
# en algunas versiones de pandas; lectura corregida:
def leer_csv_robusto(ruta):
    for codificacion in ("utf-8-sig", "utf-8", "cp1252", "latin-1"):
        try:
            return pd.read_csv(
                ruta,
                encoding=codificacion,
                sep=None,
                engine="python",
                dtype="string"
            )
        except (UnicodeError, ValueError):
            continue
    raise ValueError("No fue posible leer el archivo CSV.")

df_sol = leer_csv_robusto(archivo).copy()

n_original = len(df_sol)
df_sol["id_registro_original"] = np.arange(n_original)

# ------------------------------------------------
# 2. Normalización de nombres de columnas
# ------------------------------------------------

def normalizar_nombre(texto):
    texto = unicodedata.normalize("NFKD", str(texto))
    texto = "".join(
        c for c in texto
        if not unicodedata.combining(c)
    )
    return "".join(
        c.lower() for c in texto if c.isalnum()
    )

mapa_columnas = {
    normalizar_nombre(c): c
    for c in df_sol.columns
}

columnas_requeridas = {
    "sede": "Sede",
    "receptor": "Usuario_receptor",
    "fecha": "Fecha_Servico",
    "solicitud": "Hora_solicitud_Servicio",
    "llamado": "Hora_llamado__Servicio",
    "finalizacion": "Hora_finalizado_Servicio"
}

columnas_encontradas = {}

for clave, nombre in columnas_requeridas.items():
    nombre_normalizado = normalizar_nombre(nombre)
    if nombre_normalizado not in mapa_columnas:
        raise KeyError(
            f"Columna faltante: {nombre}. "
            f"Disponibles: {df_sol.columns.tolist()}"
        )
    columnas_encontradas[clave] = mapa_columnas[nombre_normalizado]

# ------------------------------------------------
# 3. Construcción de fechas y horas
# ------------------------------------------------

col_fecha = columnas_encontradas["fecha"]

fecha = pd.to_datetime(
    df_sol[col_fecha],
    errors="coerce",
    dayfirst=True
)

def construir_fecha_hora(fecha_base, valores):
    texto = valores.astype("string").str.strip()

    # Extraer hora cuando viene acompañada de una fecha
    hora = texto.str.extract(
        r"(\d{1,2}:\d{2}(?::\d{2}(?:\.\d+)?)?)",
        expand=False
    )

    fecha_texto = fecha_base.dt.strftime("%Y-%m-%d")

    return pd.to_datetime(
        fecha_texto + " " + hora,
        errors="coerce"
    )

df_sol["dt_solicitud"] = construir_fecha_hora(
    fecha, df_sol[columnas_encontradas["solicitud"]]
)

df_sol["dt_llamado"] = construir_fecha_hora(
    fecha, df_sol[columnas_encontradas["llamado"]]
)

df_sol["dt_finalizacion"] = construir_fecha_hora(
    fecha, df_sol[columnas_encontradas["finalizacion"]]
)

# NOTA:
# No se corrigen automáticamente cruces de medianoche.
# Deben auditarse antes de aplicar cualquier ajuste.

# ------------------------------------------------
# 4. Validación temporal
# ------------------------------------------------

df_sol["receptor"] = (
    df_sol[columnas_encontradas["receptor"]]
    .astype("string")
    .str.strip()
)

df_sol["sede"] = (
    df_sol[columnas_encontradas["sede"]]
    .astype("string")
    .str.strip()
)

df_sol["fecha_incompleta"] = df_sol[
    ["dt_solicitud", "dt_llamado", "dt_finalizacion"]
].isna().any(axis=1)

df_sol["secuencia_invalida"] = (
    (df_sol["dt_llamado"] < df_sol["dt_solicitud"]) |
    (df_sol["dt_finalizacion"] < df_sol["dt_llamado"])
)

df_sol["duracion_atencion_min"] = (
    df_sol["dt_finalizacion"] -
    df_sol["dt_llamado"]
).dt.total_seconds() / 60

df_sol["intervalo_valido"] = (
    ~df_sol["fecha_incompleta"] &
    ~df_sol["secuencia_invalida"] &
    df_sol["receptor"].notna() &
    df_sol["sede"].notna() &
    (df_sol["duracion_atencion_min"] > 0)
)

# ------------------------------------------------
# 5. Detección de solapamientos
# ------------------------------------------------
# Se compara cada atención con todas las atenciones
# previas todavía activas del mismo receptor.
# Esto evita omitir solapamientos anidados.

validos = df_sol.loc[
    df_sol["intervalo_valido"],
    [
        "id_registro_original", "receptor", "sede",
        "dt_llamado", "dt_finalizacion"
    ]
].sort_values(
    ["receptor", "dt_llamado", "dt_finalizacion"]
)

hallazgos = []

for receptor, grupo in validos.groupby(
    "receptor", sort=False
):
    activos = []

    for fila in grupo.itertuples(index=False):
        inicio = fila.dt_llamado
        fin = fila.dt_finalizacion

        activos = [
            anterior for anterior in activos
            if anterior["fin"] > inicio
        ]

        for anterior in activos:
            minutos = (
                min(fin, anterior["fin"]) -
                max(inicio, anterior["inicio"])
            ).total_seconds() / 60

            if minutos > 0:
                hallazgos.append({
                    "receptor": receptor,
                    "registro_1": anterior["id"],
                    "registro_2": fila.id_registro_original,
                    "sede_1": anterior["sede"],
                    "sede_2": fila.sede,
                    "tipo_solapamiento": (
                        "Entre sedes"
                        if anterior["sede"] != fila.sede
                        else "Misma sede"
                    ),
                    "minutos_solapados": minutos
                })

        activos.append({
            "id": fila.id_registro_original,
            "sede": fila.sede,
            "inicio": inicio,
            "fin": fin
        })

df_solapamientos = pd.DataFrame(
    hallazgos,
    columns=[
        "receptor", "registro_1", "registro_2",
        "sede_1", "sede_2", "tipo_solapamiento",
        "minutos_solapados"
    ]
)

# ------------------------------------------------
# 6. Resumen de auditoría
# ------------------------------------------------

registros_afectados = set(
    df_solapamientos["registro_1"]
) | set(
    df_solapamientos["registro_2"]
)

resumen_sol = pd.DataFrame({
    "indicador": [
        "Turnos originales",
        "Intervalos de atención válidos",
        "Fechas u horas incompletas",
        "Secuencias temporales inválidas",
        "Atenciones de duración cero",
        "Pares de atenciones solapadas",
        "Solapamientos entre sedes",
        "Solapamientos en la misma sede",
        "Registros involucrados en solapamientos",
        "Receptores involucrados en solapamientos"
    ],
    "resultado": [
        n_original,
        int(df_sol["intervalo_valido"].sum()),
        int(df_sol["fecha_incompleta"].sum()),
        int(df_sol["secuencia_invalida"].sum()),
        int((df_sol["duracion_atencion_min"] == 0).sum()),
        len(df_solapamientos),
        int((
            df_solapamientos["tipo_solapamiento"]
            == "Entre sedes"
        ).sum()),
        int((
            df_solapamientos["tipo_solapamiento"]
            == "Misma sede"
        ).sum()),
        len(registros_afectados),
        df_solapamientos["receptor"].nunique()
    ]
})

print("=" * 70)
print("5.1.7.6.4.5.5.1. AUDITORÍA DE SOLAPAMIENTOS")
print("=" * 70)

display(resumen_sol)

print("\nSOLAPAMIENTOS POR TIPO")
display(
    df_solapamientos.groupby(
        "tipo_solapamiento",
        dropna=False
    ).agg(
        pares=("receptor", "size"),
        receptores=("receptor", "nunique"),
        minutos_solapados_pares=(
            "minutos_solapados", "sum"
        )
    ).reset_index()
)

print("\nEJEMPLOS DE SOLAPAMIENTOS ENTRE SEDES")
display(
    df_solapamientos.loc[
        df_solapamientos["tipo_solapamiento"]
        == "Entre sedes"
    ].sort_values(
        "minutos_solapados", ascending=False
    ).head(20)
)

print("\nVALIDACIÓN DE CONSERVACIÓN")
assert len(df_sol) == n_original
assert df_sol["id_registro_original"].is_unique

print(f"Registros originales: {n_original:,}")
print(f"Registros conservados: {len(df_sol):,}")
print("Conservación de registros: OK")
print("Base original sin modificaciones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.5.1. AUDITORÍA DE SOLAPAMIENTOS
======================================================================

                                  indicador  resultado
0                         Turnos originales    1016267
1            Intervalos de atención válidos     883076
2                Fechas u horas incompletas     133187
3           Secuencias temporales inválidas          4
4               Atenciones de duración cero          2
5             Pares de atenciones solapadas        251
6                 Solapamientos entre sedes          8
7            Solapamientos en la misma sede        243
8   Registros involucrados en solapamientos        310
9  Receptores involucrados en solapamientos         19

SOLAPAMIENTOS POR TIPO

  tipo_solapamiento  pares  receptores  minutos_solapados_pares
0       Entre sedes      8           2                18.116667
1        Misma sede    243          19               762.050000

EJEMPLOS DE SOLAPAMIENTOS ENTRE SEDES

,receptor,registro_1,registro_2,sede_1,sede_2,tipo_solapamiento,minutos_solapados
89,1016065011,487651,767361,Soacha,Tintal plaza,Entre sedes,7.183333
88,1016065011,487652,692893,Soacha,Tintal plaza,Entre sedes,6.416667
201,39767666,493496,756076,Soacha,Tintal plaza,Entre sedes,2.633333
203,39767666,564493,678191,Soacha,Tintal plaza,Entre sedes,0.750000
204,39767666,564493,679431,Soacha,Tintal plaza,Entre sedes,0.716667
205,39767666,543034,736941,Soacha,Tintal plaza,Entre sedes,0.233333
206,39767666,539341,663462,Soacha,Tintal plaza,Entre sedes,0.133333
202,39767666,508857,722257,Soacha,Tintal plaza,Entre sedes,0.050000

VALIDACIÓN DE CONSERVACIÓN
Registros originales: 1,016,267
Registros conservados: 1,016,267
Conservación de registros: OK
Base original sin modificaciones: OK
======================================================================

In [3]:

# ==========================================================
# 5.1.7.6.4.5.5.1.1. CONCILIACIÓN DE COMPLETITUD TEMPORAL
# ==========================================================

print("=" * 70)
print("CONCILIACIÓN DE REGISTROS Y COMPLETITUD TEMPORAL")
print("=" * 70)

# 1. Completitud por campo
campos = [
    "dt_solicitud",
    "dt_llamado",
    "dt_finalizacion"
]

resumen_completitud = pd.DataFrame({
    "campo": campos,
    "registros_completos": [
        int(df_sol[c].notna().sum()) for c in campos
    ],
    "registros_incompletos": [
        int(df_sol[c].isna().sum()) for c in campos
    ]
})

resumen_completitud["pct_incompletos"] = (
    resumen_completitud["registros_incompletos"]
    / len(df_sol) * 100
).round(2)

display(resumen_completitud)

# 2. Combinaciones de completitud
patrones = pd.DataFrame({
    "solicitud": df_sol["dt_solicitud"].notna(),
    "llamado": df_sol["dt_llamado"].notna(),
    "finalizacion": df_sol["dt_finalizacion"].notna()
})

patrones_resumen = (
    patrones.value_counts(dropna=False)
    .rename("registros")
    .reset_index()
    .sort_values("registros", ascending=False)
)

display(patrones_resumen)

# 3. Incompletitud por sede
resumen_sedes = (
    df_sol.groupby("sede", dropna=False)
    .agg(
        registros=("id_registro_original", "size"),
        incompletos=("fecha_incompleta", "sum"),
        intervalos_validos=("intervalo_valido", "sum")
    )
    .reset_index()
)

resumen_sedes["pct_incompletos"] = (
    resumen_sedes["incompletos"]
    / resumen_sedes["registros"] * 100
).round(2)

display(
    resumen_sedes.sort_values(
        "incompletos", ascending=False
    )
)

# 4. Ejemplos de valores originales incompletos
columnas_originales = [
    columnas_encontradas["fecha"],
    columnas_encontradas["solicitud"],
    columnas_encontradas["llamado"],
    columnas_encontradas["finalizacion"]
]

print("\nEJEMPLOS DE REGISTROS CON TIEMPOS INCOMPLETOS")

display(
    df_sol.loc[
        df_sol["fecha_incompleta"],
        ["id_registro_original", "sede"] + columnas_originales
    ].head(20)
)

# 5. Conciliación
print("\nVALIDACIÓN FINAL")
print(f"Registros originales: {len(df_sol):,}")
print(f"Registros con intervalos válidos: {df_sol['intervalo_valido'].sum():,}")
print(f"Registros con tiempos incompletos: {df_sol['fecha_incompleta'].sum():,}")
print(f"Secuencias inválidas: {df_sol['secuencia_invalida'].sum():,}")
print("Base original conservada: OK")
print("=" * 70)

======================================================================
CONCILIACIÓN DE REGISTROS Y COMPLETITUD TEMPORAL
======================================================================

,campo,registros_completos,registros_incompletos,pct_incompletos
0,dt_solicitud,883080,133187,13.11
1,dt_llamado,883080,133187,13.11
2,dt_finalizacion,883080,133187,13.11

   solicitud  llamado  finalizacion  registros
0       True     True          True     883080
1      False    False         False     133187

,sede,registros,incompletos,intervalos_validos,pct_incompletos
13,<NA>,133187,133187,0,100.0
0,Calle 26,157060,0,157060,0.0
2,Centro mayor,79106,0,79106,0.0
3,Funza,53764,0,53763,0.0
4,Fusagasuga,45219,0,45219,0.0
1,Calle 63,47613,0,47613,0.0
5,Girardot,47419,0,47419,0.0
6,La mesa,13326,0,13326,0.0
8,Soacha,93106,0,93104,0.0
7,Santa librada,40791,0,40790,0.0
9,Suba,81721,0,81721,0.0
10,Tintal plaza,112312,0,112312,0.0
11,Unicentro de occidente,56338,0,56338,0.0
12,Usaquen,55305,0,55305,0.0

EJEMPLOS DE REGISTROS CON TIEMPOS INCOMPLETOS

,id_registro_original,sede,Fecha_Servico,Hora_solicitud_Servicio,Hora_llamado__Servicio,Hora_finalizado_Servicio
883080,883080,<NA>,<NA>,<NA>,<NA>,<NA>
883081,883081,<NA>,<NA>,<NA>,<NA>,<NA>
883082,883082,<NA>,<NA>,<NA>,<NA>,<NA>
883083,883083,<NA>,<NA>,<NA>,<NA>,<NA>
883084,883084,<NA>,<NA>,<NA>,<NA>,<NA>
883085,883085,<NA>,<NA>,<NA>,<NA>,<NA>
883086,883086,<NA>,<NA>,<NA>,<NA>,<NA>
883087,883087,<NA>,<NA>,<NA>,<NA>,<NA>
883088,883088,<NA>,<NA>,<NA>,<NA>,<NA>
883089,883089,<NA>,<NA>,<NA>,<NA>,<NA>
883090,883090,<NA>,<NA>,<NA>,<NA>,<NA>
883091,883091,<NA>,<NA>,<NA>,<NA>,<NA>
883092,883092,<NA>,<NA>,<NA>,<NA>,<NA>
883093,883093,<NA>,<NA>,<NA>,<NA>,<NA>
883094,883094,<NA>,<NA>,<NA>,<NA>,<NA>
883095,883095,<NA>,<NA>,<NA>,<NA>,<NA>
883096,883096,<NA>,<NA>,<NA>,<NA>,<NA>
883097,883097,<NA>,<NA>,<NA>,<NA>,<NA>
883098,883098,<NA>,<NA>,<NA>,<NA>,<NA>
883099,883099,<NA>,<NA>,<NA>,<NA>,<NA>

VALIDACIÓN FINAL
Registros originales: 1,016,267
Registros con intervalos válidos: 883,076
Registros con tiempos incompletos: 133,187
Secuencias inválidas: 4
Base original conservada: OK
======================================================================

In [4]:

from pathlib import Path
import pandas as pd

print("=" * 70)
print("5.1.7.6.4.5.5.1.2. AUDITORÍA DE PROCEDENCIA")
print("=" * 70)

# 1. Revisar el DataFrame utilizado
print("\nESTRUCTURA DE df_sol")
print("Filas:", len(df_sol))
print("Índice único:", df_sol.index.is_unique)
print("Primer índice:", df_sol.index[0])
print("Último índice:", df_sol.index[-1])

# 2. Localizar registros completamente vacíos
#    en los campos originales de atención
campos_fuente = [
    "Fecha_Servico",
    "Hora_solicitud_Servicio",
    "Hora_llamado__Servicio",
    "Hora_finalizado_Servicio"
]

# Utilizar los nombres reales ya identificados
campos_fuente = [
    columnas_encontradas["fecha"],
    columnas_encontradas["solicitud"],
    columnas_encontradas["llamado"],
    columnas_encontradas["finalizacion"]
]

vacios_fuente = df_sol[campos_fuente].isna().all(axis=1)

print("\nFILAS SIN INFORMACIÓN TEMPORAL ORIGINAL")
print("Total:", int(vacios_fuente.sum()))
print("Primeros índices:", df_sol.index[vacios_fuente][:10].tolist())

# 3. Verificar continuidad del bloque vacío
posiciones_vacias = [
    i for i, valor in enumerate(vacios_fuente.to_numpy())
    if valor
]

if posiciones_vacias:
    print("Primera posición vacía:", posiciones_vacias[0])
    print("Última posición vacía:", posiciones_vacias[-1])
    print(
        "Todas las filas vacías están al final:",
        posiciones_vacias == list(
            range(posiciones_vacias[0], len(df_sol))
        )
    )

# 4. Examinar otras columnas de las filas sospechosas
print("\nCOMPLETITUD DE LAS FILAS SOSPECHOSAS")
print(
    df_sol.loc[vacios_fuente]
    .notna()
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

# 5. Verificar la existencia del archivo fuente
archivo = Path("data/raw/T_DIGITURNOS.csv")

print("\nARCHIVO FUENTE")
print("Existe:", archivo.exists())

if archivo.exists():
    fuente = pd.read_csv(
        archivo,
        sep=None,
        engine="python",
        encoding="utf-8-sig",
        low_memory=False
    )
    print("Registros fuente:", len(fuente))
    print("Columnas fuente:", len(fuente.columns))

print("\nVALIDACIÓN COMPLETADA SIN MODIFICAR df_sol")
print("=" * 70)

======================================================================
5.1.7.6.4.5.5.1.2. AUDITORÍA DE PROCEDENCIA
======================================================================

ESTRUCTURA DE df_sol
Filas: 1016267
Índice único: True
Primer índice: 0
Último índice: 1016266

FILAS SIN INFORMACIÓN TEMPORAL ORIGINAL
Total: 133187
Primeros índices: [883080, 883081, 883082, 883083, 883084, 883085, 883086, 883087, 883088, 883089]
Primera posición vacía: 883080
Última posición vacía: 1016266
Todas las filas vacías están al final: True

COMPLETITUD DE LAS FILAS SOSPECHOSAS
fecha_incompleta            133187
id_registro_original        133187
secuencia_invalida          133187
intervalo_valido            133187
Sede                             0
UES                              0
SUBSERVICIO_HOMOLOGADO           0
Tipo_servicio                    0
Usuario_receptor                 0
Clasifiacion                     0
Hora_finalizado_Servicio         0
Fecha_Servico                    0
Hora_llamado__Servicio           0
Hora_solicitud_Servicio          0
dt_solicitud                     0
Tipo_Oficina                     0
Identificacion_Cliente           0
dt_llamado                       0
sede                             0
receptor                         0
dtype: int64

ARCHIVO FUENTE
Existe: False

VALIDACIÓN COMPLETADA SIN MODIFICAR df_sol
======================================================================

In [5]:

# ==========================================================
# 5.1.7.6.4.5.5.1.3.
# CORRECCIÓN DEL UNIVERSO DE AUDITORÍA
# ==========================================================

import pandas as pd

print("=" * 70)
print("CORRECCIÓN DEL UNIVERSO DE AUDITORÍA")
print("=" * 70)

# 1. Identificar filas con información original
columnas_origen = [
    "Sede",
    "UES",
    "SUBSERVICIO_HOMOLOGADO",
    columnas_encontradas["fecha"],
    columnas_encontradas["solicitud"],
    columnas_encontradas["llamado"],
    columnas_encontradas["finalizacion"]
]

columnas_origen = list(dict.fromkeys(columnas_origen))

faltantes = [
    c for c in columnas_origen
    if c not in df_sol.columns
]

assert not faltantes, (
    f"Columnas originales no encontradas: {faltantes}"
)

# 2. Distinguir filas sin información de origen
sin_informacion_origen = (
    df_sol[columnas_origen].isna().all(axis=1)
)

# 3. Crear copia independiente
df_sol_auditado = (
    df_sol.loc[~sin_informacion_origen]
    .copy()
)

# 4. Conciliar universos
print(f"Filas en df_sol: {len(df_sol):,}")
print(
    "Filas sin información de origen:",
    f"{sin_informacion_origen.sum():,}"
)
print(
    "Filas en df_sol_auditado:",
    f"{len(df_sol_auditado):,}"
)

assert (
    len(df_sol_auditado)
    + int(sin_informacion_origen.sum())
    == len(df_sol)
)

assert len(df_sol_auditado) == 883080, (
    "El universo resultante no coincide con "
    "el observado. Revisar antes de continuar."
)

# 5. Validar intervalos temporales
print("\nVALIDACIÓN TEMPORAL")

print(
    "Intervalos válidos:",
    f"{df_sol_auditado['intervalo_valido'].sum():,}"
)

print(
    "Secuencias inválidas:",
    f"{df_sol_auditado['secuencia_invalida'].sum():,}"
)

print(
    "Fechas incompletas:",
    f"{df_sol_auditado['fecha_incompleta'].sum():,}"
)

assert int(
    df_sol_auditado["intervalo_valido"].sum()
) == 883076

# 6. Comprobar que df_sol no fue alterado
assert len(df_sol) == 1016267

print("\nRESULTADO")
print("Universo de auditoría corregido: OK")
print("Base de trabajo original conservada: OK")
print("=" * 70)

======================================================================
CORRECCIÓN DEL UNIVERSO DE AUDITORÍA
======================================================================
Filas en df_sol: 1,016,267
Filas sin información de origen: 133,187
Filas en df_sol_auditado: 883,080

VALIDACIÓN TEMPORAL
Intervalos válidos: 883,076
Secuencias inválidas: 4
Fechas incompletas: 0

RESULTADO
Universo de auditoría corregido: OK
Base de trabajo original conservada: OK
======================================================================

In [6]:

# ================================================================
# 5.1.7.6.4.5.5.2. CLASIFICACIÓN Y VALIDACIÓN DE SOLAPAMIENTOS
# ================================================================

import pandas as pd
import numpy as np

# ------------------------------------------------
# 1. Validación de dependencias
# ------------------------------------------------

for nombre in ["df_sol", "df_sol_auditado", "df_solapamientos"]:
    if nombre not in globals():
        raise NameError(
            f"No existe {nombre}. Ejecuta primero las celdas "
            "de auditoría y corrección del universo."
        )

columnas_intervalos = [
    "id_registro_original",
    "receptor",
    "sede",
    "dt_solicitud",
    "dt_llamado",
    "dt_finalizacion",
    "intervalo_valido"
]

columnas_pares = [
    "receptor", "registro_1", "registro_2",
    "sede_1", "sede_2",
    "tipo_solapamiento", "minutos_solapados"
]

faltantes_intervalos = set(columnas_intervalos) - set(
    df_sol_auditado.columns
)
faltantes_pares = set(columnas_pares) - set(
    df_solapamientos.columns
)

assert not faltantes_intervalos, faltantes_intervalos
assert not faltantes_pares, faltantes_pares

assert len(df_sol) == 1016267
assert len(df_sol_auditado) == 883080
assert int(df_sol_auditado["intervalo_valido"].sum()) == 883076
assert len(df_solapamientos) == 251

# ------------------------------------------------
# 2. Reconstrucción de intervalos por pareja
# ------------------------------------------------

base_intervalos = (
    df_sol_auditado.loc[
        df_sol_auditado["intervalo_valido"],
        columnas_intervalos
    ]
    .copy()
)

assert base_intervalos["id_registro_original"].is_unique

pares = df_solapamientos.copy()

detalle_1 = base_intervalos[
    [
        "id_registro_original",
        "receptor",
        "sede",
        "dt_solicitud",
        "dt_llamado",
        "dt_finalizacion"
    ]
].rename(columns={
    "id_registro_original": "registro_1",
    "receptor": "receptor_original_1",
    "sede": "sede_original_1",
    "dt_solicitud": "solicitud_1",
    "dt_llamado": "inicio_1",
    "dt_finalizacion": "fin_1"
})

detalle_2 = base_intervalos[
    [
        "id_registro_original",
        "receptor",
        "sede",
        "dt_solicitud",
        "dt_llamado",
        "dt_finalizacion"
    ]
].rename(columns={
    "id_registro_original": "registro_2",
    "receptor": "receptor_original_2",
    "sede": "sede_original_2",
    "dt_solicitud": "solicitud_2",
    "dt_llamado": "inicio_2",
    "dt_finalizacion": "fin_2"
})

pares = pares.merge(
    detalle_1,
    on="registro_1",
    how="left",
    validate="many_to_one"
)

pares = pares.merge(
    detalle_2,
    on="registro_2",
    how="left",
    validate="many_to_one"
)

assert len(pares) == len(df_solapamientos)
assert pares[
    ["inicio_1", "fin_1", "inicio_2", "fin_2"]
].notna().all().all()

assert (
    pares["receptor"].astype(str)
    == pares["receptor_original_1"].astype(str)
).all()

assert (
    pares["receptor"].astype(str)
    == pares["receptor_original_2"].astype(str)
).all()

assert (
    pares["sede_1"].astype(str)
    == pares["sede_original_1"].astype(str)
).all()

assert (
    pares["sede_2"].astype(str)
    == pares["sede_original_2"].astype(str)
).all()

# ------------------------------------------------
# 3. Reconstrucción y conciliación de duración
# ------------------------------------------------

pares["inicio_solapamiento"] = pares[
    ["inicio_1", "inicio_2"]
].max(axis=1)

pares["fin_solapamiento"] = pares[
    ["fin_1", "fin_2"]
].min(axis=1)

pares["minutos_recalculados"] = (
    pares["fin_solapamiento"]
    - pares["inicio_solapamiento"]
).dt.total_seconds() / 60

pares["diferencia_minutos"] = (
    pares["minutos_recalculados"]
    - pares["minutos_solapados"]
).abs()

assert (pares["minutos_recalculados"] > 0).all()
assert (pares["diferencia_minutos"] < 0.000001).all()

# ------------------------------------------------
# 4. Clasificación descriptiva
# ------------------------------------------------

# Umbrales exploratorios, no reglas de negocio.
# Se utilizan únicamente para ordenar la revisión.

condiciones = [
    pares["minutos_recalculados"] <= 1,
    pares["minutos_recalculados"] <= 5,
    pares["minutos_recalculados"] <= 15
]

etiquetas = [
    "Hasta 1 minuto",
    "Más de 1 y hasta 5 minutos",
    "Más de 5 y hasta 15 minutos"
]

pares["rango_duracion"] = np.select(
    condiciones,
    etiquetas,
    default="Más de 15 minutos"
)

pares["coincidencia_inicio"] = (
    pares["inicio_1"] == pares["inicio_2"]
)

pares["coincidencia_fin"] = (
    pares["fin_1"] == pares["fin_2"]
)

pares["intervalos_identicos"] = (
    pares["coincidencia_inicio"]
    & pares["coincidencia_fin"]
)

pares["mismo_dia"] = (
    pares["inicio_1"].dt.date
    == pares["inicio_2"].dt.date
)

# Prioridad de revisión, no diagnóstico de error.
pares["prioridad_revision"] = np.select(
    [
        pares["tipo_solapamiento"].eq("Entre sedes"),
        pares["intervalos_identicos"],
        pares["minutos_recalculados"] > 15,
        pares["minutos_recalculados"] > 5
    ],
    [
        "Alta - entre sedes",
        "Alta - intervalos idénticos",
        "Media - duración mayor a 15 min",
        "Media - duración mayor a 5 min"
    ],
    default="Exploratoria"
)

pares["estado_validacion"] = "Pendiente de validación"

# ------------------------------------------------
# 5. Resumen de clasificación
# ------------------------------------------------

resumen_clasificacion = (
    pares.groupby(
        ["tipo_solapamiento", "rango_duracion"],
        dropna=False
    )
    .agg(
        pares=("registro_1", "size"),
        receptores=("receptor", "nunique"),
        minutos_pares=("minutos_recalculados", "sum"),
        intervalos_identicos=("intervalos_identicos", "sum")
    )
    .reset_index()
    .sort_values(
        ["tipo_solapamiento", "minutos_pares"],
        ascending=[True, False]
    )
)

resumen_prioridad = (
    pares.groupby("prioridad_revision")
    .agg(
        pares=("registro_1", "size"),
        receptores=("receptor", "nunique")
    )
    .reset_index()
    .sort_values("pares", ascending=False)
)

# ------------------------------------------------
# 6. Recurrencia por receptor
# ------------------------------------------------

recurrencia = (
    pares.groupby("receptor")
    .agg(
        pares_solapados=("registro_1", "size"),
        registros_1=("registro_1", lambda x: set(x)),
        registros_2=("registro_2", lambda x: set(x)),
        minutos_pares=("minutos_recalculados", "sum"),
        pares_entre_sedes=(
            "tipo_solapamiento",
            lambda x: int((x == "Entre sedes").sum())
        ),
        dias_con_solapamiento=(
            "inicio_solapamiento",
            lambda x: x.dt.normalize().nunique()
        )
    )
    .reset_index()
)

recurrencia["registros_distintos"] = recurrencia.apply(
    lambda fila: len(
        fila["registros_1"] | fila["registros_2"]
    ),
    axis=1
)

recurrencia = (
    recurrencia.drop(
        columns=["registros_1", "registros_2"]
    )
    .sort_values(
        ["pares_solapados", "minutos_pares"],
        ascending=False
    )
)

# ------------------------------------------------
# 7. Concurrencia real sin duplicar minutos
# ------------------------------------------------

# Se calcula la unión de los intervalos de intersección
# por receptor. Este resultado no debe interpretarse
# como tiempo perdido o capacidad improductiva.

def minutos_union_intervalos(grupo):
    intervalos = sorted(
        zip(
            grupo["inicio_solapamiento"],
            grupo["fin_solapamiento"]
        ),
        key=lambda x: x[0]
    )

    if not intervalos:
        return 0.0

    inicio_actual, fin_actual = intervalos[0]
    minutos = 0.0

    for inicio, fin in intervalos[1:]:
        if inicio <= fin_actual:
            fin_actual = max(fin_actual, fin)
        else:
            minutos += (
                fin_actual - inicio_actual
            ).total_seconds() / 60

            inicio_actual, fin_actual = inicio, fin

    minutos += (
        fin_actual - inicio_actual
    ).total_seconds() / 60

    return minutos

concurrencia_receptor = (
    pares.groupby("receptor")
    .apply(
        minutos_union_intervalos,
        include_groups=False
    )
    .rename("minutos_concurrencia_real")
    .reset_index()
)

recurrencia = recurrencia.merge(
    concurrencia_receptor,
    on="receptor",
    how="left",
    validate="one_to_one"
)

# ------------------------------------------------
# 8. Detalle prioritario para auditoría
# ------------------------------------------------

columnas_detalle = [
    "receptor",
    "registro_1",
    "registro_2",
    "sede_1",
    "sede_2",
    "solicitud_1",
    "inicio_1",
    "fin_1",
    "solicitud_2",
    "inicio_2",
    "fin_2",
    "minutos_recalculados",
    "rango_duracion",
    "intervalos_identicos",
    "prioridad_revision",
    "estado_validacion"
]

detalle_prioritario = (
    pares[columnas_detalle]
    .sort_values(
        "minutos_recalculados",
        ascending=False
    )
)

# ------------------------------------------------
# 9. Conciliación final
# ------------------------------------------------

registros_afectados = (
    set(pares["registro_1"])
    | set(pares["registro_2"])
)

assert len(pares) == 251
assert len(registros_afectados) == 310
assert pares["receptor"].nunique() == 19
assert int(
    pares["tipo_solapamiento"].eq("Entre sedes").sum()
) == 8
assert int(
    pares["tipo_solapamiento"].eq("Misma sede").sum()
) == 243

assert int(resumen_clasificacion["pares"].sum()) == 251
assert int(resumen_prioridad["pares"].sum()) == 251

assert (
    recurrencia["minutos_concurrencia_real"]
    <= recurrencia["minutos_pares"] + 0.000001
).all()

print("=" * 70)
print("5.1.7.6.4.5.5.2. CLASIFICACIÓN Y VALIDACIÓN")
print("=" * 70)

print("\n1. CLASIFICACIÓN POR TIPO Y DURACIÓN")
display(resumen_clasificacion)

print("\n2. PRIORIDAD DE REVISIÓN")
display(resumen_prioridad)

print("\n3. RECURRENCIA POR RECEPTOR")
display(recurrencia.head(25))

print("\n4. CASOS ENTRE SEDES")
display(
    detalle_prioritario.loc[
        detalle_prioritario["prioridad_revision"]
        == "Alta - entre sedes"
    ]
)

print("\n5. CASOS DE MAYOR DURACIÓN")
display(detalle_prioritario.head(20))

print("\n6. CONCURRENCIA REAL")
print(
    "Minutos sumados por parejas:",
    round(pares["minutos_recalculados"].sum(), 2)
)
print(
    "Minutos de concurrencia real:",
    round(
        recurrencia["minutos_concurrencia_real"].sum(),
        2
    )
)

print("\nVALIDACIÓN FINAL")
print(f"Pares conciliados: {len(pares):,}")
print(f"Registros involucrados: {len(registros_afectados):,}")
print(f"Receptores involucrados: {pares['receptor'].nunique():,}")
print("Conservación de registros: OK")
print("Base original sin modificaciones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.5.2. CLASIFICACIÓN Y VALIDACIÓN
======================================================================

1. CLASIFICACIÓN POR TIPO Y DURACIÓN

,tipo_solapamiento,rango_duracion,pares,receptores,minutos_pares,intervalos_identicos
2,Entre sedes,Más de 5 y hasta 15 minutos,2,1,13.600000,0
1,Entre sedes,Más de 1 y hasta 5 minutos,1,1,2.633333,0
0,Entre sedes,Hasta 1 minuto,5,1,1.883333,0
4,Misma sede,Más de 1 y hasta 5 minutos,148,19,402.066667,0
6,Misma sede,Más de 5 y hasta 15 minutos,43,14,315.583333,0
5,Misma sede,Más de 15 minutos,1,1,22.600000,0
3,Misma sede,Hasta 1 minuto,51,13,21.800000,0

2. PRIORIDAD DE REVISIÓN

                prioridad_revision  pares  receptores
1                     Exploratoria    199          19
3   Media - duración mayor a 5 min     43          14
0               Alta - entre sedes      8           2
2  Media - duración mayor a 15 min      1           1

3. RECURRENCIA POR RECEPTOR

,receptor,pares_solapados,minutos_pares,pares_entre_sedes,dias_con_solapamiento,registros_distintos,minutos_concurrencia_real
0,1022386599,56,155.316667,0,2,64,155.316667
1,1007345774,45,70.633333,0,1,59,70.633333
2,1016065011,26,109.150000,2,3,33,109.150000
3,39767666,22,47.216667,6,4,30,47.216667
4,1014220989,16,75.950000,0,1,17,75.950000
5,1019055558,14,59.600000,0,1,18,59.600000
6,1022415872,10,37.800000,0,1,11,37.800000
7,79595952,9,41.083333,0,1,10,41.083333
8,40049489,9,36.566667,0,1,10,36.566667
9,1082124871,7,31.166667,0,1,8,31.166667
10,82393782,6,19.983333,0,1,8,19.983333
11,1024480700,6,8.516667,0,1,7,8.516667
12,1072423665,5,17.266667,0,2,7,17.266667
13,1077865422,5,12.716667,0,1,6,12.716667
14,1091660675,5,7.800000,0,1,6,7.800000
15,52848017,4,28.516667,0,1,5,28.516667
16,1023001168,3,9.566667,0,2,6,9.566667
17,1016038265,2,9.950000,0,1,3,9.950000
18,1014246062,1,1.366667,0,1,2,1.366667

4. CASOS ENTRE SEDES

,receptor,registro_1,registro_2,sede_1,sede_2,solicitud_1,inicio_1,fin_1,solicitud_2,inicio_2,fin_2,minutos_recalculados,rango_duracion,intervalos_identicos,prioridad_revision,estado_validacion
89,1016065011,487651,767361,Soacha,Tintal plaza,2024-09-06 10:30:10,2024-09-06 10:30:10,2024-09-06 10:37:46,2024-09-06 10:24:52,2024-09-06 10:30:35,2024-09-06 10:42:35,7.183333,Más de 5 y hasta 15 minutos,False,Alta - entre sedes,Pendiente de validación
88,1016065011,487652,692893,Soacha,Tintal plaza,2024-09-06 10:17:05,2024-09-06 10:22:24,2024-09-06 10:30:10,2024-09-06 10:16:25,2024-09-06 10:23:20,2024-09-06 10:29:45,6.416667,Más de 5 y hasta 15 minutos,False,Alta - entre sedes,Pendiente de validación
201,39767666,493496,756076,Soacha,Tintal plaza,2024-02-29 15:32:22,2024-02-29 15:43:22,2024-02-29 15:47:32,2024-02-29 15:40:51,2024-02-29 15:43:45,2024-02-29 15:46:23,2.633333,Más de 1 y hasta 5 minutos,False,Alta - entre sedes,Pendiente de validación
203,39767666,564493,678191,Soacha,Tintal plaza,2024-03-01 14:56:52,2024-03-01 15:21:26,2024-03-01 15:24:41,2024-03-01 15:12:47,2024-03-01 15:22:43,2024-03-01 15:23:28,0.750000,Hasta 1 minuto,False,Alta - entre sedes,Pendiente de validación
204,39767666,564493,679431,Soacha,Tintal plaza,2024-03-01 14:56:52,2024-03-01 15:21:26,2024-03-01 15:24:41,2024-03-01 15:20:25,2024-03-01 15:23:40,2024-03-01 15:24:23,0.716667,Hasta 1 minuto,False,Alta - entre sedes,Pendiente de validación
205,39767666,543034,736941,Soacha,Tintal plaza,2024-03-01 14:57:47,2024-03-01 15:27:37,2024-03-01 15:33:05,2024-03-01 15:14:06,2024-03-01 15:30:23,2024-03-01 15:30:37,0.233333,Hasta 1 minuto,False,Alta - entre sedes,Pendiente de validación
206,39767666,539341,663462,Soacha,Tintal plaza,2024-03-02 12:13:50,2024-03-02 12:29:02,2024-03-02 12:40:57,2024-03-02 12:22:57,2024-03-02 12:39:36,2024-03-02 12:39:44,0.133333,Hasta 1 minuto,False,Alta - entre sedes,Pendiente de validación
202,39767666,508857,722257,Soacha,Tintal plaza,2024-03-01 14:25:12,2024-03-01 14:51:41,2024-03-01 14:54:53,2024-03-01 14:52:52,2024-03-01 14:53:24,2024-03-01 14:53:27,0.050000,Hasta 1 minuto,False,Alta - entre sedes,Pendiente de validación

5. CASOS DE MAYOR DURACIÓN

,receptor,registro_1,registro_2,sede_1,sede_2,solicitud_1,inicio_1,fin_1,solicitud_2,inicio_2,fin_2,minutos_recalculados,rango_duracion,intervalos_identicos,prioridad_revision,estado_validacion
92,1019055558,800851,779907,Unicentro de occidente,Unicentro de occidente,2024-05-23 10:43:37,2024-05-23 11:46:54,2024-05-23 12:27:40,2024-05-23 10:51:43,2024-05-23 12:03:15,2024-05-23 12:25:51,22.600000,Más de 15 minutos,False,Media - duración mayor a 15 min,Pendiente de validación
244,79595952,275389,204699,Centro mayor,Centro mayor,2024-05-23 09:04:43,2024-05-23 09:11:11,2024-05-23 10:24:23,2024-05-23 09:47:30,2024-05-23 10:06:34,2024-05-23 10:21:15,14.683333,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
45,1014220989,487524,513766,Soacha,Soacha,2024-08-20 10:05:52,2024-08-20 10:06:23,2024-08-20 12:00:46,2024-08-20 10:14:37,2024-08-20 10:17:56,2024-08-20 10:31:23,13.450000,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
193,1082124871,411470,425161,Girardot,Girardot,2024-07-25 09:40:44,2024-07-25 09:40:44,2024-07-25 10:15:30,2024-07-25 09:54:48,2024-07-25 09:57:28,2024-07-25 10:08:19,10.850000,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
232,52848017,754977,752961,Tintal plaza,Tintal plaza,2024-05-24 12:08:31,2024-05-24 12:08:31,2024-05-24 14:29:28,2024-05-24 12:22:03,2024-05-24 12:46:57,2024-05-24 12:57:44,10.783333,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
91,1019055558,810099,800851,Unicentro de occidente,Unicentro de occidente,2024-05-23 10:29:40,2024-05-23 11:44:07,2024-05-23 11:57:10,2024-05-23 10:43:37,2024-05-23 11:46:54,2024-05-23 12:27:40,10.266667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
87,1016065011,503337,504964,Soacha,Soacha,2024-04-17 17:53:11,2024-04-17 17:53:11,2024-04-17 18:05:55,2024-04-17 17:52:49,2024-04-17 17:55:48,2024-04-17 18:08:19,10.116667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
57,1014220989,487524,558873,Soacha,Soacha,2024-08-20 10:05:52,2024-08-20 10:06:23,2024-08-20 12:00:46,2024-08-20 11:40:26,2024-08-20 11:40:26,2024-08-20 11:49:56,9.500000,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
235,52848017,754977,767074,Tintal plaza,Tintal plaza,2024-05-24 12:08:31,2024-05-24 12:08:31,2024-05-24 14:29:28,2024-05-24 13:06:30,2024-05-24 13:06:30,2024-05-24 13:15:55,9.416667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
249,82393782,347172,338002,Fusagasuga,Fusagasuga,2024-08-26 17:42:17,2024-08-26 17:53:57,2024-08-26 18:09:10,2024-08-26 17:55:47,2024-08-26 17:59:46,2024-08-26 18:11:13,9.400000,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
55,1014220989,487524,575978,Soacha,Soacha,2024-08-20 10:05:52,2024-08-20 10:06:23,2024-08-20 12:00:46,2024-08-20 11:17:21,2024-08-20 11:27:10,2024-08-20 11:36:20,9.166667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
132,1022386599,847590,846912,Usaquen,Usaquen,2024-03-02 08:54:29,2024-03-02 09:20:02,2024-03-02 09:31:17,2024-03-02 09:22:07,2024-03-02 09:22:07,2024-03-02 09:31:35,9.166667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
162,1022415872,715693,738734,Tintal plaza,Tintal plaza,2024-02-20 11:42:12,2024-02-20 12:10:52,2024-02-20 14:26:22,2024-02-20 12:27:51,2024-02-20 12:36:17,2024-02-20 12:44:36,8.316667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
163,1022415872,715693,735630,Tintal plaza,Tintal plaza,2024-02-20 11:42:12,2024-02-20 12:10:52,2024-02-20 14:26:22,2024-02-20 12:11:56,2024-02-20 12:45:33,2024-02-20 12:53:39,8.100000,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
122,1022386599,837942,879141,Usaquen,Usaquen,2024-03-02 08:21:45,2024-03-02 08:43:07,2024-03-02 08:54:23,2024-03-02 08:24:43,2024-03-02 08:46:41,2024-03-02 09:03:27,7.700000,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
66,1016065011,452057,454104,Santa librada,Santa librada,2024-01-10 13:08:23,2024-01-10 13:57:54,2024-01-10 14:36:33,2024-01-10 14:22:44,2024-01-10 14:22:44,2024-01-10 14:30:22,7.633333,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
180,1072423665,438765,441994,La mesa,La mesa,2024-03-13 10:06:15,2024-03-13 10:06:15,2024-03-13 10:19:32,2024-03-13 10:09:13,2024-03-13 10:11:37,2024-03-13 10:19:08,7.516667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
242,79595952,275389,262456,Centro mayor,Centro mayor,2024-05-23 09:04:43,2024-05-23 09:11:11,2024-05-23 10:24:23,2024-05-23 09:55:23,2024-05-23 09:55:23,2024-05-23 10:02:36,7.216667,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación
89,1016065011,487651,767361,Soacha,Tintal plaza,2024-09-06 10:30:10,2024-09-06 10:30:10,2024-09-06 10:37:46,2024-09-06 10:24:52,2024-09-06 10:30:35,2024-09-06 10:42:35,7.183333,Más de 5 y hasta 15 minutos,False,Alta - entre sedes,Pendiente de validación
150,1022386599,846582,859520,Usaquen,Usaquen,2024-03-02 12:44:57,2024-03-02 12:44:57,2024-03-02 12:57:50,2024-03-02 12:45:58,2024-03-02 12:45:58,2024-03-02 12:52:51,6.883333,Más de 5 y hasta 15 minutos,False,Media - duración mayor a 5 min,Pendiente de validación

6. CONCURRENCIA REAL
Minutos sumados por parejas: 780.17
Minutos de concurrencia real: 780.17

VALIDACIÓN FINAL
Pares conciliados: 251
Registros involucrados: 310
Receptores involucrados: 19
Conservación de registros: OK
Base original sin modificaciones: OK
======================================================================

### 5.1.7.6.4.5.5.2. Interpretación de la clasificación y validación de solapamientos

La auditoría temporal identificó 251 pares de atenciones superpuestas, correspondientes a 310 registros y 19 receptores. El 96,8 % de los pares se presenta dentro de una misma sede, mientras que el 3,2 % corresponde a coincidencias entre sedes. Asimismo, el 81,7 % de los solapamientos tiene una duración de hasta cinco minutos, lo que evidencia la necesidad de examinar posibles transiciones operativas, diferencias en los procedimientos de cierre o registros simultáneos de atención.

Los hallazgos presentan una concentración relevante por receptor: cuatro usuarios acumulan el 59,4 % de los pares identificados. Por su parte, los ocho solapamientos entre Soacha y Tintal Plaza constituyen casos prioritarios para validar la asignación e identificación de receptores.

La reconstrucción de los intervalos originales y la conciliación de duraciones confirman la consistencia del procedimiento de detección. Los 780,17 minutos de concurrencia identificados constituyen una medida de simultaneidad registrada, pero no pueden interpretarse directamente como tiempo improductivo, insuficiencia de capacidad o errores confirmados.

En consecuencia, los resultados se consideran alertas de calidad y consistencia operativa que deben contrastarse con las reglas del sistema de turnos, la disponibilidad de receptores y los indicadores de demanda y tiempos de atención antes de formular conclusiones definitivas sobre los cuellos de botella.

## 5.1.7.6.4.5.5.3. Diagnóstico integrado de capacidad y cuellos de botella

Se integran indicadores de demanda, oportunidad de atención,
carga operativa y consistencia temporal para identificar
concentraciones de presión sobre el servicio.

Los registros originales se conservan y los solapamientos
se mantienen como alertas de auditoría, sin excluirlos
automáticamente de los indicadores de gestión.

In [7]:
# ================================================================
# 5.1.7.6.4.5.5.3.
# DIAGNÓSTICO INTEGRADO DE CAPACIDAD Y CUELLOS DE BOTELLA
# BLOQUE 1. MATRIZ BASE POR SEDE
# ================================================================

import pandas as pd
import numpy as np

# ------------------------------------------------
# 1. Conservar el universo auditado
# ------------------------------------------------

df_diag = df_sol_auditado.copy()

n_universo = len(df_diag)

assert n_universo == 883080
assert df_diag["id_registro_original"].is_unique

# ------------------------------------------------
# 2. Verificar campos necesarios
# ------------------------------------------------

columnas = [
    "sede",
    "receptor",
    "dt_solicitud",
    "dt_llamado",
    "dt_finalizacion",
    "intervalo_valido"
]

faltantes = [
    c for c in columnas
    if c not in df_diag.columns
]

if faltantes:
    raise KeyError(
        f"Columnas necesarias no encontradas: {faltantes}"
    )

# ------------------------------------------------
# 3. Calcular tiempos desde fechas originales
# ------------------------------------------------

df_diag["espera_min_diag"] = (
    df_diag["dt_llamado"] -
    df_diag["dt_solicitud"]
).dt.total_seconds() / 60

df_diag["atencion_min_diag"] = (
    df_diag["dt_finalizacion"] -
    df_diag["dt_llamado"]
).dt.total_seconds() / 60

# No se corrigen ni imputan duraciones.
# Se identifican registros temporalmente consistentes.

df_diag["tiempos_validos_diag"] = (
    df_diag["intervalo_valido"].fillna(False)
    & df_diag["espera_min_diag"].ge(0)
    & df_diag["atencion_min_diag"].gt(0)
)

# ------------------------------------------------
# 4. Marcar registros con solapamientos
# ------------------------------------------------

ids_solapados = (
    set(df_solapamientos["registro_1"])
    | set(df_solapamientos["registro_2"])
)

df_diag["alerta_solapamiento"] = (
    df_diag["id_registro_original"].isin(ids_solapados)
)

# IMPORTANTE:
# Esta marca NO excluye registros del análisis.

# ------------------------------------------------
# 5. Matriz integrada por sede
# ------------------------------------------------

base_sedes = df_diag.loc[
    df_diag["sede"].notna()
].copy()

matriz_sedes = (
    base_sedes
    .groupby("sede", dropna=False)
    .agg(
        turnos=("id_registro_original", "size"),
        receptores_observados=("receptor", "nunique"),
        turnos_validos=(
            "tiempos_validos_diag", "sum"
        ),
        registros_con_solapamiento=(
            "alerta_solapamiento", "sum"
        )
    )
    .reset_index()
)

tiempos_sedes = (
    base_sedes.loc[
        base_sedes["tiempos_validos_diag"]
    ]
    .groupby("sede")
    .agg(
        espera_promedio_min=(
            "espera_min_diag", "mean"
        ),
        espera_mediana_min=(
            "espera_min_diag", "median"
        ),
        espera_p90_min=(
            "espera_min_diag",
            lambda x: x.quantile(0.90)
        ),
        atencion_promedio_min=(
            "atencion_min_diag", "mean"
        ),
        minutos_atencion=(
            "atencion_min_diag", "sum"
        )
    )
    .reset_index()
)

matriz_sedes = matriz_sedes.merge(
    tiempos_sedes,
    on="sede",
    how="left",
    validate="one_to_one"
)

matriz_sedes["pct_registros_solapados"] = (
    100
    * matriz_sedes["registros_con_solapamiento"]
    / matriz_sedes["turnos"]
)

matriz_sedes["turnos_por_receptor_observado"] = (
    matriz_sedes["turnos"]
    / matriz_sedes["receptores_observados"].replace(0, np.nan)
)

matriz_sedes = matriz_sedes.sort_values(
    ["espera_p90_min", "turnos"],
    ascending=[False, False]
)

# ------------------------------------------------
# 6. Presentación
# ------------------------------------------------

print("=" * 70)
print("5.1.7.6.4.5.5.3. DIAGNÓSTICO INTEGRADO")
print("MATRIZ BASE POR SEDE")
print("=" * 70)

display(matriz_sedes.round(2))

# ------------------------------------------------
# 7. Validaciones
# ------------------------------------------------

assert len(df_diag) == n_universo

assert (
    matriz_sedes["turnos"].sum()
    == len(base_sedes)
)

assert (
    df_diag["alerta_solapamiento"].sum()
    == len(ids_solapados)
)

print("\nVALIDACIÓN")
print(f"Universo auditado: {n_universo:,}")
print(f"Turnos con sede: {len(base_sedes):,}")
print(
    "Registros marcados por solapamiento: "
    f"{df_diag['alerta_solapamiento'].sum():,}"
)
print("Conservación de registros: OK")
print("Solapamientos conservados: OK")
print("Base original sin modificaciones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.5.3. DIAGNÓSTICO INTEGRADO
MATRIZ BASE POR SEDE
======================================================================

,sede,turnos,receptores_observados,turnos_validos,registros_con_solapamiento,espera_promedio_min,espera_mediana_min,espera_p90_min,atencion_promedio_min,minutos_atencion,pct_registros_solapados,turnos_por_receptor_observado
9,Suba,81721,21,81721,0,7.74,2.25,23.90,5.58,455827.10,0.00,3891.48
2,Centro mayor,79106,24,79106,16,6.82,0.38,22.95,5.24,414700.93,0.02,3296.08
8,Soacha,93106,27,93104,48,7.22,3.07,20.58,5.04,468967.33,0.05,3448.37
11,Unicentro de occidente,56338,29,56338,90,6.41,0.97,20.30,5.40,304067.07,0.16,1942.69
10,Tintal plaza,112312,31,112312,30,5.67,0.00,20.28,3.94,442944.48,0.03,3622.97
7,Santa librada,40791,18,40790,5,6.63,2.12,19.67,6.45,263285.53,0.01,2266.17
12,Usaquen,55305,20,55305,66,5.95,1.02,18.68,4.93,272403.43,0.12,2765.25
0,Calle 26,157060,38,157060,26,5.49,0.57,17.67,5.87,922595.45,0.02,4133.16
1,Calle 63,47613,23,47613,6,5.22,0.63,16.95,5.43,258483.20,0.01,2070.13
4,Fusagasuga,45219,7,45219,8,5.06,1.20,15.38,4.80,216913.72,0.02,6459.86
5,Girardot,47419,7,47419,8,5.97,2.90,14.80,5.25,249079.30,0.02,6774.14
6,La mesa,13326,3,13326,7,4.44,1.03,13.57,4.55,60655.20,0.05,4442.00
3,Funza,53764,8,53763,0,3.93,0.47,12.50,3.98,214112.05,0.00,6720.50

VALIDACIÓN
Universo auditado: 883,080
Turnos con sede: 883,080
Registros marcados por solapamiento: 310
Conservación de registros: OK
Solapamientos conservados: OK
Base original sin modificaciones: OK
======================================================================

### 5.1.7.6.4.5.5.3.1. Presión operativa por sede, día y hora

Se analiza la distribución temporal de la demanda y su relación
con los tiempos de espera, identificando franjas con alta
concentración de solicitudes y posibles señales de congestión.

Los resultados corresponden a patrones observados y no
constituyen, por sí solos, evidencia de insuficiencia de personal.

In [8]:
# ================================================================
# 5.1.7.6.4.5.5.3.1.
# PRESION OPERATIVA POR SEDE, DIA Y HORA
# ================================================================

# 1. Copia de trabajo
df_franjas = df_diag.copy()

# 2. Variables temporales de solicitud
df_franjas["fecha_dia"] = (
    df_franjas["dt_solicitud"].dt.date
)

df_franjas["hora_solicitud"] = (
    df_franjas["dt_solicitud"].dt.hour
)

df_franjas["dia_semana"] = (
    df_franjas["dt_solicitud"].dt.dayofweek
)

# 3. Universo de solicitudes temporalmente identificables
base_franjas = df_franjas.loc[
    df_franjas["sede"].notna()
    & df_franjas["dt_solicitud"].notna()
].copy()

# 4. Volumen de solicitudes por sede, día y hora
demanda_franjas = (
    base_franjas
    .groupby(
        ["sede", "fecha_dia", "dia_semana", "hora_solicitud"]
    )
    .agg(
        solicitudes=("id_registro_original", "size"),
        receptores_observados=("receptor", "nunique")
    )
    .reset_index()
)

# 5. Tiempos de espera por franja
esperas_franjas = (
    base_franjas.loc[
        base_franjas["tiempos_validos_diag"]
    ]
    .groupby(
        ["sede", "fecha_dia", "dia_semana", "hora_solicitud"]
    )
    .agg(
        turnos_validos=("id_registro_original", "size"),
        espera_promedio_min=("espera_min_diag", "mean"),
        espera_mediana_min=("espera_min_diag", "median"),
        espera_p90_min=(
            "espera_min_diag",
            lambda x: x.quantile(0.90)
        )
    )
    .reset_index()
)

# 6. Integración
matriz_franjas = demanda_franjas.merge(
    esperas_franjas,
    on=[
        "sede", "fecha_dia",
        "dia_semana", "hora_solicitud"
    ],
    how="left",
    validate="one_to_one"
)

# 7. Indicador de concentración de demanda
# Referencia: percentil 75 de solicitudes por franja
# dentro de cada sede.

matriz_franjas["umbral_p75_demanda"] = (
    matriz_franjas.groupby("sede")["solicitudes"]
    .transform(lambda x: x.quantile(0.75))
)

matriz_franjas["alta_demanda_relativa"] = (
    matriz_franjas["solicitudes"]
    > matriz_franjas["umbral_p75_demanda"]
)

# 8. Identificación de franjas con demanda alta
# y espera elevada respecto al comportamiento
# general de la misma sede.

matriz_franjas = matriz_franjas.merge(
    matriz_sedes[["sede", "espera_p90_min"]].rename(
        columns={
            "espera_p90_min": "espera_p90_referencia_sede"
        }
    ),
    on="sede",
    how="left",
    validate="many_to_one"
)

matriz_franjas["espera_elevada_relativa"] = (
    matriz_franjas["espera_p90_min"]
    > matriz_franjas["espera_p90_referencia_sede"]
)

matriz_franjas["alerta_presion_operativa"] = (
    matriz_franjas["alta_demanda_relativa"]
    & matriz_franjas["espera_elevada_relativa"]
)

# 9. Resumen de franjas por sede
resumen_presion = (
    matriz_franjas.groupby("sede")
    .agg(
        franjas_observadas=("solicitudes", "size"),
        solicitudes=("solicitudes", "sum"),
        franjas_alta_demanda=(
            "alta_demanda_relativa", "sum"
        ),
        franjas_alerta_presion=(
            "alerta_presion_operativa", "sum"
        ),
        max_solicitudes_franja=("solicitudes", "max")
    )
    .reset_index()
)

resumen_presion["pct_franjas_alerta"] = (
    100
    * resumen_presion["franjas_alerta_presion"]
    / resumen_presion["franjas_observadas"]
)

resumen_presion = resumen_presion.sort_values(
    "franjas_alerta_presion",
    ascending=False
)

# 10. Resultados
print("=" * 70)
print("PRESION OPERATIVA POR SEDE, DIA Y HORA")
print("=" * 70)

display(resumen_presion.round(2))

print("\nFRANJAS CON ALERTAS DE PRESION OPERATIVA")

display(
    matriz_franjas.loc[
        matriz_franjas["alerta_presion_operativa"]
    ].sort_values(
        ["solicitudes", "espera_p90_min"],
        ascending=False
    ).head(20).round(2)
)

# 11. Validaciones
assert (
    matriz_franjas["solicitudes"].sum()
    == len(base_franjas)
)

assert len(df_diag) == 883080

print("\nVALIDACION")
print(f"Universo auditado: {len(df_diag):,}")
print(f"Solicitudes con fecha y hora: {len(base_franjas):,}")
print(f"Franjas analizadas: {len(matriz_franjas):,}")
print("Conservacion de registros: OK")
print("Base original sin modificaciones: OK")
print("=" * 70)

======================================================================
PRESION OPERATIVA POR SEDE, DIA Y HORA
======================================================================

,sede,franjas_observadas,solicitudes,franjas_alta_demanda,franjas_alerta_presion,max_solicitudes_franja,pct_franjas_alerta
12,Usaquen,2125,55305,507,278,64,13.08
0,Calle 26,2161,157060,524,253,163,11.71
11,Unicentro de occidente,2080,56338,484,251,80,12.07
10,Tintal plaza,2092,112312,519,242,140,11.57
9,Suba,1873,81721,435,237,100,12.65
7,Santa librada,1895,40791,450,223,49,11.77
1,Calle 63,2054,47613,483,213,68,10.37
3,Funza,2007,53764,502,213,69,10.61
5,Girardot,2039,47419,465,204,60,10.00
8,Soacha,2093,93106,488,195,97,9.32
6,La mesa,1941,13326,463,194,29,9.99
2,Centro mayor,1378,79106,337,179,127,12.99
4,Fusagasuga,2001,45219,475,148,63,7.40

FRANJAS CON ALERTAS DE PRESION OPERATIVA

,sede,fecha_dia,dia_semana,hora_solicitud,solicitudes,receptores_observados,turnos_validos,espera_promedio_min,espera_mediana_min,espera_p90_min,umbral_p75_demanda,alta_demanda_relativa,espera_p90_referencia_sede,espera_elevada_relativa,alerta_presion_operativa
99,Calle 26,2024-01-13,5,12,163,15,163,4.66,0.48,17.83,93.0,True,17.67,True,True
222,Calle 26,2024-01-27,5,11,149,14,149,8.83,2.20,31.82,93.0,True,17.67,True,True
285,Calle 26,2024-02-03,5,12,147,14,147,9.65,3.73,24.69,93.0,True,17.67,True,True
1795,Calle 26,2024-08-03,5,11,146,15,146,13.18,3.51,42.70,93.0,True,17.67,True,True
284,Calle 26,2024-02-03,5,11,145,14,145,8.20,1.98,23.11,93.0,True,17.67,True,True
726,Calle 26,2024-03-26,1,11,139,13,139,7.17,1.97,22.29,93.0,True,17.67,True,True
628,Calle 26,2024-03-13,2,15,138,15,138,10.82,1.79,32.47,93.0,True,17.67,True,True
1846,Calle 26,2024-08-10,5,11,138,15,138,6.47,0.46,21.04,93.0,True,17.67,True,True
2082,Calle 26,2024-09-07,5,11,138,14,138,6.81,0.00,17.67,93.0,True,17.67,True,True
223,Calle 26,2024-01-27,5,12,137,15,137,11.50,7.00,32.30,93.0,True,17.67,True,True
1523,Calle 26,2024-07-03,2,12,135,15,135,15.85,1.20,69.69,93.0,True,17.67,True,True
2145,Calle 26,2024-09-14,5,12,134,15,134,10.48,0.34,41.61,93.0,True,17.67,True,True
19500,Tintal plaza,2024-01-09,1,17,134,10,134,7.82,0.00,36.16,68.0,True,20.28,True,True
1527,Calle 26,2024-07-03,2,16,134,15,134,9.49,0.70,30.69,93.0,True,17.67,True,True
993,Calle 26,2024-04-27,5,12,131,14,131,9.98,3.33,32.63,93.0,True,17.67,True,True
256,Calle 26,2024-01-31,2,15,129,14,129,8.47,2.52,22.28,93.0,True,17.67,True,True
656,Calle 26,2024-03-16,5,11,128,14,128,11.29,2.72,39.70,93.0,True,17.67,True,True
20914,Tintal plaza,2024-06-29,5,12,128,9,128,7.50,0.00,32.73,68.0,True,20.28,True,True
1042,Calle 26,2024-05-04,5,12,128,15,128,5.68,0.97,18.16,93.0,True,17.67,True,True
1503,Calle 26,2024-06-29,5,11,127,15,127,8.29,1.05,29.13,93.0,True,17.67,True,True

VALIDACION
Universo auditado: 883,080
Solicitudes con fecha y hora: 883,080
Franjas analizadas: 25,739
Conservacion de registros: OK
Base original sin modificaciones: OK
======================================================================

### 5.1.7.6.4.5.5.3.2. Relación entre demanda, tiempos de servicio y capacidad operativa observada

**Objetivo.** Examinar la relación entre la concentración temporal de solicitudes, la duración de las atenciones, la actividad de los usuarios receptores y los tiempos de espera, para identificar posibles desajustes operativos por sede y franja horaria.

**Criterios metodológicos:**

- Se conservan los registros originales y las atenciones con solapamientos.
- La demanda se asigna a la hora de solicitud.
- Los minutos de servicio se distribuyen según el tiempo efectivamente comprendido en cada hora.
- Los receptores activos corresponden a usuarios con atenciones registradas durante la franja.
- La concurrencia se calcula a partir de intervalos temporales originales.
- No se interpreta la actividad registrada como disponibilidad laboral total ni como tasa real de utilización.
- Los hallazgos constituyen señales de presión operativa y requieren triangulación antes de confirmar cuellos de botella.

In [9]:

# ================================================================
# 5.1.7.6.4.5.5.3.2.
# DEMANDA, SERVICIO Y CAPACIDAD OPERATIVA OBSERVADA
# ================================================================

import pandas as pd
import numpy as np

# ------------------------------------------------
# 1. Validaciones y universo de trabajo
# ------------------------------------------------

requeridas = [
    "id_registro_original",
    "sede",
    "receptor",
    "dt_solicitud",
    "dt_llamado",
    "dt_finalizacion",
    "intervalo_valido"
]

faltantes = [
    c for c in requeridas
    if c not in df_sol_auditado.columns
]

if faltantes:
    raise KeyError(f"Columnas faltantes: {faltantes}")

df_cap = df_sol_auditado.copy()

assert len(df_cap) == 883080
assert df_cap["id_registro_original"].is_unique

# Universo de solicitudes temporalmente identificables
solicitudes = df_cap.loc[
    df_cap["sede"].notna()
    & df_cap["dt_solicitud"].notna()
].copy()

solicitudes["fecha_dia"] = (
    solicitudes["dt_solicitud"].dt.date
)
solicitudes["hora_solicitud"] = (
    solicitudes["dt_solicitud"].dt.hour
)

# Atenciones con intervalo positivo y consistente
servicios = df_cap.loc[
    df_cap["intervalo_valido"].fillna(False)
].copy()

servicios["duracion_servicio_min"] = (
    servicios["dt_finalizacion"]
    - servicios["dt_llamado"]
).dt.total_seconds() / 60

# ------------------------------------------------
# 2. Distribuir el tiempo de servicio por hora
# ------------------------------------------------
# Cada intervalo se divide en segmentos horarios.
# Se conservan los solapamientos como observaciones
# y no se interpreta su suma como tiempo exclusivo.

segmentos = []

for fila in servicios[
    [
        "id_registro_original",
        "sede",
        "receptor",
        "dt_llamado",
        "dt_finalizacion"
    ]
].itertuples(index=False):

    inicio = fila.dt_llamado
    fin = fila.dt_finalizacion

    cursor = inicio

    while cursor < fin:
        inicio_hora = cursor.floor("h")
        fin_hora = inicio_hora + pd.Timedelta(hours=1)
        cierre = min(fin, fin_hora)

        minutos = (
            cierre - cursor
        ).total_seconds() / 60

        segmentos.append({
            "id_registro_original": fila.id_registro_original,
            "sede": fila.sede,
            "receptor": fila.receptor,
            "franja_inicio": inicio_hora,
            "inicio_segmento": cursor,
            "fin_segmento": cierre,
            "minutos_servicio": minutos
        })

        cursor = cierre

df_segmentos = pd.DataFrame(segmentos)

# ------------------------------------------------
# 3. Métricas de actividad por franja
# ------------------------------------------------

actividad_franjas = (
    df_segmentos.groupby(
        ["sede", "franja_inicio"],
        as_index=False
    )
    .agg(
        minutos_servicio_registrados=(
            "minutos_servicio", "sum"
        ),
        receptores_activos=(
            "receptor", "nunique"
        ),
        atenciones_en_curso=(
            "id_registro_original", "nunique"
        )
    )
)

# Minutos por receptor activo: indicador descriptivo,
# no tasa de utilización.
actividad_franjas["minutos_por_receptor_activo"] = (
    actividad_franjas["minutos_servicio_registrados"]
    / actividad_franjas["receptores_activos"]
)

# ------------------------------------------------
# 4. Duración de servicios iniciados en cada hora
# ------------------------------------------------

servicios["franja_inicio"] = (
    servicios["dt_llamado"].dt.floor("h")
)

duracion_franjas = (
    servicios.groupby(
        ["sede", "franja_inicio"],
        as_index=False
    )
    .agg(
        servicios_iniciados=(
            "id_registro_original", "size"
        ),
        duracion_media_min=(
            "duracion_servicio_min", "mean"
        ),
        duracion_mediana_min=(
            "duracion_servicio_min", "median"
        ),
        duracion_p90_min=(
            "duracion_servicio_min",
            lambda x: x.quantile(0.90)
        )
    )
)

# ------------------------------------------------
# 5. Integración con demanda y espera
# ------------------------------------------------

base_integrada = matriz_franjas.copy()

base_integrada["franja_inicio"] = (
    pd.to_datetime(
        base_integrada["fecha_dia"].astype(str)
    )
    + pd.to_timedelta(
        base_integrada["hora_solicitud"], unit="h"
    )
)

matriz_capacidad = base_integrada.merge(
    actividad_franjas,
    on=["sede", "franja_inicio"],
    how="left",
    validate="one_to_one"
)

matriz_capacidad = matriz_capacidad.merge(
    duracion_franjas,
    on=["sede", "franja_inicio"],
    how="left",
    validate="one_to_one"
)

# Las horas sin actividad registrada no implican
# necesariamente ausencia de personal disponible.
columnas_actividad = [
    "minutos_servicio_registrados",
    "receptores_activos",
    "atenciones_en_curso",
    "servicios_iniciados"
]

matriz_capacidad[columnas_actividad] = (
    matriz_capacidad[columnas_actividad].fillna(0)
)

# ------------------------------------------------
# 6. Indicadores descriptivos de presión
# ------------------------------------------------

# Solicitudes por receptor que registró actividad
matriz_capacidad["solicitudes_por_receptor_activo"] = (
    matriz_capacidad["solicitudes"]
    / matriz_capacidad["receptores_activos"].replace(0, np.nan)
)

# Minutos registrados / 60:
# mide volumen equivalente de trabajo, no ocupación
# real de un puesto.
matriz_capacidad["horas_receptor_equivalentes"] = (
    matriz_capacidad["minutos_servicio_registrados"] / 60
)

# Señal exploratoria de presión:
# alta demanda y espera elevada, según sección anterior.
matriz_capacidad["alerta_integrada_preliminar"] = (
    matriz_capacidad["alerta_presion_operativa"]
)

# ------------------------------------------------
# 7. Resumen por sede
# ------------------------------------------------

resumen_capacidad = (
    matriz_capacidad.groupby("sede", as_index=False)
    .agg(
        solicitudes=("solicitudes", "sum"),
        franjas_observadas=("solicitudes", "size"),
        franjas_con_actividad=(
            "receptores_activos",
            lambda x: (x > 0).sum()
        ),
        franjas_alerta=(
            "alerta_integrada_preliminar", "sum"
        ),
        minutos_servicio_registrados=(
            "minutos_servicio_registrados", "sum"
        ),
        max_receptores_activos=(
            "receptores_activos", "max"
        ),
        max_solicitudes_hora=(
            "solicitudes", "max"
        )
    )
)

resumen_capacidad["pct_franjas_alerta"] = (
    100
    * resumen_capacidad["franjas_alerta"]
    / resumen_capacidad["franjas_observadas"]
)

resumen_capacidad = resumen_capacidad.sort_values(
    ["pct_franjas_alerta", "solicitudes"],
    ascending=[False, False]
)

# ------------------------------------------------
# 8. Presentación de resultados
# ------------------------------------------------

print("=" * 70)
print("5.1.7.6.4.5.5.3.2. CAPACIDAD OPERATIVA OBSERVADA")
print("=" * 70)

print("\n1. RESUMEN POR SEDE")
display(resumen_capacidad.round(2))

print("\n2. FRANJAS CON ALERTAS Y ACTIVIDAD REGISTRADA")

columnas_resultado = [
    "sede",
    "fecha_dia",
    "hora_solicitud",
    "solicitudes",
    "turnos_validos",
    "espera_promedio_min",
    "espera_p90_min",
    "receptores_activos",
    "minutos_servicio_registrados",
    "duracion_media_min",
    "solicitudes_por_receptor_activo"
]

display(
    matriz_capacidad.loc[
        matriz_capacidad["alerta_integrada_preliminar"],
        columnas_resultado
    ].sort_values(
        ["solicitudes", "espera_p90_min"],
        ascending=False
    ).head(20).round(2)
)

# ------------------------------------------------
# 9. Conciliación y control de integridad
# ------------------------------------------------

minutos_originales = servicios[
    "duracion_servicio_min"
].sum()

minutos_distribuidos = df_segmentos[
    "minutos_servicio"
].sum()

assert np.isclose(
    minutos_originales,
    minutos_distribuidos,
    rtol=1e-10,
    atol=1e-5
)

assert (
    matriz_capacidad["solicitudes"].sum()
    == len(solicitudes)
)

assert len(matriz_capacidad) == len(matriz_franjas)
assert len(df_cap) == 883080

print("\n3. VALIDACION FINAL")
print(f"Universo auditado: {len(df_cap):,}")
print(f"Solicitudes conciliadas: {len(solicitudes):,}")
print(f"Atenciones validas: {len(servicios):,}")
print(f"Segmentos horarios: {len(df_segmentos):,}")
print(f"Franjas de demanda: {len(matriz_capacidad):,}")
print(
    "Minutos originales: "
    f"{minutos_originales:,.2f}"
)
print(
    "Minutos distribuidos: "
    f"{minutos_distribuidos:,.2f}"
)
print("Conciliacion temporal: OK")
print("Conservacion de registros: OK")
print("Base original sin modificaciones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.5.3.2. CAPACIDAD OPERATIVA OBSERVADA
======================================================================

1. RESUMEN POR SEDE

,sede,solicitudes,franjas_observadas,franjas_con_actividad,franjas_alerta,minutos_servicio_registrados,max_receptores_activos,max_solicitudes_hora,pct_franjas_alerta
12,Usaquen,55305,2125,2125,278,271977.17,8.0,64,13.08
2,Centro mayor,79106,1378,1378,179,414540.25,12.0,127,12.99
9,Suba,81721,1873,1873,237,455139.67,10.0,100,12.65
11,Unicentro de occidente,56338,2080,2080,251,303730.95,6.0,80,12.07
7,Santa librada,40791,1895,1895,223,261833.83,6.0,49,11.77
0,Calle 26,157060,2161,2160,253,922502.05,16.0,163,11.71
10,Tintal plaza,112312,2092,2092,242,442290.83,10.0,140,11.57
3,Funza,53764,2007,2007,213,213842.23,5.0,69,10.61
1,Calle 63,47613,2054,2054,213,257554.92,8.0,68,10.37
5,Girardot,47419,2039,2038,204,248063.17,5.0,60,10.00
6,La mesa,13326,1941,1930,194,60153.67,2.0,29,9.99
8,Soacha,93106,2093,2090,195,468390.25,10.0,97,9.32
4,Fusagasuga,45219,2001,2001,148,216302.80,5.0,63,7.40

2. FRANJAS CON ALERTAS Y ACTIVIDAD REGISTRADA

,sede,fecha_dia,hora_solicitud,solicitudes,turnos_validos,espera_promedio_min,espera_p90_min,receptores_activos,minutos_servicio_registrados,duracion_media_min,solicitudes_por_receptor_activo
99,Calle 26,2024-01-13,12,163,163,4.66,17.83,15.0,720.22,4.89,10.87
222,Calle 26,2024-01-27,11,149,149,8.83,31.82,14.0,735.48,5.77,10.64
285,Calle 26,2024-02-03,12,147,147,9.65,24.69,14.0,760.23,5.33,10.50
1795,Calle 26,2024-08-03,11,146,146,13.18,42.70,15.0,805.20,7.11,9.73
284,Calle 26,2024-02-03,11,145,145,8.20,23.11,14.0,755.12,5.28,10.36
726,Calle 26,2024-03-26,11,139,139,7.17,22.29,13.0,552.27,3.97,10.69
628,Calle 26,2024-03-13,15,138,138,10.82,32.47,14.0,592.48,4.87,9.86
1846,Calle 26,2024-08-10,11,138,138,6.47,21.04,15.0,817.05,6.29,9.20
2082,Calle 26,2024-09-07,11,138,138,6.81,17.67,14.0,750.55,5.67,9.86
223,Calle 26,2024-01-27,12,137,137,11.50,32.30,15.0,763.48,5.52,9.13
1523,Calle 26,2024-07-03,12,135,135,15.85,69.69,15.0,632.80,5.27,9.00
2145,Calle 26,2024-09-14,12,134,134,10.48,41.61,15.0,812.03,6.66,8.93
19500,Tintal plaza,2024-01-09,17,134,134,7.82,36.16,10.0,430.22,3.33,13.40
1527,Calle 26,2024-07-03,16,134,134,9.49,30.69,15.0,752.72,6.37,8.93
993,Calle 26,2024-04-27,12,131,131,9.98,32.63,14.0,743.63,6.16,9.36
256,Calle 26,2024-01-31,15,129,129,8.47,22.28,14.0,579.83,5.02,9.21
656,Calle 26,2024-03-16,11,128,128,11.29,39.70,14.0,727.87,6.39,9.14
20914,Tintal plaza,2024-06-29,12,128,128,7.50,32.73,9.0,396.33,3.21,14.22
1042,Calle 26,2024-05-04,12,128,128,5.68,18.16,15.0,684.30,5.68,8.53
1503,Calle 26,2024-06-29,11,127,127,8.29,29.13,15.0,761.53,6.52,8.47

3. VALIDACION FINAL
Universo auditado: 883,080
Solicitudes conciliadas: 883,080
Atenciones validas: 883,076
Segmentos horarios: 957,757
Franjas de demanda: 25,739
Minutos originales: 4,544,034.80
Minutos distribuidos: 4,544,034.80
Conciliacion temporal: OK
Conservacion de registros: OK
Base original sin modificaciones: OK
======================================================================

In [12]:

# ================================================================
# 5.1.7.6.4.5.5.3.3.
# IDENTIFICACION Y PRIORIZACION DE CUELLOS DE BOTELLA
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("5.1.7.6.4.5.5.3.3. CUELLOS DE BOTELLA OPERATIVOS")
print("=" * 70)

# ------------------------------------------------
# 1. Copia analitica y validacion de estructura
# ------------------------------------------------

df_cuellos = matriz_capacidad.copy(deep=True)
# Homologacion de nombres para el diagnostico.
# No modifica matriz_capacidad ni los registros originales.

if "minutos_servicio" not in df_cuellos.columns:
    if "minutos_servicio_registrados" in df_cuellos.columns:
        df_cuellos = df_cuellos.rename(
            columns={
                "minutos_servicio_registrados": "minutos_servicio"
            }
        )

columnas_requeridas = [
    "sede",
    "fecha_dia",
    "hora_solicitud",
    "solicitudes",
    "turnos_validos",
    "espera_promedio_min",
    "espera_p90_min",
    "receptores_activos",
    "minutos_servicio"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in df_cuellos.columns
]

if faltantes:
    print("Columnas disponibles:")
    print(df_cuellos.columns.tolist())
    raise KeyError(
        f"Faltan columnas para el diagnostico: {faltantes}. "
        "Revisar los nombres de la seccion 5.1.7.6.4.5.5.3.2."
    )

n_franjas_original = len(df_cuellos)

# Verificar que cada franja sea unica
clave_franja = ["sede", "fecha_dia", "hora_solicitud"]

assert not df_cuellos.duplicated(
    subset=clave_franja
).any(), "Existen franjas duplicadas."

# ------------------------------------------------
# 2. Normalizacion numerica
# ------------------------------------------------

columnas_numericas = [
    "solicitudes",
    "turnos_validos",
    "espera_promedio_min",
    "espera_p90_min",
    "receptores_activos",
    "minutos_servicio"
]

for columna in columnas_numericas:
    df_cuellos[columna] = pd.to_numeric(
        df_cuellos[columna],
        errors="coerce"
    )

# La carga por receptor es una aproximacion descriptiva.
# No equivale a utilizacion real del personal.

df_cuellos["minutos_por_receptor_observado"] = (
    df_cuellos["minutos_servicio"] /
    df_cuellos["receptores_activos"].replace(0, np.nan)
)

# ------------------------------------------------
# 3. Referencias relativas por sede
# ------------------------------------------------

variables_percentil = [
    "solicitudes",
    "espera_promedio_min",
    "espera_p90_min",
    "minutos_por_receptor_observado"
]

referencias = (
    df_cuellos
    .groupby("sede", dropna=False)[variables_percentil]
    .quantile(0.75)
    .add_prefix("p75_")
    .reset_index()
)

df_cuellos = df_cuellos.merge(
    referencias,
    on="sede",
    how="left",
    validate="many_to_one"
)

# ------------------------------------------------
# 4. Senales de presion operativa
# ------------------------------------------------

df_cuellos["senal_demanda"] = (
    df_cuellos["solicitudes"] >
    df_cuellos["p75_solicitudes"]
)

df_cuellos["senal_espera_promedio"] = (
    df_cuellos["espera_promedio_min"] >
    df_cuellos["p75_espera_promedio_min"]
)

df_cuellos["senal_espera_p90"] = (
    df_cuellos["espera_p90_min"] >
    df_cuellos["p75_espera_p90_min"]
)

df_cuellos["senal_carga_observada"] = (
    df_cuellos["minutos_por_receptor_observado"] >
    df_cuellos["p75_minutos_por_receptor_observado"]
)

# Solo se clasifican las franjas con informacion
# suficiente para interpretar demanda, espera y capacidad.

df_cuellos["datos_suficientes"] = (
    df_cuellos["solicitudes"].notna() &
    df_cuellos["espera_promedio_min"].notna() &
    df_cuellos["espera_p90_min"].notna() &
    df_cuellos["receptores_activos"].gt(0) &
    df_cuellos["minutos_servicio"].notna() &
    df_cuellos["minutos_por_receptor_observado"].notna()
)

senales = [
    "senal_demanda",
    "senal_espera_promedio",
    "senal_espera_p90",
    "senal_carga_observada"
]

df_cuellos["numero_senales"] = (
    df_cuellos[senales].sum(axis=1)
)

# ------------------------------------------------
# 5. Clasificacion exploratoria
# ------------------------------------------------

condicion_critica = (
    df_cuellos["senal_espera_p90"] &
    df_cuellos["senal_demanda"] &
    df_cuellos["senal_carga_observada"]
)

condicion_alta = (
    df_cuellos["senal_espera_p90"] &
    (
        df_cuellos["senal_demanda"] |
        df_cuellos["senal_espera_promedio"] |
        df_cuellos["senal_carga_observada"]
    )
)

condicion_seguimiento = (
    df_cuellos["numero_senales"] >= 2
)

df_cuellos["prioridad_cuello"] = np.select(
    [
        ~df_cuellos["datos_suficientes"],
        condicion_critica,
        condicion_alta,
        condicion_seguimiento
    ],
    [
        "Sin evidencia suficiente",
        "Critica",
        "Alta",
        "Seguimiento"
    ],
    default="Sin alerta combinada"
)

orden_prioridad = {
    "Critica": 1,
    "Alta": 2,
    "Seguimiento": 3,
    "Sin alerta combinada": 4,
    "Sin evidencia suficiente": 5
}

df_cuellos["orden_prioridad"] = (
    df_cuellos["prioridad_cuello"].map(orden_prioridad)
)

# ------------------------------------------------
# 6. Resumen por sede
# ------------------------------------------------

resumen_cuellos = (
    df_cuellos
    .groupby("sede", dropna=False)
    .agg(
        franjas_analizadas=("solicitudes", "size"),
        solicitudes=("solicitudes", "sum"),
        franjas_criticas=(
            "prioridad_cuello",
            lambda x: (x == "Critica").sum()
        ),
        franjas_altas=(
            "prioridad_cuello",
            lambda x: (x == "Alta").sum()
        ),
        franjas_seguimiento=(
            "prioridad_cuello",
            lambda x: (x == "Seguimiento").sum()
        ),
        franjas_sin_evidencia=(
            "prioridad_cuello",
            lambda x: (x == "Sin evidencia suficiente").sum()
        )
    )
    .reset_index()
)

resumen_cuellos["franjas_prioritarias"] = (
    resumen_cuellos["franjas_criticas"] +
    resumen_cuellos["franjas_altas"]
)

resumen_cuellos["pct_franjas_prioritarias"] = (
    100 *
    resumen_cuellos["franjas_prioritarias"] /
    resumen_cuellos["franjas_analizadas"]
).round(2)

resumen_cuellos = resumen_cuellos.sort_values(
    [
        "pct_franjas_prioritarias",
        "franjas_criticas",
        "franjas_altas"
    ],
    ascending=False
)

# ------------------------------------------------
# 7. Franjas para revision prioritaria
# ------------------------------------------------

columnas_detalle = [
    "sede",
    "fecha_dia",
    "hora_solicitud",
    "solicitudes",
    "turnos_validos",
    "espera_promedio_min",
    "espera_p90_min",
    "receptores_activos",
    "minutos_servicio",
    "minutos_por_receptor_observado",
    "numero_senales",
    "prioridad_cuello"
]

detalle_prioritario = (
    df_cuellos.loc[
        df_cuellos["prioridad_cuello"].isin(
            ["Critica", "Alta"]
        ),
        columnas_detalle + ["orden_prioridad"]
    ]
    .sort_values(
        [
            "orden_prioridad",
            "espera_p90_min",
            "solicitudes"
        ],
        ascending=[True, False, False]
    )
    .drop(columns="orden_prioridad")
)

# ------------------------------------------------
# 8. Presentacion de resultados
# ------------------------------------------------

print("\n1. CLASIFICACION GENERAL")

display(
    df_cuellos["prioridad_cuello"]
    .value_counts(dropna=False)
    .rename_axis("prioridad")
    .reset_index(name="franjas")
)

print("\n2. PRIORIZACION POR SEDE")
display(resumen_cuellos)

print("\n3. PRINCIPALES FRANJAS PRIORITARIAS")
display(detalle_prioritario.head(30))

# ------------------------------------------------
# 9. Validacion final
# ------------------------------------------------

assert len(df_cuellos) == n_franjas_original

assert (
    resumen_cuellos["franjas_analizadas"].sum()
    == n_franjas_original
)

assert (
    df_cuellos["prioridad_cuello"].notna().all()
)

assert (
    df_cuellos["solicitudes"].sum()
    == matriz_capacidad["solicitudes"].sum()
)

print("\n4. VALIDACION FINAL")
print(f"Franjas originales: {n_franjas_original:,}")
print(f"Franjas clasificadas: {len(df_cuellos):,}")
print(
    "Solicitudes conservadas: "
    f"{df_cuellos['solicitudes'].sum():,.0f}"
)
print("Conservacion de franjas: OK")
print("Conservacion de solicitudes: OK")
print("Base original sin modificaciones: OK")
print("=" * 70)

======================================================================
5.1.7.6.4.5.5.3.3. CUELLOS DE BOTELLA OPERATIVOS
======================================================================

1. CLASIFICACION GENERAL

                  prioridad  franjas
0      Sin alerta combinada    17547
1                      Alta     4356
2               Seguimiento     2185
3                   Critica     1635
4  Sin evidencia suficiente       16

2. PRIORIZACION POR SEDE

,sede,franjas_analizadas,solicitudes,franjas_criticas,franjas_altas,franjas_seguimiento,franjas_sin_evidencia,franjas_prioritarias,pct_franjas_prioritarias
2,Centro mayor,1378,79106,73,258,141,0,331,24.02
4,Fusagasuga,2001,45219,130,346,149,0,476,23.79
11,Unicentro de occidente,2080,56338,156,335,141,0,491,23.61
7,Santa librada,1895,40791,115,331,161,0,446,23.54
3,Funza,2007,53764,158,314,151,0,472,23.52
12,Usaquen,2125,55305,165,334,165,0,499,23.48
6,La mesa,1941,13326,173,282,164,11,455,23.44
1,Calle 63,2054,47613,125,356,184,0,481,23.42
9,Suba,1873,81721,114,319,149,0,433,23.12
10,Tintal plaza,2092,112312,106,377,213,0,483,23.09
0,Calle 26,2161,157060,119,379,201,1,498,23.04
8,Soacha,2093,93106,83,395,204,3,478,22.84
5,Girardot,2039,47419,118,330,162,1,448,21.97

3. PRINCIPALES FRANJAS PRIORITARIAS

,sede,fecha_dia,hora_solicitud,solicitudes,turnos_validos,espera_promedio_min,espera_p90_min,receptores_activos,minutos_servicio,minutos_por_receptor_observado,numero_senales,prioridad_cuello
4618,Centro mayor,2024-02-17,11,115,115,24.541449,115.690000,10.0,494.650000,49.465000,4,Critica
18595,Suba,2024-05-04,12,71,71,31.750000,93.016667,9.0,410.233333,45.581481,4,Critica
4619,Centro mayor,2024-02-17,12,82,82,18.442276,84.181667,10.0,465.466667,46.546667,4,Critica
4621,Centro mayor,2024-02-17,14,118,118,16.199153,79.776667,11.0,509.166667,46.287879,4,Critica
4756,Centro mayor,2024-03-04,16,89,89,12.808801,79.586667,11.0,478.983333,43.543939,4,Critica
18594,Suba,2024-05-04,11,77,77,36.594589,77.920000,8.0,415.233333,51.904167,4,Critica
19966,Tintal plaza,2024-03-02,11,84,84,19.919048,77.525000,6.0,283.433333,47.238889,4,Critica
19969,Tintal plaza,2024-03-02,14,74,74,16.334009,76.215000,6.0,290.166667,48.361111,4,Critica
4499,Centro mayor,2024-02-03,14,110,110,18.150909,75.950000,11.0,506.483333,46.043939,4,Critica
4744,Centro mayor,2024-03-02,12,93,93,22.174910,75.930000,10.0,405.450000,40.545000,4,Critica
4622,Centro mayor,2024-02-17,15,92,92,16.113406,75.061667,11.0,522.800000,47.527273,4,Critica
20742,Tintal plaza,2024-06-08,10,85,85,16.528824,74.610000,6.0,269.983333,44.997222,4,Critica
17787,Suba,2024-01-27,11,83,83,23.297189,73.036667,9.0,405.050000,45.005556,4,Critica
4746,Centro mayor,2024-03-02,14,116,116,18.165948,70.775000,10.0,531.533333,53.153333,4,Critica
4768,Centro mayor,2024-03-05,17,92,92,19.232790,70.265000,10.0,484.266667,48.426667,4,Critica
1523,Calle 26,2024-07-03,12,135,135,15.847284,69.693333,15.0,632.800000,42.186667,4,Critica
1635,Calle 26,2024-07-16,11,99,99,15.902862,68.416667,13.0,588.866667,45.297436,4,Critica
19978,Tintal plaza,2024-03-04,15,69,69,15.207488,68.190000,6.0,255.166667,42.527778,4,Critica
18606,Suba,2024-05-06,16,57,57,24.091228,67.156667,8.0,347.100000,43.387500,4,Critica
17857,Suba,2024-02-05,12,61,61,13.971038,66.950000,7.0,320.033333,45.719048,4,Critica
21812,Unicentro de occidente,2024-02-03,12,40,40,24.700417,66.723333,5.0,227.416667,45.483333,4,Critica
17911,Suba,2024-02-10,12,74,74,17.775000,63.656667,8.0,405.600000,50.700000,4,Critica
21750,Unicentro de occidente,2024-01-27,11,54,54,18.661420,63.433333,5.0,256.483333,51.296667,4,Critica
4570,Centro mayor,2024-02-12,17,84,84,13.249802,63.328333,10.0,445.750000,44.575000,4,Critica
19481,Tintal plaza,2024-01-05,16,96,96,9.668403,61.991667,8.0,337.100000,42.137500,4,Critica
22983,Unicentro de occidente,2024-06-29,11,52,52,14.041987,61.885000,6.0,290.566667,48.427778,4,Critica
2440,Calle 63,2024-02-03,11,35,35,25.349048,61.840000,5.0,200.383333,40.076667,4,Critica
18596,Suba,2024-05-04,13,57,57,19.256433,61.433333,8.0,369.000000,46.125000,4,Critica
23539,Unicentro de occidente,2024-09-07,10,62,62,17.528226,61.385000,5.0,261.416667,52.283333,4,Critica
23489,Unicentro de occidente,2024-09-02,9,41,41,16.216260,61.250000,3.0,162.983333,54.327778,4,Critica

4. VALIDACION FINAL
Franjas originales: 25,739
Franjas clasificadas: 25,739
Solicitudes conservadas: 883,080
Conservacion de franjas: OK
Conservacion de solicitudes: OK
Base original sin modificaciones: OK
======================================================================

In [11]:
print("\nCOLUMNAS DE MATRIZ_CAPACIDAD")
for columna in matriz_capacidad.columns:
    print(columna)

COLUMNAS DE MATRIZ_CAPACIDAD
sede
fecha_dia
dia_semana
hora_solicitud
solicitudes
receptores_observados
turnos_validos
espera_promedio_min
espera_mediana_min
espera_p90_min
umbral_p75_demanda
alta_demanda_relativa
espera_p90_referencia_sede
espera_elevada_relativa
alerta_presion_operativa
franja_inicio
minutos_servicio_registrados
receptores_activos
atenciones_en_curso
minutos_por_receptor_activo
servicios_iniciados
duracion_media_min
duracion_mediana_min
duracion_p90_min
solicitudes_por_receptor_activo
horas_receptor_equivalentes
alerta_integrada_preliminar

### 5.1.7.6.4.5.5.3.4. Síntesis diagnóstica y recomendaciones de gestión operativa

Esta sección consolida los hallazgos del diagnóstico integrado de demanda,
tiempos de espera, duración del servicio y capacidad operativa observada.

La priorización identifica franjas que requieren revisión, sin asumir
causalidad ni equiparar los receptores observados con la planta disponible.

Los registros originales y las atenciones solapadas se conservan.

In [16]:

# ================================================================
# 5.1.7.6.4.5.5.3.4.
# SINTESIS DIAGNOSTICA Y RECOMENDACIONES DE GESTION OPERATIVA
# ================================================================

import pandas as pd
import numpy as np
from IPython.display import display

print("=" * 75)
print("5.1.7.6.4.5.5.3.4. SINTESIS DIAGNOSTICA")
print("=" * 75)

# ------------------------------------------------
# 1. Recuperacion de la clasificacion validada
# ------------------------------------------------

# Se reutiliza la clasificacion de la seccion 5.5.3.3.
# No se modifican df_cuellos, matriz_capacidad ni
# los registros originales de Digiturnos.

df_sintesis = df_cuellos.copy(deep=True)

columnas_requeridas = [
    "sede",
    "fecha_dia",
    "hora_solicitud",
    "solicitudes",
    "turnos_validos",
    "espera_promedio_min",
    "espera_p90_min",
    "receptores_activos",
    "minutos_servicio",
    "prioridad_cuello",
    "orden_prioridad"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in df_sintesis.columns
]

if faltantes:
    raise KeyError(
        f"Faltan columnas requeridas: {faltantes}"
    )

# Alias de compatibilidad, sin recalcular prioridades
df_sintesis["prioridad"] = (
    df_sintesis["prioridad_cuello"]
)

# ------------------------------------------------
# 2. Validacion de integridad
# ------------------------------------------------

total_franjas = len(df_sintesis)
total_solicitudes = int(df_sintesis["solicitudes"].sum())

assert total_franjas == 25739, (
    "No coincide el universo de franjas validado."
)

assert total_solicitudes == 883080, (
    "No coincide el universo de solicitudes validado."
)

assert not df_sintesis.duplicated(
    subset=["sede", "fecha_dia", "hora_solicitud"]
).any(), "Existen franjas duplicadas."

assert df_sintesis["prioridad"].equals(
    df_sintesis["prioridad_cuello"]
), "La clasificacion no coincide con la original."

distribucion_esperada = {
    "Sin alerta combinada": 17547,
    "Alta": 4356,
    "Seguimiento": 2185,
    "Critica": 1635,
    "Sin evidencia suficiente": 16
}

distribucion_actual = (
    df_sintesis["prioridad"]
    .value_counts(dropna=False)
    .to_dict()
)

assert distribucion_actual == distribucion_esperada, (
    "La distribucion de prioridades cambio."
)

# ------------------------------------------------
# 3. Indicadores generales del diagnostico
# ------------------------------------------------

df_sintesis["es_critica"] = (
    df_sintesis["prioridad"] == "Critica"
)

df_sintesis["es_alta"] = (
    df_sintesis["prioridad"] == "Alta"
)

df_sintesis["es_prioritaria"] = (
    df_sintesis["prioridad"].isin(
        ["Critica", "Alta"]
    )
)

df_sintesis["es_seguimiento"] = (
    df_sintesis["prioridad"] == "Seguimiento"
)

df_sintesis["sin_evidencia"] = (
    df_sintesis["prioridad"] == "Sin evidencia suficiente"
)

franjas_criticas = int(df_sintesis["es_critica"].sum())
franjas_altas = int(df_sintesis["es_alta"].sum())
franjas_prioritarias = int(
    df_sintesis["es_prioritaria"].sum()
)

solicitudes_prioritarias = int(
    df_sintesis.loc[
        df_sintesis["es_prioritaria"],
        "solicitudes"
    ].sum()
)

pct_franjas_prioritarias = (
    100 * franjas_prioritarias / total_franjas
)

pct_solicitudes_prioritarias = (
    100 * solicitudes_prioritarias / total_solicitudes
)

print("\n1. INDICADORES GENERALES")

indicadores_generales = pd.DataFrame([
    {
        "indicador": "Franjas analizadas",
        "valor": total_franjas
    },
    {
        "indicador": "Solicitudes analizadas",
        "valor": total_solicitudes
    },
    {
        "indicador": "Franjas criticas",
        "valor": franjas_criticas
    },
    {
        "indicador": "Franjas altas",
        "valor": franjas_altas
    },
    {
        "indicador": "Franjas prioritarias",
        "valor": franjas_prioritarias
    },
    {
        "indicador": "% franjas prioritarias",
        "valor": round(pct_franjas_prioritarias, 2)
    },
    {
        "indicador": "Solicitudes en franjas prioritarias",
        "valor": solicitudes_prioritarias
    },
    {
        "indicador": "% solicitudes en franjas prioritarias",
        "valor": round(pct_solicitudes_prioritarias, 2)
    }
])

display(indicadores_generales)

# ------------------------------------------------
# 4. Diagnostico consolidado por sede
# ------------------------------------------------

diagnostico_sedes = (
    df_sintesis
    .groupby("sede", dropna=False)
    .agg(
        franjas_analizadas=("solicitudes", "size"),
        solicitudes=("solicitudes", "sum"),
        franjas_criticas=("es_critica", "sum"),
        franjas_altas=("es_alta", "sum"),
        franjas_seguimiento=("es_seguimiento", "sum"),
        franjas_sin_evidencia=("sin_evidencia", "sum"),
        franjas_prioritarias=("es_prioritaria", "sum"),
        receptores_max_observados=(
            "receptores_activos", "max"
        ),
        minutos_servicio_registrados=(
            "minutos_servicio", "sum"
        )
    )
    .reset_index()
)

# Las medias de espera se ponderan por los turnos
# validos de cada franja, no por el numero de franjas.

espera_sede = (
    df_sintesis
    .assign(
        suma_espera_ponderada=lambda d:
            d["espera_promedio_min"].fillna(0)
            * d["turnos_validos"].fillna(0)
    )
    .groupby("sede", dropna=False)
    .agg(
        suma_espera_ponderada=(
            "suma_espera_ponderada", "sum"
        ),
        turnos_con_espera=(
            "turnos_validos",
            lambda x: x[
                df_sintesis.loc[x.index, "espera_promedio_min"]
                .notna()
            ].sum()
        )
    )
    .reset_index()
)

diagnostico_sedes = diagnostico_sedes.merge(
    espera_sede,
    on="sede",
    how="left",
    validate="one_to_one"
)

diagnostico_sedes["espera_media_ponderada_min"] = (
    diagnostico_sedes["suma_espera_ponderada"]
    / diagnostico_sedes["turnos_con_espera"].replace(0, np.nan)
)

diagnostico_sedes = diagnostico_sedes.drop(
    columns=[
        "suma_espera_ponderada",
        "turnos_con_espera"
    ]
)

diagnostico_sedes["pct_franjas_prioritarias"] = (
    100
    * diagnostico_sedes["franjas_prioritarias"]
    / diagnostico_sedes["franjas_analizadas"]
)

diagnostico_sedes["pct_franjas_criticas"] = (
    100
    * diagnostico_sedes["franjas_criticas"]
    / diagnostico_sedes["franjas_analizadas"]
)

diagnostico_sedes["participacion_demanda_pct"] = (
    100
    * diagnostico_sedes["solicitudes"]
    / total_solicitudes
)

# Orden descriptivo de revision:
# primero proporcion de franjas prioritarias,
# luego numero de franjas criticas y demanda.

diagnostico_sedes = (
    diagnostico_sedes.sort_values(
        [
            "pct_franjas_prioritarias",
            "franjas_criticas",
            "solicitudes"
        ],
        ascending=[False, False, False]
    )
    .reset_index(drop=True)
)

diagnostico_sedes["orden_revision"] = (
    np.arange(1, len(diagnostico_sedes) + 1)
)

print("\n2. DIAGNOSTICO INTEGRADO POR SEDE")

columnas_sede = [
    "orden_revision",
    "sede",
    "solicitudes",
    "franjas_analizadas",
    "franjas_criticas",
    "franjas_altas",
    "franjas_prioritarias",
    "pct_franjas_prioritarias",
    "pct_franjas_criticas",
    "espera_media_ponderada_min",
    "receptores_max_observados",
    "participacion_demanda_pct"
]

display(
    diagnostico_sedes[columnas_sede].round(2)
)

# ------------------------------------------------
# 5. Identificacion de franjas para intervencion
# ------------------------------------------------

columnas_franja = [
    "sede",
    "fecha_dia",
    "hora_solicitud",
    "prioridad",
    "solicitudes",
    "turnos_validos",
    "espera_promedio_min",
    "espera_p90_min",
    "receptores_activos",
    "minutos_servicio"
]

franjas_intervencion = (
    df_sintesis.loc[
        df_sintesis["es_prioritaria"],
        columnas_franja + ["orden_prioridad"]
    ]
    .sort_values(
        [
            "orden_prioridad",
            "espera_p90_min",
            "solicitudes"
        ],
        ascending=[True, False, False]
    )
    .drop(columns="orden_prioridad")
    .reset_index(drop=True)
)

print("\n3. PRINCIPALES FRANJAS PARA REVISION OPERATIVA")

display(
    franjas_intervencion.head(30).round(2)
)

# ------------------------------------------------
# 6. Recomendaciones de gestion operativa
# ------------------------------------------------

recomendaciones_gestion = pd.DataFrame([
    {
        "prioridad": 1,
        "linea_accion": "Gestion de franjas criticas",
        "hallazgo": (
            "Coincidencia de demanda elevada, "
            "espera p90 elevada y carga observada elevada."
        ),
        "recomendacion": (
            "Revisar la distribucion de turnos, "
            "la secuencia de llamados y la asignacion "
            "operativa durante las franjas criticas."
        ),
        "indicador_seguimiento": (
            "Franjas criticas; espera p90; "
            "solicitudes por franja."
        )
    },
    {
        "prioridad": 2,
        "linea_accion": "Ajuste temporal de capacidad",
        "hallazgo": (
            "Concentracion de solicitudes y variaciones "
            "en la cantidad de receptores con actividad."
        ),
        "recomendacion": (
            "Contrastar los picos de demanda con "
            "turnos programados, pausas, disponibilidad "
            "real y competencias del personal."
        ),
        "indicador_seguimiento": (
            "Solicitudes por receptor activo; "
            "receptores observados por franja."
        )
    },
    {
        "prioridad": 3,
        "linea_accion": "Mejora de oportunidad",
        "hallazgo": (
            "Existencia de franjas con tiempos de espera "
            "elevados, especialmente en la cola superior."
        ),
        "recomendacion": (
            "Analizar los servicios y subservicios "
            "que concentran las mayores esperas "
            "y revisar sus rutas de atencion."
        ),
        "indicador_seguimiento": (
            "Espera media; espera p90; "
            "proporcion de turnos sobre umbral."
        )
    },
    {
        "prioridad": 4,
        "linea_accion": "Consistencia de registros",
        "hallazgo": (
            "Se identificaron atenciones solapadas "
            "que requieren validacion operativa."
        ),
        "recomendacion": (
            "Contrastar los casos con el proceso "
            "de registro y las reglas del sistema, "
            "sin excluirlos automaticamente."
        ),
        "indicador_seguimiento": (
            "Registros con solapamiento; "
            "casos revisados; causas documentadas."
        )
    },
    {
        "prioridad": 5,
        "linea_accion": "Seguimiento y mejora continua",
        "hallazgo": (
            "Las señales operativas presentan "
            "variaciones por sede, dia y hora."
        ),
        "recomendacion": (
            "Implementar seguimiento periodico "
            "por sede y franja, contrastando "
            "resultados antes y despues de los ajustes."
        ),
        "indicador_seguimiento": (
            "Franjas criticas y altas; "
            "espera p90; tendencia de demanda."
        )
    }
])

print("\n4. RECOMENDACIONES DE GESTION OPERATIVA")
display(recomendaciones_gestion)

# ------------------------------------------------
# 7. Sintesis ejecutiva automatizada
# ------------------------------------------------

print("\n5. SINTESIS EJECUTIVA")

print(
    f"Se analizaron {total_solicitudes:,} solicitudes "
    f"distribuidas en {total_franjas:,} franjas "
    "de demanda por sede, dia y hora."
)

print(
    f"Se identificaron {franjas_prioritarias:,} "
    "franjas con prioridad critica o alta, "
    f"equivalentes al {pct_franjas_prioritarias:.2f}% "
    "del total."
)

print(
    f"Estas franjas concentran "
    f"{solicitudes_prioritarias:,} solicitudes "
    f"({pct_solicitudes_prioritarias:.2f}% "
    "del universo analizado)."
)

print(
    "La clasificacion es exploratoria: identifica "
    "coincidencias de senales de presion, "
    "pero no demuestra por si sola las causas "
    "de los cuellos de botella."
)

print(
    "Los receptores activos corresponden a usuarios "
    "con actividad registrada, no a la dotacion "
    "real disponible ni a una tasa de utilizacion."
)

print(
    "Se recomienda priorizar la revision de franjas "
    "criticas y altas, contrastando los hallazgos "
    "con horarios, servicios, procedimientos "
    "y disponibilidad efectiva de personal."
)

# ------------------------------------------------
# 8. Validacion final
# ------------------------------------------------

assert len(df_sintesis) == len(df_cuellos)
assert len(df_sintesis) == len(matriz_capacidad)

assert (
    diagnostico_sedes["franjas_analizadas"].sum()
    == total_franjas
)

assert (
    diagnostico_sedes["solicitudes"].sum()
    == total_solicitudes
)

assert (
    diagnostico_sedes["franjas_prioritarias"].sum()
    == franjas_prioritarias
)

assert len(franjas_intervencion) == franjas_prioritarias

assert df_sintesis["prioridad"].equals(
    df_sintesis["prioridad_cuello"]
)

print("\n6. VALIDACION FINAL")
print(f"Franjas conservadas: {total_franjas:,}")
print(f"Solicitudes conservadas: {total_solicitudes:,}")
print(f"Franjas prioritarias: {franjas_prioritarias:,}")
print("Conciliacion de prioridades: OK")
print("Conciliacion por sede: OK")
print("Conservacion de franjas: OK")
print("Conservacion de solicitudes: OK")
print("Base original sin modificaciones: OK")
print("=" * 75)

===========================================================================
5.1.7.6.4.5.5.3.4. SINTESIS DIAGNOSTICA
===========================================================================

1. INDICADORES GENERALES

                               indicador      valor
0                     Franjas analizadas   25739.00
1                 Solicitudes analizadas  883080.00
2                       Franjas criticas    1635.00
3                          Franjas altas    4356.00
4                   Franjas prioritarias    5991.00
5                 % franjas prioritarias      23.28
6    Solicitudes en franjas prioritarias  250284.00
7  % solicitudes en franjas prioritarias      28.34

2. DIAGNOSTICO INTEGRADO POR SEDE

,orden_revision,sede,solicitudes,franjas_analizadas,franjas_criticas,franjas_altas,franjas_prioritarias,pct_franjas_prioritarias,pct_franjas_criticas,espera_media_ponderada_min,receptores_max_observados,participacion_demanda_pct
0,1,Centro mayor,79106,1378,73,258,331,24.02,5.30,6.82,12.0,8.96
1,2,Fusagasuga,45219,2001,130,346,476,23.79,6.50,5.06,5.0,5.12
2,3,Unicentro de occidente,56338,2080,156,335,491,23.61,7.50,6.41,6.0,6.38
3,4,Santa librada,40791,1895,115,331,446,23.54,6.07,6.63,6.0,4.62
4,5,Funza,53764,2007,158,314,472,23.52,7.87,3.93,5.0,6.09
5,6,Usaquen,55305,2125,165,334,499,23.48,7.76,5.95,8.0,6.26
6,7,La mesa,13326,1941,173,282,455,23.44,8.91,4.44,2.0,1.51
7,8,Calle 63,47613,2054,125,356,481,23.42,6.09,5.22,8.0,5.39
8,9,Suba,81721,1873,114,319,433,23.12,6.09,7.74,10.0,9.25
9,10,Tintal plaza,112312,2092,106,377,483,23.09,5.07,5.67,10.0,12.72
10,11,Calle 26,157060,2161,119,379,498,23.04,5.51,5.49,16.0,17.79
11,12,Soacha,93106,2093,83,395,478,22.84,3.97,7.22,10.0,10.54
12,13,Girardot,47419,2039,118,330,448,21.97,5.79,5.97,5.0,5.37

3. PRINCIPALES FRANJAS PARA REVISION OPERATIVA

,sede,fecha_dia,hora_solicitud,prioridad,solicitudes,turnos_validos,espera_promedio_min,espera_p90_min,receptores_activos,minutos_servicio
0,Centro mayor,2024-02-17,11,Critica,115,115,24.54,115.69,10.0,494.65
1,Suba,2024-05-04,12,Critica,71,71,31.75,93.02,9.0,410.23
2,Centro mayor,2024-02-17,12,Critica,82,82,18.44,84.18,10.0,465.47
3,Centro mayor,2024-02-17,14,Critica,118,118,16.20,79.78,11.0,509.17
4,Centro mayor,2024-03-04,16,Critica,89,89,12.81,79.59,11.0,478.98
5,Suba,2024-05-04,11,Critica,77,77,36.59,77.92,8.0,415.23
6,Tintal plaza,2024-03-02,11,Critica,84,84,19.92,77.53,6.0,283.43
7,Tintal plaza,2024-03-02,14,Critica,74,74,16.33,76.22,6.0,290.17
8,Centro mayor,2024-02-03,14,Critica,110,110,18.15,75.95,11.0,506.48
9,Centro mayor,2024-03-02,12,Critica,93,93,22.17,75.93,10.0,405.45
10,Centro mayor,2024-02-17,15,Critica,92,92,16.11,75.06,11.0,522.80
11,Tintal plaza,2024-06-08,10,Critica,85,85,16.53,74.61,6.0,269.98
12,Suba,2024-01-27,11,Critica,83,83,23.30,73.04,9.0,405.05
13,Centro mayor,2024-03-02,14,Critica,116,116,18.17,70.78,10.0,531.53
14,Centro mayor,2024-03-05,17,Critica,92,92,19.23,70.26,10.0,484.27
15,Calle 26,2024-07-03,12,Critica,135,135,15.85,69.69,15.0,632.80
16,Calle 26,2024-07-16,11,Critica,99,99,15.90,68.42,13.0,588.87
17,Tintal plaza,2024-03-04,15,Critica,69,69,15.21,68.19,6.0,255.17
18,Suba,2024-05-06,16,Critica,57,57,24.09,67.16,8.0,347.10
19,Suba,2024-02-05,12,Critica,61,61,13.97,66.95,7.0,320.03
20,Unicentro de occidente,2024-02-03,12,Critica,40,40,24.70,66.72,5.0,227.42
21,Suba,2024-02-10,12,Critica,74,74,17.77,63.66,8.0,405.60
22,Unicentro de occidente,2024-01-27,11,Critica,54,54,18.66,63.43,5.0,256.48
23,Centro mayor,2024-02-12,17,Critica,84,84,13.25,63.33,10.0,445.75
24,Tintal plaza,2024-01-05,16,Critica,96,96,9.67,61.99,8.0,337.10
25,Unicentro de occidente,2024-06-29,11,Critica,52,52,14.04,61.88,6.0,290.57
26,Calle 63,2024-02-03,11,Critica,35,35,25.35,61.84,5.0,200.38
27,Suba,2024-05-04,13,Critica,57,57,19.26,61.43,8.0,369.00
28,Unicentro de occidente,2024-09-07,10,Critica,62,62,17.53,61.38,5.0,261.42
29,Unicentro de occidente,2024-09-02,9,Critica,41,41,16.22,61.25,3.0,162.98

4. RECOMENDACIONES DE GESTION OPERATIVA

,prioridad,linea_accion,hallazgo,recomendacion,indicador_seguimiento
0,1,Gestion de franjas criticas,"Coincidencia de demanda elevada, espera p90 el...","Revisar la distribucion de turnos, la secuenci...",Franjas criticas; espera p90; solicitudes por ...
1,2,Ajuste temporal de capacidad,Concentracion de solicitudes y variaciones en ...,Contrastar los picos de demanda con turnos pro...,Solicitudes por receptor activo; receptores ob...
2,3,Mejora de oportunidad,Existencia de franjas con tiempos de espera el...,Analizar los servicios y subservicios que conc...,Espera media; espera p90; proporcion de turnos...
3,4,Consistencia de registros,Se identificaron atenciones solapadas que requ...,Contrastar los casos con el proceso de registr...,Registros con solapamiento; casos revisados; c...
4,5,Seguimiento y mejora continua,Las señales operativas presentan variaciones p...,Implementar seguimiento periodico por sede y f...,Franjas criticas y altas; espera p90; tendenci...

5. SINTESIS EJECUTIVA
Se analizaron 883,080 solicitudes distribuidas en 25,739 franjas de demanda por sede, dia y hora.
Se identificaron 5,991 franjas con prioridad critica o alta, equivalentes al 23.28% del total.
Estas franjas concentran 250,284 solicitudes (28.34% del universo analizado).
La clasificacion es exploratoria: identifica coincidencias de senales de presion, pero no demuestra por si sola las causas de los cuellos de botella.
Los receptores activos corresponden a usuarios con actividad registrada, no a la dotacion real disponible ni a una tasa de utilizacion.
Se recomienda priorizar la revision de franjas criticas y altas, contrastando los hallazgos con horarios, servicios, procedimientos y disponibilidad efectiva de personal.

6. VALIDACION FINAL
Franjas conservadas: 25,739
Solicitudes conservadas: 883,080
Franjas prioritarias: 5,991
Conciliacion de prioridades: OK
Conciliacion por sede: OK
Conservacion de franjas: OK
Conservacion de solicitudes: OK
Base original sin modificaciones: OK
===========================================================================

In [14]:
print("COLUMNAS DE df_cuellos")
print(df_cuellos.columns.tolist())

print("\nDATAFRAMES DISPONIBLES CON VARIABLES DE PRIORIDAD")

for nombre, objeto in list(globals().items()):
    if isinstance(objeto, pd.DataFrame):
        columnas = [
            c for c in objeto.columns
            if "prior" in str(c).lower()
            or "critic" in str(c).lower()
            or "alerta" in str(c).lower()
        ]

        if columnas:
            print(
                f"{nombre}: "
                f"{len(objeto):,} registros | "
                f"{columnas}"
            )

COLUMNAS DE df_cuellos
['sede', 'fecha_dia', 'dia_semana', 'hora_solicitud', 'solicitudes', 'receptores_observados', 'turnos_validos', 'espera_promedio_min', 'espera_mediana_min', 'espera_p90_min', 'umbral_p75_demanda', 'alta_demanda_relativa', 'espera_p90_referencia_sede', 'espera_elevada_relativa', 'alerta_presion_operativa', 'franja_inicio', 'minutos_servicio', 'receptores_activos', 'atenciones_en_curso', 'minutos_por_receptor_activo', 'servicios_iniciados', 'duracion_media_min', 'duracion_mediana_min', 'duracion_p90_min', 'solicitudes_por_receptor_activo', 'horas_receptor_equivalentes', 'alerta_integrada_preliminar', 'minutos_por_receptor_observado', 'p75_solicitudes', 'p75_espera_promedio_min', 'p75_espera_p90_min', 'p75_minutos_por_receptor_observado', 'senal_demanda', 'senal_espera_promedio', 'senal_espera_p90', 'senal_carga_observada', 'datos_suficientes', 'numero_senales', 'prioridad_cuello', 'orden_prioridad']

DATAFRAMES DISPONIBLES CON VARIABLES DE PRIORIDAD
pares: 251 registros | ['prioridad_revision']
resumen_prioridad: 4 registros | ['prioridad_revision']
detalle_prioritario: 5,991 registros | ['prioridad_cuello']
df_diag: 883,080 registros | ['alerta_solapamiento']
base_sedes: 883,080 registros | ['alerta_solapamiento']
df_franjas: 883,080 registros | ['alerta_solapamiento']
base_franjas: 883,080 registros | ['alerta_solapamiento']
matriz_franjas: 25,739 registros | ['alerta_presion_operativa']
resumen_presion: 13 registros | ['franjas_alerta_presion', 'pct_franjas_alerta']
base_integrada: 25,739 registros | ['alerta_presion_operativa']
matriz_capacidad: 25,739 registros | ['alerta_presion_operativa', 'alerta_integrada_preliminar']
resumen_capacidad: 13 registros | ['franjas_alerta', 'pct_franjas_alerta']
df_cuellos: 25,739 registros | ['alerta_presion_operativa', 'alerta_integrada_preliminar', 'prioridad_cuello', 'orden_prioridad']
resumen_cuellos: 13 registros | ['franjas_criticas', 'franjas_prioritarias', 'pct_franjas_prioritarias']
df_sintesis: 25,739 registros | ['alerta_presion_operativa', 'alerta_integrada_preliminar', 'prioridad_cuello', 'orden_prioridad']

In [15]:
# ============================================================
# 5.1.7.6.4.5.5.3.4
# CORRECCION DE COMPATIBILIDAD PARA SINTESIS DIAGNOSTICA
# ============================================================

# Recuperar la clasificacion validada de cuellos de botella
df_sintesis = df_cuellos.copy()

# Crear alias sin modificar la clasificacion original
df_sintesis["prioridad"] = df_sintesis["prioridad_cuello"]

# Validar conservacion de registros
assert len(df_sintesis) == 25739

# Validar coincidencia de clasificaciones
assert (
    df_sintesis["prioridad"].fillna("__NULO__")
    == df_sintesis["prioridad_cuello"].fillna("__NULO__")
).all()

# Mostrar resultados
print("=" * 65)
print("VALIDACION DE CLASIFICACION PARA SINTESIS DIAGNOSTICA")
print("=" * 65)

print("\nDistribucion de prioridades:")
print(
    df_sintesis["prioridad"]
    .value_counts(dropna=False)
    .to_string()
)

print(f"\nFranjas conservadas: {len(df_sintesis):,}")
print("Clasificacion original conservada: OK")
print("Base original sin modificaciones: OK")

=================================================================
VALIDACION DE CLASIFICACION PARA SINTESIS DIAGNOSTICA
=================================================================

Distribucion de prioridades:
prioridad
Sin alerta combinada        17547
Alta                         4356
Seguimiento                  2185
Critica                      1635
Sin evidencia suficiente       16

Franjas conservadas: 25,739
Clasificacion original conservada: OK
Base original sin modificaciones: OK

5.1.7.6.4.5.5.4 — Construcción de archivos procesados y exportación reproducible

In [17]:

# ============================================================
# 5.1.7.6.4.5.5.4
# CONSTRUCCION DE ARCHIVOS PROCESADOS Y EXPORTACION REPRODUCIBLE
# ============================================================

from pathlib import Path
from datetime import datetime, timezone
import hashlib
import json
import pandas as pd

print("=" * 75)
print("5.1.7.6.4.5.5.4. EXPORTACION REPRODUCIBLE")
print("=" * 75)

# ------------------------------------------------------------
# 1. LOCALIZAR EL PROYECTO
# ------------------------------------------------------------

ruta_actual = Path.cwd().resolve()

if (ruta_actual / "data" / "raw").is_dir():
    proyecto = ruta_actual
elif (ruta_actual.parent / "data" / "raw").is_dir():
    proyecto = ruta_actual.parent
else:
    raise FileNotFoundError(
        "No se encontro data/raw. "
        "Abre el notebook desde la carpeta del proyecto."
    )

salida = proyecto / "data" / "processed"
salida.mkdir(parents=True, exist_ok=True)

print(f"\nProyecto: {proyecto}")
print(f"Destino: {salida}")

# ------------------------------------------------------------
# 2. VALIDAR LOS DATAFRAMES DE ORIGEN
# ------------------------------------------------------------

fuentes = {
    "digiturnos_atenciones": "df_diag",
    "digiturnos_franjas": "df_sintesis",
    "digiturnos_diagnostico_sedes": "resumen_cuellos",
}

for archivo, variable in fuentes.items():
    if variable not in globals():
        raise NameError(
            f"No existe el DataFrame '{variable}'. "
            "Ejecuta primero las secciones anteriores."
        )

    if not isinstance(globals()[variable], pd.DataFrame):
        raise TypeError(
            f"'{variable}' no es un DataFrame de pandas."
        )

# Se comprueba que el detalle conserve el universo auditado.
assert len(df_diag) == 883_080, (
    "El detalle no coincide con los 883.080 registros auditados."
)

assert len(df_sintesis) == 25_739, (
    "Las franjas no coinciden con las 25.739 validadas."
)

assert df_sintesis["solicitudes"].sum() == 883_080, (
    "Las solicitudes por franja no concilian."
)

assert len(resumen_cuellos) == 13, (
    "El resumen de sedes no contiene las 13 sedes esperadas."
)

# ------------------------------------------------------------
# 3. PREPARAR COPIAS INDEPENDIENTES
# ------------------------------------------------------------

tablas = {
    nombre: globals()[variable].copy(deep=True)
    for nombre, variable in fuentes.items()
}

# Se conserva el orden original de las filas y columnas.
# Se retira solamente el indice tecnico de pandas al exportar.
# No se eliminan registros ni atenciones solapadas.

# ------------------------------------------------------------
# 4. VALIDAR CAMPOS DE INTEGRACION
# ------------------------------------------------------------

requeridos = {
    "digiturnos_atenciones": ["sede"],
    "digiturnos_franjas": [
        "sede", "fecha_dia", "hora_solicitud",
        "solicitudes", "prioridad"
    ],
    "digiturnos_diagnostico_sedes": [
        "sede", "solicitudes", "franjas_prioritarias"
    ],
}

for nombre, columnas in requeridos.items():
    faltantes = [
        col for col in columnas
        if col not in tablas[nombre].columns
    ]

    if faltantes:
        raise KeyError(
            f"{nombre}: faltan columnas {faltantes}"
        )

# Clave unica de la tabla agregada por franja.
claves_franja = [
    "sede", "fecha_dia", "hora_solicitud"
]

if tablas["digiturnos_franjas"].duplicated(
    subset=claves_franja
).any():
    raise ValueError(
        "Existen claves duplicadas en digiturnos_franjas."
    )

# Clave unica del resumen por sede.
if tablas["digiturnos_diagnostico_sedes"].duplicated(
    subset=["sede"]
).any():
    raise ValueError(
        "Existen sedes duplicadas en el resumen."
    )

# ------------------------------------------------------------
# 5. EXPORTAR TABLAS VALIDADAS
# ------------------------------------------------------------

manifiesto = {
    "proceso": "Digiturnos - exportacion reproducible",
    "fecha_utc": datetime.now(
        timezone.utc
    ).isoformat(),
    "universo_auditado": 883080,
    "franjas_validadas": 25739,
    "criterios": {
        "conservar_registros_originales": True,
        "excluir_solapamientos_automaticamente": False,
        "clasificacion_prioridad": (
            "Exploratoria; no representa causalidad"
        ),
        "capacidad": (
            "Actividad observada; no disponibilidad contractual"
        )
    },
    "archivos": {}
}

for nombre, tabla in tablas.items():

    destino = salida / f"{nombre}.csv"

    tabla.to_csv(
        destino,
        index=False,
        sep=";",
        encoding="utf-8-sig",
        date_format="%Y-%m-%d %H:%M:%S",
        float_format="%.8f"
    )

    hash_sha256 = hashlib.sha256(
        destino.read_bytes()
    ).hexdigest()

    manifiesto["archivos"][destino.name] = {
        "filas": int(len(tabla)),
        "columnas": int(len(tabla.columns)),
        "sha256": hash_sha256,
        "campos": tabla.columns.tolist()
    }

    print(
        f"\nEXPORTADO: {destino.name}"
        f"\nFilas: {len(tabla):,}"
        f"\nColumnas: {len(tabla.columns)}"
    )

# ------------------------------------------------------------
# 6. EXPORTAR DICCIONARIO DE DATOS
# ------------------------------------------------------------

diccionario = []

for nombre, tabla in tablas.items():
    for columna in tabla.columns:
        diccionario.append({
            "tabla": nombre,
            "campo": columna,
            "tipo_pandas": str(tabla[columna].dtype),
            "registros": len(tabla),
            "nulos": int(tabla[columna].isna().sum()),
            "porcentaje_nulos": round(
                tabla[columna].isna().mean() * 100, 4
            )
        })

df_diccionario = pd.DataFrame(diccionario)

df_diccionario.to_csv(
    salida / "digiturnos_diccionario.csv",
    index=False,
    sep=";",
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# 7. EXPORTAR MANIFIESTO DE TRAZABILIDAD
# ------------------------------------------------------------

ruta_manifiesto = salida / "digiturnos_manifiesto.json"

with open(
    ruta_manifiesto,
    "w",
    encoding="utf-8"
) as archivo:
    json.dump(
        manifiesto,
        archivo,
        ensure_ascii=False,
        indent=2
    )

# ------------------------------------------------------------
# 8. VALIDACION FINAL DE ARCHIVOS
# ------------------------------------------------------------

print("\n" + "=" * 75)
print("VALIDACION FINAL")
print("=" * 75)

for nombre, tabla in tablas.items():
    ruta = salida / f"{nombre}.csv"

    filas_exportadas = sum(
        1 for _ in open(
            ruta,
            "r",
            encoding="utf-8-sig"
        )
    ) - 1

    assert filas_exportadas == len(tabla), (
        f"Error de conciliacion en {nombre}"
    )

    print(
        f"{nombre}: "
        f"{filas_exportadas:,} filas - OK"
    )

print("\nUniverso de atenciones conservado: OK")
print("Franjas de demanda conservadas: OK")
print("Sedes conservadas: OK")
print("Solapamientos no excluidos: OK")
print("Archivos originales sin modificaciones: OK")
print("Diccionario de datos: OK")
print("Manifiesto de trazabilidad: OK")

print("\nEXPORTACION FINALIZADA")
print("=" * 75)

===========================================================================
5.1.7.6.4.5.5.4. EXPORTACION REPRODUCIBLE
===========================================================================

Proyecto: C:\Users\acoba\Documents\GitHub\Prueba_Analista_BI
Destino: C:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\processed

EXPORTADO: digiturnos_atenciones.csv
Filas: 883,080
Columnas: 26

EXPORTADO: digiturnos_franjas.csv
Filas: 25,739
Columnas: 46

EXPORTADO: digiturnos_diagnostico_sedes.csv
Filas: 13
Columnas: 9

===========================================================================
VALIDACION FINAL
===========================================================================
digiturnos_atenciones: 883,080 filas - OK
digiturnos_franjas: 25,739 filas - OK
digiturnos_diagnostico_sedes: 13 filas - OK

Universo de atenciones conservado: OK
Franjas de demanda conservadas: OK
Sedes conservadas: OK
Solapamientos no excluidos: OK
Archivos originales sin modificaciones: OK
Diccionario de datos: OK
Manifiesto de trazabilidad: OK

EXPORTACION FINALIZADA
===========================================================================

In [18]:

# ============================================================
# 5.1.7.6.4.5.5.5
# INSPECCION DE ESQUEMAS PARA POSTGRESQL
# ============================================================

import pandas as pd

tablas_modelo = {
    "digiturnos_atenciones": df_diag,
    "digiturnos_franjas": df_sintesis,
    "digiturnos_diagnostico_sedes": resumen_cuellos
}

for nombre, df in tablas_modelo.items():

    print("\n" + "=" * 75)
    print(f"TABLA: {nombre}")
    print("=" * 75)

    print(f"Registros: {len(df):,}")
    print(f"Columnas: {len(df.columns)}")

    esquema = pd.DataFrame({
        "columna": df.columns,
        "tipo_python": df.dtypes.astype(str).values,
        "nulos": df.isna().sum().values,
        "ejemplo": [
            str(df[col].dropna().iloc[0])
            if df[col].notna().any()
            else None
            for col in df.columns
        ]
    })

    print(esquema.to_string(index=False))

===========================================================================
TABLA: digiturnos_atenciones
===========================================================================
Registros: 883,080
Columnas: 26
                 columna    tipo_python  nulos                                          ejemplo
                    Sede         string      0                                         Calle 26
                     UES         string      0                                         Subsidio
            Clasifiacion         string      0                          Radicacion afiliaciones
        Usuario_receptor         string      0                                         39767666
           Tipo_servicio         string      0                                         Servicio
  SUBSERVICIO_HOMOLOGADO         string      0 Rad afiliacion trabajadores hasta 10 formularios
           Fecha_Servico         string      0                                       20/03/2024
 Hora_solicitud_Servicio         string      0                                         10:49:41
  Hora_llamado__Servicio         string      0                                         10:54:47
Hora_finalizado_Servicio         string      0                                         10:56:03
  Identificacion_Cliente         string      0                                         29012215
            Tipo_Oficina         string      0                                           Bogota
    id_registro_original          int64      0                                                0
            dt_solicitud datetime64[us]      0                              2024-03-20 10:49:41
              dt_llamado datetime64[us]      0                              2024-03-20 10:54:47
         dt_finalizacion datetime64[us]      0                              2024-03-20 10:56:03
                receptor         string      0                                         39767666
                    sede         string      0                                         Calle 26
        fecha_incompleta           bool      0                                            False
      secuencia_invalida           bool      0                                            False
   duracion_atencion_min        float64      0                               1.2666666666666666
        intervalo_valido           bool      0                                             True
         espera_min_diag        float64      0                                              5.1
       atencion_min_diag        float64      0                               1.2666666666666666
    tiempos_validos_diag           bool      0                                             True
     alerta_solapamiento           bool      0                                            False

===========================================================================
TABLA: digiturnos_franjas
===========================================================================
Registros: 25,739
Columnas: 46
                           columna    tipo_python  nulos             ejemplo
                              sede         object      0            Calle 26
                         fecha_dia         object      0          2024-01-02
                        dia_semana          int32      0                   1
                    hora_solicitud          int32      0                   7
                       solicitudes          int64      0                  27
             receptores_observados          int64      0                   6
                    turnos_validos          int64      0                  27
               espera_promedio_min        float64      0   6.818518518518518
                espera_mediana_min        float64      0  0.2833333333333333
                    espera_p90_min        float64      0  21.016666666666673
                umbral_p75_demanda        float64      0                93.0
             alta_demanda_relativa           bool      0               False
        espera_p90_referencia_sede        float64      0  17.666666666666668
           espera_elevada_relativa           bool      0                True
          alerta_presion_operativa           bool      0               False
                     franja_inicio datetime64[us]      0 2024-01-02 07:00:00
                  minutos_servicio        float64      0  113.86666666666667
                receptores_activos        float64      0                 5.0
               atenciones_en_curso        float64      0                21.0
       minutos_por_receptor_activo        float64     16  22.773333333333333
               servicios_iniciados        float64      0                21.0
                duracion_media_min        float64     17   5.788888888888889
              duracion_mediana_min        float64     17   5.116666666666666
                  duracion_p90_min        float64     17                11.9
   solicitudes_por_receptor_activo        float64     16                 5.4
       horas_receptor_equivalentes        float64      0   1.897777777777778
       alerta_integrada_preliminar           bool      0               False
    minutos_por_receptor_observado        float64     16  22.773333333333333
                   p75_solicitudes        float64      0                93.0
           p75_espera_promedio_min        float64      0   6.741947565543071
                p75_espera_p90_min        float64      0  20.603333333333346
p75_minutos_por_receptor_observado        float64      0   40.14315476190477
                     senal_demanda           bool      0               False
             senal_espera_promedio           bool      0                True
                  senal_espera_p90           bool      0                True
             senal_carga_observada           bool      0               False
                 datos_suficientes           bool      0                True
                    numero_senales          int64      0                   2
                  prioridad_cuello            str      0                Alta
                   orden_prioridad          int64      0                   2
                         prioridad            str      0                Alta
                        es_critica           bool      0               False
                           es_alta           bool      0                True
                    es_prioritaria           bool      0                True
                    es_seguimiento           bool      0               False
                     sin_evidencia           bool      0               False

===========================================================================
TABLA: digiturnos_diagnostico_sedes
===========================================================================
Registros: 13
Columnas: 9
                 columna tipo_python  nulos      ejemplo
                    sede         str      0 Centro mayor
      franjas_analizadas       int64      0         1378
             solicitudes       int64      0        79106
        franjas_criticas       int64      0           73
           franjas_altas       int64      0          258
     franjas_seguimiento       int64      0          141
   franjas_sin_evidencia       int64      0            0
    franjas_prioritarias       int64      0          331
pct_franjas_prioritarias     float64      0        24.02

In [21]:

# ============================================================
# 5.1.7.6.4.5.5.5
# DIAGNOSTICO DEL FORMATO CSV
# ============================================================

from pathlib import Path
import csv

proyecto = Path.cwd().resolve()

if proyecto.name.lower() == "notebooks":
    proyecto = proyecto.parent

ruta = (
    proyecto
    / "data"
    / "processed"
    / "digiturnos_atenciones.csv"
)

print("=" * 70)
print("DIAGNOSTICO DEL ARCHIVO")
print("=" * 70)

print("Ruta:", ruta)
print("Existe:", ruta.exists())

if not ruta.exists():
    raise FileNotFoundError(ruta)

print("Tamano en bytes:", ruta.stat().st_size)

# Mostrar las primeras lineas fisicas
print("\nPRIMERAS 5 LINEAS:")

with open(ruta, "r", encoding="utf-8-sig") as f:
    for i in range(5):
        linea = f.readline()
        print(f"Linea {i+1}: {repr(linea[:350])}")

# Examinar la linea reportada por Pandas
print("\nLINEAS CERCANAS AL ERROR:")

with open(ruta, "r", encoding="utf-8-sig") as f:
    for i, linea in enumerate(f, start=1):
        if 1974 <= i <= 1980:
            print(f"Linea {i}: {repr(linea[:350])}")
        if i > 1980:
            break

# Detectar separador probable
print("\nDETECCION DEL SEPARADOR:")

with open(ruta, "r", encoding="utf-8-sig") as f:
    muestra = f.read(10000)

try:
    dialecto = csv.Sniffer().sniff(
        muestra,
        delimiters=",;\t|"
    )
    print("Separador probable:", repr(dialecto.delimiter))
except csv.Error:
    print("No se pudo identificar un separador confiable.")

print("\nDIAGNOSTICO FINALIZADO")

======================================================================
DIAGNOSTICO DEL ARCHIVO
======================================================================
Ruta: C:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\processed\digiturnos_atenciones.csv
Existe: True
Tamano en bytes: 258868924

PRIMERAS 5 LINEAS:
Linea 1: 'Sede;UES;Clasifiacion;Usuario_receptor;Tipo_servicio;SUBSERVICIO_HOMOLOGADO;Fecha_Servico;Hora_solicitud_Servicio;Hora_llamado__Servicio;Hora_finalizado_Servicio;Identificacion_Cliente;Tipo_Oficina;id_registro_original;dt_solicitud;dt_llamado;dt_finalizacion;receptor;sede;fecha_incompleta;secuencia_invalida;duracion_atencion_min;intervalo_valido;es'
Linea 2: 'Calle 26;Subsidio;Radicacion afiliaciones;39767666;Servicio;Rad afiliacion trabajadores hasta 10 formularios;20/03/2024;10:49:41;10:54:47;10:56:03;29012215;Bogota;0;2024-03-20 10:49:41;2024-03-20 10:54:47;2024-03-20 10:56:03;39767666;Calle 26;False;False;1.26666667;True;5.10000000;1.26666667;True;False\n'
Linea 3: 'Calle 26;Subsidio;Radicacion afiliaciones;52622358;Servicio;Rad afiliacion trabajadores hasta 10 formularios;7/09/2024;10:08:56;10:09:18;10:12:34;20000240;Bogota;1;2024-09-07 10:08:56;2024-09-07 10:09:18;2024-09-07 10:12:34;52622358;Calle 26;False;False;3.26666667;True;0.36666667;3.26666667;True;False\n'
Linea 4: 'Calle 26;Subsidio;Radicacion afiliaciones;52622358;Servicio;Rad afiliacion trabajadores hasta 10 formularios;7/09/2024;10:12:34;10:12:34;10:16:37;20000240;Bogota;2;2024-09-07 10:12:34;2024-09-07 10:12:34;2024-09-07 10:16:37;52622358;Calle 26;False;False;4.05000000;True;0.00000000;4.05000000;True;False\n'
Linea 5: 'Calle 26;Subsidio;Tarjeta multiservicios;1024494171;Servicio;Entrega tams primera vez;2/09/2024;9:22:11;9:22:11;9:28:19;20000187;Bogota;3;2024-09-02 09:22:11;2024-09-02 09:22:11;2024-09-02 09:28:19;1024494171;Calle 26;False;False;6.13333333;True;0.00000000;6.13333333;True;False\n'

LINEAS CERCANAS AL ERROR:
Linea 1974: 'Calle 26;Subsidio;Subsidio de vivienda;52622358;Servicio;Informacion general subsidio de vivienda;27/02/2024;16:54:57;16:56:12;17:05:40;11404157;Bogota;1972;2024-02-27 16:54:57;2024-02-27 16:56:12;2024-02-27 17:05:40;52622358;Calle 26;False;False;9.46666667;True;1.25000000;9.46666667;True;False\n'
Linea 1975: 'Calle 26;Subsidio;Pagos;1103714304;Servicio;Cambio de clave por olvido;19/02/2024;14:53:20;14:53:20;14:54:03;11403675;Bogota;1973;2024-02-19 14:53:20;2024-02-19 14:53:20;2024-02-19 14:54:03;1103714304;Calle 26;False;False;0.71666667;True;0.00000000;0.71666667;True;False\n'
Linea 1976: 'Calle 26;Subsidio;Pagos;1103714304;Servicio;Cambio de clave por olvido;19/02/2024;14:50:11;14:50:32;14:53:20;11403675;Bogota;1974;2024-02-19 14:50:11;2024-02-19 14:50:32;2024-02-19 14:53:20;1103714304;Calle 26;False;False;2.80000000;True;0.35000000;2.80000000;True;False\n'
Linea 1977: 'Calle 26;Educacion;Educacion;1033797428;Comercial;Informacion, inscripcion cet tyt y tl;27/06/2024;16:18:44;16:25:05;16:31:08;11372219;Bogota;1975;2024-06-27 16:18:44;2024-06-27 16:25:05;2024-06-27 16:31:08;1033797428;Calle 26;False;False;6.05000000;True;6.35000000;6.05000000;True;False\n'
Linea 1978: 'Calle 26;Subsidio;Radicacion afiliaciones;1024480700;Servicio;Rad afiliacion trabajadores hasta 10 formularios;27/06/2024;16:56:23;16:56:51;17:01:17;11372219;Bogota;1976;2024-06-27 16:56:23;2024-06-27 16:56:51;2024-06-27 17:01:17;1024480700;Calle 26;False;False;4.43333333;True;0.46666667;4.43333333;True;False\n'
Linea 1979: "Calle 26;Subsidio;Administracion afiliados;52273627;Servicio;Pqr's cuota monetaria;23/07/2024;8:44:42;8:46:13;8:58:57;11372206;Bogota;1977;2024-07-23 08:44:42;2024-07-23 08:46:13;2024-07-23 08:58:57;52273627;Calle 26;False;False;12.73333333;True;1.51666667;12.73333333;True;False\n"
Linea 1980: 'Calle 26;Credito;Credito;53167689;Comercial;Radicacion cupo credito;6/08/2024;11:43:29;11:43:29;11:50:40;11372206;Bogota;1978;2024-08-06 11:43:29;2024-08-06 11:43:29;2024-08-06 11:50:40;53167689;Calle 26;False;False;7.18333333;True;0.00000000;7.18333333;True;False\n'

DETECCION DEL SEPARADOR:
Separador probable: ';'

DIAGNOSTICO FINALIZADO

In [22]:

# ============================================================
# 5.1.7.6.4.5.5.5
# DICCIONARIO DE DATOS PARA POSTGRESQL
# VERSION CORREGIDA - CSV SEPARADOS POR PUNTO Y COMA
# ============================================================

from pathlib import Path
import pandas as pd

# ------------------------------------------------------------
# 1. IDENTIFICAR DIRECTORIO DEL PROYECTO
# ------------------------------------------------------------

proyecto = Path.cwd().resolve()

if proyecto.name.lower() == "notebooks":
    proyecto = proyecto.parent

directorio = proyecto / "data" / "processed"

# ------------------------------------------------------------
# 2. DEFINIR ARCHIVOS EXPORTADOS
# ------------------------------------------------------------

archivos = {
    "digiturnos_atenciones": "digiturnos_atenciones.csv",
    "digiturnos_franjas": "digiturnos_franjas.csv",
    "digiturnos_diagnostico_sedes":
        "digiturnos_diagnostico_sedes.csv"
}

registros_esperados = {
    "digiturnos_atenciones": 883080,
    "digiturnos_franjas": 25739,
    "digiturnos_diagnostico_sedes": 13
}

# ------------------------------------------------------------
# 3. CONSTRUIR DICCIONARIO DE DATOS
# ------------------------------------------------------------

diccionarios = []
resumen_archivos = []

for tabla, archivo in archivos.items():

    ruta = directorio / archivo

    if not ruta.exists():
        raise FileNotFoundError(
            f"No se encuentra el archivo: {ruta}"
        )

    print("\n" + "=" * 75)
    print(f"TABLA: {tabla}")
    print("=" * 75)

    # Leer muestra para inferir tipos
    muestra = pd.read_csv(
        ruta,
        sep=";",
        nrows=10000,
        encoding="utf-8-sig",
        low_memory=False
    )

    # Contar registros y nulos sobre el archivo completo
    total_filas = 0

    nulos = {
        columna: 0
        for columna in muestra.columns
    }

    for bloque in pd.read_csv(
        ruta,
        sep=";",
        chunksize=50000,
        encoding="utf-8-sig",
        dtype="string"
    ):

        if bloque.columns.tolist() != muestra.columns.tolist():
            raise ValueError(
                f"Estructura inconsistente en {tabla}"
            )

        total_filas += len(bloque)

        for columna in bloque.columns:
            nulos[columna] += int(
                bloque[columna].isna().sum()
            )

    # Validar conservación de registros
    esperado = registros_esperados[tabla]

    if total_filas != esperado:
        raise AssertionError(
            f"{tabla}: {total_filas:,} registros. "
            f"Se esperaban {esperado:,}."
        )

    # Documentar columnas
    for columna in muestra.columns:

        valores = muestra[columna].dropna()

        ejemplo = (
            str(valores.iloc[0])
            if not valores.empty
            else ""
        )

        diccionarios.append({
            "tabla": tabla,
            "columna": columna,
            "tipo_inferido_muestra":
                str(muestra[columna].dtype),
            "nulos_archivo_completo":
                nulos[columna],
            "ejemplo": ejemplo
        })

    resumen_archivos.append({
        "tabla": tabla,
        "registros": total_filas,
        "columnas": len(muestra.columns),
        "validacion": "OK"
    })

    print(f"Registros: {total_filas:,}")
    print(f"Columnas: {len(muestra.columns)}")
    print("Conservacion de registros: OK")

# ------------------------------------------------------------
# 4. EXPORTAR DICCIONARIO
# ------------------------------------------------------------

diccionario = pd.DataFrame(diccionarios)

ruta_diccionario = (
    directorio / "digiturnos_diccionario_datos.csv"
)

diccionario.to_csv(
    ruta_diccionario,
    index=False,
    sep=";",
    encoding="utf-8-sig"
)

# ------------------------------------------------------------
# 5. VALIDACION FINAL
# ------------------------------------------------------------

resumen = pd.DataFrame(resumen_archivos)

print("\n" + "=" * 75)
print("VALIDACION FINAL DEL DICCIONARIO")
print("=" * 75)

print(resumen.to_string(index=False))

print("\nColumnas documentadas:", len(diccionario))
print("Archivo generado:", ruta_diccionario)

print("\nConservacion de registros: OK")
print("Archivos originales sin modificaciones: OK")
print("Diccionario de datos generado: OK")

print("=" * 75)

===========================================================================
TABLA: digiturnos_atenciones
===========================================================================
Registros: 883,080
Columnas: 26
Conservacion de registros: OK

===========================================================================
TABLA: digiturnos_franjas
===========================================================================
Registros: 25,739
Columnas: 46
Conservacion de registros: OK

===========================================================================
TABLA: digiturnos_diagnostico_sedes
===========================================================================
Registros: 13
Columnas: 9
Conservacion de registros: OK

===========================================================================
VALIDACION FINAL DEL DICCIONARIO
===========================================================================
                       tabla  registros  columnas validacion
       digiturnos_atenciones     883080        26         OK
          digiturnos_franjas      25739        46         OK
digiturnos_diagnostico_sedes         13         9         OK

Columnas documentadas: 81
Archivo generado: C:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\processed\digiturnos_diccionario_datos.csv

Conservacion de registros: OK
Archivos originales sin modificaciones: OK
Diccionario de datos generado: OK
===========================================================================

In [23]:

from pathlib import Path
import pandas as pd

# 5.1.7.6.4.5.5.6.1
# Inventario de columnas para el modelo PostgreSQL

raiz = Path.cwd()
if raiz.name.lower() == "notebooks":
    raiz = raiz.parent

carpeta = raiz / "data" / "processed"

archivos = {
    "digiturnos_atenciones": "digiturnos_atenciones.csv",
    "digiturnos_franjas": "digiturnos_franjas.csv",
    "digiturnos_diagnostico_sedes": "digiturnos_diagnostico_sedes.csv",
}

def tipo_postgresql(serie):
    valores = serie.dropna().astype("string").str.strip()
    valores = valores[valores.ne("")]

    if valores.empty:
        return "TEXT"

    nombre = str(serie.name).lower()

    # Identificadores: nunca convertir a números.
    if any(x in nombre for x in [
        "identificacion", "usuario_receptor", "receptor",
        "documento", "codigo"
    ]):
        return "TEXT"

    if nombre.startswith("dt_"):
        return "TIMESTAMP"

    if nombre == "fecha_dia":
        return "DATE"

    if nombre == "hora_solicitud":
        return "SMALLINT"

    if nombre.startswith("id_registro"):
        return "BIGINT"

    numeros = pd.to_numeric(valores, errors="coerce")

    if numeros.notna().all():
        if (numeros % 1 == 0).all():
            return "BIGINT"
        return "DOUBLE PRECISION"

    return "TEXT"


inventario = []

for tabla, archivo in archivos.items():
    ruta = carpeta / archivo

    if not ruta.exists():
        raise FileNotFoundError(f"No existe: {ruta}")

    muestra = pd.read_csv(
        ruta,
        sep=";",
        encoding="utf-8-sig",
        nrows=10000,
        dtype="string",
        low_memory=False
    )

    for posicion, columna in enumerate(muestra.columns, 1):
        inventario.append({
            "tabla": tabla,
            "posicion": posicion,
            "columna_original": columna,
            "tipo_postgresql_propuesto": tipo_postgresql(
                muestra[columna]
            ),
            "nulos_muestra": int(
                muestra[columna].isna().sum()
            )
        })

df_inventario_sql = pd.DataFrame(inventario)

ruta_salida = carpeta / "digiturnos_inventario_sql.csv"

df_inventario_sql.to_csv(
    ruta_salida,
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

print("=" * 75)
print("INVENTARIO PARA DISEÑO POSTGRESQL")
print("=" * 75)

for tabla in archivos:
    datos = df_inventario_sql[
        df_inventario_sql["tabla"] == tabla
    ]

    print(f"\nTABLA: {tabla}")
    print(f"Columnas: {len(datos)}")
    print(
        datos[
            ["posicion", "columna_original",
             "tipo_postgresql_propuesto"]
        ].to_string(index=False)
    )

print("\nArchivo generado:", ruta_salida)
print("Columnas inventariadas:", len(df_inventario_sql))

===========================================================================
INVENTARIO PARA DISEÑO POSTGRESQL
===========================================================================

TABLA: digiturnos_atenciones
Columnas: 26
 posicion         columna_original tipo_postgresql_propuesto
        1                     Sede                      TEXT
        2                      UES                      TEXT
        3             Clasifiacion                      TEXT
        4         Usuario_receptor                      TEXT
        5            Tipo_servicio                      TEXT
        6   SUBSERVICIO_HOMOLOGADO                      TEXT
        7            Fecha_Servico                      TEXT
        8  Hora_solicitud_Servicio                      TEXT
        9   Hora_llamado__Servicio                      TEXT
       10 Hora_finalizado_Servicio                      TEXT
       11   Identificacion_Cliente                      TEXT
       12             Tipo_Oficina                      TEXT
       13     id_registro_original                    BIGINT
       14             dt_solicitud                 TIMESTAMP
       15               dt_llamado                 TIMESTAMP
       16          dt_finalizacion                 TIMESTAMP
       17                 receptor                      TEXT
       18                     sede                      TEXT
       19         fecha_incompleta                      TEXT
       20       secuencia_invalida                      TEXT
       21    duracion_atencion_min          DOUBLE PRECISION
       22         intervalo_valido                      TEXT
       23          espera_min_diag          DOUBLE PRECISION
       24        atencion_min_diag          DOUBLE PRECISION
       25     tiempos_validos_diag                      TEXT
       26      alerta_solapamiento                      TEXT

TABLA: digiturnos_franjas
Columnas: 46
 posicion                   columna_original tipo_postgresql_propuesto
        1                               sede                      TEXT
        2                          fecha_dia                      DATE
        3                         dia_semana                    BIGINT
        4                     hora_solicitud                  SMALLINT
        5                        solicitudes                    BIGINT
        6              receptores_observados                      TEXT
        7                     turnos_validos                    BIGINT
        8                espera_promedio_min          DOUBLE PRECISION
        9                 espera_mediana_min          DOUBLE PRECISION
       10                     espera_p90_min          DOUBLE PRECISION
       11                 umbral_p75_demanda          DOUBLE PRECISION
       12              alta_demanda_relativa                      TEXT
       13         espera_p90_referencia_sede          DOUBLE PRECISION
       14            espera_elevada_relativa                      TEXT
       15           alerta_presion_operativa                      TEXT
       16                      franja_inicio                      TEXT
       17                   minutos_servicio          DOUBLE PRECISION
       18                 receptores_activos                      TEXT
       19                atenciones_en_curso                    BIGINT
       20        minutos_por_receptor_activo                      TEXT
       21                servicios_iniciados                    BIGINT
       22                 duracion_media_min          DOUBLE PRECISION
       23               duracion_mediana_min          DOUBLE PRECISION
       24                   duracion_p90_min          DOUBLE PRECISION
       25    solicitudes_por_receptor_activo                      TEXT
       26        horas_receptor_equivalentes                      TEXT
       27        alerta_integrada_preliminar                      TEXT
       28     minutos_por_receptor_observado                      TEXT
       29                    p75_solicitudes          DOUBLE PRECISION
       30            p75_espera_promedio_min          DOUBLE PRECISION
       31                 p75_espera_p90_min          DOUBLE PRECISION
       32 p75_minutos_por_receptor_observado                      TEXT
       33                      senal_demanda                      TEXT
       34              senal_espera_promedio                      TEXT
       35                   senal_espera_p90                      TEXT
       36              senal_carga_observada                      TEXT
       37                  datos_suficientes                      TEXT
       38                     numero_senales                    BIGINT
       39                   prioridad_cuello                      TEXT
       40                    orden_prioridad                    BIGINT
       41                          prioridad                      TEXT
       42                         es_critica                      TEXT
       43                            es_alta                      TEXT
       44                     es_prioritaria                      TEXT
       45                     es_seguimiento                      TEXT
       46                      sin_evidencia                      TEXT

TABLA: digiturnos_diagnostico_sedes
Columnas: 9
 posicion         columna_original tipo_postgresql_propuesto
        1                     sede                      TEXT
        2       franjas_analizadas                    BIGINT
        3              solicitudes                    BIGINT
        4         franjas_criticas                    BIGINT
        5            franjas_altas                    BIGINT
        6      franjas_seguimiento                    BIGINT
        7    franjas_sin_evidencia                    BIGINT
        8     franjas_prioritarias                    BIGINT
        9 pct_franjas_prioritarias          DOUBLE PRECISION

Archivo generado: c:\Users\acoba\Documents\GitHub\Prueba_Analista_BI\data\processed\digiturnos_inventario_sql.csv
Columnas inventariadas: 81